### PR TITLE
made changes in the roadmap to display merged PRs

### LINKED ISSUE #3047: Roadmap "Implemented features" showing spam issues that have been closed
**Describe the bug**
Currently, closed GitHub issues are being displayed on the Roadmap section of the site (as "implemented features"), even if these issues were spam. This potentially allows users to submit issues on this repo with titles that will be displayed on the live website, which poses potential security risks to our users (ie. soliciting funds to a 0x address).

**To Reproduce**

1. Go to https://ethereum.org/en/about/#roadmap
1. Scroll down to "Implemented features"
1. Notice that cards are a mix of closed PRs, and also closed issues. See screenshot below... ATM, there is a spam entry (this one is harmless).

**Expected behavior**

- This section should include PRs that have been merged into `dev` branch
- Whether or not to display issues is in question... At the least, issues that have been marked as spam on GitHub should be filtered out.
- If this isn't possible, I'd argue we don't need to show closed issues at all, and can just display the merged PRs. 

**Screenshots**
image

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on this issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by adi44**
Added a new condition ```issue.pull_request!==""```` in the roadmap.js implemented function.

so currently as per the issue #3047 it displays the closed issues which do not have any pull request and it might be a spam. so I have added the condition which checks whether there is pull request made or not for the closed issues. if yes then it will display on website else it wont.

## Related Issue

resolved #3047

### CODE REVIEW

**Comment by adi44** [comment]
@wackerow Pls review

**Review by wackerow — CHANGES_REQUESTED** [review]
@adi44 This looks like it should help, but it also doesn't stop someone from creating bogus PRs... Not sure we can do this easily, but any thoughts on a way to check if that PR has actually been merged into `dev`?
If it's too much, this will at least be a nice start.

(Btw, noticed a stray `package-lock.json` change... do me a favor and revert this from the branch... using `yarn` instead of `npm install` should avoid this in the future)

**Comment by adi44** [comment]
> @adi44 This looks like it should help, but it also doesn't stop someone from creating bogus PRs... Not sure we can do this easily, but any thoughts on a way to check if that PR has actually been merged into `dev`?
> If it's too much, this will at least be a nice start.
> 
> (Btw, noticed a stray `package-lock.json` change... do me a favor and revert this from the branch... using `yarn` instead of `npm install` should avoid this in the future)

@wackerow I have removed package-lock.json

**Comment by adi44** [comment]
> > @adi44 This looks like it should help, but it also doesn't stop someone from creating bogus PRs... Not sure we can do this easily, but any thoughts on a way to check if that PR has actually been merged into `dev`?
> > If it's too much, this will at least be a nice start.
> > (Btw, noticed a stray `package-lock.json` change... do me a favor and revert this from the branch... using `yarn` instead of `npm install` should avoid this in the future)
> 
> @wackerow I have removed package-lock.json

we can use github API specifically for Pull requests

**Comment by adi44** [comment]
@wackerow Pls review it

**Comment by adi44** [comment]
@wackerow @shazow Pls review

**Review by shazow — APPROVED** [review]
Not sure if you meant to ping me to review, but looks fine to me. :)

Personally I'd consider using Github Milestones (and possibly Labels) for this kind of data, but that would require more gardening effort by maintainers.

**Review by wackerow — APPROVED** [review]
@adi44 Hey sorry, wasn't sure if you meant you were going to try working with the API more. I'll pull this in for now as it solves the majority of cases, can always readdress in the future if it becomes more of an issue.
Thanks @adi44 !

**Comment by wackerow** [comment]
@all-contributors please add @adi44 for bug fix

**Comment by adi44** [comment]
@wackerow thanks! For merging it. Yeah in future we can make it more better if it causes more issues

**Comment by wackerow** [comment]
@adi44 Re-opened #3047 if you wanted to take another look at this... Posted a screenshot of a spam PR that wasn't merged being displayed within the roadmap cards. Let me know if you're interested or not and I can re-assign if need be =)

**Pull request merged**
