### PR TITLE
refactor(ContentHero): update and apply component usage

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Description

This PR add modifications to the `ContentHero` component and applies it to the `Upgrade` layout.

- The `description` section of the hero can accept either a string or components
  - In prod for the `Upgrade` layout, a list of descriptions render with a "last updated" timestamp
- The `Image` component has new styling with predefined dimensions
- Update types to allow for the `heroImg` prop to accept either a string or the static image data object, depending on the hero component to be used.
- Affects the [/merge](https://ethereum.org/en/roadmap/merge/) and [beacon-chain](https://ethereum.org/en/roadmap/beacon-chain/) pages

## Additional Information

This relieves a bug in the [roadmap merge page](https://ethereum.org/en/roadmap/merge/) where the alignment of the image and content in not centered and the image is clipped.

### CODE REVIEW

**Comment by TylerAPfledderer** [comment]
Hey @nloureiro ! Would like a review from you on these updates.

- [UI Snapshot update of the `ContentHero` story](https://www.chromatic.com/test?appId=63b7ea99632763723c7f4d6b&id=660ce91187cd410aaeae1c16)
- [Updated `ContentHero` component in Storybook](https://63b7ea99632763723c7f4d6b-heocvpqqrj.chromatic.com/?path=/story/organisms-layouts-hero--content-hero)
- [/merge page preview](https://deploy-preview-12639--ethereumorg.netlify.app/en/roadmap/merge/)
- [/beacon-chain page preview](https://deploy-preview-12639--ethereumorg.netlify.app/en/roadmap/beacon-chain)
  - Noting for this page that the image does not seem to work quite as well for the new layout

**Comment by TylerAPfledderer** [comment]
> we might need to accept imageProps so that the consumer can tweak the image as necessary.

It's not clear to me how that would be possible if this hero is being applied in a layout component. Unless you would be thinking of setting up some conditional at the layout level to set overrides based on the image file path provided by front matter. Is that what you are thinking of?

**Comment by pettinarip** [comment]
@TylerAPfledderer
True. Perhaps its not going to be useful here.

I was basically thinking about overriding the defaults to try to recreate the same styles we had before in the `Upgrade` layout image.

```ts
// Roadmap layout
<ContentHero heroImg={frontmatter.image}>

// Upgrade layout
<ContentHero heroImg={frontmatter.image} imageProps={{ objectFit: "cover", ... }}>
```

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer
> True. Perhaps its not going to be useful here.
> 
> I was basically thinking about overriding the defaults to try to recreate the same styles we had before in the `Upgrade` layout image.
> 
> ```ts
> // Roadmap layout
> <ContentHero heroImg={frontmatter.image}>
> 
> // Upgrade layout
> <ContentHero heroImg={frontmatter.image} imageProps={{ objectFit: "cover", ... }}>
> ```

Oh! I could look at this.

**Comment by wackerow** [comment]
@pettinarip Is this something that should hold things up from a dev perspective?

cc: @nloureiro for an approval

**Comment by pettinarip** [comment]
> @pettinarip Is this something that should hold things up from a dev perspective?
> 
> cc: @nloureiro for an approval

No, I'd say that if designers are ok its ready to be merged

**Comment by TylerAPfledderer** [comment]
> Hey @nloureiro ! Would like a review from you on these updates.
> 
> - [UI Snapshot update of the `ContentHero` story](https://www.chromatic.com/test?appId=63b7ea99632763723c7f4d6b&id=660ce91187cd410aaeae1c16)
> - [Updated `ContentHero` component in Storybook](https://63b7ea99632763723c7f4d6b-heocvpqqrj.chromatic.com/?path=/story/organisms-layouts-hero--content-hero)
> - [/merge page preview](https://deploy-preview-12639--ethereumorg.netlify.app/en/roadmap/merge/)
> - [/beacon-chain page preview](https://deploy-preview-12639--ethereumorg.netlify.app/en/roadmap/beacon-chain)
>   - Noting for this page that the image does not seem to work quite as well for the new layout

@nloureiro provided the above links again for visibility with your review!

**Comment by nloureiro** [comment]
Thank you @TylerAPfledderer 

I'm not sure where to give feedback on the chromatic part. Here or on the chromatic side?

But for the dev preview link, I found some adjustments needed. let me know if this makes sense

(https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=11713%3A6568&mode=design&t=dokTXVgchl8dd6uE-1)
Screen Shot 2024-04-09 05 32 14 PM

**Comment by TylerAPfledderer** [comment]
> Thank you @TylerAPfledderer 
> 
> I'm not sure where to give feedback on the chromatic part. Here or on the chromatic side?
> 
> But for the dev preview link, I found some adjustments needed. let me know if this makes sense
> 
> (https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=11713%3A6568&mode=design&t=dokTXVgchl8dd6uE-1)
> Screen Shot 2024-04-09 05 32 14 PM
> 

@nloureiro sorry, here is an [updated snapshot](https://www.chromatic.com/test?appId=63b7ea99632763723c7f4d6b&id=660de14110119826685701a3)

I think if there are changes needed, to deny the snapshot and add a comment in Chromatic underneath the snapshot. I think that is more streamlined for you and isolate the discussions.

[UI Test discussions](https://www.chromatic.com/test?appId=63b7ea99632763723c7f4d6b&id=660de14110119826685701a3)

The anchor bar beneath the hero is not showing as a part of the component. I think this and removing the "last updated" content are a different scope.

**Comment by TylerAPfledderer** [comment]
Updated the branch and removed the "More Content" anchor link at the bottom

**Comment by wackerow** [comment]
@nloureiro https://www.chromatic.com/review?appId=63b7ea99632763723c7f4d6b&number=12639&type=linked&view=activity Currently blocking; can merge once approved

**Review by nloureiro — APPROVED** [review]

**Comment by nloureiro** [comment]
> @nloureiro https://www.chromatic.com/review?appId=63b7ea99632763723c7f4d6b&number=12639&type=linked&view=activity Currently blocking; can merge once approved

It looks good to me!

**Pull request merged**
