### PR TITLE
Update community-meetups.json

### PR DESCRIPTION
**Pull request by CeciSakurita**
Added the ETH Bolivia 2024 Buildathon, organized by the Ethereum Bolivia community that will be held in Santa Cruz de la Sierra, Bolivia on August, 9th to 11th

### CODE REVIEW

**Comment by CeciSakurita** [comment]
Hi
Wanted to add the ETH Bolivia 2024 Buildathon, this is our second edition of the event, the biggest blockchain buildathon held in Bolivia at the moment, and organized by the Ethereum Bolivia community who is very active and regularly helds meetups in 2 cities: La Paz and Santa Cruz, this year achieved a new activation in Cochabamba city and now is helding a Solidity Workshop as a starter point of community activities in that city.
Happy to answer any question you would have, please consider adding this event as is a great achievement for the community and its growth.

Greetings,
Ceci Sakura

**Review by minimalsm — CHANGES_REQUESTED** [review]
Thanks for the PR @CeciSakurita 💪 

I think this would be more appropriate to be listed as an event? See the [correct file here](https://github.com/ethereum/ethereum-org-website/blob/dev/src/data/community-events.json)

**Review by CeciSakurita — COMMENTED** [review]
yes, you're right
adding the event to the right file 

thank you!

**Review by wackerow — APPROVED** [review]
Thanks @CeciSakurita! Went ahead and migrated this over to the community events file, instead of the meetups. I took the description from the intro copy at the top of the website.

**Pull request merged**
