### PR TITLE
add further reading [Fixes #11699]

### LINKED ISSUE #11699: Suggest additional resource to be linked
### Is your feature request related to a problem? Please describe.

This [page](https://ethereum.org/en/nft/#further-reading) informs readers about NFTs and links to further readings. I suggest adding another reading that gives an overview of many NFT dApps people can use today on Ethereum.

### Describe the solution you'd like

I'd like to suggest an additional link for the "Further reading" section. It lists many popular NFT dApps and tools available on Ethereum: https://www.ethereum-ecosystem.com/blockchains/ethereum/nfts

### Describe alternatives you've considered

Rather than suggesting the specific link I've mentioned, we could link to other high-quality resources on the topic.

### Additional context

_No response_

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by Maxservais**
## Description

Added a new resource to the 'Further Reading' section on the Ethereum NFT page, providing a comprehensive list of popular NFT DApps & Tools on the Ethereum network. This enhances the page by offering direct access to practical examples and applications of NFTs.

## Summary by CodeRabbit

- **Documentation**
	- Added a link to "Popular NFT Apps and Tools" across various sections and translations of the NFT documentation, enhancing resource accessibility for users.

### CODE REVIEW

**Comment by Maxservais** [comment]
@wackerow could I get your feedback on this PR when you can spare some time? Thanks a lot!

**Review by konopkja — APPROVED** [review]

**Review by wackerow — COMMENTED** [review]
Thanks @Maxservais! Looks good, just not sure about adding this to the non-English pages with the English label... Typically we would add this to the English page only, and then it would be uploaded to Crowdin for translation... is there a reason these are added for `fil`, `pcm` and `tr` here?

**Comment by Maxservais** [comment]
Hey @wackerow, really sorry, it was a mistake.
I have removed the text from the translated files!

**Review by wackerow — APPROVED** [review]
Thanks @Maxservais!

**Pull request merged**
