### PR TITLE
SEO update meta titles

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

Adds meta titles to md pages and a few react pages.

## Related Issue

#13796

### CODE REVIEW

**Comment by konopkja** [comment]
@pettinarip  

the table in the issue defining titles had few formating issues here on github and hid full titles for few URLs: 

What are NFTs? | Benefits and use
What is a DAO? | Decentralized Autonomous Organization
How to use Ethereum Wallets | Step by Step
List of Ethereum Wallets | ethereum.org
What is DeFi? | Benefits and Use of Decentralised Finance

**Comment by pettinarip** [comment]
> @pettinarip
> 
> the table in the issue defining titles had few formating issues here on github and hid full titles for few URLs:
> 
> What are NFTs? | Benefits and use What is a DAO? | Decentralized Autonomous Organization How to use Ethereum Wallets | Step by Step List of Ethereum Wallets | ethereum.org What is DeFi? | Benefits and Use of Decentralised Finance

@konopkja ah ok, I see. Will update those.

Just to clarify, in all these pages we automatically concatenate the text ` | ethereum.org` to the meta titles. So, for example, "What are NFTs? | Benefits and use" would become "What are NFTs? | Benefits and use | ethereum.org".

Is this ok? or would you think it would be better to use " | ethereum.org" only on pages we consider appropriate?

**Comment by konopkja** [comment]
> > @pettinarip
> > the table in the issue defining titles had few formating issues here on github and hid full titles for few URLs:
> > What are NFTs? | Benefits and use What is a DAO? | Decentralized Autonomous Organization How to use Ethereum Wallets | Step by Step List of Ethereum Wallets | ethereum.org What is DeFi? | Benefits and Use of Decentralised Finance
> 
> @konopkja ah ok, I see. Will update those.
> 
> Just to clarify, in all these pages we automatically concatenate the text ` | ethereum.org` to the meta titles. So, for example, "What are NFTs? | Benefits and use" would become "What are NFTs? | Benefits and use | ethereum.org".
> 

> Is this ok? or would you think it would be better to use " | ethereum.org" only on pages we consider appropriate?

only on those pages we consider appropriate, actually i dont think what you say is true? see example below 

Screenshot 2024-10-25 at 16 27 06

**Comment by pettinarip** [comment]
> | ethereum.org

Ok @konopkja, pushed those changes.

To confirm, by removing the default "| ethereum.org", from now on the only page that will have this is the find wallet page that has "List of Ethereum Wallets | ethereum.org". The rest will no longer have it.

LMK if you would like to add more pages into this group.

**Review by corwintines — APPROVED** [review]

**Comment by corwintines** [comment]
https://app.netlify.com/sites/ethereumorg/deploys/676119333f219a1a3e077b17

There was a failing API key causing this to not build. Fixed that and now its building, so going to merge.

**Pull request merged**
