### PR TITLE
Remove 2018 article that is not updated often

### PR DESCRIPTION
**Pull request by ethers**
Fix date on 2018 article that is not updated often

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks for this suggestion @ethers!

This relates to #799. What are your thoughts on removing this link entirely, given it's fairly outdated?

**Comment by samajammin** [comment]
I'm open to ideas but my current stance agrees with the user report in that issue to remove everything published before 2019.

**Comment by ethers** [comment]
I commented on #799  For this link, it does seem better to remove. Should this PR be updated?

**Comment by samajammin** [comment]
Yes @ethers please go ahead & update this PR to remove this link entirely. Thanks!

**Comment by ethers** [comment]
@samajammin Done

**Pull request merged**
