### PR TITLE
Fixed typo in 'Sending transactions using Web3' tutorial

### PR DESCRIPTION
**Pull request by stefan-wuest**
Fixed typo in 'Sending transactions using Web3' tutorial 

'for signing' instead of 'for singing'

Issue https://github.com/ethereum/ethereum-org-website/issues/5042

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks @stefan-wuest!

**Review by minimalsm — APPROVED** [review]
Thanks for the PR @stefan-wuest ✌️.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

**Comment by minimalsm** [comment]
@all-contributors please add @stefan-wuest for docs

**Comment by stefan-wuest** [comment]
> Thanks for the PR @stefan-wuest ✌️.
> 
> Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

Thanks very much @minimalsm . Already joined the Discord yesterday as I certainly will contribute in the future.
I will claim my POAP shortly and will have a look at the whole process (=inspiration) because we're working on a Learn2Earn program (Watch Videos, Answer Questions, Get POAP) with the Ethereum Cat Herders.

**Pull request merged**
