### PR TITLE
Fix link to /glossary/#zk-proof

### PR DESCRIPTION
**Pull request by AlehNat**
Fix the link in the document
## Description
Just a simple fix of the link.

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Hey @AlehNat, thanks for the PR ❤️ 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
Oops. Some conflicting files that we need to fix here.

**Comment by minimalsm** [comment]
@all-contributors please add @AlehNat for docs

**Comment by AlehNat** [comment]
@minimalsm Appreciate your review and adding me to the contributor list!  I've fixed the merge conflict.

**Pull request merged**
