### PR TITLE
Add new wallets & exchanges

### PR DESCRIPTION
**Pull request by samajammin**
## Description

Add new wallets & exchanges

## Related Issue
#1411 #1432 #1686

### CODE REVIEW

**Comment by samajammin** [comment]
Ready for your review @GeorgeTrotter!

**Comment by ryancreatescopy** [comment]
@samajammin @GeorgeTrotter should #1432 have added monolith to /get-eth?

**Review by ryancreatescopy — COMMENTED** [review]
See comment above

**Comment by samajammin** [comment]
@ryancreatescopy my understanding from our sprint planning discussion was to not worry about parity between /find-wallets & /get-eth yet.

**Comment by ryancreatescopy** [comment]
good point

**Review by ryancreatescopy — APPROVED** [review]

**Pull request merged**
