### PR TITLE
Added using unsupported languages

### PR DESCRIPTION
**Pull request by qbzzt**
When there is no library you just use the JSON-RPC interface directly (or write a library)

## Description

A user asked how to use Swift. We figured more than one person could use the answer.

## Related Issue

This is based on #2222

### CODE REVIEW

**Comment by wackerow** [comment]
@qbzzt Thanks for putting up this... Just thinking ahead, we may want to wait til #2352 is merged (migrates that JSON-RPC documentation to ethereum.org), and update this link to point internally. Just requested a review on that PR to get it moving.

**Comment by qbzzt** [comment]
> @qbzzt Thanks for putting up this... Just thinking ahead, we may want to wait til #2352 is merged (migrates that JSON-RPC documentation to ethereum.org), and update this link to point internally. Just requested a review on that PR to get it moving.

If it is merged soon, I agree. If it takes too long, we might as well merge this as is and then modify when #2352 is merged.

**Comment by ryancreatescopy** [comment]
We'll merge the JSON-RPC stuff today so I've altered the PR to make it ready! Thanks for doing this @qbzzt !

**Review by wackerow — APPROVED** [review]
👍

**Comment by samajammin** [comment]
Dependent on #2352

**Review by samajammin — COMMENTED** [review]
Thanks!

**Pull request merged**
