### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by rojotek**
Minor update to client feature table.

## Description

Very small update to the feature table around the clients.

### CODE REVIEW

**Review by corwintines — CHANGES_REQUESTED** [review]
https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Starting-node/

Hey @rojotek, was looking at the Besu docs above and it isn't mentioning other networks. Do you have a resource I could look at to confirm this PR? Thanks!

**Comment by rojotek** [comment]
The specific network shortcuts available through the config file are just the short cuts to more advanced settings in the configuration file and genesis blocks.

It can connect to any devp2p network using settings available in these:

https://besu.hyperledger.org/en/stable/HowTo/Configure/Genesis-File/
https://besu.hyperledger.org/en/stable/HowTo/Configure/Using-Configuration-File/

This is similar to the offerings in the other clients.

**Comment by corwintines** [comment]
Thanks for the clarity @rojotek :)

**Review by corwintines — APPROVED** [review]

**Comment by corwintines** [comment]
@all-contributors can you add @rojotek for content

**Comment by corwintines** [comment]
@rojotek make sure to come claim your POAP in the ethereum.org discord :)

https://discord.gg/TFbn6fnf

**Pull request merged**
