### PR TITLE
Tutorial copy adjustment

### PR DESCRIPTION
**Pull request by B-Harden**
Adding word to improve readability.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks for the edit @B-Harden!

**Review by wackerow — APPROVED** [review]
@B-Harden Thanks!

**Comment by wackerow** [comment]
@all-contributors please add @B-Harden for copy fix

**Comment by wackerow** [comment]
@all-contributors please add @B-Harden for content fix

**Pull request merged**
