### PR TITLE
Remove native modifier [Fixes #835]

### LINKED ISSUE #835: Console error re: `Navlink` component
**Describe the bug**
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: The .native modifier for v-on is only valid on components but it was used on <a>.

found in

---> <NavLink> at docs/.vuepress/theme/components/NavLink.vue
       <NavDropdown> at docs/.vuepress/theme/components/NavDropdown.vue
         <NavLinks> at docs/.vuepress/theme/components/NavLinks.vue
           <Navigation> at docs/.vuepress/theme/components/Navigation.vue
             <Layout> at docs/.vuepress/theme/Layout.vue
               <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
                 <Root>
```

Removing the `v-on` usage (line 16) should resolve this.

**To Reproduce**
Load the app & inspect browser console.

**Expected behavior**

No errors should log

**Screenshots**

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

Introduced in #794

### PR DESCRIPTION
**Pull request by samajammin**
## Description
Remove native modifier on `NavLink` `a` tag

## Related Issue
#835

### CODE REVIEW

**Comment by samajammin** [comment]
@carlfairclough please confirm no functionality changes as a result of this but I believe this should fix the issue. Thanks!

**Comment by carlfairclough** [comment]
Yep this works, but interestingly it prevents the drop down from closing. A very, _very_, minor problem

**Comment by samajammin** [comment]
@carlfairclough could you clarify what you mean? When I try searching in this preview deploy, the search result dropdown closes after making a selection. Not sure if that's what you're referring to though.

**Comment by carlfairclough** [comment]
This targets external links — if you click the Ethereum Studio link, the dropdown doesn't seem to close, but as it opens a new tab it's not a major issue

**Comment by samajammin** [comment]
Ah whoops, ya you're right 😅 been thinking about search too much - this has nothing to do with that.

I agree, It seems to be inconsistent in if it closes or not but given that it opens a new tab it's hard to notice. Going to merge & close this out since it gets ride of the console errors.

**Pull request merged**
