### PR TITLE
Add SmartContract.Codes to Security Tools

### PR DESCRIPTION
**Pull request by ninabreznik**

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks for the contribution @ninabreznik but I'm hesitant to add a "pre-alpha" product to this site as a resource. Can you provide assurances for the following submission criteria (from [this repo's README](https://github.com/ethereum/ethereum-org-website#-developers)):

 - Is the tool well documented?
   - Does documentation exist? 
   - Is it sufficient to use the tool?
   - Has it been recently updated?
 - Is the tool widely used? 
   - We will consider metrics such as Github stars, download statistics, and whether it is used by known companies or projects.
 - Is the tool of sufficient quality?
   - Are there recurring bugs?
   - Is the tool reliable?

Otherwise I suggest we wait until it's in a mature phase.

**Comment by serapath** [comment]
Hey @samajammin 

The tool is well documented and you can try it out right now, so I would say it is totally sufficient to use the tool. We are updating it all the time and given that it is such a young project, we got quite a lot of traction (see: https://twitter.com/ninabreznik/status/1170132016504946688) and we have users and a few heavy ones who actively give us feedback in our gitter chat.

Regarding tool quality, we got a lot of positive feedback for how convenient it is to use the tool - again https://smartcontract.codes go there and try it for yourself.

The only currently known bug is that some contracts can't be opened, but that is related to older solidity versions where the emscripten transpiled c++ version the compiler just won't work in some browser versions and not a lot can be done about it other than telling users that for those contracts they might need to use a different tool.

Otherwise, it works quite reliably :-)

**Comment by ninabreznik** [comment]
@samajammin Hey, I also updated our documentation :) 
https://github.com/ethereum-play/smartcontract.codes/blob/master/README.md

We're in the process to implement MythX and Sooho to our product and we're in touch with POA Network and QuickBlocks who are supporting our p2p database and are planning on running a node and to contribute more verified contracts to it.

**Comment by samajammin** [comment]
@CPSTL - have you had a chance to review this?

**Comment by CPSTL** [comment]
> @CPSTL - have you had a chance to review this?

Yes - it LGTM. Hello @ninabreznik @serapath, could you please resolve the conflicts?

**Comment by ninabreznik** [comment]
> > @CPSTL - have you had a chance to review this?
> 
> Yes - it LGTM. Hello @ninabreznik @serapath, could you please resolve the conflicts?

Done! Thanks!

**Comment by ninabreznik** [comment]
Thank you

**Pull request merged**
