### PR TITLE
Local fonts

### PR DESCRIPTION
**Pull request by pettinarip**
Currently, our fonts are consumed from Google by using `next/font/google`. As these fonts are fetched at build time to then be stored and selfhosted, sometimes those fetches fail making the build to fail.

## Description

Add the fonts to the repo to fetch them locally at build time instead of relying on third-party services.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
🚀

**Review by corwintines — CHANGES_REQUESTED** [review]
Sorry, approved this but noticing some differences now. 

The font spacing seems off only for the Inter font, but IBMPlexMono (used in code) is fine. 

Screenshot 2024-01-23 at 1 54 20 PM
Screenshot 2024-01-23 at 1 54 34 PM

**Comment by wackerow** [comment]
+1, noticing a slight difference in how Inter appears... `mono` fonts look unchanged

**Review by wackerow — APPROVED** [review]
Nice, perfect match now... pulling in. Thanks @pettinarip!

**Pull request merged**
