### PR TITLE
added a resource on the Ethereum ecosystem

### PR DESCRIPTION
**Pull request by ArpitIngle**
added a comprehensive resource for learning about the Ethereum ecosystem , both basic and advanced

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @ArpitIngle, thanks for the PR! 

Cool resource you're building ❤️ Unfortunately, we lean towards not listing any resources that are [under 6 months old as per our listing policy.](https://ethereum.org/en/contributing/adding-products/) You're more than welcome to check back in, in a few months when the project is a little more mature 💪

Keep buidling 😎

**Comment by minimalsm** [comment]
@all-contributors please add @ArpitIngle for ideas

**Comment by ArpitIngle** [comment]
> Hey @ArpitIngle, thanks for the PR!
> 
> Cool resource you're building ❤️ Unfortunately, we lean towards not listing any resources that are [under 6 months old as per our listing policy.](https://ethereum.org/en/contributing/adding-products/) You're more than welcome to check back in, in a few months when the project is a little more mature 💪
> 
> Keep buidling 😎

Sure , Thanks.

**Comment by ArpitIngle** [comment]
> Hey @ArpitIngle, thanks for the PR!
> 
> Cool resource you're building ❤️ Unfortunately, we lean towards not listing any resources that are [under 6 months old as per our listing policy.](https://ethereum.org/en/contributing/adding-products/) You're more than welcome to check back in, in a few months when the project is a little more mature 💪
> 
> Keep buidling 😎

It's been seven months 😅
Can you please add my project now? Thanks.

**Pull request closed without merging**
