### PR TITLE
Add effect to button (dapps page) [Fixes #5676]

### LINKED ISSUE #5676: On-hover effect missing on 'Go' button (dapps page)
**Describe the bug**

Under the 'Get started' section of [the dapps page](https://ethereum.org/en/dapps/) the 'Go' button does not have an on-hover effect.

**To Reproduce**

1. Go to 'https://ethereum.org/en/dapps/'
1. Scroll down to 'Get started'
1. Hover over the 'Go' button
1. See error

**Expected behavior**

The button should have an appropriate on-hover effect.

**Screenshots**

image

**Additional context**

There are other, properly styled orange on-hover buttons on the page that can be used to ascertain the correct style.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by tomaspasie**
## Description
This PR adds an on-hover effect to the 'Go' button on the dapps page. (https://ethereum.org/en/dapps/)

## Related Issue
#5676

### CODE REVIEW

**Review by minimalsm — COMMENTED** [review]
Thanks @tomaspasie, this looks good!

Any chance you could remove the yarn/package.json files from this?

**Review by pettinarip — CHANGES_REQUESTED** [review]
Thanks @tomaspasie for this.

As @minimalsm said lets remove the changes made in:
- `package-lock.json`
- `package.json`
- `yarn.lock`

**Comment by tomaspasie** [comment]
No Problem! Everything should be fixed now.

@minimalsm @pettinarip

**Review by minimalsm — APPROVED** [review]
Thanks @tomaspasie ❤️

Be sure to [claim 2022 POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @tomaspasie for code

**Comment by minimalsm** [comment]
@pettinarip can you merge please? I'm unable to.

**Review by pettinarip — APPROVED** [review]
🚀

**Pull request merged**
