### PR TITLE
Use consistent format for block numbers in history

### PR DESCRIPTION
**Pull request by fvictorio**
Sorry for deleting the template, but this is a pretty self-explanatory change.

### CODE REVIEW

**Comment by fvictorio** [comment]
Actually, I _could_ have given a better explanation: the last entries use commas for the block number but the older ones don't. That's it.

**Review by corwintines — APPROVED** [review]
Definitely prefer this for readability, thanks @fvictorio!

**Comment by samajammin** [comment]
Thanks @fvictorio! I agree we should be consistent on this.

Looking into this a bit I did notice that etherscan doesn't use any commas or other separators between block numbers (even though they use commas for other numbers), e.g. https://etherscan.io/block/13634817

I also notice in the [Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf) they don't use commas:
Image 2021-11-17 at 1 24 19 PM

I do wonder why this is - I agree it hurts legibility a bit. On the other hand, it's easier to copy & paste.

I couldn't find any "official" way to reference block numbers (I suspect there is none) but I might suggest that we don't use commas to keep consistency with these sources. Open to opinions here.

**Comment by fvictorio** [comment]
My two cents: I think that, for this particular context, using commas feel better. The downside is that copy-pasting them also means removing the commas, but there aren't that many entries, so I don't think it's a big deal. In etherscan, OTOH, it makes more sense, because I figure people copy-paste those numbers more often. With respect to the yellow paper... I think they should use commas too in that part.

**Review by samajammin — APPROVED** [review]

**Comment by minimalsm** [comment]
Merging now 🎉

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @fvictorio for docs

**Pull request merged**
