### PR TITLE
Fixed overflowing button text in stablecoins page

### LINKED ISSUE #9784: Bug report: overflowing button text in stablecoins page
### Describe the bug

1. the text of the button is overflowing
2. the colored background is too small, could be much wider so there is more space for the content inside

### To reproduce

1. Go to (https://ethereum.org/en/stablecoins/)
2. Scroll down to "Use your stablecoins
3. See error

### Expected behavior

increase width of the components on mobile

### Screenshots

Screenshot 2023-03-23 at 17 11 36

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MukulKolpe**
## Description

Fixed overflowing text from `More on decentralized finance (DeFi)` button on the stablecoins page.

## Related Issue

Fixes #9784

### CODE REVIEW

**Comment by MukulKolpe** [comment]
Hey @corwintines, @konopkja can you please review this PR?

**Comment by corwintines** [comment]
Hey @MukulKolpe 

Appreciate the work done here so far. This problem is a bit more related to the actual Button component and should be resolved in that as opposed to a single use of it. I will assign this to me to look more closely into the issue and report back here.

**Comment by MukulKolpe** [comment]
Yes, @corwintines. Makes sense, since it is used and extended multiple times throughout the site, It's better to fix the Button Component itself. I too will look into this and report here if I find anything useful.

**Comment by pettinarip** [comment]
@corwintines I've created a new issue under the DS implementation epic to keep track of this #10020. I'm assigning it to you for now. LMK in case you need help on this and I can take it.

**Comment by corwintines** [comment]
Great, thanks! Will look into this over the next week.

**Comment by konopkja** [comment]
seems like this is fixed, so closing this

**Pull request closed without merging**
