### PR TITLE
feat: lambda school added in the developer bootcamps

### LINKED ISSUE #3660: Add Lambda School to developer bootcamps
**Is your feature request related to a problem? Please describe.**

https://lambdaschool.com/learn-blockchain-development

**Describe the solution you'd like**

Add to "Developer bootcamps" section of https://ethereum.org/en/developers/learning-tools/

**Additional context**

I suppose we don't have clear listing criteria for these type of additions but Lambda School is a fairly well known, well funded & highly regarded online web development bootcamp.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by MukulKolpe**
## Description
Lambda School added in the developer bootcamp

## Related Issue

Fixes #3660

Screenshot (93)

### CODE REVIEW

**Comment by minimalsm** [comment]
@MukulKolpe thanks for the PR. Will get this reviewed early on Monday.

**Comment by MukulKolpe** [comment]
Let me know if there should be any updates in the PR. 
Thank you!!

**Comment by minimalsm** [comment]
@MukulKolpe thanks so much for this ❤️ sorry for the delay. Was checking some details around the release date of the Bootcamp itself. PR looks great and I'm merging now.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @MukulKolpe for code

**Comment by MukulKolpe** [comment]
Thank you so much @minimalsm for your appreciation. I will definitely keep contributing to the project.😀

**Pull request merged**
