### PR TITLE
Md layouts tw migration & unification

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

Effort to consolidate similar looking layouts.

- Created a new base layout called `ContentLayout` that uses the `ContentHero`
- Updated the following layouts to use `ContentLayout`: Upgrade, Roadmap, Staking, Translatathon, and UseCases

| Layout       | Production Link | Preview Link |
|----------------|-----------------|--------------|
| Upgrade        | [prod](https://ethereum.org/en/roadmap/merge/) | [pr](https://deploy-preview-13843--ethereumorg.netlify.app/en/roadmap/merge/) |
| Staking - Pools| [prod](https://ethereum.org/en/staking/pools/) | [pr](https://deploy-preview-13843--ethereumorg.netlify.app/en/staking/pools/) |
| Roadmap - Index| [prod](https://ethereum.org/en/roadmap/) | [pr](https://deploy-preview-13843--ethereumorg.netlify.app/en/roadmap/) |
| Roadmap - Security| [prod](https://ethereum.org/en/roadmap/security/) | [pr](https://deploy-preview-13843--ethereumorg.netlify.app/en/roadmap/security/) |
| Translatathon  | [prod](https://ethereum.org/en/contributing/translation-program/translatathon/) | [pr](https://deploy-preview-13843--ethereumorg.netlify.app/en/contributing/translation-program/translatathon/) |
| Use Cases      | [prod](https://ethereum.org/en/nft/) | [pr](https://deploy-preview-13843--ethereumorg.netlify.app/en/nft/) |

## TODO
- [x] Run initial round of testing and feedback
- [x] Complete migration of internal components (used in the layouts) to Tailwind
- [x] Migrate UseCases layout
- [x] Add story for `ContentLayout`
- [x] Remove build command for testing
- [x] Add banner in use-cases layout

### CODE REVIEW

**Comment by nloureiro** [comment]
For the heroes, I made this comparison on Figma.

All looks very good! Great improvement on the UX of different pages

Only 2 points:
- the hub hero
- on the use cases all the use cases should use "uses cases" on top of the title to follow the menu structure.

**Comment by nloureiro** [comment]
@pettinarip does this ones fall under a different template?

my take is that all should follow the DS heroes, and these ones are still different.  
@konopkja, any pushback on updating this one to the same hero template? With the gradient background?

Screen Shot 2024-09-12 10 31 48 AM
Screen Shot 2024-09-12 10 31 36 AM
Screen Shot 2024-09-12 10 31 23 AM

**Comment by pettinarip** [comment]
> @pettinarip does this ones fall under a different template?

They do, they are different layouts. You can see that the ones that we changed have the left sidenav and the content on the right.

However, we could create a different PR to update the heros for these pages if we all agree. But I wouldn't include that in this PR.

**Comment by pettinarip** [comment]
Cool! thanks for the early feedback @nloureiro.

> * the hub hero

Ok, let me see how we can keep this.

> * on the use cases all the use cases should use "uses cases" on top of the title to follow the menu structure.

Hmm ok. Got the idea but this section is used for the breadcrumbs and they are supposed to be links. But we don't have a page under `/use-cases` to make the connection. Personally, I wouldn't like to add a hack to make a section of the breadcrumbs not clickable, just for this case. Let me think more about it.

**Comment by konopkja** [comment]
lgtm what pablo did, regarding nuno's question about merging all headers according to the template: maybe just worried how the ETH page would look like with gradient, not a very strong stance here.

Personally i think the design without gradient looks clearer and simpler and less corporate, but that is a different conversation.

**Comment by nloureiro** [comment]
> Cool! thanks for the early feedback @nloureiro.
> 
> > * the hub hero
> 
> Ok, let me see how we can keep this.
> 
> > * on the use cases all the use cases should use "uses cases" on top of the title to follow the menu structure.
> 
> Hmm ok. Got the idea but this section is used for the breadcrumbs and they are supposed to be links. But we don't have a page under `/use-cases` to make the connection. Personally, I wouldn't like to add a hack to make a section of the breadcrumbs not clickable, just for this case. Let me think more about it.


True, they are supposed to be breadcrumbs but:
1. we don´t follow the navigation. If they are supposed to be breadcrumbs "usecase", it's the right work to be there :)
2. I wanted to avoid this...
Screen Shot 2024-09-12 02 08 12 PM

this falls out of scope for this PR, but we need to think how to make the navigation and breadcrumbs match.

**Comment by nloureiro** [comment]
> lgtm what pablo did, regarding nuno's question about merging all headers according to the template: maybe just worried how the ETH page would look like with gradient, not a very strong stance here.
> 
> Personally i think the design without gradient looks clearer and simpler and less corporate, but that is a different conversation.

Yes, we need to be careful about that one, need some design work to make it work


Regarding removing the gradient, is this what you have in mind?
Screen Shot 2024-09-12 02 14 23 PM

**Comment by konopkja** [comment]
> > lgtm what pablo did, regarding nuno's question about merging all headers according to the template: maybe just worried how the ETH page would look like with gradient, not a very strong stance here.
> > Personally i think the design without gradient looks clearer and simpler and less corporate, but that is a different conversation.
> 
> Yes, we need to be careful about that one, need some design work to make it work
> 
> Regarding removing the gradient, is this what you have in mind? Screen Shot 2024-09-12 02 14 23 PM

yes but not for this sidebar template, that one looks terrible without further adjustements

**Comment by nloureiro** [comment]
> > > lgtm what pablo did, regarding nuno's question about merging all headers according to the template: maybe just worried how the ETH page would look like with gradient, not a very strong stance here.
> > > Personally i think the design without gradient looks clearer and simpler and less corporate, but that is a different conversation.
> > 
> > 
> > Yes, we need to be careful about that one, need some design work to make it work
> > Regarding removing the gradient, is this what you have in mind? Screen Shot 2024-09-12 02 14 23 PM
> 
> yes but not for this sidebar template, that one looks terrible without further adjustements

😅 like you said, another conversation...

I was trying to see if we could pull a quick hack, but no

**Review by nloureiro — APPROVED** [review]

**Review by wackerow — APPROVED** [review]
Let's go!! 🔥 💪 
Thanks for this, nice job @pettinarip!

**Pull request merged**
