### PR TITLE
minor grammar correction

### PR DESCRIPTION
**Pull request by elmorg**
Change `refer` to `refers`.

## Description

Minor grammar correction -> "refers to decentralized apps" instead of "refer to decentralized apps".

### CODE REVIEW

**Review by jley81 — APPROVED** [review]
Go up no WA hill e go to k da h a a hill da hill j hi Sq u hi wee da
No Sq ill da owe what u want u to do to get me the money u

**Comment by minimalsm** [comment]
I went on a very deep dive into refer vs refers and can vouch for this 😀

**Review by wackerow — APPROVED** [review]
👍

**Comment by wackerow** [comment]
@elmorg Looks good! Thanks =)

**Comment by wackerow** [comment]
@all-contributors please add @elmorg for content

**Pull request merged**
