### PR TITLE
ModifiedDoc

### PR DESCRIPTION
**Pull request by mohitlovecoding**

### CODE REVIEW

**Comment by samajammin** [comment]
Hey @mohitlovecoding - thanks for the PR! Could you please explain these changes? We just received very similar PRs (#1557 & #1558) - wondering if these are coming from bots 🤔

**Review by ryancreatescopy — COMMENTED** [review]
Thanks for the PR but these changes: 
- are grammatically incorrect
- use more complicated words than necessary
- remove our conversational tone

for example:
Line 18 doesn't need a `?`
Line 83 doesn't make sense with `read to our documentation`
Line 87 `Credits` plural doesn't read as well as `Thanks`

**Comment by Trott** [comment]
@ryancreatescopy You might want to [add an `invalid` label](https://hacktoberfest.digitalocean.com/details/#spam) to this one.

**Comment by Trott** [comment]
> Hey @mohitlovecoding - thanks for the PR! Could you please explain these changes? We just received very similar PRs (#1557 & #1558) - wondering if these are coming from bots 🤔

It's people trying to get a Hacktoberfest t-shirt without meaningfully contributing to open source. By adding the `invalid` or `spam` label to the PRs, it prevents them from being counted (since Hacktoberfest doesn't require a PR to land for it to count, so just closing it allows the author to get credit for the PR anyway).

**Pull request closed without merging**
