### PR TITLE
Create DBW20

### PR DESCRIPTION
**Pull request by eberhardtj**

### CODE REVIEW

**Review by samajammin — CHANGES_REQUESTED** [review]
Hey @eberhardtj - I appreciate the effort here!

To add an event to our community page, you'll want to edit this file:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/community/index.md

1) Click the "Edit this file" (pencil icon) at the top right
2) Add your event to the "Upcoming events" section (here's a [guide on Markdown syntax](https://guides.github.com/features/mastering-markdown/)), e.g.
```
- [Dutch Blockchain Week](https://www.dutchblockchainweek.com/ ) - _Virtual Conference_ (December 2-8, 2020)
```
 3) Click "Commit changes" to create a new branch & submit the PR

**Comment by eberhardtj** [comment]
Thank you for the tips! Done. (hopefully..)

**Comment by samajammin** [comment]
@eberhardtj I'm not seeing any new commits or a new PR?

**Comment by ryancreatescopy** [comment]
Closing out in favour of #1708

**Comment by eberhardtj** [comment]
> Closing out in favour of #1708

Hey @ryancreatescopy I deleted the spaces for the link to work properly. Is there something else I should do ?

**Pull request closed without merging**
