### PR TITLE
Sort meetup list

### PR DESCRIPTION
**Pull request by amm98d**
## Description

Added a function that implements the Fisher-Yates Shuffling algorithm.

## Related Issue

#4657

### CODE REVIEW

**Comment by amm98d** [comment]
Hey @samajammin, updated from random shuffling to sort by country+city. Kindly review.

**Review by corwintines — CHANGES_REQUESTED** [review]
Hey @amm98d, thanks for the contribution. At the moment this wont work. You'll need to do the following. 

- import lodash at the top of the file. You could even just import the sortBy method: `import { sortBy } from 'lodash'`
- store the sorted list in a variable: `const sortedMeetups = sortBy(meetups, ['emoji', 'location'])`
- use the sortedMeetups variable in the render method of this component where we map over the list of meetups. ie: `sortedMeetups.map`

**Comment by amm98d** [comment]
> Hey @amm98d, thanks for the contribution. At the moment this wont work. You'll need to do the following.
> 
> * import lodash at the top of the file. You could even just import the sortBy method: `import { sortBy } from 'lodash'`
> * store the sorted list in a variable: `const sortedMeetups = sortBy(meetups, ['emoji', 'location'])`
> * use the sortedMeetups variable in the render method of this component where we map over the list of meetups. ie: `sortedMeetups.map`

Understood. I followed the syntax from the documentation, my bad. Pushing changes shortly.

**Review by minimalsm — APPROVED** [review]
LGTM :-) the deploy preview isn't working right now (unrelated issue) but working fine locally.

**Review by wackerow — APPROVED** [review]
Looks good! Just cleared some merge conflicts since this file had been worked on since this PR. Thanks @amm98d ! Don't forget to swing over to Discord and claim your POAP =)

**Comment by wackerow** [comment]
@all-contributors please add @amm98d for code

**Pull request merged**
