### PR TITLE
Add asssets page

### PR DESCRIPTION
**Pull request by samajammin**
## Description
See details in the issue.

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/235

## Screenshots (if appropriate):
assets-page

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by samajammin** [comment]
@jjmstark still a WIP (need to add remaining assets) but the layout is ready for feedback.

**Comment by jjmstark** [comment]
This is great - only change I would make to general layout right now is that we should think about the order this information is presented. Is a person coming to this page most likely looking for previous landing page artwork, or an ethereum logo? We should make an informed choice, and then prioritize in that order.

**Comment by samajammin** [comment]
> Is a person coming to this page most likely looking for previous landing page artwork, or an ethereum logo? We should make an informed choice, and then prioritize in that order.

Agreed & I believe they're most likely looking for Ethereum image assets. I didn't find much search volume on any terms (a couple 10-100/month around "ethereum images") to give us much insight but my hunch is that it's a more common use case than checking out previous artwork. I think it's just a question of if we want to promote that program & get contributors to submit artwork.

**Comment by samajammin** [comment]
@jjmstark completed for Section 2 ("General Ethereum Graphic Assets") & for now just removed Section 1 ("Previous landing page artwork"). It's not the prettiest page but it at least makes all these assets available.

Do you have the credit information for the previous artwork (see description of the issue https://github.com/ethereum/ethereum-org-website/issues/235)?  If not we could merge this as is & create a separate TODO for that piece.

**Comment by jjmstark** [comment]
Not yet - let's merge and make that a separate PR.

**Pull request merged**
