### PR TITLE
Added Ethereum in Bengali (local to kolkata)

### PR DESCRIPTION
**Pull request by Kuekuatsheu95**

### CODE REVIEW

**Comment by sorumfactory** [comment]
Bengali is available on CrowdIn 👍

**Comment by samajammin** [comment]
Thanks for the addition! Hope you keep looking for way to contribute 😄

**Comment by samajammin** [comment]
@all-contributors please add @Kuekuatsheu95 for content & translation

**Comment by sorumfactory** [comment]
@Kuekuatsheu95 
+) Below is the link to join the Bengali translation :)
https://crowdin.com/project/ethereumfoundation/bn#

**Pull request merged**
