### PR TITLE
Updated job page links

### PR DESCRIPTION
**Pull request by ksaitor**
- Added more job search resources

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @ksaitor, if you or someone else could do us a favor and fill out an issue with the new product request below so we can take a closer look and we can get back to you 👍🏻 Thanks!

```
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

<!-- Name of the product -->

**Product description:**

<!-- What does it do? -->

**How long has it been around?**

<!-- We prioritise products that are battle-tested. -->

**Where do you think it should go?**

<!-- List the pages where you think this tool is most relevant on ethereum.org -->

**GitHub URL**

<!-- Please provide a link to the product's repo. -->

**Docs URL**

<!-- Please provide a link to the product's docs. -->

**Is the product open source?**

<!-- We prioritise open source projects when possible. -->

**Additional context**

<!-- Add any other context or screenshots about the feature request here. -->
```

**Comment by ksaitor** [comment]
Hi @minimalsm, thanks for looking into this. If I understood your request correctly, here is the details:

**Product name:** 
Crypto Jobs List

**Product description:** 
Cryptocurrency and Blockchain Job board. 

**How long has it been around?**
Since October 2017

**Where do you think it should go?**
https://ethereum.org/en/community/#ethereum-jobs

**GitHub URL**: 
https://github.com/cryptojobslist

**Docs URL**: 
n/a

**Is the product open source?**: 
Partially

**Additional context**
Been helping many projects in Ethereum space hire engineers and non-tech talent as well. Most notably: Argent Wallet, Prysmatic Labs, Giveth, MakerDAO, Dune Analytics, and others.
https://twitter.com/cryptojobslist
https://www.linkedin.com/company/cryptojobslist/

**Review by wackerow — APPROVED** [review]
@ksaitor looks good, thanks!

**Comment by wackerow** [comment]
@all-contributors please add @ksaitor for content

**Pull request merged**
