### PR TITLE
refactor: remove luxon package, replace with JS Intl library

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Updates `getLocaleTimestamp.ts` inside `src/lib/utils/time.ts` to use `Intl.DateTimeFormat` instead of luxon tooling. 
- Adds an optional `options` prop here to override display options as-needed
- Remove usage of luxon inside `CommunityEvents/index.tsx`, replacing with updated usage of `getLocaleTimestamp`
- `yarn remove luxon @types/luxon`

## Related Issue
https://www.notion.so/efdn/Review-if-we-can-replace-some-packages-with-native-implementation-1875f79b99f04555aa60bb5f7b14e8c0?pvs=4

Fixes https://github.com/ethereum/ethereum-org-website/issues/12019

## Summary by CodeRabbit

- **Refactor**
	- Improved date handling across the app for better localization and efficiency.
- **New Features**
	- Updated display logic for last updated and deploy dates to enhance user experience.
- **Chores**
	- Removed unnecessary dependencies and streamlined date formatting.

### CODE REVIEW

**Comment by nhsz** [comment]
@wackerow Excellent! Seems we also need to remove `@types/luxon`

**Comment by wackerow** [comment]
Good catch; removed the types package... thanks @nhsz!

**Comment by wackerow** [comment]
Getting a strange result where the lastDeployDate in the Footer is causing the build to fail with:

```
Export encountered errors on following paths:
        /_error: /500
       ...
```

Added a temporary debugging patch to check for paths starting with `/500` and skipping the rendering of the deploy date for those cases. Want to see if this builds okay on Netlify (working locally), but I don't really see this as a final solution though; open to thoughts.

**Review by pettinarip — CHANGES_REQUESTED** [review]
Nice job! All looks fine @wackerow except this one in the tutorials page
image

**Review by pettinarip — APPROVED** [review]
Fixed! merging @wackerow 💪🏼

**Pull request merged**
