### PR TITLE
Fix spacing issue in the Staking page

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

- Adds a gap between sections.
- Migrates `h2`s to `Heading`s
- Removes inner margin from `StakingCommunityCallout` to be set by the parent

### CODE REVIEW

**Comment by nloureiro** [comment]
@TylerAPfledderer do you have safari?

This PR break the page on my side in safari, dunno if it's just me, because it's ok on all other browsers
Screen Shot 2023-05-16 09 19 59 AM

**Comment by nhsz** [comment]
> @TylerAPfledderer do you have safari?
> 
> This PR break the page on my side in safari, dunno if it's just me, because it's ok on all other browsers Screen Shot 2023-05-16 09 19 59 AM

confirmed, same issue in Safari

**Comment by pettinarip** [comment]
Good catch @nloureiro. Thanks for the confirmation @nhsz.

Will try to fix it soon.

**Comment by corwintines** [comment]
This is actually an issue in production as well, so wasnt introduced in this PR.

**Review by corwintines — APPROVED** [review]

**Pull request merged**
