### PR TITLE
✨ feat: Improve documentation for ERC-4626 interface 

### LINKED ISSUE #12870: ✨ feat: Improve documention ERC-4626 interface
### Is your feature request related to a problem? Please describe.

The documentation for the interface can benefit from
- Return variable names for view functions
- A visual map of the interface

### Describe the solution you'd like

Add the suggested content to the document

### Describe alternatives you've considered

N.A

### Additional context

_No response_

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by raxhvl**
## Description
- [x] Adds name return variable as defined in the [specs](https://eips.ethereum.org/EIPS/eip-4626)
- [x] A glanceable visual map of the interface that highlights: 
  - [x] Functions that MUST revert.
  - [x] Functions that MUST include fees.
  - [x] Functions that MUST NOT include fees.
  - [x] Functions that MUST round down.
  - [x] Functions that MUST emit events.

## Related Issue

closes #12870 

## Summary by CodeRabbit

- **Documentation**
	- Updated the ERC-4626 standards documentation to include more descriptive return values for functions handling assets, enhancing clarity and user understanding.

### CODE REVIEW

**Comment by raxhvl** [comment]
@coderabbitai review

**Comment by nloureiro** [comment]
@raxhvl, thank you for your contribution! 

I made a version more aligned with the overall style of the map image.

What do you think?  

map-of-erc-4626


If everything is ok with the image, can you make the change on the PR?

**Comment by raxhvl** [comment]
@nloureiro I love it!. A small fix: `convertToShares` and `convertToAssets` must be marked `MUST round down towards 0` and NOT `MUST NOT revert`. 

When you are done making the change, I will add that to the PR.


Thank you for making this look good, oh design whisperer!

**Comment by wackerow** [comment]
Great! @nloureiro assigning to you for design review, @ me when ready and I can do a final sweep

**Comment by nloureiro** [comment]
> @nloureiro I love it!. A small fix: `convertToShares` and `convertToAssets` must be marked `MUST round down towards 0` and NOT `MUST NOT revert`.
> 
> When you are done making the change, I will add that to the PR.
> 
> Thank you for making this look good, oh design whisperer!

oh, yes, my bad... should be good now

map-of-erc-4626

**Comment by raxhvl** [comment]
@nloureiro @wackerow All clear!

**Comment by nloureiro** [comment]
@raxhvl sorry... I saw it on a good display and realized I should have exported 2x the size.

Can you stitch with this one? 🙌
map-of-erc-4626

**Review by nloureiro — APPROVED** [review]

**Comment by raxhvl** [comment]
@nloureiro. Done! Quick heads up the resolution has increased but the image size is actually smaller 70 kb vs 77kb from earlier.

**Comment by nloureiro** [comment]
> @nloureiro. Done! Quick heads up the resolution has increased but the image size is actually smaller 70 kb vs 77kb from earlier.

yes, no worries. 77kb is still a pretty small size for this.

all is good on my end.

thank you for your contribution.

**Review by corwintines — APPROVED** [review]
Nice, LGTM! Thanks @nloureiro and @raxhvl!

**Comment by corwintines** [comment]
@all-contributors can you add @raxhvl for content

**Pull request merged**
