### PR TITLE
fix link to The Merge

### PR DESCRIPTION
**Pull request by Ghospel**
Link to "The Merge" page was referring to a faulty url.

## Description

I updated the link to the correct page.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks, @Ghospel!

**Comment by corwintines** [comment]
@all-contributors can you add @Ghospel for content

**Comment by corwintines** [comment]
Thanks for fixing this @Ghospel!

Make sure you come claim your POAP in the ethereum.org discord: https://discord.gg/CetY6Y4 :)

**Comment by Ghospel** [comment]
My pleasure!

**Pull request merged**
