### PR TITLE
chore: update shapeshift logo

### LINKED ISSUE #14084: Update ShapeShift Mobile logo
### Is your feature request related to a problem? Please describe.

The logo for ShapeShift Mobile is not the most recent version of the logo.

### Describe the solution you'd like

Update the logo following the new brand asset available here: https://shapeshift.com/brand-assets

### Describe alternatives you've considered

None, it seems pretty straight-forward.

### Additional context

The new logo to use: 

FOX SQUARE LOGO_White

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by firebomb1**
## Description

- Updates the ShapeShift Mobile wallet logo following the recent brand asset update.
- ~~Switching to SVG format.~~
- Update the wallet `last_updated` field.

## Preview link

https://deploy-preview-14085--ethereumorg.netlify.app/en/wallets/find-wallet

## Related Issue

- Closes #14084

### CODE REVIEW

**Comment by firebomb1** [comment]
Looks like SVG files aren't support through that config file yet, switching back to a 200x200 transparent PNG.

**Comment by wackerow** [comment]
Hey @firebomb1, thanks for the help here. Curious, you pointed to the [ShapeShift assets page](https://shapeshift.com/brand-assets) where I see this icon, but I also see an icon for light mode (black on white), and at the bottom I still see the blue icon that is being replaced in this PR.

Can you help clarify the changes here? Curious if you're affiliated with the ShapeShift team, or if you happened to come across this? Just trying to confirm that we actually want to switch this over, since the black background is a box in light mode and the blue circle handles that.

If we do want to switch, we should probably also adjust the "brand color" to black so the decorative fade line updates as well:

image

**Comment by corwintines** [comment]
+1, would like a bit of clarity around the brand assets here given what is currently being used exists on the assets page

**Review by wackerow — APPROVED** [review]
Great! Thanks for the explanation @firebomb1 
LGTM! Pulling in

**Comment by firebomb1** [comment]
No problem @wackerow, thanks for your care and the merge!

**Pull request merged**
