### PR TITLE
Added a hand waiving gif in place of Sticker.

### PR DESCRIPTION
**Pull request by Uttam-Singhh**
Just a minimal and quick change to the README File to enhance the view.
I Added a hand waiving GIF in place of a Sticker.

### CODE REVIEW

**Comment by Uttam-Singhh** [comment]
Please review @samajammin @wackerow @ryancreatescopy !

**Review by minimalsm — CHANGES_REQUESTED** [review]
Could you add an alt to the image for accessibility :)

https://support.siteimprove.com/hc/en-gb/articles/115000013031-Accessibility-Image-Alt-text-best-practices

**Comment by Uttam-Singhh** [comment]
Sure!

**Comment by Uttam-Singhh** [comment]
Is it good to go to get merged?😅

**Comment by minimalsm** [comment]
> Is it good to go to get merged?😅

One of the core devs will review it next week. They're pretty swamped so please have patience 🙏  Thanks again ❤️

**Comment by wackerow** [comment]
Hah, I guess I don't have any objection here other than maybe how it's infinite... @ryancreatescopy thoughts here?

**Comment by ryancreatescopy** [comment]
how do I preview this?

**Comment by wackerow** [comment]
@ryancreatescopy https://github.com/ethereum/ethereum-org-website/blob/11b394a7b35f3339bfe81cdee295a844147cc203/README.md

**Comment by Uttam-Singhh** [comment]
What about this?

**Review by wackerow — APPROVED** [review]
@Uttam-Singhh 👍🏻 LGTM =)

**Comment by Uttam-Singhh** [comment]
Thank you!

**Pull request merged**
