### PR TITLE
Add placeholder avatar to prevent layout jumping [Fixes #2809]

### LINKED ISSUE #2809: No loading state for FileContributors components
**Describe the bug**

As a result of #2713, the FileContributors component creates a jumpy interaction on page load.

**To Reproduce**

1. Go to a documentation / tutorial page
2. View jump in layout when component data loads

e.g. screencast:

https://user-images.githubusercontent.com/8097623/114082565-c12b7600-9862-11eb-81dc-3f0d3cd2e6f7.mp4

**Expected behavior**

We should add a loading state, e.g. with a dummy avatar or at least keeping the component height consistent during loading state so the page layout doesn't jump. Will need to account for different screen sizes.

**Screenshots**

See above

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

I believe we can also remove `gatsby-source-graphql` now that we're fetching Github data client-side?
https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-config.js#L223

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by hueyhe**
## Description

Add placeholder avatar to prevent layout jumping [Fixes #2809]

### CODE REVIEW

**Comment by wackerow** [comment]
@hueyhe Hey, thanks for doing this! Was just looking at it, seems to work pretty well.

I'll defer to @ryancreatescopy on styling comments, then I'll be happy to double check the code and bring this in 👍🏻

**Comment by ryancreatescopy** [comment]
I think it'd be cool if we had a loading state for text and button too. Maybe something like this super rough sketch:
image

could even add some kind of light animation to it to suggest it's loading, it looks a little jerky right now.

**Comment by hueyhe** [comment]
> image

@ryancreatescopy OK. I'll work on that.

**Comment by hueyhe** [comment]
@ryancreatescopy I've updated the skeleton style and added a transition from the loading state to loaded state.
FYI, I'm not good at picking colors. The skeleton might look a bit bright in dark mode. Please tell me if you have any suggestion.

**Comment by wackerow** [comment]
Added a commit using some of our theme colors instead, which respond to light and dark mode. 
image
image

**Review by wackerow — CHANGES_REQUESTED** [review]
image
@hueyhe I like how this is coming along! Noticed this causes a bug on mobile though, mind taking a look at that?
May just be a matter of hiding the contributors button until loading is done.

**Comment by hueyhe** [comment]
@wackerow I've fixed the bug on mobile. Please comment if there's any other problem.

**Review by wackerow — APPROVED** [review]
@hueyhe lookin good! Thanks for being patient, pulling in now =)

**Comment by wackerow** [comment]
@all-contributors please add @hueyhe for code

**Pull request merged**
