### PR TITLE
Added AlphaWallet mobile wallet

### PR DESCRIPTION
**Pull request by jzaki**
Added to list of wallets

## Description

added url+description

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jzaki** [comment]
@samajammin Do you know what is the fault with Labeler?
```
##[error]HttpError: Resource not accessible by integration
##[error]Resource not accessible by integration
##[error]Node run failed with exit code 1
```

**Comment by samajammin** [comment]
@jzaki don't worry about that failure. I fixed that issue in https://github.com/ethereum/ethereum-org-website/pull/345

**Comment by jzaki** [comment]
Is there anything else needed for this PR? AlphaWallet has remained opensource, and originally forked from TrustWallet (it stopped updating the public repo).

**Comment by samajammin** [comment]
@jjmstark please review. Thanks!

**Comment by jzaki** [comment]
Hey Josh (@jjmstark) What are your thoughts on this? Is this blocked on us?

**Comment by samajammin** [comment]
Thank you for your submission & apologies for the delayed reply! We've paused adding new wallets to this list for now, but have taken note of this submission for the future. We are considering ways to expand or rotate this list to include more options, while also ensuring a simple and clear process for the user.

**Pull request closed without merging**
