### PR TITLE
Update the Ethereum website's footer, replace the Twitter logo with the new X logo. 

### LINKED ISSUE #11567: Update the Ethereum website's footer, replace the Twitter logo with the new X logo.
### Description

This issue addresses the need to replace the existing Twitter logo with the new X logo in the footer of the Ethereum website. The update is essential for maintaining a consistent and up-to-date brand identity on the website. The current Twitter logo should be replaced with the approved X logo in the designated footer section. This change not only ensures brand consistency but also provides a refreshed look for the website, aligning it with the latest branding guidelines.

### PR DESCRIPTION
**Pull request by shubhusion**
Update the Ethereum website's footer, replace the Twitter logo with the new X logo. 

## Description

Updated react icons version and Updated Old Twitter logo with the new X logo

## Related Issue

Fixes #11567

### CODE REVIEW

**Comment by darigovresearch** [comment]
Thanks for making a pull request @shubhusion 

Currently cant check if the pull request resolves the issue, can any maintainers advise on the live preview?

It currently says page not found

image

**Comment by shubhusion** [comment]
I tested the changes on my local server before making PR. However, I will double-check why there is a "Page Not Found" error and try to rectify the issue.

**Comment by corwintines** [comment]
@all-contributors can you add @shubhusion for idea

**Comment by corwintines** [comment]
Thanks @shubhusion 

We aren't interested in changing the logo at this time. More information can be found here: https://github.com/ethereum/ethereum-org-website/pull/11224

**Pull request closed without merging**
