### PR TITLE
Adding the Status DApp Integration Center

### PR DESCRIPTION
**Pull request by jinhojang6**
A pull request to add the DApp Integration Center to the Developer Resources page( https://ethereum.org/developers/#other-tools)

## Description

The Dapp Integration Center is a step by step guide to optimize dapps for use in Status. This includes mobile first best practice, security and privacy requirements, leveraging the Status API, and how to submit to [dap.ps](https://dap.ps/).

## Related Issue
The DApp Integration Center: https://github.com/ethereum/ethereum-org-website/issues/593

## Screenshots (if appropriate):
Screen Shot 2019-12-03 at 2 22 14 AM

### CODE REVIEW

**Comment by samajammin** [comment]
@CPSTL please review at your earliest convenience. Thanks!

**Comment by jinhojang6** [comment]
@samajammin @CPSTL 

Can I know how the review is going? :)

**Comment by CPSTL** [comment]
@jinhojang6 Just one comment from me - it may make more sense to dedicate this PR to the homepage of https://status.im/docs/ rather than just submitting it for the Dapp Integration Center. 

For example, you could create the PR for https://status.im/docs/ and have it appear like so: 

**Status - a messenger, crypto wallet, and Web3 browser built with state of the art technology.**
- Documentation
- DApp Integration Center
- Get Help

WDYT?

**Comment by samajammin** [comment]
That suggestion makes sense to me @CPSTL, given that Status isn't mentioned anywhere else on the site (other than a link to Embark).

**Pull request closed without merging**
