### PR TITLE
Add ETHVietnam to community-events

### PR DESCRIPTION
**Pull request by Tuongg2312**
"title": "ETHVietnam",
    "to": "https://www.eth-vietnam.com/",
    "sponsor": null,
    "location": "HoChiMinh City, Vietnam",
    "description": "The Ethereum Vietnam is the largest & the first annual Vietnam Ethereum event focused on technology and community.",
    "startDate": "2022-08-31",
    "endDate": "2022-09-04"

## Description
ETHVIETNAM 2022 is the first blockchain
conference in Vietnam with the organizers
of global large-scale iconic blockchain and
cryptocurrency. Empowers participants to
shape this new world, while cementing the
Viet community as a thriving hub of
Ethereum and blockchain innovation

### CODE REVIEW

**Review by Tuongg2312 — COMMENTED** [review]
Nice event, very useful for me

**Comment by minimalsm** [comment]
Hey @Tuongg2312, are you involved in this event?

Just calling out the website is pretty broke...

- Many blank pages
- Many of the links are 404s
- Template used hasn't been fully removed (see image below)
- There are mentions of dates around Feb 2022?

Screenshot 2022-06-17 at 13 54 37

**Comment by Tuongg2312** [comment]
Hi @joshua , thanks for your feedback about our website problems. We’ll fix
it as soon as possible.

I’m Tuong , come from Vietnam and my main job is graphic designer.
Together with my team, we want to organize the ETHVietnam event, in order
to bring a lot of value to the local and global community.

This is the first ETH conference held in vietnam and we don’t have enough
experience in this, so we really need advice and suggestions from you guys
on the issues we might be facing.

 Thanks and hope to hear from you soon !!





Vào Th 6, 17 thg 6, 2022 lúc 19:56 Joshua ***@***.***> đã
viết:

**Comment by minimalsm** [comment]
Hey @Tuongg2312 :-) As I understand it, things are still slightly TBD on the dates for your events? Please re-submit when the dates are 100% finalized, and the website reflects this. good luck with the event!!

**Pull request closed without merging**
