### PR TITLE
Image optimzation

### PR DESCRIPTION
**Pull request by howdyAnkit**
## Description
This PR is regarding the Tool Feature #1658

Imgbot Optimizes Images and optimizes the Images Automatically

This PR is all about Image Optimization and Image Compression Done With the help of a Simple Tool Imgbot.

You can Find Imgbot On the Internet Here -> https://imgbot.net/
You can read More about Imgbot Here -> https://imgbot.net/docs/
You can create Your own Workflow From here -> https://github.com/marketplace/imgbot

## Related Issue

#1658

### CODE REVIEW

**Comment by samajammin** [comment]
@howdyAnkit thanks for submitting this! Is this ready for review? I saw you mentioned something in Discord about opening a separate PR.

**Comment by howdyAnkit** [comment]
Yeah @samajammin this is ready for review. the previous PR was having some merge conflicts so I had to close that PR and fix the mentioned merge conflicts in this PR. 

Thankyou :)

**Review by samajammin — CHANGES_REQUESTED** [review]
Looks great @howdyAnkit but please remove the package-lock.json file. We use a yarn.lock in this project.

Thanks!

**Review by samajammin — APPROVED** [review]
LGTM! Thanks!

**Comment by samajammin** [comment]
Whoops, I didn't notice all the merge commits until after I merged 😩 

@howdyAnkit next time, please make sure you branch off `dev`, not `master` so we avoid all these merge commits from your PR. More on the dev process here: https://github.com/ethereum/ethereum-org-website#the-contribution-process

**Comment by howdyAnkit** [comment]
Thankyou @samajammin for addressing this really learned a great Lesson today.
Will keep this in mind. Sorry for creating the trouble 😔.

**Pull request merged**
