### PR TITLE
Update Aave logo

### PR DESCRIPTION
**Pull request by omahs**
Resolves https://github.com/ethereum/ethereum-org-website/issues/13341

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
Thanks @omahs! Logos look good, but I think we need to adjust these.

We current display the Aave logo on two pages:
- `/dapps` page -- `public/images/dapps/aave.png`
- `/stablecoins` -- `public/images/stablecoins/aave.png`

On `/stablecoins` we have a gradient background applied, and to match Aave branding I would suggest we use a white monochrome with a transparent background, so it looks similar to <https://aave.com/>:

image

For the `/dapps` page we should try to use a square aspect-ratio, so I would use the file currently being used here for the `/stablecoins` page (colored circle with white logo inside)

**Comment by omahs** [comment]
@wackerow Thanks for the quick review! I updated the files

**Review by wackerow — APPROVED** [review]
Looks good! Thanks @omahs, I just pushed a commit to resize the icon back to the previous 160px. Pulling in!

**Comment by wackerow** [comment]
@all-contributors please add @omahs for maintenance

**Pull request merged**
