### PR TITLE
fix(typo): Norveçce

### PR DESCRIPTION
**Pull request by Periyot**
## Description

typo should be Norveççe instead of Norveçce

### CODE REVIEW

**Review by corwintines — COMMENTED** [review]
This looks correct when looking online @minimalsm @lukassim

**Comment by Periyot** [comment]
If you write Norveçce in the translation, you will not get an error, but if you translate the result, we can see that it is Norveççe, also it appears as Norveççe in the wikipedia link: https://tr.wikipedia.org/wiki/Norveççe

**Comment by minimalsm** [comment]
Hey, thanks for the PR @Periyot. Please note that changes to translated content are usually handled in Crowdin, the localization tool we use, since all the content there gets reviewed by our language service provider. We've checked and will merge this but you can also suggest future fixes and improvements in Crowdin.

If you want to get involved with the Translation Program, [you can join the translation project in Crowdin](https://crowdin.com/project/ethereum-org). 

You can find more information about the program and using Crowdin on the [Translation Program page on the website](https://ethereum.org/en/contributing/translation-program/).

**Comment by minimalsm** [comment]
@all-contributors please add @Periyot for docs, bugs

**Pull request merged**
