### PR TITLE
Updated PT-BR language resources

### PR DESCRIPTION
**Pull request by Gwinest**
Added an updated popular portal to the list of Ethereum related sources in brazilian portuguese.

### CODE REVIEW

**Comment by wackerow** [comment]
@isabelladebrito or @minimalsm Are we looking to list this type of resource? Little hard for me to tell, but appears to be an investors guide?

**Comment by Gwinest** [comment]
Yes, it is an investors guide, it has some Ethereum related guides,
including EIPs descriptions and explanations in Portuguese, I'm a developer
and I find it very useful

Em sex., 26 de jul. de 2024 18:47, Paul Wackerow ***@***.***>
escreveu:

**Comment by corwintines** [comment]
If there are any specific pages for the EIP's then I think its ok. But, as a whole if there is a lot of investor guides then I don't think there is a need for it.

**Comment by corwintines** [comment]
Going to close this out as is @Gwinest. But, if you would like to suggest some resources on EIPs that would be good here. Wary of including stuff investor guide material.

**Pull request closed without merging**
