### PR TITLE
Use proper capitalisation for Ewasm

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Review by ryancreatescopy — COMMENTED** [review]
Thanks for flagging. Does it even need capitalisation at all? I've seen it as `ewasm` in a lot of places.

**Comment by axic** [comment]
It was eWASM, ewasm, then Ewasm stylistically. The two most accepted versions are Ewasm and ewasm. I don't really mind if this PR is merged or not.

**Comment by wackerow** [comment]
image
The GitHub repo seems to default to just `ewasm` 
Given this, with how much ambiguity there is in the community, I'm in favor of just leaving all lowercase

**Comment by wackerow** [comment]
Hah.. and noticing even more ambiguity in that one of the repos in that screenshot use "Ewasm"... Overall I'm indifferent on this one I guess, but I do like the idea of trying to pick one and be consistent.

**Comment by axic** [comment]
Yes, in the end we did not follow through at every single occasion to rename it. We do use Ewasm in every single [team update on the EF blog](https://blog.ethereum.org/2020/12/09/ef-supported-teams-research-and-development-update-2020-pt-2/#ewasm) and other public communication.

**Comment by axic** [comment]
> I'm in favor of just leaving all lowercase

The etherem.org website currently uses eWASM, fyi.

**Review by ryancreatescopy — APPROVED** [review]

**Comment by ryancreatescopy** [comment]
@all-contributors please add @axic for content.

**Review by samajammin — APPROVED** [review]
👍

**Comment by axic** [comment]
Thanks!

**Pull request merged**
