### PR TITLE
Updated nav structure and added new home icon

### PR DESCRIPTION
**Pull request by ryancreatescopy**
## Description

Reorganising the nav structure of ethereum.org to house future content.

### Todo: 
- [ ] update footer with same structure as nav bar
- [x] addd aria labels to new navbar dropdowns

### CODE REVIEW

**Comment by samajammin** [comment]
@ryancreatescopy FYI I added the aria labels

**Comment by wackerow** [comment]
This looks great btw! Couldn't help but dive in...

...Not sure how to incorporate this without a separate PR, but 3f104e1 updates this to check off that other todo box if you want to use it. 

image

**Comment by ryancreatescopy** [comment]
> @ryancreatescopy This looks great btw! Couldn't help but dive in...
> 
> ...Not sure how to incorporate this without a separate PR, but [3f104e1](https://github.com/ethereum/ethereum-org-website/commit/3f104e13d786fc9dbad3e606f592d86dc26df82b) updates this to check off that other todo box if you want to use it.
> 
> image

Thanks Paul! I defer to @samajammin on how to get that commit into this PR. 

A few comments on the footer though:
- Community will be it's own section in the new reorg, so this should be reflected in the footer
- Perhaps we go with two rows in the Footer as having 6 columns could look a little tight

**Comment by ryancreatescopy** [comment]
@samajammin made a few tweaks in the last commit but there seems to be some strange things happening... items that won't disappear from the nav in content `> 1.1` and strings that won't update even when I change them in `en.json` – let's chat through this!

**Comment by wackerow** [comment]
@ryancreatescopy hah, yeah I see the "Community" change now... was wondering why it was in two places before. 

@samajammin I'll take a look at this and let you know if I can figure it out. If I'm able to fix it, would it be easiest to just submit a second PR since I don't have access?.. let me know if you have other thoughts, in meantime any changes I'll just post to my fork and reference.

**Comment by wackerow** [comment]
@ryancreatescopy I suspect this issue (items not disappearing from nav content > 1.1) is centered around here:
https://github.com/ethereum/ethereum-org-website/blob/5c770cc86a6ee783a5216272c69532f7108672f7/src/components/Nav/index.js#L314
_// If contentVersion includes EDN (>1.1), strip out Developers links for desktop nav (those versions use SubNav instead)_

This new layout has a new dropdown menu for 'Developers' header, so this step of 'striping out' the Dev links to leave a plain 'Developers' header button does not seem necessary anymore.

Changing the above line to "false" (or just commenting out the entire `linkSections.splice()`) gets rid of the redundant 'Developers' header menu.

**Comment by samajammin** [comment]
Closing in favor of #1738

**Pull request closed without merging**
