### PR TITLE
Removed pointer from bootcamps at developers Learning page (Fixes #13521) 

### LINKED ISSUE #13521: Bug report
### Describe the bug

In [Developers Learning tools](https://ethereum.org/en/developers/learning-tools/) and Developer bootcamps section when we open [Pointer](https://pointer.gg/) **Learn web3 dev skills with fun interactive tutorials. Earn crypto rewards along the way** the link shows 404 deployment not found.

### To reproduce

1. Go to 'https://ethereum.org/en/developers/learning-tools/'
2. Scroll down to 'Developer bootcamps'
3. Click on Pointer

### Expected behavior

When we go to [Developers Learning tools](https://ethereum.org/en/developers/learning-tools/) and scroll down to Developer bootcamps inside that section we have various platforms including[ Pointer](https://pointer.gg/) 
image
but when we click on the link of Pointer it shows 404. Kindly it'd be corrected with it's original link. 

### Screenshots

image
ss

### Desktop (please complete the following information)

- OS: [windows 11]
- Browser: [Chrome]

### Smartphone (please complete the following information)

- Device [techno pova]
- OS [android 10]
- Browser: [Chrome]

### Additional context

_No response_

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by panditdhamdhere**
Bug report #13521

## Description
In [Developers Learning tools](https://ethereum.org/en/developers/learning-tools/) and Developer bootcamps section when we open [Pointer](https://pointer.gg/) Learn web3 dev skills with fun interactive tutorials. Earn crypto rewards along the way the link shows 404 deployment not found. 

I removed [Pointer](https://pointer.gg/) from the code as it was assigned to me.

[issue here](https://github.com/ethereum/ethereum-org-website/issues/13521#issuecomment-2273912268)

### CODE REVIEW

**Comment by panditdhamdhere** [comment]
Hi @pettinarip can anyone review this

**Review by minimalsm — CHANGES_REQUESTED** [review]
Thanks for the PR @panditdhamdhere 💪 

This looks good, but I think we should do the additional cleanup in this PR also. Would you be able to: 

- remove all instances of "page-developers-learning-tools:page-learning-tools-pointer-description" from our intl files? (a search and remove of these will do it)
- delete the image that we were importing (@/public/images/dev-tools/pointer.png)

Thanks!

**Comment by panditdhamdhere** [comment]
Hi @minimalsm Can you please check now and give me feedback? Thank you very much for your suggestions.

**Review by corwintines — APPROVED** [review]
LGTM, thanks @panditdhamdhere!

**Comment by corwintines** [comment]
@all-contributors can you add @panditdhamdhere for code

**Pull request merged**
