### PR TITLE
refactor: postmergebanner to chakra

### PR DESCRIPTION
**Pull request by ImMiguelP**
## Description

Migrates `PostMergeBanner` component from `emotion` to `chakra-ui`

## Related Issue
#8632

### CODE REVIEW

**Review by TylerAPfledderer — COMMENTED** [review]
LGTM! 🚀 

Not block: For #8806, might want to remove flexbox styling here for that issue's PR in favor of applying it directly to `BannerNotificaton`.

**Comment by ImMiguelP** [comment]
> LGTM! 🚀
> 
> Not blocking: For #8806, might want to remove flexbox styling here for that issue's PR in favor of applying it directly to `BannerNotificaton`.

Sounds good so in this scenario the Center component will be used to keep all texts centered. I'll commit the new code rn.

**Comment by TylerAPfledderer** [comment]
@ImMiguelP make sure to remove the `justifyContent` prop if `Center` is being used, because the component will render the center value.

**Review by pettinarip — APPROVED** [review]
Good job @ImMiguelP. Merging this for now and I agree that we shouldn't need the use of `Center` in this component once #8806 gets fixed.

**Pull request merged**
