### PR TITLE
docs/build: Add Backend APIs -> Infura

### PR DESCRIPTION
**Pull request by shazow**
I added a new section for Backend APIs to add Infura.

Let me know if there's a better place to put it. :)

### CODE REVIEW

**Comment by jjmstark** [comment]
@maurelian thoughts on categorization here? I think this is probably fine as-is but want others input.

**Comment by shazow** [comment]
Could always move it elsewhere later. :)

**Comment by shazow** [comment]
Ping. :cactus:

**Comment by shazow** [comment]
CI looks good, merge away. :)

**Pull request merged**
