### PR TITLE
doc: fix Stack size typo in Understanding the Yellow Paper EVM's spec…

### LINKED ISSUE #10983: Bug report
### Describe the bug

Typo on https://ethereum.org/en/developers/tutorials/yellow-paper-evm/#91-basics (I think the stack should be 1024 items, not bytes)

Written:
```The maximum size of the stack is 1024 bytes```

Correction:
```The maximum size of the stack is 1024 items, each of size 256 bits```

Note:
If Stack is of size 1024 bytes, then it can only store up to 32 items at a time. Which is contrarian to https://www.evm.codes/about#stack :
```
The stack currently has a maximum limit of 1024 values. 
```

### To reproduce

1. Go to https://ethereum.org/en/developers/tutorials/yellow-paper-evm/#91-basics
2. Click on search "1024 bytes"
3. See error

### Expected behavior

I think the stack should be 1024 items, not 1024 bytes

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by Eikix**
I read in https://www.evm.codes/about#stack that the Stack has a size of 1024 elements, each of 256 bits, rather than the Stack being of size 1024 bytes (32 elements of 32 bytes)

## Related Issue

Resolves #10983

### CODE REVIEW

**Comment by minimalsm** [comment]
Thanks @Eikix!

@qbzzt could you review?

**Review by qbzzt — APPROVED** [review]
I feel bad I made the mistake - thank you for fixing it for me.

**Review by wackerow — APPROVED** [review]
Looks good! So sorry for delays here, thank you for patching @Eikix!

**Comment by wackerow** [comment]
@all-contributors please add @Eikix for bug fix

**Pull request merged**
