### PR TITLE
Add Origin Ether to staking products

### LINKED ISSUE #10293: Add Origin Ether dapp
### Project name

Origin Ether

### Product type

Staking pool

### If other product type, please describe

_No response_

### Logo

OETH

### Description

Origin Ether (OETH) is a ETH LSD aggregator that combines the yield-generating functions of Lido, Rocket Pool, and Frax into one single, diversified token.

### Website

https://oeth.com/

### If software is involved, is everything open source?

Yes, everything is open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

Yes, OETH is a fork of OUSD

### Is the product out of beta development?

The Origin Ether dapp repo can be found via https://github.com/originprotocol.

Origin Ether is a fork of Origin Dollar: https://ousd.com/ 

### What wallets support the product or service?

Any wallet that supports ERC20 tokens can support OETH.

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

There is no minimum ETH required to use OETH.

### If a service, what are the fees associated with using the service?

There is a 20% performance fee on the yield generated when using OETH. There is also a 0.0025% exit fee when exiting OETH through the dapp, which is avoidable when exiting through any supported DEX.

### If the product or service involved a liquidity token, what are the tokens involved?

OETH is backed by WETH and the following liquid staking derivates:

Lido stETH: 0xae7ab96520de3a18e5e111b5eaab095312d7fe84
Rocketpool rETH: 0xae78736cd615f374d3085123a210448e74fc6393
Frax frxETH: 0xae78736cd615f374d3085123a210448e74fc6393
wETH: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

### What date did the project or service go live?

Origin Ether launched on May 16th 2023.

### Has the project undergone an external security audit?

Origin Ether has undergone multiple audits, all of which can be seen on the [Audits Page ](https://docs.oeth.com/security-and-risks/audits)of the OETH docs.

### Has the project undergone any security bug bounties?

There is an open bug bounty for up to $250k USD on [Immunefi](https://immunefi.com/bounty/origindollarousd/).

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

The OETH contracts are fully owned by the Timelock, which is controlled by OGV stakers.

### If a pooled staking service, can users participate as a node operator without permission?

Users can participate as a node operator without permission with OETH collateral Rocketpool, but not with OETH itself.

### If listing a staking-as-a-service, are users required to sign-up for an account?

_No response_

### If listing as staking-as-a-service, who has access to the signing keys?

_No response_

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

_No response_

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

_No response_

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

_No response_

### What platforms are supported?

OETH is available on all platforms.

### What user interfaces are supported?

OETH is available on all interfaces.

### Social media links

OP Core Twitter https://twitter.com/OriginProtocol
OP Defi Twitter https://twitter.com/OriginDeFi
Telegram	https://t.me/originprotocol
Discord https://discord.com/invite/ogn
Medium https://blog.originprotocol.com/
Github https://github.com/originprotocol
Facebook https://www.facebook.com/originprotocol/
Youtube https://www.youtube.com/c/originprotocol
Reddit https://www.reddit.com/r/originprotocol/
LinkedIn https://www.linkedin.com/company/originprotocol/
Tik Tok https://www.tiktok.com/@origin_protocol
Instagram https://instagram.com/originprotocol

### Would you like to work on this issue?

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by wackerow**
## Description
Adds Origin Ether to staking products under pool services

## Related Issue
- Closes #10293

### CODE REVIEW

**Review by corwintines — APPROVED** [review]

**Comment by hanniabu** [comment]
@wackerow with all due respect, what is up this addition?

1. It's actually not an LST at all and just a defi yield protocol that deposits your funds into other projects like Convex, Rocket Pool, Lido, and something called Morpho. This exposes uninformed users to additional risk that they're likely unaware of, and would love to ignore with the site advertising 9.36% APY.
2. There's only 223 holders so it's an extremely new/risky protocol on top of that: https://etherscan.io/token/0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3
3. It has a green checkmark for execution diversity, yet both Rocket Pool and Lido have a question mark. How can that be?

**Comment by sumpg41** [comment]
Hi @hanniabu, Peter from Origin Protocol here.

> 1. It's actually not an LST at all and just a defi yield protocol that deposits your funds into other projects like Convex, Rocket Pool, Lido, and something called Morpho. 

You are correct in that OETH is not an LST, it is a yield aggregator that uses 5 tokens for collateral: ETH, wETH, stETH, rETH, and frxETH. The 9.36% yield comes from a combination of the validator rewards of the 3 LSTs, plus deploying ETH/wETH on Curve/Convex and Morpho. Morpho is a reputable protocol with $320m+ in TVL, though at this time only 103.32 (0.67%) ETH of OETH collateral is going to Morpho.

> This exposes uninformed users to additional risk that they're likely unaware of, and would love to ignore with the site advertising 9.36% APY.

The OETH collateral makeup and how yield is generated is always available in real time on the [OETH homepage](https://www.oeth.com/). It is also available on the OETH [analytics page](https://www.oeth.com/analytics). We are not trying to hide anything, all of the information on OETH is readily available on the [OETH docs](https://docs.oeth.com/).

> 2. There's only 223 holders so it's an extremely new/risky protocol on top of that: https://etherscan.io/token/0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3

You are correct in that it is a new protocol - OETH launched just over 1 month ago, so it makes sense that the number of holders is smaller than other LSTs and aggregators. However, OETH uses 95% of the same code as [OUSD](https://etherscan.io/token/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86), which launched more than 2 years ago and hit a peak TVL of $300m with no issues. @wackerow maybe we can update the "BATTLE TESTED" section to a green checkmark because of this? The OUSD/OETH codebase has been [audited 10+ times ](https://docs.oeth.com/security-and-risks/audits) and OpenZeppelin is now on retainer to constantly review 100% of our smart contract changes. 

[Origin Protocol](https://www.originprotocol.com/) launched in 2017 and is a reputable project with the goal of onboarding the next 100M users to crypto. We prioritize security over new feature development at all times.

**Comment by sumpg41** [comment]
@wackerow, it looks like this was deleted from the website. Any info you can share?

**Comment by hanniabu** [comment]
It was removed because it's not an LSD

https://github.com/ethereum/ethereum-org-website/pull/10496

**Pull request merged**
