### PR TITLE
Fixed a typo in docs

### PR DESCRIPTION
**Pull request by SebastianSupreme**
## Description

Fixed a small grammar error in the documentation.
@minimalsm you missed this one during PR #8108. 😅

### CODE REVIEW

**Comment by samajammin** [comment]
Hmmm is this actually an error? Why should that be capitalized? 🤔

**Comment by samajammin** [comment]
I dont think it should be - it's not the beginning of a sentence...

**Comment by SebastianSupreme** [comment]
@samajammin 
In German, sentences are capitalized after a colon.
That's how it was supposed to look like from the beginning.
See https://github.com/ethereum/ethereum-org-website/pull/8108 for reference.

**Comment by samajammin** [comment]
Oh interesting! Didn't know that 😃

**Comment by SebastianSupreme** [comment]
@samajammin 
So... will you merge it?

**Review by corwintines — APPROVED** [review]

**Pull request merged**
