### PR TITLE
[WIP] purple color tokens as primary color

### PR DESCRIPTION
**Pull request by nloureiro**
We are working on a big transformation in the style, and this PR is to test:

- what if we have the "same" primary color? we choose purple

you can follow the color explorations here:
https://www.figma.com/design/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=16-58&t=ziK8H00GQthayEmc-1

### CODE REVIEW

**Comment by TylerAPfledderer** [comment]
@nloureiro if you'd like, in order to keep the workflow consistent, I can go through the [UI Test](https://www.chromatic.com/build?appId=63b7ea99632763723c7f4d6b&number=2665) check as a dev to make sure the application of this new color scheme is expected from the coding side.

And I can keep an eye on this PR and go through this check as new changes come in.

**Comment by nloureiro** [comment]
> @nloureiro if you'd like, in order to keep the workflow consistent, I can go through the [UI Test](https://www.chromatic.com/build?appId=63b7ea99632763723c7f4d6b&number=2665) check as a dev to make sure the application of this new color scheme is expected from the coding side. There are currently 181 changes I can review and approve.
> 
> And I can keep an eye on this PR and go through this check as new changes come in.

Oh, great.
That would be a good idea, is it possible to do it?

keep in mind that we will have purple as the main color but will start to use 3 more colors on the UI
red/magenta, blue, and green.

**Comment by TylerAPfledderer** [comment]
> > @nloureiro if you'd like, in order to keep the workflow consistent, I can go through the [UI Test](https://www.chromatic.com/build?appId=63b7ea99632763723c7f4d6b&number=2665) check as a dev to make sure the application of this new color scheme is expected from the coding side. There are currently 181 changes I can review and approve.
> > 
> > And I can keep an eye on this PR and go through this check as new changes come in.
> 
> Oh, great.
> That would be a good idea, is it possible to do it?
> 
> keep in mind that we will have purple as the main color but will start to use 3 more colors on the UI
> red/magenta, blue, and green.
> 
> 
> 
> 

Good to know, thank you!

I can simply go through the changes to approve or deny. I probably don't have the ability to push changes in the code.

**Comment by nloureiro** [comment]
This PR served it's purpose, it's time to rest

**Pull request closed without merging**
