### PR TITLE
Add CryptoValley jobs 

### PR DESCRIPTION
**Pull request by Unforkable**

### CODE REVIEW

**Comment by Unforkable** [comment]
Hello Ethereum Github Team,

First I'd like to apologize if I have done something weird. This is the first time I use github.

I would like to add the CryptoValley.jobs Job Board to the Crypto Jobs section. I think it could be helpful for people looking for Ethereum related jobs. Is this the way to do it? 

Thank you in advance for your help 🙏

**Comment by minimalsm** [comment]
Thanks for the PR @Unforkable,

We'll try to review this and get back to you as soon as we're able 😀❤️

**Review by minimalsm — APPROVED** [review]
Thanks @Unforkable 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @Unforkable for docs

**Pull request merged**
