### PR TITLE
Added a search input to the languages page

### LINKED ISSUE #3036: Add search to languages page
**Is your feature request related to a problem? Please describe.**

Request from Discord user - add search to the languages page:
https://ethereum.org/en/languages/

**Describe the solution you'd like**

Add a search input on the page that filters language results. Support search by both English & native language titles.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by cth0604**
## Description

Added a search input to the languages page so the languages can be dynamically filtered and rendered onto the page.

## Related Issue

[Fixes #3036]

### CODE REVIEW

**Comment by wackerow** [comment]
@cth0604 Nice! before diving further into the code, curious if we should consider adding a "clear" or "X" button somewhere with this to automatically clear and reset filters. Curious what @ryancreatescopy thinks from a UX standpoint.

Also, a thought would be to switch the placeholder text from "Search" to maybe "Filter" to distinguish it from the site-wide "Search"

Otherwise this looks to be working, and I like how it can filter based on both native and translated language names (ie. searching "esp" or "span" finds "espanol/spanish")

**Comment by cth0604** [comment]
@wackerow Thanks for the detailed feedback! I'll try making the suggested changes for the next commit.

**Comment by cth0604** [comment]
@wackerow I've made the suggested changes. Please take a look!

**Review by wackerow — APPROVED** [review]
@cth0604 Looks good! I made one small adjustment to make the width more mobile responsive. Thanks for this!

**Comment by wackerow** [comment]
@all-contributors please add @cth0604 for code

**Pull request merged**
