### PR TITLE
Add SettleMint to popular node services list

### PR DESCRIPTION
**Pull request by snigdha920**
## Description

SettleMint is a popular node as a service platform. Check it out! -> https://console.settlemint.com/ 

This PR proposes to add it to the popular node services list. 

## Related Issue

Added SettleMint (link to platform, link to docs) along with its various features in the list of popular node services.

### CODE REVIEW

**Review by minimalsm — CHANGES_REQUESTED** [review]
Hey @snigdha920, thanks for the PR 💪

Could you rearrange this so SettleMint is in alphabetical order [as per our product listing.](https://ethereum.org/en/contributing/adding-products/#product-ordering)

**Comment by snigdha920** [comment]
> Hey @snigdha920, thanks for the PR 💪
> 
> Could you rearrange this so SettleMint is in alphabetical order [as per our product listing.](https://ethereum.org/en/contributing/adding-products/#product-ordering)

Yes, I'll do that right away. Thanks for your prompt review!

**Comment by snigdha920** [comment]
> Hey @snigdha920, thanks for the PR 💪
> 
> Could you rearrange this so SettleMint is in alphabetical order [as per our product listing.](https://ethereum.org/en/contributing/adding-products/#product-ordering)

Fixed!

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
Thanks @snigdha920! Merging now.

Remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

**Comment by minimalsm** [comment]
@all-contributors please add @snigdha920 for docs

**Comment by snigdha920** [comment]
> Thanks @snigdha920! Merging now.
> 
> Remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

How exciting! Thanks 🙂

**Pull request merged**
