### PR TITLE
Fix typo on contributing page

### PR DESCRIPTION
**Pull request by nitin094-hub**
## Description

Made some changes to contributing page on the website.
## Related Issue

issue #5763

### CODE REVIEW

**Review by samajammin — APPROVED** [review]
Thanks for the fix!

**Comment by nitin094-hub** [comment]
Your welcome

**Comment by minimalsm** [comment]
Thanks again @nitin094-hub 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @nitin094-hub for docs

**Comment by nitin094-hub** [comment]
Defiantly want to contribute more !

**Pull request merged**
