### PR TITLE
Add ethereum-json-rpc.com

### PR DESCRIPTION
**Pull request by Destiner**
Adds a link and a short description for [ethereum-json-rpc.com](https://ethereum-json-rpc.com).

## Description

Adds a paragraph to the "Execution client spec" section on the "JSON-RPC" page, highlighting "Ethereum JSON RPC" tool — the interactive API playground for Ethereum JSON-RPC spec. One distinctive feature of the tool is that it allows the user to execute methods right from the browser.

The playground is [open-source](https://github.com/Destiner/ethereum-json-rpc).

> Disclaimer: I am the creator of the tool.

Recreating the PR to fix the file path.

### CODE REVIEW

**Review by wackerow — COMMENTED** [review]
This is great, thanks @Destiner!

I'm wondering if we want to highlight this a little bit more... It seems like it was kinda just plopped in that section.

What if add a heading just above the "JSON-RPC API Methods" section, ie: "JSON-RPC API playground", and had a sentence or two guiding people to this as an option to try out the endpoints found below?

**Comment by Destiner** [comment]
Hey @wackerow!

That makes sense. I've updated the copy as per your suggestion.

**Review by wackerow — APPROVED** [review]
Great! Thanks @Destiner, very nice tool that has always been missing here.

**Comment by wackerow** [comment]
@all-contributors please add @Destiner for tool

**Pull request merged**
