### PR TITLE
Update Roadmap.tsx

### PR DESCRIPTION
**Pull request by MahendraBishnoi29**
Refactor Roadmap.tsx
## Description

Removed Unnecessary {" "} from `Roadmap.tsx` component

### CODE REVIEW

**Review by minimalsm — COMMENTED** [review]
Hey @MahendraBishnoi29, thanks for the PR. Most of these spaces are required. See the screenshot please 🤔 

Screenshot 2022-09-08 at 17 01 41

**Comment by MahendraBishnoi29** [comment]
> > @minimalsm got it but why you didn't used `&nbsp;`🤔
> 
> `&nbsp` would mean that the end and start word in the sentences would be attached to each other which doesn't make much sense to me 🤔 it could also cause some issues at smaller screen sizes.

fine should i close this PR now?

**Comment by minimalsm** [comment]
Yeah, let's close this out. Thanks for trying to clean up though, we definitely need it 😀

**Comment by minimalsm** [comment]
@all-contributors please add @MahendraBishnoi29 for ideas

**Comment by MahendraBishnoi29** [comment]
> @all-contributors please add @MahendraBishnoi29 for ideas

where's this list of contributors 😀

**Comment by minimalsm** [comment]
> > @all-contributors please add @MahendraBishnoi29 for ideas
> 
> where's this list of contributors 😀

Here https://ethereum.org/en/contributing/#contributors :-)

**Comment by MahendraBishnoi29** [comment]
> > > @all-contributors please add @MahendraBishnoi29 for ideas
> > 
> > 
> > where's this list of contributors 😀
> 
> Here https://ethereum.org/en/contributing/#contributors :-)

i'm not there yet ☹

**Pull request closed without merging**
