### PR TITLE
Add Cartesi to Optimistic Rollups

### PR DESCRIPTION
**Pull request by colinsteil**
## Description

Cartesi has recently unveiled upgrading Descartes to Optimistic Rollups, the article and spec can be found here: https://medium.com/cartesi/scalable-smart-contracts-on-ethereum-built-with-mainstream-software-stacks-8ad6f8f17997

## Related Issue

Addition

### CODE REVIEW

**Review by tasdienes — APPROVED** [review]

**Comment by samajammin** [comment]
Thanks for the PR! @all-contributors please add @colinsteil for content.

**Comment by colinsteil** [comment]
Thanks guys! Will this be reflected on the site soon?

**Comment by samajammin** [comment]
@colinsteil just deployed! Should be live within 10 min or so.

**Comment by colinsteil** [comment]
Hey Sam,

Thanks a bunch!

Cheers,

Colin

**Pull request merged**
