### PR TITLE
Footer navigation update [Closes #11955, Closes #12376]

### LINKED ISSUE #11955: Epic: Implement navigation redesign
## Summary
Last quarter (Q4 2023) designs were created for a revamp of the ethereum.org navigation bar. Feedback on the existing navigation structure left many users unsure of where to start, or how to access the information they are looking for quickly.

The new designs offer a tiered approach, revamping the old top-level navigation, and re-prioritizing and re-organizing different pages to improve user experience.

This quarter (Q1 2024) these design changes are planned to be implemented on the site. This includes implementing the new nav bar layout, and improving accessibility of these items for keyboard users and screen readers.

## Design
https://www.figma.com/file/VFKy8nGjdd4PuSdogBUJGA/Redesign-menu-navigation?type=design&node-id=1207-122492&mode=design&t=9ELyGK0OXhohPIGm-0

## Notion
https://www.notion.so/efdn/Implement-navigation-changes-aa93cef4f2244acb96bb12e9f54e5271?pvs=4

### LINKED ISSUE #12376: Change the footer navigation
### Is your feature request related to a problem? Please describe.

With the new Header Navigation in production, we want to explore the change on the footer.
It does not need to have the same information architecture, but it should be updated.

### Describe the solution you'd like

A new navigation on the footer

### Describe alternatives you've considered

as many as possible

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Updates footer link architecture, layout and styling to match [latest Figma designs](https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=4%3A43546&mode=design&t=lngEz5mxBY3MCoFm-1)
- Includes the addition of three new strings to `common.json` namespace that will require translations
- Updates syntax to use Chakra tokens and latest code conventions

## Preview link
- https://deploy-preview-12396--ethereumorg.netlify.app/

## Related Issue
- Follow-up task to complete #11955
- Closes #12376

## Summary by CodeRabbit

- **Refactor**
	- Improved code quality and maintainability in the footer component.
- **New Features**
	- Enhanced footer links structure for better navigation.
- **Style**
	- Updated styling for a more cohesive footer appearance.

### CODE REVIEW

**Comment by nhsz** [comment]
IMO links should maybe use the `body.medium` color to have more contrast with the headings, as the current version @nloureiro

**Comment by nloureiro** [comment]
> IMO links should maybe use the `body.medium` color to have more contrast with the headings, as the current version @nloureiro

Changed back to body.medium and made some changes to the links.

@wackerow @nhsz, what do you think?

**Comment by wackerow** [comment]
Looks good! Thanks @nloureiro... just pushed a clean-up commit and updated with `dev`... marked as ready for review

**Review by nloureiro — APPROVED** [review]

**Review by corwintines — APPROVED** [review]
LGTM, nice

**Pull request merged**
