### PR TITLE
feat(docs): add `ethers-kt` to developer tooling docs

### PR DESCRIPTION
**Pull request by ArtificialPB**
## Description

Add [ethers-kt](https://github.com/Kr1ptal/ethers-kt) to tooling docs.

## Related Issue

PR for: #12409

## Summary by CodeRabbit

- **New Features**
    - Introduced the `ethers-kt` library across various sections of the documentation, providing developers with a new tool for EVM-based blockchain development in Kotlin/Java/Android.
    - Added comprehensive examples and guides for using `ethers-kt` in scenarios such as ERC20 token transfers, UniswapV2 swaps, and balance tracking.

- **Documentation**
    - Updated the documentation to include links to `ethers-kt` GitHub, examples, and Discord community for additional support and learning resources.
    - Expanded the programming languages and frameworks documentation to cover the integration and usage of `ethers-kt` for blockchain development.

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
Hey @ArtificialPB! Thanks for diving into this... 

Before I get too far, I appreciate the effort of adding the translated versions as well, but I need to mention that all of our non-English content goes through a process involving Crowdin and Acolad to have them formally reviewed/approved.

New additions should always start with just English and they'll be pushed to Crowdin to start the process, then merged into GitHub from there once approved.

---

Secondly, a small note that PR #12605 is currently open which organizes the products on the `/apis/backend` page... We should let that get merged before pulling this in, but in the meantime the three sub-cateogies that were suggested on that PR are:

> 1. Infrastructure and Node Services
> 2. Development Tools
> 3. Blockchain Services

Where do you see `ethers-kt` fitting best amongst these?

**Comment by ArtificialPB** [comment]
Hey @wackerow, appreciate the feedback! I've removed all but the English content.

As for the `/apis/backend` page, `ethers-kt` fits best into the second one, `Development Tools`.

I'll wait for that PR to get merged, and rebase on top of it.

**Comment by wackerow** [comment]
Great, thanks!

**Comment by wackerow** [comment]
@all-contributors please add @ArtificialPB for tool

**Comment by ArtificialPB** [comment]
@wackerow awesome, thank you!

**Pull request merged**
