### PR TITLE
Load content from data files

### PR DESCRIPTION
**Pull request by vdusart**
Source homepage code examples from data files

## Description

Load the content of the code examples (on homepage) from the corresponding files in `/src/data`

## Related Issue

#7150

### CODE REVIEW

**Comment by vdusart** [comment]
@samajammin I don't know why but sometimes webpack tries to bundle the `CreateWallet.js` file even if it is in the exclude list inside the `webpack.config.ts` so it creates an error :cry: 
Do you have an idea ?

**Comment by pettinarip** [comment]
> I don't know why but sometimes webpack tries to bundle the `CreateWallet.js` file even if it is in the exclude list inside the `webpack.config.ts` so it creates an error cry Do you have an idea ?

Nice job @vdusart! I don't know the answer to that but I'll play with it a bit and see if I can help you out.

**Comment by pettinarip** [comment]
@vdusart can you explain why do we need/want to exclude this file? I removed the webpack config file you added and everything worked as expected. IMO I don't think we have to exclude it since it is a module that needs to be imported in the page file.

Anyway, here is how you can extend the webpack config in Gatsby https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/

**Comment by vdusart** [comment]
I'm not sure but sometimes it was not working because webpack was trying to bundle the file and as we don't have some modules (like ethers) it was not compiling...
I thought that putting this file in the exclude files from webpack will arrange it but apparently not 😢

**Comment by vdusart** [comment]
In fact you were right @pettinarip the `webpack.config.ts` file is useless, I just removed it :smile:

**Review by samajammin — APPROVED** [review]
👏

**Pull request merged**
