### PR TITLE
Fix list styles

### LINKED ISSUE #8031: Visual regression in markdown lists
### Describe the bug

The lists are no longer displaying as intended.

- Spacing between list items is not correct

You can [see how they displayed before in this preview](https://ethereumorgwebsitedev01-networkupgradescomponent.gtsb.io/en/nft) versus [how they display now.](https://ethereum.org/en/nft/)

### To reproduce

1. Go to https://ethereum.org/en/nft/
2. Scroll down to [the NFT examples section](https://ethereum.org/en/nft/#nft-comparison)
3. See visual regression

### Expected behavior

The list should be correctly formatted ([as per the previous visual style](https://ethereumorgwebsitedev01-networkupgradescomponent.gtsb.io/en/nft)) with adequate space between list items.

### Screenshots

Current:

Screenshot 2022-09-26 at 11 44 53

Before (expected):

Screenshot 2022-09-26 at 11 45 01

### Additional context

I suspect this happened as part of [the migration to Chakra.](https://github.com/ethereum/ethereum-org-website/issues/6374)

### PR DESCRIPTION
**Pull request by AidanPine**
## Description

Added global styles to temporarily fix list formatting issue.

## Related Issue
Fixes #8031

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Thanks @AidanPine for the PR 💪, this looks good to me. 

Could someone double-check this before we merge? (maybe @pettinarip?)

**Review by pettinarip — APPROVED** [review]
LGTM

**Comment by minimalsm** [comment]
Thanks @AidanPine 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @AidanPine for code

**Pull request merged**
