### PR TITLE
add some current resources to ETH 2.0 section

### PR DESCRIPTION
**Pull request by ethers**

### CODE REVIEW

**Comment by sukich** [comment]
Can someone add Status.im to Ethereum wallet section HTTPS://status.im/get

**Comment by samajammin** [comment]
Hi @sukich - thanks for joining the discussion but that's not at all relevant to this PR. If you want to suggest a change to the website please open an issue & follow the prompts to justify your reasoning.

**Comment by samajammin** [comment]
@ethers I'm going to accept these changes & move your links to the bottom in a subsequent PR

**Comment by ethers** [comment]
@samajammin Thanks; was going to do as you suggested and sorry for the delay.

**Pull request merged**
