### PR TITLE
Deprecate /deprecated-software Page [Fixes #12193]

### LINKED ISSUE #12193: Deprecate `/deprecated-software` page
## Issue
The [`/deprecated-software`](https://ethereum.org/deprecated-software) gets very little traffic and is not maintained. There are challenges associated with maintaining this type of page, as it requires resources to constantly be scanning for potential new software that is considered "deprecated" without any mechanism to automate. Impact vs effort on this page is strongly towards the high effort /low impact side. As such, we should deprecate this page.

## Task
- Remove this page for all languages
- Remove associated image assets that are not used anywhere else (if any)

### PR DESCRIPTION
**Pull request by FaybianB**
## Description

- Removes /deprecated-software for all languages
- Removes associated image assets that are not used anywhere else

## Related Issue

[Fixes #12193]

https://github.com/ethereum/ethereum-org-website/issues/12193

### CODE REVIEW

**Review by nhsz — CHANGES_REQUESTED** [review]
@FaybianB Thanks! The associated translations of the page should also be removed

**Comment by FaybianB** [comment]
> @FaybianB Thanks! The associated translations of the page should also be removed

@nhsz Thanks! I believe this has been addressed. Please let me know if there are other areas that I've missed.

**Comment by FaybianB** [comment]
> > @FaybianB Thanks! The associated translations of the page should also be removed
> 
> @nhsz Thanks! I believe this has been addressed now. Please let me know if there are other areas that I've missed.

**Review by nhsz — APPROVED** [review]
LGTM!

**Pull request merged**
