### PR TITLE
Add Persian translations [Resolves #220]

### LINKED ISSUE #220: Site Translation: Persian
Volunteers needed to complete this translation!
https://crowdin.com/project/ethereumfoundation/fa#

### PR DESCRIPTION
**Pull request by shayanb**
## Description
Added Persian translation and useful articles. 

## Related Issue
This PR addresses: https://github.com/ethereum/ethereum-org-website/issues/220

## How Has This Been Tested?

Yes, ran locally and tested 

## Screenshots (if appropriate):
Farsi Home Page

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by shayanb** [comment]
@samajammin Thanks for the review and the fix. All comments have been addressed.

I tried to fix all right-to-left issues but missed that highlight. It'd be great if you can fix that, I also added you to my branch in case you prefer to do it before the merge. 

P.S. the other thing I found showing a bit weird are the arrows in the titles. I think it'd be fixed with a CSS tweak but CSS is not my best suit.

Me working with CSS

**Comment by samajammin** [comment]
Mmm ya I see what you mean. Still looks a bit weird because the arrow is pointing in the opposite direction but I fixed the margin so at least it doesn't overlay the header.

Everything looks good to me! I'll let you know when I hear back from our translations team.

Thanks again!

**Comment by shayanb** [comment]
@samajammin Hey, any updates?

**Comment by shayanb** [comment]
@samajammin what seems to be the hold up? Is there anything I can help out with? maybe refer some peers to review the translation?

**Comment by samajammin** [comment]
@shayanb sorry for the radio silence! We're still waiting on the final review & signoff 😕I'll keep you posted.

**Comment by samajammin** [comment]
Sorry to say we're still waiting on approval from our external partner. I assure you we're working hard to improve this translation process (and we will soon)! I'll keep you updated here.

**Comment by samajammin** [comment]
Ok @shayanb - I apologize, looks like there's been miscommunication on this. It appears our review service needs the translation [to be in the CrowdIn project](https://crowdin.com/project/ethereumfoundation/fa#) (the translation platform we've been using) in order to complete the review. I should have more clearly explained this in [the issue](https://github.com/ethereum/ethereum-org-website/issues/220). You're the first person to open up a pull request directly in Github (which is awesome!) but we didn't think through how to manage that case on our end.

I'm looking into how to get your translated markdown files into Crowdin but am surprisingly having a very hard time doing it. They don't support uploading markdown files in their interface or [via the API](https://support.crowdin.com/api/upload-translation/) and it's hard for me to know which phrases match up with the translated text (I can't read Persian) so I can't copy & paste the translations in.

I'm working through this issue with the Crowdin support team. If you'd like to get this out the door ASAP, it might be quickest to add the translation directly into Crowdin. Here's an invite link:
https://crowdin.com/project/ethereumfoundation/invite
Otherwise, I will continue to keep you posted.

Sidenote, I've been researching ways to improve this process (e.g. I notice the React team handles all their translations in directly in Github w/ repo forks & bots). If you're interested in discussing potential solutions for our ongoing translation program, I'd love to chat with you! Please let me know either way.

**Comment by samajammin** [comment]
Yay. @shayanb I just got buy-in to get this merge & deployed until we fix this clunky review process. Thanks again for your patience. Again if you're interested in collaborating as a translation maintainer please let me know!

**Comment by shayanb** [comment]
@samajammin Thank you Sam. You just restored my hope in a open source non-bureaucratic world again :) 

And yes, I am interested in collaborating as a translation maintainer :)

**Pull request merged**
