### PR TITLE
Fix ButtonLink arrow logic

### PR DESCRIPTION
**Pull request by corwintines**
## Description
- Add optional hideArrow prop to ButtonLink, and remove these props from product cards and other buttons where applicable.

### CODE REVIEW

**Comment by minimalsm** [comment]
Should we hide this on buttons that already have an Icon?

Screenshot 2022-05-09 at 20 20 01

Screenshot 2022-05-09 at 20 19 57

**Comment by minimalsm** [comment]
Just noting on ButtonLinks that span two lines, the indicator positioning isn't ideal.

Screenshot 2022-05-09 at 21 05 00

**Review by wackerow — APPROVED** [review]

**Comment by nloureiro** [comment]
@corwintines would this be a quick solution to include the icon using css
`  &:after {
    margin-left: 0.14em;
    margin-right: 0.3em;
    display: inline-block;
    content: "";
    transition: all 0.1s ease-in-out;
    font-style: normal;
    width: 12px;
    height: 12px;
    background-image: url("data:image/svg+xml;utf8,<svg width='12' height='12' viewBox='0 0 12 12' fill='none' xmlns='http://www.w3.org/2000/svg'><path fill-rule='evenodd' clip-rule='evenodd' d='M0.5 0.5H1H5.91228V1.5H1.5V10.5H10.5V6.4386H11.5V11V11.5H11H1H0.5V11V1V0.5ZM10.5 2.20711L5.35355 7.35355L4.64645 6.64645L9.79289 1.5H8V0.5H11H11.5V1V4H10.5V2.20711Z' fill='black'/></svg>");
  }
  &:hover {
    &:after {
      transform: translate(0.15em, -0.2em);
    }
  }
``

Screen Shot 2022-05-16 07 13 12 PM
still have to figure out how to change the color using the theme

**Review by wackerow — CHANGES_REQUESTED** [review]
https://build-1ed89d44-6434-4667-8868-df1209cafa05.gtsb.io/ru/developers/docs
image
Cleared cache and rebuilt to make sure it wasn't that, getting it on Brave and Safari.

Still getting this arrow

**Comment by nloureiro** [comment]
> https://build-1ed89d44-6434-4667-8868-df1209cafa05.gtsb.io/ru/developers/docs image Cleared cache and rebuilt to make sure it wasn't that, getting it on Brave and Safari.
> 
> Still getting this arrow

The arrow only appears on the smaller screens. 
Screen Shot 2022-05-17 08 25 15 AM

My take > remove the arrow on all screens as long that it has the Github icon on the left. >>> the idea behind this is that when we have the Github icon is enough for the user to know that will jump out of ethereum.org to Github.

**Comment by nloureiro** [comment]
I have discussed this issue with @konopkja and we're good with the present solution for now.
Screen Shot 2022-05-17 12 09 17 AM


and improve the in the future with a new icon. something like this 
Screen Shot 2022-05-17 12 09 23 AM

**Comment by wackerow** [comment]
Yeah agree on plan to remove arrow if there is already an icon present on the button, applied to both desktop and mobile

Can iterate on design, just out of scope for this PR

**Comment by wackerow** [comment]
Ok, found where that other arrow was coming from and added a `hideArrow` flag to this one as well. Gonna pull in, can iterate further in separate PRs.

**Review by wackerow — APPROVED** [review]

**Pull request merged**
