### PR TITLE
Site Translation: Add Bengali (v1.1) Fixes #962

### LINKED ISSUE #962: Site Translation: Add Bengali (v1.1)
### Prize Bounty
60 DAI

### Challenge Description
Bengali translations have completed review & are ready to be added to the website!

### Submission Requirements
1. Download the [files from CrowdIn](https://crowdin.com/project/ethereumfoundation/bn#) for this version of the content (`Contents v.1.1`). You may need to sign up for CrowdIn & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).
2. Create new directory: /docs/translations/bn/
3. Copy in the CrowdIn files (the strings.json & markdown files) into the new /docs/translations/bn/ directory, keeping the same directory structure as in CrowdIn (i.e. the subdirectories & index.md filenames)
4. In each newly added markdown file...
- Within the [front matter](https://vuepress.vuejs.org/guide/frontmatter.html):
  - Confirm each file has `description`, `og:title` & `og:description` meta properties - check out other translation markdown files for reference
  - Confirm each file has the correct `lang` property (it should match the `locales` key in config.js)
- Update all relative links to include the language path by running our [script](https://github.com/ethereum/ethereum-org-website/blob/dev/scripts/updateInternalLinks.js), i.e. run `yarn update-internal-links bn` from the root of the project 
5. Add the site navigation for the translation in config.js by adding a new `locales` key. It should match the structure of other v1.1 translations (e.g. Swedish, `/se/`). For reference, you can see the site version of each language in translations.js `version` key.
6. Update the /utils/translations.js file
- Import the strings.json file for this language, e.g.
```const sk = require('../../../translations/sk/strings.json')```
- Add the imported file variable to the `stringTranslations` object for this language (the key should match the `locales` key from config.js)
- Add an entry to the `languageMetaData` object for this language, e.g.
```sk: { language: 'Slovenský', 'language-english': 'Slovak', path: '/sk/' },```

**Additional context**

For further guidance, see https://github.com/ethereum/ethereum-org-website/pull/779 as a recent translation addition.

### Judging Criteria
The prize will be awarded to the first valid submission.

### PR DESCRIPTION
**Pull request by sebastiantf**
Fixes #962

### CODE REVIEW

**Comment by samajammin** [comment]
@sebastiantf thank you for this PR! This is tough but unfortunately I'm going to reject this in favor of #964 as the "first valid submission" for this bounty.  Reason being, although this PR was opened first, #964 had a valid submission (implemented the criteria with a successful build) before this.

Please let me know if you have any questions. I hope you continue to submit bounties for us!

**Comment by sebastiantf** [comment]
@samajammin Can you please share how you identified which PR had the successful build first?

**Comment by samajammin** [comment]
You can see if a build fails or succeeds by the "x" mark or the "check" mark next to the commits, e.g:

Image 2020-04-13 at 4 25 30 PM


Then looking at the timing of the respective commits:

```
~/code/ef/ethereum-org-website « git:(pr/963)
$ git log
commit 1a454d1312294eca3f70386c4d55cec448e8f6f9 (HEAD -> pr/963)
Author: Sebastian T F <sebastian.tharakan97@gmail.com>
Date:   Tue Apr 14 00:57:10 2020 +0530

    fix languageMetaData key
```

vs.

```
~/code/ef/ethereum-org-website « git:(pr/964)
$ git log
commit cc8ac0c7db52812f67a6b0afe93716c37b116c75
Author: Antonio Della Porta <antonio@localhost.localdomain>
Date:   Mon Apr 13 21:18:29 2020 +0200

    Adds Bengali Language
```
The other PR's commit is just barely before yours.

**Comment by sebastiantf** [comment]
You mean my commit was at `00:57:10 +0530` and the other commit was at `00:48:29 +0530`?

**Comment by samajammin** [comment]
That was my understanding, yes.

**Comment by sebastiantf** [comment]
Ok @samajammin. Thanks for the clarification.

**Pull request closed without merging**
