### PR TITLE
Fix/stablecoin card

### PR DESCRIPTION
**Pull request by vdusart**
Fixing style of stablecoin button margin

## Description

I created a styled button with mb and mr params.

Hope that was what you meant @wackerow when you talked about a `gap` [here](https://github.com/ethereum/ethereum-org-website/issues/7281#issuecomment-1210773349)

## Related Issue

Fix: #7281

### CODE REVIEW

**Review by minimalsm — CHANGES_REQUESTED** [review]
Hey @vdusart, nice work on this 💪 

Not blocking but I think it'd be a lot cleaner if we applied these styles from the parent. E.g. currently if we want to get rid of the second Button, we'd have to alter the styling on the first. But this is behaviour we'd probably want to use elsewhere too, so maybe pulling this into its own component would make sense at a future date.

My personal preference would be to have these buttons full width, I think it looks better at every screen size. @nloureiro any thoughts? 

DAI is full width. USDC is current width.

Screenshot 2022-08-11 at 12 48 47

Screenshot 2022-08-11 at 12 54 11

Screenshot 2022-08-11 at 12 54 24

**Comment by vdusart** [comment]
@minimalsm I agree with you for the full size, it's nicer !
I'm not sure to understand what you mean with the first part of the comment... :cry:

**Comment by minimalsm** [comment]
> I'm not sure to understand what you mean with the first part of the comment... 😢

I mean that ideally, the styling of these elements would come from the parent element. We're duplicating styles by putting the same margins on different buttons. If we want to make style changes, the code must be edited in both places.

**Comment by Andy-Waine** [comment]
Hi @vdusart - I'm interested in tackling this issue, but I see you've already done a lot of the legwork. Perhaps I could contribute to your PR? or are you currently working on this?

**Comment by vdusart** [comment]
Hey @Andy-Waine I'm not sure but I think it's almost done (maybe some quick changes) 🫤
But if you like design stuff you should definitely join the discord and especially the `ui-library-migration`! There will be for sure work to do there !! 😁

**Comment by Andy-Waine** [comment]
@vdusart Awesome - I'll definitely do that. Thanks!

**Pull request closed without merging**
