### PR TITLE
CSS fix for H4 [Closes #3600]

### LINKED ISSUE #3600: Crowdfunding Dapps Button broke on Defi Page
**Describe the bug**
On [the DeFi learn page](https://ethereum.org/en/defi/) the 'See crowdfunding dapps' button is completely non functional for me. Clicking does nothing, no re-direct and no hover effects.

**To Reproduce**

1. Go to 'https://ethereum.org/en/defi/'
2. Scroll down to 'Fund your ideas section'
3. Click on 'See crowdfunding dapps' button

**Expected behavior**
- Button should redirect to https://ethereum.org/en/dapps/?category=finance
- Button should have an on hover drop shadow applied

**Screenshots**
9a3bc01d0bad7e8c293f482b2bbc157d

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave
- Version: 1.24.82

**Additional context**

At a glance it doesn't appear different to buttons that are working?

**Broken Button**
```javascript
<ButtonLink to="/dapps/?category=finance">See crowdfunding dapps</ButtonLink>
```

**Working Button**
```javascript
<ButtonLink to="/dapps/?category=finance">See investment dapps</ButtonLink>
```

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by JaredFlomen**
## Description

CSS issue

## Related Issue

#3600

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @JaredFlomen thanks for another quick PR to solve this ❤️

Definitely fixes the issue we were having and doesn't seem to break [anything in the other templates that use it](https://github.com/ethereum/ethereum-org-website/search?q=header4). Would love some eyes on this @wackerow as it is changing a Shared component incase I'm missing anything. One thing worth noting is that ```unset``` [doesn't have support on IE](https://caniuse.com/?search=unset) at all.

**Review by wackerow — APPROVED** [review]
This looks good to me. @minimalsm This is the `h4` component that gets used by any of the markdown files using the "static", "use-cases", "eth2" or "tutorial" templates, so this seems like the proper place to fix this issue. Not too worried about the Internet Explorer compatibility simply from a usage perspective... from a sample on Matomo:

image

@JaredFlomen Thanks!

**Comment by minimalsm** [comment]
Awesome! Thanks for your second PR @JaredFlomen ✌️🌟

**Comment by minimalsm** [comment]
@all-contributors please add @JaredFlomen for bug fix

**Pull request merged**
