### PR TITLE
Added beaconcha.in block explorer

### PR DESCRIPTION
**Pull request by Sanketh-Maturi**
## Description

Added the new open source beaconcha.in block explorer to the block explorers and services list.

### CODE REVIEW

**Review by wackerow — COMMENTED** [review]
Thanks @Sanketh-Maturi! Agree we should get Beaconchain.in listed.

Only question this raises for me is the ordering of projects. @corwintines any thoughts on this? Should we just make these alphabetical order by default?

**Comment by minimalsm** [comment]
We should probably separate these by chain, but we can do that later. I'd say let's keep the most used (therefore most useful?) blockexplorer (Etherscan) at the top for now, but no strong opinion here.

**Comment by corwintines** [comment]
I don't have a strong opinion. Maybe Etherscan then alphabetical for now.

**Comment by corwintines** [comment]
@wackerow @minimalsm ill push up a change for that tomorrow and merge if theres no opposition.

**Review by corwintines — APPROVED** [review]

**Pull request merged**
