### PR TITLE
Fix typo in proof-of-work developer doc (Chinese)

### PR DESCRIPTION
**Pull request by VignetteApril**
## Description
Fix typo

### CODE REVIEW

**Comment by minimalsm** [comment]
@riely007 reviewing

**Comment by Riely007** [comment]
> ## Description
> Fix typo

thank you! The modified one looks great! There was indeed a typo in the sentence before. 🙏

**Comment by minimalsm** [comment]
Thanks for spotting and fixing this @VignetteApril ✌️.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap)  also 🥳!

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
@all-contributors please add @VignetteApril for translations

**Pull request merged**
