### PR TITLE
fix: upgrate new twitter logo #12379

### PR DESCRIPTION
**Pull request by iepn**
## Description
image

https://react-icons.github.io/react-icons/search/#q=FaXTwitter

https://github.com/ethereum/ethereum-org-website/blob/2c8b2acf6cdc6849894c5e040962c3860e161526/src/components/Footer.tsx#L33-L36

### Twitter

```diff
+ import { FaXTwitter } from "react-icons/fa6";
- icon: FaTwitter,
+ icon: FaXTwitter,
```

## Related Issue

#12379

## Summary by CodeRabbit

- **Style**
	- Updated the Twitter icon in the footer and changed its color for better visual integration.
	- Added a new social link for YouTube with the respective icon.

### CODE REVIEW

**Comment by Sels13** [comment]
it is very nice, thank you so much

**Comment by iepn** [comment]
> Would personally prefer to not convert this, and/or migrate entirely to Farcaster

Okay, thank you.

**Comment by wackerow** [comment]
Hey @iepn, circling back, I didn't mean to unilaterally decide this 😆, sorry to give that impression... was just dropping an opinion on it.

@nloureiro I know you've talked about migrating forward with this branding change. What're your latest thoughts here? Personally just in the camp that I'd prefer to start primarily supporting a more values-aligned platform altogether, but not a hill I'm dying on right now.

**Comment by iepn** [comment]
In fact, I also really like Twitter's previous little blue bird logo. If the team decides to replace all logos with the 'X' logo, please let me know, and at that time, I will submit a PR for a complete switch to the X platform, rather than this one which only involves the bottom navigation.

After hearing your thoughts, I attempted to submit the Farcaster logo for inclusion in react-icons, so that the team could directly use the Farcaster logo through react-icons. However, their icon library is complex and convoluted, making it difficult to know where to start when submitting a PR. Most of their support seems to come from addressing issues raised by users, rather than direct community contributions.

Of course, as an alternative, Farcaster's logo could be saved and referenced as image files (such as SVG or PNG), but I am concerned that this might conflict with the team's coding standards.

Therefore, I chose to close the PR. If in the future, the team comes up with a new solution or approach, I will definitely take the opportunity to learn ^_^ !

You can take a look:

https://github.com/ethereum/ethereum-org-website/pull/12467
https://github.com/ethereum/ethereum-org-website/pull/12485

**Comment by iepn** [comment]
> Hey @iepn, circling back, I didn't mean to unilaterally decide this 😆, sorry to give that impression... was just dropping an opinion on it.
> 
> @nloureiro I know you've talked about migrating forward with this branding change. What're your latest thoughts here? Personally just in the camp that I'd prefer to start primarily supporting a more values-aligned platform altogether, but not a hill I'm dying on right now.

In fact, I also really like Twitter's previous little blue bird logo. If the team decides to replace all logos with the 'X' logo, please let me know, and at that time, I will submit a PR for a complete switch to the X platform, rather than this one which only involves the bottom navigation.

After hearing your thoughts, I attempted to submit the Farcaster logo for inclusion in react-icons, so that the team could directly use the Farcaster logo through react-icons. However, their icon library is complex and convoluted, making it difficult to know where to start when submitting a PR. Most of their support seems to come from addressing issues raised by users, rather than direct community contributions.

Of course, as an alternative, Farcaster's logo could be saved and referenced as image files (such as SVG or PNG), but I am concerned that this might conflict with the team's coding standards.

Therefore, I chose to close the PR. If in the future, the team comes up with a new solution or approach, I will definitely take the opportunity to learn ^_^ !

You can take a look:

https://github.com/ethereum/ethereum-org-website/pull/12467
https://github.com/ethereum/ethereum-org-website/pull/12485

**Pull request closed without merging**
