### PR TITLE
Grammar enhancement

### PR DESCRIPTION
**Pull request by jhhornn**

### CODE REVIEW

**Review by minimalsm — COMMENTED** [review]
'Is being' is [passive progressive present tense](https://linguisticsgirl.com/present-progressive-passive-english-verbs/), which makes this use passive voice. 

If we want to make this use active voice using the present tense we'd probably want to write: 'ethereum.org is improving and changing...' but then we'd have to change the rest of the sentence to adhere to the same tense.

**Comment by jhhornn** [comment]
Should it be left that way or restructured?

**Review by corwintines — APPROVED** [review]
Thanks, @jhhornn!

Citing https://ethereum.org/en/contributing/style-guide/#use-active-voice

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. We also have our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) 🥳!

**Comment by corwintines** [comment]
@all-contributors can you add @jhhornn for doc

**Comment by jhhornn** [comment]
You're welcome and thank you for the opportunity as well @corwintines 

I've not been able to claim my POAP as I was blocked from submitting my PR link on discord.

**Pull request merged**
