### PR TITLE
Adjust the styles of the comm events widget

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

Small tweaks on the styles of the community events widget.

### CODE REVIEW

**Comment by nloureiro** [comment]
Can I leave some minimal changes?

@konopkja let me know what you think

Screen Shot 2023-08-09 06 05 09 PM

**Comment by konopkja** [comment]
> Can I leave some minimal changes?
> 
> @konopkja let me know what you think
> 
> Screen Shot 2023-08-09 06 05 09 PM

sure, please go ahead

**Comment by pettinarip** [comment]
@konopkja @nloureiro I've updated the styles.

**Review by nloureiro — APPROVED** [review]

**Comment by nloureiro** [comment]
Looks good to me! thank you

**Review by corwintines — APPROVED** [review]

**Pull request merged**
