### PR TITLE
Biconomy added

### PR DESCRIPTION
**Pull request by tarun1475**
Biconomy is a relayer infrastructure network and transaction platform enabling you to build applications easily and reduce the friction between your applications built on the blockchain and your end-users.

### CODE REVIEW

**Comment by samajammin** [comment]
Hey @CPSTL - could you please give this a review when able? Thank!

**Comment by tarun1475** [comment]
> @tarun1475 Do you have an examples of how Ethereum developers have used Biconomy? This would be a nice touch to add to your documentation / website.

We are currently under our alpha and below are the few projects which have successfully integrated biconomy. 

Mexa SDK Integrations: 
1) [DaoStack](https://github.com/daostack/alchemy/pull/1625 ) 
2) [Matic Cross chain gasless transactions]( https://github.com/torusresearch/torus-website/pull/979)
3) [Pouch Defi Wallet](https://devfolio.co/submissions/pouch-wallet)
4) [InstCryp ](https://github.com/sunnyRK/mexa-sdk/tree/instCryp/Examples/InstCryp)
5)  [AtomiX Network ](https://github.com/anuditnagar/mexa-sdk/tree/master/Examples/AtomiX%20Network)

Biconomy core Api Integration 
1)  [Torus wallet integration ](https://github.com/torusresearch/torus-website/pull/979)

There are more projects which are testing it out and we are in the process of launching our beta mainnet next week and we will surely add these project examples in our documentation.

**Comment by CPSTL** [comment]
@tarun1475 I think once you have launched your beta on mainnet and the project examples have been included in your documentation, we can come back to this.

**Comment by tarun1475** [comment]
@CPSTL Sure Thanks. Will update here once we launch on mainnet.

**Comment by samajammin** [comment]
@tarun1475 closing this out for now, please feel free to re-open this PR once you have launched your beta on mainnet and the project examples have been included in your documentation. Thanks!

**Comment by tarun1475** [comment]
Hi @samajammin & @CPSTL , Last week we have successfully launched our infrastructure on ethereum mainnet and have also added the projects building on top of biconomy section in our documentation. 
Docs: https://docs.biconomy.io/examples/projects-building-on-biconomy 
Mainnet launch relevant links :-
1). https://medium.com/biconomy/biconomy-beta-launch-d6ad979fffce
2). https://decrypt.co/27768/biconomy-brings-gasless-transactions-to-ethereum 

I was bit occupied and was about to update it here. Can you please proceed with review process now?

**Pull request closed without merging**
