### PR TITLE
Add Stablecoins.wtf reference [Fixes #7093]

### LINKED ISSUE #7093: Add Stablecoins.wtf reference to the stablecoins-subpage
Hey, I would like to add [stablecoins.wtf](https://stablecoins.wtf) as a reference on the stablecoins-subpage. In my upcoming PR I used the same mode of presentation as the tools on the `layer-2` subpage and added them to the bottom of the page. This also opens up the possibility of adding more tools in the future.

CC @samajammin 

Screen Shot 2022-07-16 at 22 52 53

### PR DESCRIPTION
**Pull request by wottpal**
## Description

I added a tool-section at the bottom of the `stablecoins` subpage (similar to this on the `layer-2` subpage) and added [stablecoins.wtf](https://stablecoins.wtf) as a first item. See attached screenshot:

Screen Shot 2022-07-16 at 22 52 53

CC @samajammin 

## Related Issue

#7093

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @wottpal, awesome resource you've created 😍 We're gonna make some design tweaks to this but happy to add it as a resource to the stablecoins page. 

We plan on making this 50% of its current width, and the description will look too long/awkward as a result. Would you mind if we cut the description to the first sentence?

**Comment by wottpal** [comment]
Thanks for your compliments, @minimalsm (It will get even better in the future 🤓).
Both sounds fine to me @minimalsm! Go ahead and lmk if i can help!

**Comment by corwintines** [comment]
Merged dev in to resolve a conflict, sorry for adding a linter change to this 😅 Going to quickly add in that 50% width change.

**Review by corwintines — APPROVED** [review]
Made the style adjustments, and small copy adjustments as well. Thanks for the contribution @wottpal! Let me know what you think! @minimalsm let me know if there is anything else needed, but I think this is good to go now.

**Comment by wottpal** [comment]
@corwintines looks great!

**Pull request merged**
