### PR TITLE
Removed broken link and fixed incorrect id in url

### PR DESCRIPTION
**Pull request by SavPhill**
Removed link on line 520 which was broken - http://sourceforge.net/p/bitcoin/mailman/message/31709140/.

Edited the url of the wikipedia to reflect the correct scroll to it for Simplified Payment Verification.
From https://en.bitcoin.it/wiki/Scalability#Simplifiedpaymentverification to https://en.bitcoin.it/wiki/Scalability#Simplified_payment_verification

## Description

1. Fixing a broken link to a resource which is no longer available. 
2. Editing the url of a link to make the id instantly accessible.
## Related Issue

1. Visit the link titled Peter Todd on Merkle sum trees on point 21 of Further Reading: http://sourceforge.net/p/bitcoin/mailman/message/31709140/
It is no longer accessible.
2. Visit the link titled Simplified payment verification on point 13 of further reading: https://en.bitcoin.it/wiki/Scalability#Simplified_payment_verification. The scroll to ID is incorrect and it opens the top of the page, which makes the link appear incorrect initially for the user.

### CODE REVIEW

**Review by minimalsm — CHANGES_REQUESTED** [review]
Hey @SavPhill, thanks for catching this. 

We decided that we would not be alterating the Whitepaper (checkout #3794 for context), apart from fixing things that are broke. So we'd definitely want to keep the Peter Todd further reading link.

Luckily, we have a web archive version of the Peter Todd on Merkle sum trees that we can use instead: https://web.archive.org/web/20140623061815/http://sourceforge.net/p/bitcoin/mailman/message/31709140/

**Comment by SavPhill** [comment]
> Hey @SavPhill, thanks for catching this. 
> 
> 
> 
> We decided that we would not be alterating the Whitepaper (checkout #3794 for context), apart from fixing things that are broke. So we'd definitely want to keep the Peter Todd further reading link.
> 
> 
> 
> Luckily, we have a web archive version of the Peter Todd on Merkle sum trees that we can use instead: https://web.archive.org/web/20140623061815/http://sourceforge.net/p/bitcoin/mailman/message/31709140/

Thank you- new commit made with the edit: 

https://github.com/ethereum/ethereum-org-website/commit/a3a7a49316daae2b18e66a5e14f0dbaee2f6cb97

**Review by corwintines — APPROVED** [review]
Thanks for fixing these broken links @SavPhill!

**Comment by corwintines** [comment]
@all-contributors can you add @SavPhill for docs

**Pull request merged**
