### PR TITLE
Remove RimbleUI from dapp tools section [Fixes #3734]

### LINKED ISSUE #3734: Broken Link - Rimble URL not working
**Describe the bug**
In the `Intro to Dapp` section the link [https://rimble.consensys.design](url) is not working.

```
## Dapp tools {#dapp-tools}
**Rimble UI** **_- Adaptable components and design standards for decentralized applications._**
- [rimble.consensys.design](https://rimble.consensys.design)
```

**To Reproduce**

1. Go to  [https://ethereum.org/en/developers/docs/dapps/](url)
2. Scroll down to [https://ethereum.org/en/developers/docs/dapps/#dapp-tools](url)
3.  Click on `rimble.consensys.design`

**Expected behavior**
It should take to the home page of `rimble.consensys.design`

**Desktop (please complete the following information):**
Not required

**Smartphone (please complete the following information):**
Not required

**Additional context**
None

### PR DESCRIPTION
**Pull request by raj-shekhar1**
Remove the RimbleUI from the dapp-tools sections in all pages(including the translations).
## Related Issue
#3734 

## Related Discussion
#3740

### CODE REVIEW

**Comment by raj-shekhar1** [comment]
@minimalsm I have removed the complete `rimble-ui` resource from the dapp-tools section including the `rimble-ui github` and `example demo app` links. Please let me know if this works fine or any other suggestions.

**Comment by minimalsm** [comment]
Hey @raj-shekhar1 thanks! Yeah, this is perfect. 

Just FYI I removed the double line spacing where you removed RimbleUI - it renders the same way but 1 less line and is a bit cleaner to look at. 

I've created an issue (#3782) to add some additional dapp tools in place of RimbleUI [as suggested here](https://github.com/ethereum/ethereum-org-website/pull/3740#issuecomment-907864560).

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @raj-shekhar1 for docs

**Comment by raj-shekhar1** [comment]
> Hey @raj-shekhar1 thanks! Yeah, this is perfect.
> 
> Just FYI I removed the double line spacing where you removed RimbleUI - it renders the same way but 1 less line and is a bit cleaner to look at.
> 
> I've created an issue (#3782) to add some additional dapp tools in place of RimbleUI [as suggested here](https://github.com/ethereum/ethereum-org-website/pull/3740#issuecomment-907864560).
> 
> Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also !

Awesome !!  thanks.

**Pull request merged**
