### PR TITLE
Scroll to anchor links [Fixes: #294]

### PR DESCRIPTION
**Pull request by bakaoh**
Smooth scroll to anchor links

## Description

Use css `scroll-behavior: smooth;` to smooth scroll to anchor links

## Related Issue

Fixes: #294

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by samajammin** [comment]
@bakaoh thank you for this PR! The scroll looks good but I noticed when clicking on different pages, it creates an awkward UX - it doesn't start at the top of the new page & scrolls up to the top:

Screen Recording 2019-10-08 at 12 46 PM

Any ideas on how to prevent this?

**Comment by bakaoh** [comment]
@samajammin -- i disabled scroll when clicking on different pages, don't know if there's any clearer solution

**Comment by samajammin** [comment]
Nice @bakaoh! The only issue I'm seeing now is that after the scroll, the sidebar menu is not highlighting the correct section. Example below - when I select "Block Explorers" section, the sidebar highlights "Testing Tools":

Screen Recording 2019-10-09 at 05 00 PM

One way to solve this might be configuring the plugin we use:
https://vuepress.vuejs.org/plugin/official/plugin-active-header-links.html#install

**Comment by bakaoh** [comment]
@samajammin --- sorry, i didn't find anyway to fix that, smooth scroll is not work well with `@vuepress/plugin-active-header-links`

> The problem is that, @vuepress/plugin-active-header-links watches the scroll event to set the active sidebar link, and smooth-scroll will trigger the scroll event for sure.

**Comment by samajammin** [comment]
@bakaoh I'm closing this out for now. Please feel free to reopen if you find a solution! I appreciate the effort you put into this!

**Pull request closed without merging**
