### PR TITLE
Add nft resources for interacting with, viewing, and displaying nft contracts

### PR DESCRIPTION
**Pull request by pileofscraps**
The current docs only include contract standards but no resources for interacting with NFT contracts post-deployment. I added one resource, the Alchemy NFT API, for interacting with, viewing, and integrating with NFTs.

## Description
Added information about the Alchemy NFT API for interacting with, viewing, and integrating with NFTs as part of the entire NFT build process.

### CODE REVIEW

**Review by Aivolt1 — APPROVED** [review]

**Review by Aivolt1 — APPROVED** [review]

**Review by minimalsm — CHANGES_REQUESTED** [review]
Hey @pileofscraps,

Thansk for the PR. Really excited about Alchemy's NFT API and am happy to find a place for it on the site. 

That being said, I don't think this is the right place given this page is aimed at non-technical individuals, not developers. Perhaps in the [data and analytics developer doc](https://ethereum.org/en/developers/docs/data-and-analytics/) makes sense? Open to other ideas 🙏

**Comment by minimalsm** [comment]
@pileofscraps just pinging to make sure you've seen this.

Also, on second thought, this is a Javascript API so it probably [makes sense to add it to that page](https://docs.alchemy.com/alchemy/enhanced-apis/nft-api).

**Comment by pileofscraps** [comment]
hey @minimalsm! Thanks for the ping here. Been working through a backlog since going to ETHDenver and missed this. Sorry about that. I agree that a higher-level overview might make a bit more sense for this PR. Let me make the changes!

**Comment by pileofscraps** [comment]
^Ooop sorry; following up here! Not sure exactly what changes would be best. I, personally, think that the Build with NFTs section makes the most sense for this addition as you mentioned @minimalsm. But can move it elsewhere too. *Responded to your discord message as well.

**Review by minimalsm — APPROVED** [review]
Hey @pileofscraps,

We're doing a deploy so to get this live before we leave for the weekend I've pulled in the changes I outlined on Discord. Feel free to open a discussion (or PR) if there is somewhere else you think this makes sense (DMs are open too).

Thanks again. Be sure to claim your [2022 POAPs](https://ethereum.org/en/contributing/#poap) also 🥳!

**Pull request merged**
