### PR TITLE
Added safe check to completed quiz item so it doesn't return undefined

### PR DESCRIPTION
**Pull request by checkomkar**
## Description
Added safe check so completed quiz item so it doesn't return undefined

## Related Issue

#10828

### CODE REVIEW

**Review by pettinarip — CHANGES_REQUESTED** [review]
Thanks for the PR @checkomkar.

Even though this change fixes the first issue and lets you load the page, it has another problem.

When you try to make one of the new quizzes like "Run a node", once you finish it, the logic tries to save the progress and it fails, crashing the page.

To simulate the error:
1. Manually add old quiz data in localstorage:

```
key: quizzes-stats
data: {"score":0,"average":[],"completed":"{\"what-is-ethereum\":[false,0],\"what-is-ether\":[false,0],\"web3\":[false,0],\"wallets\":[false,0],\"security\":[false,0],\"nfts\":[false,0],\"layer-2\":[false,0],\"merge\":[false,0]}"}
```

2. Try to complete the "Run a node" quiz

**Comment by checkomkar** [comment]
> Thanks for the PR @checkomkar.
> 
> Even though this change fixes the first issue and lets you load the page, it has another problem.
> 
> When you try to make one of the new quizzes like "Run a node", once you finish it, the logic tries to save the progress and it fails, crashing the page.
> 
> To simulate the error:
> 
> 1. Manually add old quiz data in localstorage:
> 
> ```
> key: quizzes-stats
> data: {"score":0,"average":[],"completed":"{\"what-is-ethereum\":[false,0],\"what-is-ether\":[false,0],\"web3\":[false,0],\"wallets\":[false,0],\"security\":[false,0],\"nfts\":[false,0],\"layer-2\":[false,0],\"merge\":[false,0]}"}
> ```
> 
> 2. Try to complete the "Run a node" quiz

Hey @pettinarip, thank you for highlighting the issue. I have added a fix for the same, see if that work. Thanks, cheers!

**Comment by wackerow** [comment]
Thanks for the help @checkomkar! Just tried this out, and the /quizzes page does load, but I'm getting strange results in the summary section... "Completed" quizzes only seems to increment if the user scores 100%, and the "Your total points" score stays at `0 / 54` no matter what. The green tick mark for completion also only shows up if you score 100%.

**Comment by pettinarip** [comment]
FYI @checkomkar thanks for trying to fix this issue but we've decided to revert these changes #10873 for now until we have a more robust solution which probably is going to involve doing a refactor on the quizzes logic.

**Comment by pettinarip** [comment]
Thanks again @checkomkar for the effort you put on this. I'll close this one in favor of #10873. FYI we will try to do a refactor to find a better solution #10887

**Pull request closed without merging**
