### PR TITLE
Use-cases banner/hero mobile fixes

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Hides "edit" banner for use-cases on mobile
- Centers hero image on mobile

cc: @samajammin @ryancreatescopy

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Although better, we still can't see any page content bar the emoji? If we make this change, maybe we should adjust the height of the hero container entirely to push more of the content into view?

**Comment by samajammin** [comment]
> maybe we should adjust the height of the hero container entirely to push more of the content into view

Agreed @ryancreatescopy. @wackerow can you look into adjusting the hero height for mobile? Thanks!

**Review by samajammin — CHANGES_REQUESTED** [review]
See comment above.

**Comment by samajammin** [comment]
@wackerow @ryancreatescopy FYI merging this since we're about to deploy. @wackerow please make further changes in a separate PR - thanks!

**Pull request merged**
