### PR TITLE
Add new page for Delphi developers

### PR DESCRIPTION
**Pull request by svanas**

### CODE REVIEW

**Comment by samajammin** [comment]
Awesome - thanks for this PR! 

I'll review this more thoroughly when time allows but from a quick glance, it looks like all resource links are from [your personal medium](https://medium.com/@svanas/) & are about [Delphereum](https://github.com/svanas/delphereum). Are there any other Delphi projects or resources in the Ethereum space? Is there any third party content about Delphereum? The goal with these Language-specific pages is to offer a balanced resource & avoid promotion of individual projects (not to say that's the case but it could be perceived given the current page content). We also try our best to make sure projects added have [proven community usage](https://github.com/ethereum/ethereum-org-website#-developers) before adding them to the website.

**Comment by svanas** [comment]
Hey @samajammin! I am afraid Ethereum adoption in the Delphi community is super low. Accepting this MR can change that maybe. Thanks!

**Comment by svanas** [comment]
@samajammin if you need an independent opinion about this Delphi library, then you could talk to [Nethereum](https://nethereum.com/)'s @juanfranblanco maybe. Thanks!

**Comment by juanfranblanco** [comment]
@samajammin @svanas Delphereum is the only Delphi integration client for Ethereum, and its aim is to bridge the barrier and help Delphi developers to integrate with Ethereum, and of course Ethereum developers leverage Delphi if they require it. 

I have followed @svanas work for a while and it is fantastic. As many as other client integration projects the intention is to help on Ethereums outreach to that developer community and of course you are not going to find many articles by other parties, as Delphi is a small community to start with.

On that note, IMHO diversity of articles can be a double sword. Whilst I understand the perspective of having many people writing about an specific integration platform or topic, we may have an editorial issue with documentation (or topics linked) as they might become outdated, or much worst incorrect, not helpful, a plain copy of other source or worst something like medium that can be edited (an attack) or put a pay wall.

I know myself is hard enough to keep Nethereum documentation up to date with all the different changes due to new improvements (I hope) on how to do things. I believe what is needed is for developers to have an easy way to get started, with the latest documentation that will reduce the barrier of entry.

**Comment by samajammin** [comment]
Thanks for your patience on this!

@all-contributors please add @svanas for content.

**Pull request merged**
