### PR TITLE
Homepage finishing touches

### PR DESCRIPTION
**Pull request by ryancreatescopy**
## Description

- Reverted title and subtitle to translated strings. We'll address copy separately. 
- Increased font size of title to `l3`

## Related Issue

Related to #1017 

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
@samajammin couldn't figure out the best way to fix the breakpoints, maybe we can take a look together.

**Comment by samajammin** [comment]
@ryancreatescopy FYI just pushed those footer updates to get the alignment consistent.

I also rebased off `dev` & force pushed to get this branch up to date.

**Comment by jjmstark** [comment]
Looks all good to me - ready to ship!

**Comment by samajammin** [comment]
@all-contributors please add @ryancreatescopy for code

**Pull request merged**
