### PR TITLE
Add Ethereum Ecosystem Sepolia faucet to dev docs /networks

### PR DESCRIPTION
**Pull request by Maxservais**
## Description

This PR introduces a link to Ethereum Ecosystem' sepolia faucet: https://www.ethereum-ecosystem.com/faucets/ethereum-sepolia

People struggle to find faucets that have plenty of ETH to distribute AND do not get depleted by malicous actors with bots. This faucet is bot/spam-resistant and provides generous drips to users.

### CODE REVIEW

**Comment by corwintines** [comment]
Thanks @Maxservais 

I see this is just an iframe wrapper for https://ethereum-sepolia.degenchest.com/, shouldn't we just link out to this instead?

**Comment by Maxservais** [comment]
> Thanks @Maxservais
> 
> I see this is just an iframe wrapper for https://ethereum-sepolia.degenchest.com/, shouldn't we just link out to this instead?

Hey @corwintines,

Thanks for your comment!

Yes, it’s indeed an iframe wrapper. If we don’t link to https://www.ethereum-ecosystem.com/faucets/ethereum-sepolia, people won't see the other faucets we run (for Mode, Base, and Optimism Sepolia - and probably a few more soon). You can check them out here: https://www.ethereum-ecosystem.com/faucets.

I've also set up privacy-friendly and cookie-less web analytics to track activity on the faucets page, which I haven’t done on degenchest.com. This makes it easier to detect bot usage and implement stricter rules for the faucets.

I'll leave the decision to you! Let me know your thoughts.

Cheers,
Maxime

**Review by wackerow — APPROVED** [review]
Looks good, thanks @Maxservais!

**Comment by wackerow** [comment]
Oops sorry, missed the discussion, but I think this is fine. The linked page does have a nice FAQ and other helpful links, I'm not against this (@Maxservais assuming no complains from [degenchest](https://ethereum-sepolia.degenchest.com/))

**Pull request merged**
