### PR TITLE
fixed link to Grafana

### PR DESCRIPTION
**Pull request by Luis-Mx**
## Description

Small fix to correct the link to Grafana

## Related Issue

None

### CODE REVIEW

**Comment by smysmymrik1803** [comment]
Ok

**Comment by smysmymrik1803** [comment]
All is ok

**Review by wackerow — APPROVED** [review]
@Luis-Mx 👍 Thanks for catching!

**Comment by wackerow** [comment]
@all-contributors please add @Luis-Mx for bug fix

**Pull request merged**
