### PR TITLE
Add title attribute to iframe (a11y)

### PR DESCRIPTION
**Pull request by entonbiba**
Adds a title attribute to the iframe element with the video title. Allows screen readers to identify that the iframe content is a video.
```
title="YouTube video titled What Are NFTs and How Can They Be Used in Decentralized Finance? DEFI Explained"
```

### CODE REVIEW

**Comment by DiKarat** [comment]
[]()

**Review by jley81 — APPROVED** [review]

**Review by jley81 — APPROVED** [review]

**Review by corwintines — APPROVED** [review]
Thanks for adding some accessibility @entonbiba!

**Comment by minimalsm** [comment]
@all-contributors please add @entonbiba for a11y

**Comment by minimalsm** [comment]
Thanks for the PR on this @entonbiba 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Pull request merged**
