### PR TITLE
Update package version to fix m1 chip error

### PR DESCRIPTION
**Pull request by alantoa**
## Description
Hi, maintainers, I'm a front-end developer, looking at this document to learn web3, thank you very much for your resources！

I‘m trying to update the documentation to help with the translation work, when I run `yarn` get error logs:
```
> sharp@0.29.3 install /Users/joshua/Projects/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using existing vendored libvips v8.12.1
  TOUCH Release/obj.target/libvips-cpp.stamp
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/sharp-darwin-x64/src/common.o
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp-darwin-x64/src/common.o] Error 1
```

Then I found the reason, `sharp` version must greater than `v0.30.1` when use M1 chip.

Specific reason you can see https://github.com/lovell/sharp/issues/3048, so I updated the package, and  also upgraded the `gatsby` related packages.

## Related Issue
https://github.com/lovell/sharp/issues/3048
https://github.com/ethereum/ethereum-org-website/issues/3796

## My system version 
System: MacOS Monterey 12.2
Chip: Apple M1 Pro
Node: v16.14.0

### CODE REVIEW

**Comment by wackerow** [comment]
Hey @alantoa, thanks for reporting! @samajammin @corwintines Are you folks getting any issues with the M1?

**Comment by wackerow** [comment]
Ah, nevermind, I see the issue now, can review tomorrow =)

**Comment by corwintines** [comment]
@alantoa I am running this on a M1 chip with this current package settings, but I havent updated to Montery yet either. Will take a closer look today as I ran into this issue initially when setting up my macbook as well though.

**Comment by alantoa** [comment]
@corwintines Thank you! 
I think this needs upgrade!

**Comment by alantoa** [comment]
Hi, @pettinarip, thank you for reply!
I changed it according to your method, it's work in M1 chip well down!
Now I submit a PR, If have any problem, I'll change it again.
Thank you!

**Comment by alantoa** [comment]
Hi, @corwintines, excuse me, Is there any progress in this PR?
Because I also have to submit some docs PR, thank you!

**Comment by wackerow** [comment]
Curious if anyone else has encountered this issue with an M1. @samajammin have you encountered this at all. Are you running macOS Monterey?

@alantoa If you have some other docs and this solution is working for you locally, feel free to just push a separate PR with the doc changes specifically and we can take a look.

**Review by pettinarip — APPROVED** [review]
@alantoa I made a cleanup on the `yarn.lock` file since it had a lot of changes that were not needed (probably because you had installed/uninstalled other packages before) and I bumped the code gatsby version that has `sharp` as a dependency too.

Thanks for the help! 💪🏼

**Comment by pettinarip** [comment]
@all-contributors please add @alantoa for dependencies

**Comment by pettinarip** [comment]
https://github.com/all-contributors please add @alantoa for tool

**Comment by pettinarip** [comment]
@all-contributors please add @alantoa for tool

**Comment by alantoa** [comment]
@pettinarip I'm very happy to be merged! 🚀
Thank you!💕

**Pull request merged**
