### PR TITLE
remove outdated speedrunethereum tutorials

### LINKED ISSUE #12835: Stale external tutorials need removed/updated.
### Describe the bug

The two external tutorials by Austin Griffith are linking to a stale repository and will need updated to the newer scaffold-ETH2 challenges.

### To reproduce

See links in the existing Simple NFT Example and Decentralized Staking App tutorials.

### Expected behavior

These examples will need removed and updated.

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ZakGriffith**
## Description
Remove outdated speedrunethereum tutorials

## Related Issue
- Closes #12835

### CODE REVIEW

**Comment by ZakGriffith** [comment]
This references Issue #12835

**Review by wackerow — COMMENTED** [review]
Hey thanks @ZakGriffith! Although the tutorials need pruning in general, we could consider just updating the links here... Looks like they've just been migrated to

- https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-0-simple-nft
- https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-1-decentralized-staking

Any reason you wanted to take them down instead of update?

**Comment by ZakGriffith** [comment]
It appeared that when I added them all at the same time it grouped them all well in the list.  But if that isn't the case, I can edit to just update the two old tutorials and add in the other new ones.

**Comment by wackerow** [comment]
@ZakGriffith Sounds good! Flipped this to draft until this is updated... 

image

When it's ready just click Ready for review and @ me =)

**Comment by ZakGriffith** [comment]
Looking that [PR#12836](https://github.com/ethereum/ethereum-org-website/pull/12836) was merged with these updated challenges.  This PR can be safely closed without merge.  Thank you @wackerow

**Comment by wackerow** [comment]
Great, thanks @ZakGriffith!

**Comment by ZakGriffith** [comment]
I apologize and was incorrect.  With the merge of [PR#12836](https://github.com/ethereum/ethereum-org-website/pull/12836) this one will also need merged as is because they are now duplicates of two challenges introduced in that PR. @wackerow

**Review by corwintines — APPROVED** [review]
LGTM! Checked this over and looked ready for review @ZakGriffith so I flipped it over. Going to bring this in, but if you think anything was missed let me know!

**Pull request merged**
