### PR TITLE
Update logo.svg to square [Fixes #6165]

### LINKED ISSUE #6165: Publish certificate and logo to the ethereum.org website
**Describe the solution you'd like**

We've got the certificate and logo for the https://github.com/ethereum/devops/issues/784 and now to put it live we need to publish them somewhere on the ethereum.org website. Then I'll add required DNS records. 
[bimi.zip](https://github.com/ethereum/ethereum-org-website/files/8576923/bimi.zip) contains `logo.svg` and `bimi.pem`.
Please publish them in any convenient folder on  ethereum.org and share the URLs with me.

**Additional context**

Here's a description of what's it and how it looks like - https://www.dmarcanalyzer.com/bimi/how-to-create-a-bimi-record/

### PR DESCRIPTION
**Pull request by samajammin**
## Description

Update logo.svg to square. 

Context: https://www.dmarcanalyzer.com/bimi/how-to-create-a-bimi-record/

> BIMI works with [SVG images](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics). The SVG image has to be squared logo, without any additional text.

## Related Issue

#6165

### CODE REVIEW

**Comment by samajammin** [comment]
> Hey Sam, unfortunately this won't work as intended. The certificate file has a digital signature of the logo.svg inside. It should be updated or it will break the integration.

Ok, can we updated the certificate file with the new square logo.svg?

**Comment by Aldekein** [comment]
I'm trying to figure out certificate reissuance with DigiCert, since Google is asking me for more and more weird proofs while I already supplied them all helpful information.

**Comment by minimalsm** [comment]
@Aldekein any update on th is :-)?

**Comment by Aldekein** [comment]
Yes. Google is silently debugging it in their depths. I've checked what it's visible on user side: they convert SVG to PNG on backend and supply it base64-encoded to the browser, so that's where the problem occurs. Meanwhile I'm passing all the hoops to reissue the certificate with a new logo through DigiCert. While it's in progress, I've disabled the DNS entry to hide the distorted logo from public.

**Comment by Aldekein** [comment]
The new certificate I'll get soon (hopefully) should be added to this PR besides `static/logo.svg` file and then merged.

**Comment by Aldekein** [comment]
Here are the updated cert and logo: [bimi_certificate_and_logo.zip](https://github.com/ethereum/ethereum-org-website/files/8833443/bimi_certificate_and_logo.zip)

**Review by minimalsm — APPROVED** [review]

**Pull request merged**
