### PR TITLE
feat(theme): add Alert component and theme

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Description
_This is part of the [Implementation of the DS v1](https://github.com/ethereum/ethereum-org-website/issues/9548)_

Adds the `Alert` component and theming per the [new DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=2114-43571)

### CODE REVIEW

**Comment by nloureiro** [comment]
@TylerAPfledderer the hover effect on the close button for the alerts needs to be the same as the tags, my bad,  I did not add this detail to the Figma file. sorry about that

**Review by pettinarip — CHANGES_REQUESTED** [review]
Nice job @TylerAPfledderer 

Based on @nloureiro's comment, we need to apply the same styles on the close button as in the Tag component. https://dev--63b7ea99632763723c7f4d6b.chromatic.com/?path=/story/molecules-display-content-tags--style-variants-basic

FYI and context, we also have this other issue https://github.com/ethereum/ethereum-org-website/issues/10266 that is going to impact both components styles.

**Comment by TylerAPfledderer** [comment]
@pettinarip right. Would it be fine to handle the close button as a separate PR as before, but one PR to cover both the tag and the alert?

**Comment by pettinarip** [comment]
> @pettinarip right. Would it be fine to handle the close button as a separate PR as before, but one PR to cover both the tag and the alert?

Make sense. Will approve it then 👍🏼

**Review by pettinarip — APPROVED** [review]

**Pull request merged**
