### PR TITLE
Configured ESLint & Prettier

### PR DESCRIPTION
**Pull request by eswarasai**
## Description
- [x] Configured `eslint` and `prettier` as per the [article](https://alligator.io/vuejs/vue-eslint-prettier/)
- [x] Configured `husky` and `pretty-quick` to run linting on staged Git files

```
$ yarn lint --> Lints all the `.js` & `.vue` files under `docs/.vuepress` folder
$ yarn lint:fix --> Auto-fixes the lint warnings
```

## Related Issue
Fixes: #351 

## Checklist:
- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by eswarasai** [comment]
@samajammin - This PR adds the necessary configuration to support ESLint formatting in the project. If you can clone the repo of this branch and run the above commands, you can see the linting errors/warnings. Let me know if you'd like me to fix those errors as well as part of this PR. I didn't want to bloat the PR with all the file changes without deciding on the rules for linting.

Looking forward for your review. Thanks!

**Comment by samajammin** [comment]
Thanks for your submission! Will review ASAP - definitely by end of this week.

**Comment by samajammin** [comment]
Hey @eswarasai - thank you again for your submission!

I checked out the branch, installed dependencies with `yarn` but my `yarn lint` command seems to hang:
```
~/code/ef/ethereum-org-website « git:(pr/353)
$ yarn lint
yarn run v1.19.1
$ eslint "docs/.vuepress/**/*.{js,vue}"
...
```
Any sense of what the issue might be? Running `eslint` on a specific file seems to work. 

I'm on MacOS Catalina running node `v10.13.0`.

**Comment by eswarasai** [comment]
@samajammin - Thanks for the quick review. I've tried the `yarn lint` on the same env as yours and it did work perfectly fine for me. Just to be sure, I've also rebased and resolved the conflicts from that of `dev` branch. Sorry about the force push!

Can you please do a `git pull -r` on this PR and do a clean installation by running `rm -rf node_modules` and then `yarn`?

Please do let me know in case the issue still persists. Thanks!

**Comment by samajammin** [comment]
@eswarasai just tried that, same issue unfortunately. Here's my logs... perhaps something to do with the incorrect/unmet peer dependencies?

```
~/code/ef/ethereum-org-website « git:(pr/353)
$ rm -rf node_modules/

~/code/ef/ethereum-org-website « git:(pr/353)
$ yarn
yarn install v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > vuepress-plugin-sitemap@2.3.0" has unmet peer dependency "chalk@^2.0.0".
warning " > vuepress-plugin-sitemap@2.3.0" has unmet peer dependency "commander@^2.0.0".
warning " > vuepress-plugin-sitemap@2.3.0" has unmet peer dependency "esm@^3.0.0".
warning " > eslint-plugin-prettier@3.1.1" has unmet peer dependency "prettier@>= 1.13.0".
warning " > eslint-plugin-vue@5.2.3" has incorrect peer dependency "eslint@^5.0.0".
warning "eslint-plugin-vue > vue-eslint-parser@5.0.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > pretty-quick@2.0.0" has unmet peer dependency "prettier@>=1.8.0".
[4/4] 🔨  Building fresh packages...
$ netlify-lambda install
netlify-lambda: installing function dependencies
✨  Done in 11.76s.
```

**Comment by eswarasai** [comment]
@samajammin - I highly doubt that as it's working perfectly fine for me. Have you tried running the `eslint` command itself? -- `./node_modules/.bin/eslint "docs/.vuepress/**/*.{js,vue}"`

**Comment by eswarasai** [comment]
@samajammin - No problem at all. Thanks for taking out time in helping me.
Would definitely love to keep contributing more to the project in any way I can 🙂

**Pull request merged**
