### PR TITLE
404 redirect bug

### PR DESCRIPTION
**Pull request by corwintines**
## Description
- Fix redirects on pages that dont exist to properly 404

https://6295310882fe9e2a5c53ad57--ethdotorg-corwin-test.netlify.app/en/testsestse
Can test with the above link, personal Netlify deploy to test production behaviour. 

Screen Shot 2022-05-30 at 2 27 39 PM

### CODE REVIEW

**Comment by corwintines** [comment]
Test with linked Netlify deploy in description :)

**Review by pettinarip — CHANGES_REQUESTED** [review]
@corwintines I think that now it is always resolving a 404.

```
// valid url
curl -I https://6295310882fe9e2a5c53ad57--ethdotorg-corwin-test.netlify.app/en/staking
HTTP/2 404

// invalid url, correct response
curl -I https://6295310882fe9e2a5c53ad57--ethdotorg-corwin-test.netlify.app/asadasd
HTTP/2 404

// invalid nested url, correct response
curl -I https://6295310882fe9e2a5c53ad57--ethdotorg-corwin-test.netlify.app/en/staking/asadasd
HTTP/2 404
```
On existing paths, it is first returning a 404 but then it fetches the correct content.

=====

I would suggest turning off the flag `generateMatchPathRewrites` in our two redirect packages.
- https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify/
- https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/

That will avoid the rule `gatsby-plugin-intl` is writing for us, ending up in these files.
_More context:_ that intl plugin is writing some `matchPath`s for each lang we have https://github.com/wiziple/gatsby-plugin-intl/blob/master/src/gatsby-node.js#L102

**Comment by samajammin** [comment]
@pettinarip will the recent change to our intl plugin #7022 change any of this?

**Comment by pettinarip** [comment]
> @pettinarip will the recent change to our intl plugin #7022 change any of this?

I doubt it. The plugin is not touching many of these things. I mean, we are still doing the same as before in terms of redirects and 404s.

But I can take a look at this. I think it is related to the nested routes problem #6488

**Comment by pettinarip** [comment]
@corwintines closing this in favor of #7137

**Pull request closed without merging**
