### PR TITLE
Fix wrong translation (Chinese Ethereum stack developer doc)

### PR DESCRIPTION
**Pull request by wuzekang**
「心里模型」 is the wrong translation

- https://zhuanlan.zhihu.com/p/30665743
- https://translate.google.cn/?sl=en&tl=zh-CN&text=mental%20model&op=translate

### CODE REVIEW

**Comment by Riely007** [comment]
> 「心里模型」 is the wrong translation
> 
> * https://zhuanlan.zhihu.com/p/30665743
> * https://translate.google.cn/?sl=en&tl=zh-CN&text=mental%20model&op=translate
> 
> ## Description
> ## Related Issue

yes! ought to be "心智模型“. ty! ❤️

**Review by minimalsm — APPROVED** [review]
Thanks for the PR @wuzekang and thanks for double checking @Riely007 😬❤️

**Comment by minimalsm** [comment]
@wuzekang be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

**Comment by minimalsm** [comment]
@all-contributors please add @wuzekang for docs, translations

**Pull request merged**
