### PR TITLE
Fix ERC-4626 interface

### PR DESCRIPTION
**Pull request by vdusart**
Fixing wrong ERC-4626

## Related Issue
#7132

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Thanks @vdusart, LGTM 🚀 

@bahurum can you confirm if you think resolves the issue you highlighted in #7132 adequately?

**Comment by bahurum** [comment]
> Thanks @vdusart, LGTM rocket
> 
> @bahurum can you confirm if you think resolves the issue you highlighted in #7132 adequately?

Functions `exchangeRate()` and `baseUnit()` should be removed. Also, I believe the final note on batch functions should be removed too since it doesn't apply to this EIP. Except for this, the applied changes fix the issue :+1:

**Comment by vdusart** [comment]
> > Thanks @vdusart, LGTM rocket
> > @bahurum can you confirm if you think resolves the issue you highlighted in #7132 adequately?
> 
> Functions `exchangeRate()` and `baseUnit()` should be removed. Also, I believe the final note on batch functions should be removed too since it doesn't apply to this EIP. Except for this, the applied changes fix the issue +1

The last commit should fix it @bahurum :smile:

**Comment by bahurum** [comment]
> > > Thanks @vdusart, LGTM rocket
> > > @bahurum can you confirm if you think resolves the issue you highlighted in #7132 adequately?
> > 
> > 
> > Functions `exchangeRate()` and `baseUnit()` should be removed. Also, I believe the final note on batch functions should be removed too since it doesn't apply to this EIP. Except for this, the applied changes fix the issue +1
> 
> The last commit should fix it @bahurum smile

Great, the issue is now fixed for me! Thank you @vdusart :smile:

**Review by minimalsm — APPROVED** [review]
Thanks @vdusart and @bahurum 

❤️

**Pull request merged**
