### PR TITLE
Added Ethereum in Telugu

### PR DESCRIPTION
**Pull request by its-VSP**
Telugu is a local language spoken in the Indian states of Andhra Pradesh and Telangana

### CODE REVIEW

**Comment by sorumfactory** [comment]
Hello, @its-VSP 
Thank you for your suggestions. We're excited to have Telugu translation. It's now available in Crowdin. If you aren't part of our Slack Workspace yet, please join and communicate with other translators by joining Telugu group :) 

https://join.slack.com/t/ethtranslation/shared_invite/enQtODQzNTM0ODEzMjUzLTM3ZTg1ZjkxNDFjY2ZiOGNlM2M0ZmNhZmVmMjI3NGM5OWE4YjhhZTdkYmVkZThiNzVmM2JlYzM3NTA5NjVmNTE

**Comment by samajammin** [comment]
Thanks for your addition! I hope you continue to look for ways to contribute 😄

**Comment by samajammin** [comment]
@all-contributors please add @its-VSP for content & translation

**Comment by sorumfactory** [comment]
@its-VSP
+) Below is the link to join the Telugu translation :) 
https://crowdin.com/project/ethereumfoundation/te#

**Pull request merged**
