### PR TITLE
fix typo under "MetaMask" description

### PR DESCRIPTION
**Pull request by jspence425**
Updating "over 1 million" to "over 21 million"

### CODE REVIEW

**Review by samajammin — APPROVED** [review]
Not sure if typo or just copy that hasn't been updated in a couple years 😆

**Comment by samajammin** [comment]
Thanks for the PR @jspence425!

Just to confirm - is there any references you could cite to back this claim?

**Comment by jspence425** [comment]
Hey @samajammin, this copy lives on the homepage https://metamask.io:

image

This is why it leads me to believe it was a simple typo, because the copy is 1:1 aside from that number.

**Comment by samajammin** [comment]
A quick Google shows plenty of sources referencing that number, so I feel fine merging this in 👌

**Pull request merged**
