### PR TITLE
Updated ECH invite link 

### PR DESCRIPTION
**Pull request by SunitRoy2703**
## Description

Updated ECH invite link from `discord.io` page to original discord invite link

## Related Issue

Users don't have to get redirected from `discord.io` the slash page

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
Yeah definitely faster this way, too bad we can't have speed and the nice URL hah. Thanks @SunitRoy2703!

**Comment by SunitRoy2703** [comment]
I have just added the invite link, which their `discord.io` page was redirecting to

Please check if there is any problem with this

@minimalsm @wackerow

**Comment by minimalsm** [comment]
> @minimalsm I'm cool with this as long as there isn't any particular spam preventing reason.

Ya agree if it doesn't serve a particular purpose we should just use the native invite. I'm just cognizant that the ECH discord was recently hacked so it might be a security concern. I've pinged Pooja on Discord to weigh in.

**Comment by poojaranjan** [comment]
We decided to go by the customized link for convenience and safety. But, if there is a preference to have native link for Discord, it shouldn't be a problem for us. 
To be sure that the invite link added to the Ethereum.org website should be for unlimited period, I'd recommend adding https://discord.gg/Nz6rtfJ8Cu

**Review by wackerow — APPROVED** [review]

**Comment by wackerow** [comment]
Thanks for weighing in @poojaranjan! And thank you @SunitRoy2703 for the fix!

**Comment by wackerow** [comment]
@all-contributors please add @SunitRoy2703 for bug patch

**Comment by SunitRoy2703** [comment]
> Thanks for weighing in @poojaranjan! And thank you @SunitRoy2703 for the fix!

Thank you so much!

**Pull request merged**
