### PR TITLE
Replaced hero image on the wallets page with hero image from find wallets page

### LINKED ISSUE #9210: Replace hero image on /wallets page
### Is your feature request related to a problem? Please describe.

The current robot hero image on the [wallets](https://ethereum.org/en/wallets) page doesn't really fit. When making the [find wallets](https://ethereum.org/en/wallets/find-wallet) page we came up with a new hero image that could be used in place of this robot.

### Describe the solution you'd like

Replace the robot hero image on the [wallets page](https://ethereum.org/en/wallets) with a new image. The image on the [find wallet page](https://ethereum.org/en/wallets/find-wallet) will work for now.

### Describe alternatives you've considered

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MukulKolpe**
Fixes #9210

## Description

Replaced the current robot hero image on the [wallets](https://ethereum.org/en/wallets) page with a new hero image from the [find wallets](https://ethereum.org/en/wallets/find-wallet) page.

### CODE REVIEW

**Comment by MukulKolpe** [comment]
@corwintines, @minimalsm please can you review this PR?

**Comment by corwintines** [comment]
@MukulKolpe on it. Sorry for delay.

**Review by corwintines — APPROVED** [review]
Thanks @MukulKolpe

**Comment by MukulKolpe** [comment]
Thank you, @corwintines!

**Pull request merged**
