### PR TITLE
Add challenges.ethereum.org

### PR DESCRIPTION
**Pull request by ethers**
Add challenges.ethereum.org

### CODE REVIEW

**Comment by jjmstark** [comment]
@ethers doesn't look like this is in the right place, as you have added it to the "Layer 2" section but `challenges` isn't particular to Layer 2 tech. 

Is there another place where you think it would make sense on this page?

**Comment by ethers** [comment]
@jjmstark The section is "Improving Ethereum’s Scalability" which has L1 and L2.  It looked like a section on L2, but that's only because all links for the section are at the end: it probably isn't helpful to intersperse the L1 links between the L1 and L2 descriptions?
The link to Making Sense of L2 could be brought down after the other articles on scalability to help emphasize that the section is about scalability?  Or is there a "how to contribute" or "call to action" section somewhere else on the site that I missed?

**Comment by samajammin** [comment]
> Or is there a "how to contribute" or "call to action" section somewhere else on the site that I missed?

That sounds relevant to #489 (PR: #520), which I believe is planned to be incorporated into the Community page (#269). @jjmstark any update on the progress of that? If it's far off, should we consider merging #520 & adding this there in the meantime?

**Comment by samajammin** [comment]
Going to accept & merge this for now. I believe adding this to the Community page (#269) would be beneficial as bounties are a great way for folks to get involved with the ecosystem. Thanks folks!

**Comment by samajammin** [comment]
@all-contributors please add @ethers for content

**Pull request merged**
