### PR TITLE
Fix typo in ERC-20 Contract Walk-Through

### PR DESCRIPTION
**Pull request by said026**
## Description

Fix a small typo in ERC-20 Contract Walk-Through

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks @said026!

**Comment by corwintines** [comment]
@all-contributors can you add @said026 for content

**Comment by corwintines** [comment]
@said026 make sure to come claim your POAP in the ethereum.org discord :)

https://discord.gg/zCHhRAgQ

**Comment by said026** [comment]
> @said026 make sure to come claim your POAP in the ethereum.org discord :)
> 
> https://discord.gg/zCHhRAgQ

Thanks for merging my first PR, will make sure to claim my POAP. Have a good day !

**Pull request merged**
