### PR TITLE
Add staking rewards sections

### PR DESCRIPTION
**Pull request by 0xonramp**
## Description

Adds information on staking rewards to `/staking` and `/staking/pools`.

### CODE REVIEW

**Comment by dev-indexcoop** [comment]
Preview can be viewed here: https://ethereumorgwebsitedev01-0xonrampethereumorgwebsitestak.gatsbyjs.io/en/staking/

Thanks for the help @0xonramp.

Ethereum.org friends: we at Index Coop hoped this addition to the pages would be value adding for the user and sit well within the current aesthetic. Do you have any feedback for us? Thank you. @corwintines @jmcook1186 @minimalsm @nhsz

**Comment by dev-indexcoop** [comment]
Could we get some feedback, please? I'm not sure who to direct the question to though.

**Comment by corwintines** [comment]
Leaving my 2 cents here for now, but I don't see this as appropriate content on the staking section of the site

1. This is pretty self promotional for Index Coop in creating its own section of content 
2. This is an index of other actual staking products, this is not protocol staking
3. In order to list staking products, we have a pretty robust product listing form here which would need to be filled out: https://ethereum.org/en/contributing/adding-staking-products/, https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&projects=&template=suggest_staking_product.yaml&title=Suggest+a+staking+product+or+service

Given this page is specifically for protocol staking, I would reject this.

**Comment by corwintines** [comment]
Going to close this out with the above reasoning. Feel free to reopen and push back if you disagree.

**Comment by dev-indexcoop** [comment]
Hi @corwintines,

Thank you for this feedback. If this first proposal came across as a little inorganic, our apologies - it was discussed as an idea with a few Ethereum.org folks and us. Hence, we made the PR.

We'd love to try and achieve something value adding _and_ organic here - what about a dedicated page for indexes which dsETH would fall under as one? Naturally, a diligence process - as for the LST protocols you describe - could be involved.

Thanks. Cc 0xonramp

**Comment by corwintines** [comment]
If you want to open an issue up for discussion I think that would be the next step. Will bring up for comment when its made :)

**Comment by dev-indexcoop** [comment]
Thanks @corwintines,

New issue created here: https://github.com/ethereum/ethereum-org-website/issues/10844.

How can we help you and others bring this up for comment? We're a little unsure on process.

Thanks again.

**Pull request closed without merging**
