### PR TITLE
Shows link/chain icon on hover [Fixes #4487]

### LINKED ISSUE #4487: Link on titles being slightly tedious to click
When hovering over a title on a page the link/chain icon button does not appear unless you hover over the title first then move the cursor across to the icon

**To Reproduce**
For example, go the https://ethereum.org/en/eth2/beacon-chain/

1. Scroll down till you reach "introducing staking"
2. Hover cursor to the left of the "introducing staking" title
3. See the icon doesn't come up

**Expected behavior**

When hovering the cursor to the left of a title, the chain icon apearing

**Desktop (please complete the following information):**

- OS: Window
- Browser: Google Chrome

### PR DESCRIPTION
**Pull request by arghyab0**
When hovering over a subheading on a page, the link/chain icon now appears without having to hover over the title first.

## Description

The original issue could be fixed by using the 'opacity' CSS property. The link icon is given an initial opacity of 0 and on hover is it made 1. I found this to be the simplest solution that requires minimal change. Cheers!

## Related Issue

[Fixes #4487]

### CODE REVIEW

**Review by samajammin — CHANGES_REQUESTED** [review]
Thanks for the PR @arghyab0! This looks great to me but could you please not delete the .env.example file?

**Comment by arghyab0** [comment]
Hey @samajammin, thanks for the review. Sorry for deleting the .env.example file, I have put it back in as requested. Cheers!

**Comment by arghyab0** [comment]
Hey @samajammin, thanks for the review. Sorry for deleting the .env.example file, I have put it back in as requested. Have a nice day!

**Review by Kamushy — APPROVED** [review]

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
Thanks for the PR @arghyab0 ✌️.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @arghyab0 for code

**Pull request merged**
