### PR TITLE
[ShadCN] Migrate Select

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Description

Migrates `Select` component to ShadCN/Tailwind.

Maintains the api from `react-select` and introduces `tailwind-variants` to create the style variants.

Not moving to the ShadCN `Select` as it would require additional logic to mimic `react-select`, and should be addressed in a future PR.

### CODE REVIEW

**Review by pettinarip — COMMENTED** [review]
Nice @TylerAPfledderer this looks cleeean ✨ 

I think this is ready to replace the old Select and complete the migration. Would you mind doing that in this PR? I could help with that as well.

**Comment by TylerAPfledderer** [comment]
@pettinarip I will move on to doing that switch. Thanks!

**Comment by TylerAPfledderer** [comment]
@pettinarip updates have been pushed. Made changes to import for new `Select` in five locations

**Review by pettinarip — APPROVED** [review]
Looks great @TylerAPfledderer! gj 🎉

**Pull request merged**
