### PR TITLE
Support RTL (Initial)

### PR DESCRIPTION
**Pull request by SNikhill**
## Description

This merge will fix the home page to better support RTL languages

The support for the RTL graph is not a part of this PR as configuring Recharts is more cumbersome than thought.

- I have used the Arabic Language to test out the same.

## Related Issue

- #5087

### CODE REVIEW

**Comment by SNikhill** [comment]
I am using "auto" as the direction when it is RTL language as the same would help in case the content is a mixture of both LTR and RTL language.

For Example, in the footer, some links are in English and some are in Arabic.

**Comment by SNikhill** [comment]
(The issue with code-examples is already taken care of by some other change)

**Comment by SNikhill** [comment]
A conflict. `Link.js` was shifted to `Link.tsx`. Looks like the project is being shifted to TypeScript.

**Review by minimalsm — APPROVED** [review]
Sorry for the delay and thanks @SNikhill

**Pull request merged**
