### PR TITLE
removed past events and a dead projects

### PR DESCRIPTION
**Pull request by peth-yursick**

### CODE REVIEW

**Comment by wackerow** [comment]
Nice, thanks!... currently rebuilding `community` page, and am implementing a filter to remove old events once last day of event has passed so hopefully some of this won't be as necessary to keep front-end UI up to date. (#1763)

**Comment by samajammin** [comment]
Thanks for this @peth-yursick! @GeorgeTrotter @ryancreatescopy can you please confirm these projects (MarketingDAO & MetaClan) are no longer active?

**Comment by samajammin** [comment]
Confirmed that MarketingDAO is in "hibernation", so safe to remove for now.

**Comment by samajammin** [comment]
Dropped a question in the MetaClan Discord: https://discord.com/channels/672197369370247201/695336008522399804/776183680611385374

**Comment by ryancreatescopy** [comment]
I've also messaged metaclan on Twitter. Awaiting response.

**Review by samajammin — APPROVED** [review]

**Comment by samajammin** [comment]
Received reply from MetaClan - "for now it's kinda down" - so accepting & removing for now.

**Comment by samajammin** [comment]
@all-contributors please add @peth-yursick for content.

**Pull request merged**
