### PR TITLE
Polygon Hermez no longer exists and link is non-functional, should be renamed to Polygon zkEVM 

### LINKED ISSUE #9263: Polygon Hermez no longer exists and link is non-functional, should be renamed to Polygon zkEVM
### Describe the bug

https://ethereum.org/en/developers/docs/scaling/zk-rollups/

links to https://docs.hermez.io/zkEVM/architecture/introduction/

which no longer exists

### To reproduce

1.Go to https://ethereum.org/en/developers/docs/scaling/zk-rollups/
2.Scroll to the bottom at "who is working on a zkEVM"

### Expected behavior

Should be linked to https://polygon.technology/solutions/polygon-zkevm

Description should be changed to :

Polygon zkEVM is a decentralized ZK Rollup on the Ethereum mainnet working on a zero-knowledge Ethereum Virtual Machine (zkEVM) that executes Ethereum transactions in a transparent way, including smart contracts with zero-knowledge-proof validations.

### Screenshots

Screenshot 2023-01-23 at 00 50 12

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mesquitaoliveira**
Polygon Hermez no longer exists and link is non-functional, should be renamed to Polygon zkEVM [Fixes #9263]

## Description

This PR resolves the link error and changes the description:
https://docs.hermez.io/zkEVM/architecture/introduction
https://polygon.technology/solutions/polygon-zkevm

## Screenshot:
image

Old version here:
https://github.com/0xPolygonHermez/zkevm-doc/blob/feature/merge-hermez-1.0-docs/mkdocs/docs/zkEVM/architecture/introduction.md or
https://docs.hermez.io/zkEVM/zkProver/Verifiable-Computations/Fibonacci

Updated similar version: https://wiki.polygon.technology/docs/zkEVM/zkProver/mfibonacci-example

## Related Issue

Fixes #9263

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
LGTM!

**Review by Fqc301033 — APPROVED** [review]

**Review by Fqc301033 — APPROVED** [review]

**Review by Fqc301033 — APPROVED** [review]

**Review by Fqc301033 — APPROVED** [review]

**Review by corwintines — APPROVED** [review]
Thanks, @mesquitaoliveira! Appreciate it.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. We are in the process of getting our 2023 POAPs ready, but once they are you can [claim yours](https://ethereum.org/en/contributing/#poap)also 🥳

**Comment by corwintines** [comment]
@all-contributors can you add @mesquitaoliveira for docs

**Comment by mesquitaoliveira** [comment]
Thanks, @corwintines!🎉

> Thanks, @mesquitaoliveira! Appreciate it.
> 
> Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. We are in the process of getting our 2023 POAPs ready, but once they are you can [claim yours](https://ethereum.org/en/contributing/#poap)also 🥳

**Pull request merged**
