### PR TITLE
Adding metaschool to developer learning tools

### PR DESCRIPTION
**Pull request by Ash20pk**
I would like to add our platform metaschool to `developers/learning-tools page.`

We are a web3 education platform which helps web2 developers transit to web3 and we already have a whole learning track for Ethereum

Adding Metaschool information to the Learning Tools page. Included Metaschool logo and files changes as necessary.

Thanks

### CODE REVIEW

**Comment by Ash20pk** [comment]
I had a chat with @samajammin he said go for it

**Review by corwintines — APPROVED** [review]
Thanks, @Ash20pk

**Comment by corwintines** [comment]
@all-contributors can you add @Ash20pk for content

**Comment by Ash20pk** [comment]
> Thanks, @Ash20pk

Thank @corwintines for the merge !

**Pull request merged**
