### PR TITLE
Fixed Documentation Punctuation

### PR DESCRIPTION
**Pull request by arcAman07**
There was a punctuation error in the docs and I though of fixing it.

## Description

I really believe in solving and contributing in smallest of the issues so I saw the error and thought of fixing it.

### CODE REVIEW

**Comment by minimalsm** [comment]
@arcAman07 thanks for the PR 😄 👍

**Comment by arcAman07** [comment]
Thanks I am looking forward to contribute more to this amazing organisation.

**Comment by minimalsm** [comment]
@arcAman07 Awesome! Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team ✌️

**Comment by arcAman07** [comment]
Sure actually I really wanted to get started with proper contributing to ethereum. I am pretty well versed with the concepts of blockchain and smart contracts. Also I do know how to code smart contracts in solidity. So just wanted to ask how to venture into this organization and contribute in bigger things

**Pull request merged**
