### PR TITLE
feat(RoadmapActionCard): create story

### LINKED ISSUE #13211: RoadmapActionCard
# Create story tests for RoadmapActionCard component

## Prerequisite

To get yourself up to speed on how we use storybook on ethereum.org, learn more [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/applying-storybook.md)

## What to do
- [x] Move `/src/components/Roadmap/RoadmapActionCard.tsx` to `/src/components/Roadmap/RoadmapActionCard/index.tsx`
- [x] Fix any imports for RoadmapActionCard component
- [x] Create story file `/src/components/Roadmap/RoadmapActionCard/RoadmapActionCard.stories.tsx`
- [x] Write story testing render of the RoadmapActionCard component in context of use. 

Note: For reference of this component in use, look at [/public/content/roadmap/index.md](https://github.com/ethereum/ethereum-org-website/blob/9fe3b2d2af409bee47fba1759541af962ce2274c/public/content/roadmap/index.md#L25). You can see the context used is in a [CardGrid component](https://github.com/ethereum/ethereum-org-website/blob/9fe3b2d2af409bee47fba1759541af962ce2274c/src/layouts/Roadmap.tsx#L37). Please reference implementation for your storybook test.

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Description

Create basic story for the `RoadmapActionCard` in context with the `CardGrid` component from the `Roadmap` layout.

## Related Issue

- Closes #13211

## Additional Info

This PR also includes a fix to `Translation`, now using `InlineLink` as the component for transforming anchor tags. Previously, a possible cyclical dependency import was occuring, and failing the Chromatic check

### CODE REVIEW

**Comment by wackerow** [comment]
image

`GlossaryTooltip` and `GlossaryDefinition` errors

**Comment by TylerAPfledderer** [comment]
> image
> 
> `GlossaryTooltip` and `GlossaryDefinition` errors

Waiting on #13205 to see if that fixes it

**Comment by pettinarip** [comment]
> > image
> > `GlossaryTooltip` and `GlossaryDefinition` errors
> 
> Waiting on #13205 to see if that fixes it

Merged

**Comment by TylerAPfledderer** [comment]
@wackerow @pettinarip it now throws the same error locally, just with a slightly different error stack
```bash
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (index.tsx:81:1)
    at ./src/components/Translation.tsx (Translation.tsx:19:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at ./src/components/Glossary/GlossaryTooltip/index.tsx (src_components_Glossary_GlossaryTooltip_index_tsx-src_components_TooltipLink_tsx-src_componen-3ad31d.iframe.bundle.js:24:81)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at ./src/components/TooltipLink.tsx (index.tsx:81:1)
```

I don't understand why it's pointing to an unrelated component and only throws with `RoadmapActionCard` 🫠

**Comment by TylerAPfledderer** [comment]
But based on this information, I still see the issue lying in `GlossaryTooltip` in the way 

```tsx
const components = {
  a: InlineLink,
}
```
is overriding
```tsx
const defaultTransform = {
  a: TooltipLink,
}
```

for the `htmr()` in `Translation`.

**Comment by wackerow** [comment]
@TylerAPfledderer I was just able to build this locally without those errors. Are we sure that override is a problem? Curious how this Netlify build goes

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer I was just able to build this locally without those errors. Are we sure that override is a problem? Curious how this Netlify build goes

What happens after initial load of Storybook with the RoadmapActionCard story open and you refresh the entire page?

**Comment by wackerow** [comment]
@TylerAPfledderer Yeah sorry, I take that back, I'm still getting it for this molecule:

```
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (http://localhost:6006/src_components_Glossary_GlossaryTooltip_index_tsx-src_components_TooltipLink_tsx-src_componen-3ad31d.iframe.bundle.js:463:42)
    at ./src/components/Translation.tsx (http://localhost:6006/src_components_Glossary_GlossaryTooltip_index_tsx-src_components_TooltipLink_tsx-src_componen-3ad31d.iframe.bundle.js:599:49)
    at options.factory (http://localhost:6006/runtime~main.iframe.bundle.js:655:31)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:313:21)
    at ./src/components/Glossary/GlossaryTooltip/index.tsx (http://localhost:6006/src_components_Glossary_GlossaryTooltip_index_tsx-src_components_TooltipLink_tsx-src_componen-3ad31d.iframe.bundle.js:24:81)
    at options.factory (http://localhost:6006/runtime~main.iframe.bundle.js:655:31)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:313:21)
    at ./src/components/TooltipLink.tsx (http://localhost:6006/src_components_Glossary_GlossaryTooltip_index_tsx-src_components_TooltipLink_tsx-src_componen-3ad31d.iframe.bundle.js:468:83)
```

**Comment by TylerAPfledderer** [comment]
@wackerow looking closer, I think `InlineLink` might be the issue.

It's being imported in `GlossaryTooltip` and the `TooltipLink`, and `Translation` imports `TooltipLink`, while `GlossaryTooltip` passes `InlineLink` to `Translation` to override `TooltipLink` in use with the anchor tag.

Did I get that logic flow right? 😅

**Comment by wackerow** [comment]
@TylerAPfledderer Yeah, I'm seeing the same thing, and simply removing the `components` object, don't pass this to `Translation`, and just changing the `defaultTransform` to

```tsx
const defaultTransform = {
  a: InlineLink,
}
```

**Comment by TylerAPfledderer** [comment]
@wackerow yep, looks that seems to work as well on my end.

How would you prefer confirming this? Just make the change in this PR or make a new PR?

Since it is only a problem right now when making a new story, I think it's fine to add the bloat and notate as a minor addition.

If for whatever reason Chromatic still fails, then can decide at that point whether or not to revert the commit in favor of a different PR.

**Comment by wackerow** [comment]
Yeah I think that's fine, I'll commit this patch and push it

**Comment by TylerAPfledderer** [comment]
> Yeah I think that's fine, ~I'll commit this patch and push it~ just committed and pushed that patch

Hallelujah, it works! 🎉🎺

**Review by corwintines — APPROVED** [review]
Awesome, LGTM!

**Pull request merged**
