### PR TITLE
docs: Add covalent info into backend API libraries

### PR DESCRIPTION
**Pull request by davidzhangg**
This PR adds Covalent as a API provider to the list of backend API libraries!
CovalentHQ -> https://www.covalenthq.com/

### CODE REVIEW

**Comment by davidzhangg** [comment]
Hey @minimalsm, my colleague created a PR a while ago -> https://github.com/ethereum/ethereum-org-website/pull/10999
Can we get this merged in? Thanks!

**Review by wackerow — COMMENTED** [review]
Lgtm, thank @davidzhangg! 

There are merge conflicts here since a recent PR (#12605) added sub-categories on this page... 

```
1. Infrastructure and Node Services
2. Development Tools
3. Blockchain Services
```

When you clean the conflicts you'll just have to place it at the end of one of these three categories. Probably "Blockchain services"? Let me know if you want a hand here

**Comment by davidzhangg** [comment]
@wackerow fixed the merge conflict!

**Review by wackerow — APPROVED** [review]
Looks good, thanks @davidzhangg

**Pull request merged**
