### PR TITLE
Adding Ethplorer to the list of block explorers

### PR DESCRIPTION
**Pull request by ArtemKo7v**
## Description

Adds Ethplorer as a block explorer to the list of block explorers.

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks for the PR!

@CPSTL - please review at your earliest convenience.

**Comment by CPSTL** [comment]
Hey @ArtemKo7v, looks good to me. However, I'd like to request one change - we ask users to add new additions to the bottom of each list to keep treatment consistent and fair. Please make that update and we will get this merged!

**Comment by ArtemKo7v** [comment]
> Hey @ArtemKo7v, looks good to me. However, I'd like to request one change - we ask users to add new additions to the bottom of each list to keep treatment consistent and fair. Please make that update and we will get this merged!

Updated. Thank you!

**Comment by samajammin** [comment]
Hey @ArtemKo7v - sorry for the delay on this. We recently underwent a major refactor of the site - this page now exists at [/src/content/developers/index.md](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/index.md) - could you please rebase with the latest from the `dev` branch, then make this addition in that file? It might be easiest to open a new PR.

Please let me know if you'd prefer me to save you the hassle & I will make this change ourselves. I just want to ensure we give you proper commit credit if you'd like 😄. Thanks!

**Comment by ArtemKo7v** [comment]
> Hey @ArtemKo7v - sorry for the delay on this. We recently underwent a major refactor of the site - this page now exists at [/src/content/developers/index.md](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/index.md) - could you please rebase with the latest from the `dev` branch, then make this addition in that file? It might be easiest to open a new PR.
> 
> Please let me know if you'd prefer me to save you the hassle & I will make this change ourselves. I just want to ensure we give you proper commit credit if you'd like 😄. Thanks!

Thank you! We would be grateful if you could please make these changes yourself.

**Comment by samajammin** [comment]
Closing this in favor of #1167

**Comment by samajammin** [comment]
@all-contributors please add @ArtemKo7v for content.

**Pull request closed without merging**
