### PR TITLE
Fix docs h4 anchor covered by navbar [Fixes #3892]

### LINKED ISSUE #3892: URL Fragment Identifier bug on H4 headings
**Describe the bug**
When you visit a developer doc and use the section header ID's in the sidebar or visit the the URL directly (i.e. go to /docs/nodes-and-clients/#openethereum) the heading is cut off at the top of the screen by the nav and subnav.

This problem only happens on H4s.

Example - https://ethereum.org/en/developers/docs/nodes-and-clients/#erigon
Screenshot 2021-09-13 at 13 17 08

If we inspect the element and delete the navbar and subnav we will see the heading at the top of the page.

Screenshot 2021-09-13 at 13 16 50

**To Reproduce**

1. Go to 'https://ethereum.org/en/developers/docs/nodes-and-clients/#erigon'
2. See error

**Expected behavior**
The heading should be visible below the subnav.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave Browser
- Version: 1.28.106

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by calvinsomething**
## Description

Inherited `Header4` from `SharedStyledComponents` and copied styling for same headers from the tutorials template. Everything appears to work as intended.

## Related Issue

This closes #3892.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks @calvinsomething! Looks good with following previous patterns.

Would be curious if there is a better way to do this with element scrolling, but that feels like an overall tech debt thing to address and not specific to this.

**Comment by minimalsm** [comment]
Thanks, appreciate the PR @calvinsomething 👍 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @calvinsomething for bugs and code

**Comment by minimalsm** [comment]
> Would be curious if there is a better way to do this with element scrolling, but that feels like an overall tech debt thing to address and not specific to this.

@corwintines would appreciate it if you could explain this to me so I can create an issue 👍🙂

**Comment by calvinsomething** [comment]
Great! Thank you 😄

**Pull request merged**
