### PR TITLE
Replace broken ETH staking link with an updated, valid one [Fixes #5198]

### LINKED ISSUE #5198: Broken link to ETH staking on the Beacon Chain upgrade page
**Describe the bug**

The link to information about ETH staking is broken (Resource Not Found) on the Beacon Chain upgrade page.

**To Reproduce**

1. Go to https://ethereum.org/en/upgrades/beacon-chain/
2. Click on 'stake your ETH' under the 'WHEN'S IT SHIPPING?' section
3. See 'Resource Not Found' error after being navigated to the https://ethereum.org/en/upgrades/staking/

**Expected behavior**

Expected to be navigated to a valid page relevant to staking ETH, perhaps the ETH staking landing page such as https://ethereum.org/en/staking/

**Screenshots**
beacon_chain_upgrade_page

resource_not_found

**Desktop (please complete the following information):**

- OS: MacOS 12.1
- Browser: Safari
- Version: 15.2 (17612.3.6.1.6)

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro
- OS: iOS 15.2.1
- Browser: Safari
- Version: 15

**Additional context**

N/A

**Want to contribute?**

Yes! Would love to help fix and test this bug with a PR :)

### PR DESCRIPTION
**Pull request by lingzhong**
Replace all broken (outdated) links to the ETH staking page.

## Description

Replace all broken (outdated) links to the ETH staking page, in all available languages.

## Related Issue

 #5198

### CODE REVIEW

**Comment by lingzhong** [comment]
Hey @minimalsm changes done, tested. Build passed. PTAL!

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
Thanks for spotting and fixing this @lingzhong ✌️.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

**Comment by minimalsm** [comment]
@all-contributors please add @lingzhong for docs

**Comment by samajammin** [comment]
Thanks @lingzhong!

**Pull request merged**
