### PR TITLE
Add EIP information to "Get Involved" page

### PR DESCRIPTION
**Pull request by Pandapip1**
## Description

Adds EIP-related links to "Get Involved" page.

CC @dtedesco1 

## Related Issue

*N.A.*

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Just moved some of the button links that were added, but LGTM. Thanks @Pandapip1!

**Comment by Mohya8240** [comment]
:)

**Comment by Zaitnoori** [comment]
Noori

**Comment by mustafacryptolife** [comment]
[]()

**Pull request merged**
