### PR TITLE
Spanish correction on whitepaper

### PR DESCRIPTION
**Pull request by rich1n**
democratizadr => democratizador

### CODE REVIEW

**Comment by minimalsm** [comment]
Thanks for the PR @rich1n 🤘

Looks correct (according to Google translate), just waiting on a Spanish speaker confirming.

cc: @pettinarip

**Review by pettinarip — APPROVED** [review]
Looks good! thanks @rich1n!

**Comment by rich1n** [comment]
thanks for the approval; if found any spanish translation issue again I'll make another PR.

**Comment by lukassim** [comment]
> thanks for the approval; if found any spanish translation issue again I'll make another PR.

Hey, please note that the translation changes aren't normally handled on GitHub.
The translations should always be changed in Crowdin, whereas the source content changes are handled on GitHub.

In case there are any other revisions you would like to make, feel free to highlight them in Crowdin and tag @LukaK to make sure we get eyes on this as soon as possible. Thanks.

**Comment by minimalsm** [comment]
@all-contributors please add @rich1n for docs, translations

**Comment by minimalsm** [comment]
Thanks @rich1n ❤️

**Comment by LukaK** [comment]
@lukassim think you have tagged me by mistake :)

**Comment by lukassim** [comment]
@LukaK Seems like it, apologies... 😅

**Comment by LukaK** [comment]
@lukassim No worries, best of luck!

**Comment by rich1n** [comment]
thanks, @lukassim, I have some weeks translating on crowdin...

**Pull request merged**
