### PR TITLE
Add Bedrock (RockX) to pooled staking products [Closes #9792]

### LINKED ISSUE #9792: Suggest a staking product or service
### Project name

Bedrock Liquid Staking & Staking Pool

### Product type

Staking Pool

### If other product type, please describe

-

### Logo

rockx_logo-white text@2x
rockx_logo-dark text@2x

### Description

Bedrock is a non-custodial solution that fits the needs of institutions looking for a foundation for liquid staking at scale through cutting-edge technology and regulatory compliance. By bringing a whole new level of transparency and security to liquid staking, Bedrock allows institutions to unlock liquidity safely while leveraging a true crypto-native solution.

### Website

https://bedrock.rockx.com/

### If software is involved, is everything open source?

Yes, everything is open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

The product is out of beta development and has been launched on Ethereum mainnet. It has been online for ~ 6 months. https://etherscan.io/tx/0x725b15afd741bef44fef37e612204150d451dc514af2bab133273121107a5fb3

Project GitHub: https://github.com/RockX-SG/stake

LP: https://app.balancer.fi/#/ethereum/pool/0xbfce47224b4a938865e3e2727dc34e0faa5b1d82000000000000000000000527

### What wallets support the product or service?

All wallets that support ERC20 tokens

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

No minimum, however we recommend staking more than 0.01 ETH,

### If a service, what are the fees associated with using the service?

10% of staking rewards

### If the product or service involved a liquidity token, what are the tokens involved?

UniETH is the liquidity token

Verification of total uniETH supply on-chain: https://etherscan.io/token/0xF1376bceF0f78459C0Ed0ba5ddce976F1ddF51F4
Verification of all deposits into uniETH on-chain: https://etherscan.io/address/0x4beFa2aA9c305238AA3E0b5D17eB20C045269E9d

### What date did the project or service go live?

29 Sep 2022 (https://etherscan.io/tx/0x725b15afd741bef44fef37e612204150d451dc514af2bab133273121107a5fb3)

### Has the project undergone an external security audit?

Yes

Smart contract audit report: https://github.com/RockX-SG/stake/blob/main/PeckShield-Audit-Report-RockXStaking-v1.0.pdf

### Has the project undergone any security bug bounties?

None yet, however, we plan to launch a bug bounty in the near future.

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

Yes, it is all managed by smart contracts

### If a pooled staking service, can users participate as a node operator without permission?

Yes

### If listing a staking-as-a-service, are users required to sign-up for an account?

-

### If listing as staking-as-a-service, who holds the signing keys, and withdrawal keys?

-

### If a pooled staking service, what percent of node operators are running a super-majority consensus layer client?

Currently at 100%, however, we will be implementing DVT to decentralize the validators in addition to setting up the Bedrock DAO.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

-

### What platforms are supported?

Most platforms supported including Linux, macOS, Windows, iOS, Android

### What user interfaces are supported?

Browser app for now

### Social media links

Twitter: https://twitter.com/rockx_official
LinkedIn: https://www.linkedin.com/company/rockx-official
Discord: https://discord.gg/YJzs4UwsTp
YouTube: https://www.youtube.com/channel/UCur9s16EemOPuY_YAXhtG9A

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Adds Bedrock by RockX to list of pooled staking services

@Gandalf-Dust-Wizard On the issue it was noted that users could join as node operators to back the pooled staking without any permission. I may have missed it, but I wasn't able to find how to do this on the website. If users are able to join without permission to contribute as node operators, please do me a favor and guide me where a user could find this option, and we can update that flag from `false` to `true`.

## Related Issue
- Closes #9792

### CODE REVIEW

**Review by corwintines — APPROVED** [review]

**Comment by Gandalf-Dust-Wizard** [comment]
@wackerow in relation to your question above, please find an answer below:

Because the way Bedrock works is that there is a First In First Out logic to the smart contract that pools the 32 ETH it receives to be deployed as a validator node. To that end, users are made part of nodes permissionlessly without any control or permission required by RockX.

**Comment by wackerow** [comment]
@Gandalf-Dust-Wizard Okay, if I understand correctly, the pool is permissionless to join as a staker (ETH contributor), but it's not set up where anyone can become a node _operator_ for the pool... is this correct? Or is there a way for me/others to participate by running client software for the pool, and managing validators?

**Comment by wackerow** [comment]
Just want to check because the "Permission nodes" indicator on the pooled staking services is in regards to the ability for anyone to join as a node operator, not just contributing ETH. This indicator is looking at the node infrastructure itself that backs the pools.

**Comment by Gandalf-Dust-Wizard** [comment]
Sorry, forgot to update this thread. But as spoken on Discord, you are right and we are currently permission nodes. On the other note I mentioned on Discord. Please see the new logo for Bedrock to replace the current RockX logo.
Bedrock-logo

**Pull request merged**
