### PR TITLE
update links to client diversity [Fixes #7896]

### LINKED ISSUE #7896: Links to "client diversity" are broken
### Describe the bug

On the "[Spin up your own Ethereum node](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/)" page there are three links to "client diversity" which do not work.

### To reproduce

1. go to https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
2. click on [client diversity](https://ethereum.org/en/developers/docs/client-diversity)
3. it shows a 404 page

### Expected behavior

It should link to this page:
https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barro32**
Update the links to the "client diversity" page. 

[Fixes #7896]

### CODE REVIEW

**Review by jmcook1186 — APPROVED** [review]
thanks for catching this!

**Review by minimalsm — APPROVED** [review]
Thanks for the PR @barro32 💪 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also!

**Comment by minimalsm** [comment]
@all-contributors please add @barro32 for docs

**Comment by barro32** [comment]
Thank you!

**Pull request merged**
