### PR TITLE
Solidity is not "heavily inspired by JavaScript"

### PR DESCRIPTION
**Pull request by Arachnid**

### CODE REVIEW

**Comment by franzihei** [comment]
Yes, absolutely agree with this change. I didn't know there were other places that talk about Solidity, otherwise I would have suggested this change myself! :) See https://ethereum.org/en/developers/docs/smart-contracts/languages/ where we said "most profoundly influenced by C++" - but of course Solidity takes concepts from other languages as well. Generally one can say that Solidity will feel familiar for anybody who has experience with curly-bracket languages (https://en.wikipedia.org/wiki/List_of_programming_languages_by_type#Curly-bracket_languages).

**Comment by franzihei** [comment]
This really makes me wonder why people still believe Solidity is inspired by JavaScript... Btw we wrote a section on language influences [here in the docs](https://docs.soliditylang.org/en/latest/language-influences.html).

**Review by minimalsm — APPROVED** [review]
Thanks for the PR @Arachnid and thanks for confirming @franzihei. I feel like I see this everywhere (possibly the fault of the ethereum.org docs). I'll keep a lookout for anywhere else on the site we discuss this and fix those cases also.

**Comment by minimalsm** [comment]
@Arachnid you're also able to [claim a 2022 contributor POAP](https://ethereum.org/en/contributing/#poap) for this 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @Arachnid for docs

**Pull request merged**
