### PR TITLE
Implementing security.txt

### PR DESCRIPTION
**Pull request by fredriksvantes**
## Description

Adding security.txt to https://ethereum.org/.well-known/security.txt as per https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12

## Related Issue
#3486

### CODE REVIEW

**Comment by fredriksvantes** [comment]
Public key is in the following PR: #3486

**Comment by Aldekein** [comment]
https://ethereum.org/security_at_ethereum.org.asc gives 404 error and is not part of this PR.

**Comment by fredriksvantes** [comment]
> https://ethereum.org/security_at_ethereum.org.asc gives 404 error and is not part of this PR.

I've now moved the security_at_ethereum.org.asc into this PR (instead of being in #3486)

**Comment by JustinDrake** [comment]
As a side note I don't have access to security@ethereum.org.

(I do have access to eth2security@ethereum.org but that's used for recruiting security researchers, not for disclosing vulnerabilities.)

**Review by samajammin — APPROVED** [review]
Thanks for this!

**Pull request merged**
