### PR TITLE
Adding Consensys Staking to staking provider list

### LINKED ISSUE #10316: List Consensys under staking as a service
### Project name

Consensys

### Product type

Staking as a service

### If other product type, please describe

_No response_

### Logo

Staking Logo

### Description

Consensys Staking is a self-custodial staking service for Ethereum that offers enterprise-grade staking for ETH holders. The service focuses on security and resilience and has SOC2 Types I and II certification. It is multi-cloud, multi-client and multi-region to give customers a distributed staking operation.

Consensys’ expertise and engagement in the ecosystem that include leading products like Teku, Metamask, Infura and Besu as well as protocol-level research and development.  Consensys Staking is able to leverage the expertise of these teams to deliver the best possible service to its customers.

### Website

https://consensys.net/staking/?utm_source=Ethereum%20Foundation&utm_medium=Website&utm_campaign=Partner

### If software is involved, is everything open source?

Portions of code are open source: provide link(s) to project repo(s)

### Is the project a fork? If yes, which project was forked?

No

### Is the product out of beta development?

Yes. We have been in production and mainnet since genesis of the Beacon Chain on December 1, 2020.

### What wallets support the product or service?

Metamask, MMI and Wallet Connect

### If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?

32 ETH is the minimum

### If a service, what are the fees associated with using the service?

We take a custom percentage of fees based on the expected volume of staking.

### If the product or service involved a liquidity token, what are the tokens involved?

No tokens are involved.

### What date did the project or service go live?

December 1, 2020

### Has the project undergone an external security audit?

We undergo security audits every year.

### Has the project undergone any security bug bounties?

Hackerone - https://hackerone.com/consensys?type=team

### Is the project being actively maintained?

Yes

### Is the product or service free of trusted/human intermediaries?

There is no part of the user journey involving the trust of funds to Consensys or a smart contract by Consensys.

### If a pooled staking service, can users participate as a node operator without permission?

No pooling in this service.

### If listing a staking-as-a-service, are users required to sign-up for an account?

Yes. The user has to agree to our terms and conditions to be given an account.

### If listing as staking-as-a-service, who has access to the signing keys?

Signer Keys are generated and injected directly into cloud-based HSMs. Access to these is restricted to the remote signer software.

The user must maintain access to their withdrawal key(s). Consensys Staking never has access to any withdrawal key.

### If a pooled staking service or SaaS provider, what type of withdrawal credentials are being utilized / who holds the withdrawal keys?

User holds their withdrawal key(s).

### If a pooled staking service or SaaS provider, what percent of node operators are running a super-majority client?

We run 50% Lighthouse and 50% Teku at time of writing. We currently run majority Geth execution layer but are looking to diversify over the next quarter.

### If listing node or client tooling, which consensus layer clients (Lighthouse, Teku, Nimbus, or Prysm) are supported?

We run Lighthouse and Teku.

### What platforms are supported?

Linux, macOS and Windows

### What user interfaces are supported?

browser app and graphiql and api

### Social media links

_No response_

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by beetrootkid**
## Description

Added Consensys Staking to the staking-products.json
Added ConsensysStakingGlyphicon to the src files
NB: The second file I'm not sure I've done correctly but hoping for some help to verify cc @wackerow 

## Related Issue
- Closes #10316

### CODE REVIEW

**Comment by wackerow** [comment]
Hey @beetrootkid! Apologies for delays here, but was able to circle back and get this in working order. Couple things:

- I updated the icon to use just the icon portion of the logo from the website. This will fit our theming much better than just using the "words" ("consensys staking") logo.
- I updated a couple field values based on the information that was provided in the original post/discussion; please double check these and let us know if you disagree.

Of note, there is a small bug on this page in the preview where all products are showing "battle tested" with the caution (yellow) icon... this is not yet in production, but is in our `dev` branch and a patch is up here: #12607... By the time this PR hits production the "battle tested" indicator for Consensys Staking will be green, given the launch was years ago.

**Comment by beetrootkid** [comment]
@wackerow  - thanks a lot for following up and fixing 🙏🏾. Looking forward to seeing this change live.

**Review by wackerow — APPROVED** [review]
Looks good, thanks @beetrootkid

**Comment by wackerow** [comment]
@all-contributors please add @beetrootkid for tool

**Pull request merged**
