### PR TITLE
Add Sirato to the list of block explorers.

### PR DESCRIPTION
**Pull request by conor10**
## Description

- Provided link to Sirato home page and Goerli instance
- Add link to blockchain data concepts for less technical users

## Related Issue

N/A

### CODE REVIEW

**Comment by corwintines** [comment]
Thanks @conor10. 

We currently don't list products less than 6 months old. You can see our listing policy [here](https://ethereum.org/en/contributing/adding-products/).

I'm going to close this out with that in mind.

**Comment by conor10** [comment]
@corwintines Sitato is a rebrand of Epirus. Here’s a blog post referencing it back in 2019. It’s been around for a long time, all that’s changed is the name.

https://medium.com/web3labs/epirus-blockchain-explorer-free-version-now-available-30c348028dec

**Comment by conor10** [comment]
Hi @corwintines did you see my comment above? 👆🏻

**Comment by corwintines** [comment]
Thanks for the update @conor10, that helps.

I just had one other question then. Is there a reason someone needs to give their personal information to use this block explorer?

**Comment by conor10** [comment]
Thanks @corwintines. 
From our website we ask for an email to send a sequence of Sirato getting started emails.
If someone heads straight to the GitHub repo there are no constraints.

**Comment by corwintines** [comment]
Interesting. Ok, going to reopen this to review then. Thanks for your patience here.

**Review by corwintines — APPROVED** [review]

**Pull request merged**
