### PR TITLE
refactor(WalletTable): update a11y with accordion

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Related Issue
Discussion #10034

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @TylerAPfledderer :) thanks for this. 

Changes so far are big improvements for a11y. Is this ready for review?

**Comment by TylerAPfledderer** [comment]
@pettinarip @minimalsm this is now available for review!

**Comment by TylerAPfledderer** [comment]
This PR currently suffers from the issue of bumping Chakra to `2.7.*`, which would be super helpful here because `2.7.1` exposes the [SkipNav component tandem](https://chakra-ui.com/docs/components/skip-nav/usage) to provide more flexible instances of skip navigation.

The current alternative would be to install `@chakra-ui/skip-nav` separately, which is what I have currently done here.

**Comment by wackerow** [comment]
Hey @TylerAPfledderer this looks great! Agree this is a big level-up for a11y... 

Is this ready now? Not sure I understand fully your comment on the Chakra versions... we're using 2.8.0 now, should this work with your setup?

(Also, keep in mind @nloureiro opened a PR recently to potentially remove the nested scrolling from the wallets page #11174, just noting)

**Comment by TylerAPfledderer** [comment]
@wackerow it's all fixed (via one of the branch updates).

It should be all good if you're good with it! 😁

**Comment by corwintines** [comment]
Going to close this out with the wallet refactor that is going on. I think we can come back to this after if still needed, but probably going to be very out of date by that time. If you disagree @TylerAPfledderer feel free to reopen though.

**Comment by TylerAPfledderer** [comment]
> Going to close this out with the wallet refactor that is going on. I think we can come back to this after if still needed, but probably going to be very out of date by that time. If you disagree @TylerAPfledderer feel free to reopen though. 

@corwintines all good with me. Thank you!

**Pull request closed without merging**
