### PR TITLE
Updating Cherubs DAO and adding a new project to the list

### PR DESCRIPTION
**Pull request by metalc**
## Description
1- Updating Cherubs DAO to Cerebrum DAO
2- Updating the hyperlink of Cherubs DAO to 21 Impact Labs 
3- Adding DeSci Collective project to the list - https://twitter.com/DeSciCollective

## Related Issue
https://github.com/ethereum/ethereum-org-website/pull/7096

### CODE REVIEW

**Comment by corwintines** [comment]
Hey @metalc. Can you give a little more information on these changes? Why is Cherubs DAO switching to Cerebrum DAO?

I still think what @minimalsm said about DeSci collective holds true here.

**Comment by metalc** [comment]
Hello @corwintines thanks for the reply - as for Cherubs DAO we are moving it to Cerebrum DAO to keep the focus targeted towards Brain Health and Longevity, Cerebrum DAO is also now under the main company which is 21 Impact Labs - https://21impactlabs.com/ it's part of the rebranding and positioning strategy.

Moreover, for DeSci Collective initially, @minimalsm comment was right and I think we established a strong foundation by now. We have a running podcast and we are on Ep. 11 with a lot of contributions to the DeSci space. However, we are fine if we keep this on hold for now until we grow a bit more, but I'll keep that up to you.

Here is the link to the podcast - https://descicollective.buzzsprout.com/

Please let me know if you need anything else and I'm here to answer all the questions.

**Comment by corwintines** [comment]
@metalc I've pushed up some changes to remove the links that were being added here. 

For the 21 Impact Labs link, there really isn't any information about the project on that page. And the projects being linked out to aren't out. 

For the descicollective project, there isn't an announced mint date at the moment https://mintable.app/DeSciCollective . Doesn't really make sense for this to be on ethereum.org. 

Agree with removing ChreubsDAO though.

**Review by corwintines — APPROVED** [review]

**Comment by metalc** [comment]
@corwintines Appreciate your feedback, however, I just want to clarify a couple of things.

- **21 Impact Labs** is the main holding company behind two projects **DeSci Collective** & **Cerebrum DAO** (which will launch next week under http://cerebrumdao.com/)
- As for **DeSci Collective**, the main focus is on the podcast which we run on a regular basis we are already on Ep. 15 (**DeSci Collective Podcast** https://descicollective.buzzsprout.com/ - we are on Apple, Amazon, Spotify, etc.

It'll be awesome to put DeSci Collective Podcast in the learning section and add 21 Impact Labs or Cerebrum DAO to the list.

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Pull request merged**
