### PR TITLE
Added Storage section

### PR DESCRIPTION
**Pull request by virgil**
Seems a sensible thing to mention.

### CODE REVIEW

**Comment by jjmstark** [comment]
makes sense to me - thoughts @maurelian @CPSTL?

**Comment by maurelian** [comment]
If this is targetting developers coming to ethereum... a sentence with context as to _why_ they need storage might be useful?

**Comment by virgil** [comment]
Suggest whatever you'd like to better explain it and the merger can add it in.

**Comment by maurelian** [comment]
Sorry for blocking this. I don't have time right now to modify it, and think it's better included imperfectly than not at all. I've merged locally to fix a conflict and pushed these changes to staging.

**Pull request closed without merging**
