### PR TITLE
feat: Add Hungarian (v1.1)

### PR DESCRIPTION
**Pull request by aranhaagency**
## Description

Hungarian version v1.1 translation has been added

## Related Issue
close https://github.com/ethereum/ethereum-org-website/issues/1447

### CODE REVIEW

**Comment by samajammin** [comment]
@aranhaagency thank you for this PR! I'm going to accept this & pay you the bounty but a couple notes:

1) You should not have submitted a PR before getting approval to work on this bounty. Gitcoin has changed the way they provide bounties & as a result, there's no longer a way for us to run bounties like we have in the past (accepting the 1st to complete the PR, regardless of applying for a bounty). You should only work on a bounty if you have applied to work on the bounty & have received approval to do so. If you submit a PR again without approval, I won't pay out the bounty.

2) The build is currently breaking, because you forgot a `lang: hu` in the frontmatter of one of the project files. Please always check to ensure you're build is working correctly before you submit work for a bounty. I'm going to accept it this time given it's a small fix but moving forward I will reject PRs that have failing builds.

**Comment by samajammin** [comment]
@aranhaagency please submit your work via Gitcoin in order to receive the bounty: https://gitcoin.co/issue/ethereum/ethereum-org-website/1447/100023708

**Comment by samajammin** [comment]
@aranhaagency see comment above.

**Comment by aranhaagency** [comment]
> @aranhaagency see comment above.

I did, sorry for the time.

**Pull request merged**
