### PR TITLE
Adding Crossmint as a Related Tool for Smart Contract deployment

### PR DESCRIPTION
**Pull request by rohit-710**
Adding Crossmint as a Related Tool for Smart Contract deployment

## Description

Added Crossmint as one of the options for Smart Contract deployments

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/11636

### CODE REVIEW

**Comment by rohit-710** [comment]
https://github.com/ethereum/ethereum-org-website/issues/11636

Issue Link above

**Review by nnnnnnsssss — APPROVED** [review]

**Review by wackerow — APPROVED** [review]
Looks good @rohit-710, appreciate the adjustments on these PRs... gonna pull these in.

Will just note that in general the product listings on the site are due for a bit of re-organizing, data-gathering and pruning, so eventually there may be some changes and/or requests here to keep the quality and safety up for users (general statement, not just applicable for Crossmint)

**Comment by wackerow** [comment]
@all-contributors please add @rohit-710 for tool

**Comment by rohit-710** [comment]
Hey @wackerow, that's completely understandable. Please let me know if you need me to make any changes in the future. 

Thank you so much!

**Pull request merged**
