### PR TITLE
Deleting ERC-777 and ERC-1555

### PR DESCRIPTION
**Pull request by ensaryusuf**
Same links but for ERC20 page.

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
@ensaryusuf Same as on #2821... I would just remove the whole "Related topics" section since this link becomes lonely and redundant.

**Comment by ensaryusuf** [comment]
Everything okey.

**Review by wackerow — APPROVED** [review]
@ensaryusuf looks good! thanks =)

**Comment by wackerow** [comment]
@all-contributors please add @ensaryusuf for bug fix

**Pull request merged**
