### PR TITLE
News website BR

### PR DESCRIPTION
**Pull request by mateusnds**
Inclusion of Livecoins news website.

### CODE REVIEW

**Comment by mateusnds** [comment]
> ing us a bit more inf

> @mateusnds would you mind giving us a bit more information on what this website reports on?

Hey @corwintines, sorry for the lack of information and thank you for kindly reviewing the inclusion request.

Livecoins is one of the largest cryptocurrency news portals in Brazil and in Portuguese, we have approximately 4 million monthly pageviews and publish content focused on Ethereum, please visit livecoins.com.br/ethereum.

As I saw that there are other sites similar to ours, with content about cryptocurrencies and Ethereum, I would like to add Livecoins as a news source.

We also have an exclusive tool that shows the volume of Ethereum traded on all exchanges operating in Brazil, if you can, please visit https://www.mercadocripto.livecoins.com.br/ETHBRL

As we always write news about Ethereum, I would like to include my website as a source of information in Portuguese.

Thank you very much

**Comment by corwintines** [comment]
Great, thanks for the info @mateusnds

**Review by corwintines — APPROVED** [review]
LGTM

**Comment by corwintines** [comment]
@all-contributors can you add @mateusnds for content

**Comment by corwintines** [comment]
@mateusnds make sure to come claim your POAP from the ethereum.org discord :)

https://discord.gg/zCHhRAgQ

**Pull request merged**
