### PR TITLE
Adds new resource: Crunchbase for Web3 Grants

### PR DESCRIPTION
**Pull request by feliche93**
## Description

Finding grants that really match your target blockchain, protocol category and specific use case is not an easy task. That's why I developed together with a friend Crunchbase for web3 grants: https://www.cryptoneur.xyz/web3-grants

We plan to further develop the following features:

- **Filters:** Filter by category, blockchain eco system, funding amount or use cases to find grants that match your idea.
- **Past Applications:** Understand and have interesting statistics on past successful grant applications
- **RFPs:** Give grants an easy way to share a "wish list" of ideas they would like people to build
- **Easy to collaborate:** We currently work on a simple UI to let everyone easily contribute and update info and hopefully reward them also in the future

All the code is [open-source
](https://github.com/feliche93/cryptoneur/tree/master/packages/frontend/src/app/web3-grants).

### CODE REVIEW

**Comment by feliche93** [comment]
@corwintines I saw there was a merge conflict, since I added this last week. Is there anything else you'd need from my side? :) Happy to make further edits if needed or supply additional information.

Thanks 🙏

**Comment by feliche93** [comment]
@minimalsm I remember you also helped me last time with reviewing the changes 🙏 Let me know if I can provide any more info or anything needs to be changed! Big thanks! 😊

**Comment by corwintines** [comment]
@feliche93 just had a couple of questions. 

How are these grants pages updated? Are you guys scraping the internet for this? Are the projects coming and updating these? My main concern right now is there is not a lot of information on this page about the grants.

**Comment by feliche93** [comment]
@corwintines, thanks great feedback! 

We build it in such a way that anyone can easily contribute, and update/add new info through an online form. No technical skills needed. 

As you rightfully pointed out though, we are still in the process of talking to protocols and getting their data on there. Coming up with a unified data format for all different grants, past applications, RFPs was not that easy since we wanted to build something that addressed users and protocols pain points, but we feel good about the schema now and push more data in there manually. 

For past/funded projects as well as RFPs we will set up scrapers that keep everything in synch automatically. We also go through twitter and keep an eye on any new grant announcements. 

Support through a link would definitely help us to hopefully have more ppl contribute and update info or find relevant grants. 

Let me know if you have any more questions or would like some additional info!

**Comment by feliche93** [comment]
@corwintines we just added another 15 grants and are now at 43 grants. We will continue adding until we have at least +100 well researched and documented grants. We are also good with the past applications data schema and will most likely start scraping and synching past applications to grants this weekend.

Let me know if you need any more info! Thanks 🙏 Felix

**Comment by feliche93** [comment]
@corwintines quickly wanted to check in, if you had any additional feedback 🙏

**Review by corwintines — APPROVED** [review]
Thanks, @feliche93. Softened the language a bit.

**Pull request merged**
