### PR TITLE
Add Chinese traditional (zh-tw) translated images for buckets 7 and 11 

### PR DESCRIPTION
**Pull request by nloureiro**
Add the translation images for:

Zh-TW: bucket 7, bucket 11

### CODE REVIEW

**Comment by nloureiro** [comment]
> @nloureiro I'd expected us to have have fixed alignment on a few of these images.
> 
> Screenshot 2023-10-17 at 11 56 54 Screenshot 2023-10-17 at 11 57 34

yes, still testing the flow

will fix this for sure

**Comment by nloureiro** [comment]
> We should remove the web1 image as it's identical to the fallback version

ok

**Comment by minimalsm** [comment]
Ahh I see, if you're just testing out flow be sure to mark as draft until ready for review :)

**Comment by nloureiro** [comment]
ready for review

**Review by corwintines — APPROVED** [review]

**Pull request merged**
