### PR TITLE
Added MetaMask grants and removed Consensys grants

### LINKED ISSUE #8522: Request to add MetaMask Grants DAO to Ethereum grants list
MetaMask has recently opened a grants programme with a yearly $2.4M budget.

On behalf of MetaMask, I'm requesting it to be added to the [Ethereum grants](https://ethereum.org/en/community/grants/) list.

* [Link to the grants programme that we request to add](https://metamaskgrants.org/)
* [Official announcement](https://consensys.net/blog/press-release/consensys-launches-metamask-grants-dao/)

Additionally Consensys Grants is finished and inactive. I also request it to be removed from the website

### PR DESCRIPTION
**Pull request by ritave**
## Description

I went through all the content and replaced all locations with Consensys Grants with MetaMask Grants.

## Related Issue

fixes #8522

### CODE REVIEW

**Review by minimalsm — COMMENTED** [review]
Thanks @ritave 

Has Consensys grants been discontinued?

**Comment by ritave** [comment]
@minimalsm Yes, I confirm that Consensys Grants are inactive. You can verify this yourself by trying to apply through the link in the source

image

**Comment by minimalsm** [comment]
Noting I've confirmed ConsenSys grants have been inactive for a while and have no active plan to return them any time soon. Let's re-add ConsenSys if they spin up new grant submissions.

**Review by minimalsm — APPROVED** [review]
Thanks @ritave 🙏

**Comment by minimalsm** [comment]
@all-contributors please add @ritave for docs

**Pull request merged**
