### PR TITLE
fix: Fixed padding in What is Ethereum section

### LINKED ISSUE #10217: section Ethereum in numbers is broken in mobile
### Describe the bug

https://ethereum.org/en/what-is-ethereum/

this page has a section  Ethereum in numbers that has a inline padding to make room in bigger screens

this padding is breaking the layout in xs screens.

Screen Shot 2023-05-15 02 18 17 PM
Screen Shot 2023-05-15 02 18 01 PM

### To reproduce

1. Go to [https://ethereum.org/en/what-is-ethereum/](https://ethereum.org/en/what-is-ethereum/) on a smaller than 400px screen
2. Scroll down to Ethereum in numbers
4. See error the layout not centred

### Expected behavior

all should be on centered

### Screenshots

Screen Shot 2023-05-15 02 20 59 PM
Screen Shot 2023-05-15 02 20 41 PM

### Desktop (please complete the following information)

Screen Shot 2023-05-15 02 18 17 PM
Screen Shot 2023-05-15 02 18 01 PM

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by HassanTanveer**
## Description
Fixed padding for smaller screens

image

## Related Issue
Fixes #10217

### CODE REVIEW

**Review by corwintines — APPROVED** [review]

**Comment by corwintines** [comment]
@nloureiro looks good to me, but want to get your approval before merging.

**Comment by nloureiro** [comment]
Is there a development preview? can´t find it...

**Comment by corwintines** [comment]
Sorry, just tested this locally. Triggered a rebuild on Gatsby side. Not sure why the timeout didnt make it to GitHub.

**Review by nloureiro — APPROVED** [review]

**Comment by nloureiro** [comment]
> Sorry, just tested this locally. Triggered a rebuild on Gatsby side. Not sure why the timeout didnt make it to GitHub.

looks good to me. This fixes the bug

**Review by nhsz — APPROVED** [review]
LGTM

**Pull request merged**
