### PR TITLE
Close nav dropdown on link select

### PR DESCRIPTION
**Pull request by mul53**
## Description
Navbar closes on link selection 

## Related Issue
Issue #545

### CODE REVIEW

**Comment by samajammin** [comment]
@all-contributors please add @mul53 for code

**Comment by samajammin** [comment]
FYI @mul53 - for next time, please reference the issue number in your commit message. This will automatically close the issue out. See here for more details: https://github.com/ethereum/ethereum-org-website#deployment-lifecycle

**Comment by samajammin** [comment]
@mul53 I'm noticing this console error:
```
app.b3fc325e.js:7 TypeError: t.closeMenu is not a function
    at click (4.f7c6a2a7.js:1)
    at Ne (app.b3fc325e.js:7)
    at HTMLAnchorElement.n (app.b3fc325e.js:7)
    at HTMLAnchorElement.i._wrapper (app.b3fc325e.js:7)
```
It occurs when clicking on a `<NavLink />` that is not a child of `<DropdownLink />`, e.g. the "Enterprise" navbar link. Would you please look into handling this (so the NavLink component doesn't always expect to receive the `closeMenu` prop)? Thanks in advance 😄

**Comment by samajammin** [comment]
Disregard, I added a quick fix for that.

**Comment by mul53** [comment]
Cool, next time i will be more careful.

**Pull request merged**
