### PR TITLE
Release candidate v7.14.2

### PR DESCRIPTION
**Pull request by pettinarip**
***
### :zap: Changes
- migrated: pages/developers/learning-tools.tsx to Chakra UI (#10348) @Seek4samurai
- refactor: template/docs.tsx to chakra (#10375) @amit-ksh
- refactor(theme): implement nested semantic tokens (#10278) @TylerAPfledderer
- Update community-events.json (#10459) @RostyslavBortman
- Update community-meetups.json (#10460) @RostyslavBortman
- Update consensus-bounty-hunters.csv (#10431) @asanso

***
### :unicorn: Contributors
Thank you @RostyslavBortman, @Seek4samurai, @TylerAPfledderer, @amit-ksh, @asanso, @corwintines and @pettinarip for the contributions! :trophy:
***

### CODE REVIEW

**Comment by Sosyetekadir** [comment]
Ben tam sen

**Comment by wackerow** [comment]
@RostyslavBortman Yes! Please feel welcome to [open an issue](https://github.com/ethereum/ethereum-org-website/issues/new/choose) about this

**Comment by RostyslavBortman** [comment]
@wackerow maybe you could just suggest here the correct code?

**Comment by RostyslavBortman** [comment]
@wackerow I updated the flag in the pull request. Please update the stage https://github.com/ethereum/ethereum-org-website/pull/10459

**Pull request merged**
