### PR TITLE
Typo correction

### PR DESCRIPTION
**Pull request by SuperDelphi**
Edit: Typo

Edited a typo in language-resources.md

## Description

Removed accidental repetition in the sentence (see issue).

## Related Issue

https://github.com/ethereum/ethereum-org-website/issues/6363

### CODE REVIEW

**Review by joeurassa — APPROVED** [review]

**Review by wackerow — APPROVED** [review]
Thanks @SuperDelphi! Good catch =)

**Comment by wackerow** [comment]
@all-contributors please add @SuperDelphi for content patch

**Comment by wackerow** [comment]
@SuperDelphi Welcome and thanks =) Don't forget to stop into our Discord to claim your POAP and see what else is going on!

**Comment by SuperDelphi** [comment]
> @SuperDelphi Welcome and thanks =) Don't forget to stop into our Discord to claim your POAP and see what else is going on!

Thanks @wackerow :) I'm already on the server, it's my first PR but I help to translate!

**Comment by SuperDelphi** [comment]
By the way, can I have the "Translation" badge in the all-contributors table, please? (thanks!)
My Crowdin profile (about 20k translated words): https://crowdin.com/profile/superdelphi

**Comment by wanto3** [comment]
.

**Pull request merged**
