### PR TITLE
Fix typo in Spanish dapps developer docs

### PR DESCRIPTION
**Pull request by pabloped**
Changed "le desarrollador" to "el desarrollador" in Centralización.

## Description
Microfix misspelled word: changed "le desarrollador" to "el desarrollador".

## Related Issue

Microfix misspelled word: changed "le desarrollador" to "el desarrollador" in "Centralización" item in "IMPLICACIONES DEL DESARROLLO DE UNA DAPP" section.

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Hey @pabloped, thanks for the PR ❤️

Please note that changes to translated content are usually handled in Crowdin, the localization tool we use since all the content there gets reviewed by our language service provider. Merging this but noting that fixes made in Crowdin will get rolled out more quickly.

If you want to get involved with the Translation Program, you can [join the translation project in Crowdin.](https://crowdin.com/project/ethereum-org/invite/)

You can find more information about the program and using Crowdin on the [Translation Program page on the website](https://ethereum.org/en/contributing/translation-program/).

**Comment by minimalsm** [comment]
@all-contributors please add @pabloped for docs, translations

**Comment by minimalsm** [comment]
Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

**Comment by pabloped** [comment]
That's great! Thanks a lot

**Pull request merged**
