### PR TITLE
Fix table overflow

### LINKED ISSUE #7163: Opcode table horizontal scrolling
**Describe the bug**

The Opcode table on this page https://ethereum.org/en/developers/docs/evm/opcodes is hard to use because of the horizontal scroll functionality. The table has a large number of rows that do not fit into a single page view - to view all the rows vertical scrolling is required. There are also more columns than can fit into a single page view. 

To access out-of-view columns it is necessary to scroll right, which currently requires scrolling to the bottom of the table. However, this puts the row/opcode number out of view, so that with the desired column in view, the row identifier is now obscured. 

This makes it very awkward to access information for specific opcodes using the table.

**To Reproduce**

1.Go to https://ethereum.org/en/developers/docs/evm/opcodes
2. Make an arbitrary choice of row, e.g. 44 - the DIFFICULTY Opcode
3. Try to view content in columns currently out of view - this requires scrolling rightwards at the bottom of the page
4. Try to find the 44 DIFFICULTY Opcode with the desired column still in view.

**Expected behavior**

Either enable arrow-key/click-and-drag horizontal scrolling or put all columns in view by default.

**Screenshots**

Screencast of the problem here: https://discordapp.com/channels/714888181740339261/999252773457633290/999634096839983275

**Desktop (please complete the following information):**

- OS: Linux (Ubunto 20.04)
- Browser: Brave
- Version: 1.40.107

**Additional context**

Issue seems to be desktop specific - on Android the issue is fixed by right-swiping without needing to scroll vertically to the scroll-bar.

### LINKED ISSUE #12119: The table is too large for small screens
### Describe the bug

in this page

https://ethereum.org/en/energy-consumption

The table is overflowing the content and breaks the layout on small screens 

### To reproduce

1. Go to https://ethereum.org/en/energy-consumption
2. on screen smaller than 450px
3. See error

### Expected behavior

It should have horizontal scroll

### Screenshots

Screen Shot 2024-02-06 09 31 01 AM

### Desktop (please complete the following information)

iOs safari and chrome 

### Smartphone (please complete the following information)

Iphone

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

Adds relative position to the table container to avoid overflows.

## Related Issue

- Fixes #12119
- Fixes #7163

### CODE REVIEW

**Comment by TylerAPfledderer** [comment]
@pettinarip it still does not seem to be fixed 🤔

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer thanks for testing. Could you double-check it? using incognito could be better, just to avoid any potential cache.
> 
> I tested this on ios (safari and chrome), linux & win (chrome & brave) and it is working fine. LMK what OS and browser you are testing.

So what I showed above is from Chrome on Android 14. Also breaking similarly in:
- Firefox Android 14 (Incognito)
- Chrome Android 14 (Incognito)
- Brave Windows OS (normal and private window)

**Comment by pettinarip** [comment]
@TylerAPfledderer tested it using BrowserStack and it worked fine in a Samsung Galaxy S24, android 14, Chrome & FF.

image

Its weird. I've also tested it in my personal android phone and worked too. Perhaps it is the browser version? 🤔 Im using Chrome v121.0.6167.164

**Comment by wackerow** [comment]
@pettinarip Yeah, I am seeing the same thing as @TylerAPfledderer... both on iOS (Brave and Safari), and Android (Chrome... technically Vanadium)... and also when mocking mobile sizes using a desktop browser.

The horizontal scroll only goes away if I remove the table entirely, otherwise it's definitely persisting for me.

**Comment by pettinarip** [comment]
@wackerow wow, this is even weirder haha

I've tested it on my personal phone (android), on a physical iphone, on different laptops, and they all work fine for me! what is going on! xD

Are we all using the correct preview deploy? it is https://deploy-preview-12128--ethereumorg.netlify.app/developers/docs/evm/opcodes

**Comment by TylerAPfledderer** [comment]
> @wackerow wow, this is even weirder haha
> 
> I've tested it on my personal phone (android), on a physical iphone, on different laptops, and they all work fine for me! what is going on! xD
> 
> Are we all using the correct preview deploy? it is https://deploy-preview-12128--ethereumorg.netlify.app/developers/docs/evm/opcodes

@pettinarip actually look at this page:
https://deploy-preview-12128--ethereumorg.netlify.app/energy-consumption

**Comment by wackerow** [comment]
Yeah, +1 to @TylerAPfledderer... @pettinarip I am _not_ having issues with the opcodes page, but I _am_ getting horizontal scroll on the energy consumption page (caused by the table)

**Comment by pettinarip** [comment]
Aha! @TylerAPfledderer @wackerow I missed that case! 🙃 for some reason I always thought you were testing the opcodes page haha...my bad.

Ok! I've set a width to one of the containers that were used in the Static layout and that should fix the issue.

**Comment by TylerAPfledderer** [comment]
> Aha! @TylerAPfledderer @wackerow I missed that case! 🙃 for some reason I always thought you were testing the opcodes page haha...my bad.
> 
> Ok! I've set a width to one of the containers that were used in the Static layout and that should fix the issue.

Good with me!

**Review by minimalsm — APPROVED** [review]
Fixed for me now :)

**Review by wackerow — APPROVED** [review]
Working great! Thanks @pettinarip!

**Pull request merged**
