### PR TITLE
update /staking testnet references to Holesky [Fixes #13168]

### LINKED ISSUE #13168: Solo staking page: Goerli has been deprecated; use Holesky
### Describe the bug

The [`/staking/solo`](https://ethereum.org/en/staking/solo/#get-started-on-the-staking-launchpad) page has a widget for users to get started with staking, but it is still pointing to the Goerli Launchpad. This should be updated to use the [Holesky testnet Launchpad](https://holesky.launchpad.ethereum.org/en/) instead.

### To reproduce

1. Go to https://ethereum.org/en/staking/solo/#get-started-on-the-staking-launchpad
2. Click on the dropdown for "Choose a network"
3. See use of Goerli testnet, which has been deprecated.

### Expected behavior

References to Goerli should be removed and replaced with the Holesky testnet where users can practice staking before going to Mainnet.

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by SnehalSrivastava27**
Made all the translation changes required in the src/intl/**/page-staking.json

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
@lukassim Hey, I went through Crowdin and updated `age-staking-launchpad-widget-testnet-label` and `age-staking-launchpad-widget-testnet-start` for all completed langs, but I didn't do these other two:

- `comp-withdrawal-credentials-verify-goerli`
- `page-staking-launchpad-widget-p1`

Any chance you could help get these updated as well? And is it going to cause issues if we change this id here?

@SnehalSrivastava27 If we make a change to the string id's, we should make sure they stay lowercase, ie `-Holesky` should be `-holesky` throughout

**Comment by SnehalSrivastava27** [comment]
@wackerow  got it will make the changes and update in a while.

**Comment by lukassim** [comment]
> @lukassim Hey, I went through Crowdin and updated `age-staking-launchpad-widget-testnet-label` and `age-staking-launchpad-widget-testnet-start` for all completed langs, but I didn't do these other two:
> 
> * `comp-withdrawal-credentials-verify-goerli`
> * `page-staking-launchpad-widget-p1`
> 
> Any chance you could help get these updated as well? And is it going to cause issues if we change this id here?
> 
> @SnehalSrivastava27 If we make a change to the string id's, we should make sure they stay lowercase, ie `-Holesky` should be `-holesky` throughout

Hey,
No, changing the id shouldn't cause any issues
Just let me know when the content is final and we can get any remaining content translated

**Comment by wackerow** [comment]
Great thanks @lukassim... @SnehalSrivastava27 Thanks for the additional changes! I pushed a couple commits to help get this over the line after spotting a few other usages on the `/staking` pages, and some overlap with the `/staking/withdrawals` page.

I think that just about does it for all the `/staking` pages.

**Review by wackerow — APPROVED** [review]

**Comment by wackerow** [comment]
Working well, pulling in. Thanks @SnehalSrivastava27!

**Comment by wackerow** [comment]
@all-contributors please add @SnehalSrivastava27 for maintenance

**Pull request merged**
