### PR TITLE
fix typo in "what is ethereum" section

### PR DESCRIPTION
**Pull request by aleksbrgt**
Added the missing word **first** in the sentence 
> Launched in 2015, Ethereum is the world’s programmable blockchain.

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks, @aleksbrgt! I don't think that's a typo though, I believe that wording is intentional.

@jjmstark please confirm.

**Comment by aleksbrgt** [comment]
Ok, I have compared with other translations before submitting, in french and spanish, they both mention "first" or "leader".

**Comment by samajammin** [comment]
Ah, I appreciate your diligence! 

If translations do differ, that's likely due to the fact that language translations inevitably lag behind the English version. e.g. you can see this English page was edited recently (before we've had the time to update any translations): https://github.com/ethereum/ethereum-org-website/commit/29976933b5a907e0b99edf6e1ded7fa8696858ae#diff-5a51cee2f499492793d4fa62b1ecf407

You can learn more about our content version management here: https://ethereum.org/languages/
We're hoping to cut a new release for our translators to hop on soon!

**Comment by jjmstark** [comment]
hey @aleksbrgt! Good eye, but confirming this is an intentional wording choice. We decided that saying "**first** programmable blockchain" was unnecessary, and actually underplayed Ethereum's position. Simply saying that Ethereum is **the** world's programmable blockchain was both simpler & more true to the confident tone of that page.

**Comment by aleksbrgt** [comment]
Ok, thank you for clarifying the phrasing

**Pull request closed without merging**
