### PR TITLE
Add Rust Developer Docs

### LINKED ISSUE #266: Programming-Language Specific Pages: Rust
### Prize Bounty
0.3 ETH

### Challenge Description
Let's add resource pages that cater to specific user groups to make Ethereum more approachable to a broader range of people.

Build a dedicated page for Rust developers that includes:
- a brief description of Ethereum
- beginner articles
- intermediate articles
- advanced use patterns
- Rust projects and tools
- Rust communities (e.g. project Gitter channels)

The Python page is a great template to work off:
https://ethereum.org/python/

Also, add a link to the page from the [/developers page "Language Specific Resources" section](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/developers/index.md#language-specific-resources).

### Submission Requirements
The PR must include everything outlined in the challenge description above.

### Submission Deadline
The deadline for submissions is November 11, 2019.

### Judging Criteria
The prize will be awarded to the first valid submission.

### Winner Announcement Date
The submission will be reviewed by November 18. Winner announcements and prize payouts will occur before November 31, 2019.

### PR DESCRIPTION
**Pull request by Man-Jain**
# Programming-Language Specific Pages: Rust

## Description
Added language-specific page for Rust following https://ethereum.org/python/ page as a template

## Related Issue
Resolves #266 

## Checklist:

- [X] I have read the contributing guidelines in the project README.
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Man-Jain** [comment]
> Thank you @Man-Jain for your contribution!
> 
> I've already merged #361, which was the first PR to solve this issue. Since your PR has valuable additions on top of #361, we'd still like to incorporate your contributions & reward you for the bounty. Please rebase off the current `dev` branch & incorporate your content into the existing Rust page (docs/rust/index.md). Please be sure to delete any duplicate information / link references.
> 
> Thanks again!

Thanks @samajammin I have done the changes as you requested. Please consider them and give any feedbacks

**Comment by Man-Jain** [comment]
> Thanks for making these updates! I hope you continue to contribute & curate this page

Yes I will definitely.

**Comment by samajammin** [comment]
@all-contributors please add @Man-Jain for content

**Comment by samajammin** [comment]
@all-contributors please add @Man-Jain for content

**Comment by samajammin** [comment]
@all-contributors please add @Man-Jain for content

**Comment by samajammin** [comment]
@all-contributors please add @Man-Jain for content

**Comment by samajammin** [comment]
4th times a charm 😆

**Pull request merged**
