### PR TITLE
professional terms keep english

### PR DESCRIPTION
**Pull request by WiiCoder**
## Description

professional terms keep english

### CODE REVIEW

**Review by Jessie1980758 — APPROVED** [review]

**Comment by Riely007** [comment]
agree! but maybe keep a space between chinese and English?

**Comment by minimalsm** [comment]
Hey @Riely007, curious why this species shouldn't be translated?

See our current stance here: https://ethereum.org/en/contributing/translation-program/translators-guide/#terms-without-established-translations

**Comment by Riely007** [comment]
> Hey @Riely007, curious why this species shouldn't be translated?
> 
> See our current stance here: https://ethereum.org/en/contributing/translation-program/translators-guide/#terms-without-established-translations

Great question! Some rational behind: 

1. Most old CN blogs related to Ethereum keep gas as "gas", rather than "燃气“, or “矿工费", eg, “Master Ethereum" CN version, EthFans Blog, ECN Blog. In order to keep it consistent, it's better to keep it in "gas". 

Some examples: 
- https://www.ethereum.cn/Technology/a_quick_explanation_of_what_the_point_of_the_eip
- https://learnblockchain.cn/search?word=gas
- https://github.com/inoutcode/ethereum_book/blob/master/%E7%AC%AC%E5%8D%81%E4%B8%89%E7%AB%A0.asciidoc

2. Gas is related to "gas limit" and "gas price". By keeping it in "gas", it's easy for devs to understand. Most CN developer doc keep it in gas as well. 

Note: I prefer to explain what is Gas at Glossary, but no need to translate.

**Comment by minimalsm** [comment]
Thanks again for the PR @WiiCoder

**Comment by minimalsm** [comment]
@all-contributors please add @WiiCoder for ideas

**Pull request closed without merging**
