### PR TITLE
Add "Languages" page [Resolves #258]

### LINKED ISSUE #258: Add a "Languages" page
## Expected Behavior

- Create a page that displays available languages on [ethereum.org](http://ethereum.org) as well as progress of every language underway, and show ways for folks to contribute
    - example: [https://reactjs.org/languages](https://reactjs.org/languages)
    - example: [https://isreacttranslatedyet.com](https://isreacttranslatedyet.com/)
- Challenge: when we *change* or *add content* to ethereum.org, but which is not yet translated into language X, this page ought to show that the translation is now incomplete. Is that possible?

## Current Behavior
Page does not exist

## Possible Solution
Build a new page with this functionality. This could be a good model:
https://github.com/reactjs/reactjs.org-translation
Use a similar bot? Or integrate with crowdin API, such that this page reflects the true % complete?

## Context

Provide a dedicated landing page to refer folks to, both for users looking for translations & volunteers looking to help keep translated content up to date.

### PR DESCRIPTION
**Pull request by samajammin**
## Description
Provide a dedicated page (ethereum.org/languages) to refer folks to, both for users looking for translations & volunteers looking to help keep translated content up to date.

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/258

## Screenshots (if appropriate):

Desktop
Image 2019-10-04 at 5 17 36 PM

Mobile
Image 2019-10-04 at 5 17 21 PM

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by samajammin** [comment]
I think this is a reasonable V1 of this page:
- Displays a static list of available languages (in English)
- Displays a static list of languages that exist in CrowdIn as of today but not yet completed (in English)
- Links to CrowdIn projects & volunteer form for folks to get involved

In future iterations, I'd like to have this page:
- Pull real-time data from Crowdin to display a dynamic list of languages
- Display completion percentage for each language
- Translated for each language

**Comment by samajammin** [comment]
Couple comments/thoughts on this version:

**Comment by jjmstark** [comment]
1. In the preview, the "drop down menu" to select a language has been replaced with a link that takes the user to the /languages page. Is that intended functionality? I assume we should preserve some ability to select a new language from the landing page. 

2. 

>The "contribute" link goes to the respective Crowdin page for that language. Should this link to the Github issue instead? Or the volunteer form? The Crowdin page doesn't give any clear direction on how to get involved.

The "contribute" link should take the user to the volunteer application form.

3. 

>The volunteer form we link to is a bit outdated. We should remove the "Closing date: August 25th" copy. Should we also remove the "* participated in a translation project related to Blockchain at least once"? IMO blockchain translation experience feels like an unnecessarily restrictive filter.

Agree with those changes - can you ask Taeyeon to change the form or give you permission? She currently has control over it. 

Otherwise, this looks good to go as a v1.

**Comment by samajammin** [comment]
Thanks for the review. I've updated those links to the volunteer form.

> In the preview, the "drop down menu" to select a language has been replaced with a link that takes the user to the /languages page. Is that intended functionality? I assume we should preserve some ability to select a new language from the landing page.

Yes, that was intentional. I just figured the extra click might be worth drawing awareness to the translation program. I'm also fine with keeping the "Languages" header link as a dropdown but then where do you think we should link to this page? We could add a "Languages" link to the footer?

**Comment by jjmstark** [comment]
Got it - I think preserving the drop-down functionality should be our default for now. Maybe the link to the /langauges page can go both in the footer, and in the language-drop down menu itself?

Open to removing the drop down function later, just think its worth a separate discussion and more input.

**Comment by samajammin** [comment]
@jjmstark cool, done.

Let me know if you think the "view all" link in the dropdown looks awkward. We can easily scrap it.

**Pull request merged**
