### PR TITLE
Enables above XL width for docs content [Fixes #1780]

### LINKED ISSUE #1780: XL screen layout for docs.js
**Is your feature request related to a problem? Please describe.**

Our docs.js template doesn't render well on XL screens. 

**Describe the solution you'd like**

Ideally the content should remain central but background color and borders should respond to the size of the screen.

image

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- If path includes `/docs/` the _content_ view will allow full width beyond 1504px (`theme.variables.maxPageWidth`)

@ryancreatescopy Took another look at this. A little different than the screenshot I posted in the issue, but while testing I kinda liked how the documents content could be expanded using this setup, instead of remaining with fixed max-width. Viewing this on my iMac certainly helps make the docs feel less crammed and utilizes more of the screen real estate, but curious what you think.

## Related Issue
#1780

### CODE REVIEW

**Review by samajammin — APPROVED** [review]
Nice @wackerow! This makes the site nav look a _bit_ weird on XL screens:

Image 2021-03-18 at 2 28 37 PM

But I can't think of a better solution. I think this change is a significant improvement vs. current layout:
Image 2021-03-18 at 2 31 41 PM

Ultimately I'll defer to @ryancreatescopy's take.

**Comment by ryancreatescopy** [comment]
This causes a few other issues with our "needs help" pages (see screenshots).

image
image

I think it's fine to push this change once the above are fixed. As Sam says, it's an improvement. 

We may want to think about a more wholesale change moving forward around whether we want to scale up the content width for the larger screens site-wide...

**Review by ryancreatescopy — CHANGES_REQUESTED** [review]
see comment

**Comment by samajammin** [comment]
This is also an issue: https://deploy-preview-2671--ethereumorg.netlify.app/en/developers/docs/transactions/

The width is overflowing due to a code block.

**Review by samajammin — CHANGES_REQUESTED** [review]
See comment above - let's address that before merging.

**Comment by wackerow** [comment]
The above should take care of the CallToContribute width, and the unlimited width when encountering very long non-breaking strings (like a tx hash). 

I also noticed the top banner on incomplete pages does not yet extend full width and looks off. 
image

**Comment by wackerow** [comment]
ping @ryancreatescopy @samajammin... let me know your thoughts on this after the last changes

**Review by jley81 — APPROVED** [review]

**Comment by wackerow** [comment]
@minimalsm Yeah, I'm having a hard time disagreeing... after coming back to this, the extra wide lines of text feel a little more difficult in terms of readability. Perhaps there is a better way we can take advantage of the extra space. @samajammin Any thoughts here?  Wouldn't be against closing this until we have a cleaner plan.

**Comment by minimalsm** [comment]
Hey @samajammin, thoughts on closing this out for now based on the readability concerns I listed above?

**Comment by wackerow** [comment]
Let's clear up design goals on this first, closing for now

**Comment by Scott1UP** [comment]
Hey 👋  

This has been closed for a bit, however, I thought it might be useful to dig into this a little further from a design perspective.

Having looked at this more closely, I'd recommend a few tweaks to solve the XL-width issue–whilst keeping a good reading (and aesthetic) experience for the user.

First screen: 1920x1080
1920x1080

After 1504px, I recommend moving away from the main content being slightly left-aligned. This allows for a more conventional 'reading focused mode' to begin–whereby the content will have an equal margin on either side of it. 

From my experiments in Figma, the width of the Contents should remain at 640px until it hits 1920 width. At this point, I'd suggest increasing the width of the content to 700px to make the content look more appropriate for larger screen sizes–without damaging the reading experience.

Second screen: 2560x1440
2560x1440

Expanding the entire view to fit XL screens is difficult to get right; the navigation often ends up too far away from the main content and ultimately, one thing will always suffer.

Hope this is of some use. Let me know your thoughts/comments ✌️

**Comment by minimalsm** [comment]
cc: @wackerow

**Pull request closed without merging**
