### PR TITLE
remove bloxstaking card fixes issue #13116

### LINKED ISSUE #13116: Remove BloxStaking card from Staking as a Service provider page
### Describe the bug

As per their own website: 
> BloxStaking has sunset.
> Blox has shut down. Node Operations are now ceased.

Blogpost: https://www.bloxstaking.com/blog/product-updates/bloxstaking-moving-to-new-horizons/

### To reproduce

1. Go to https://ethereum.org/en/staking/saas/#saas-providers
2. Scroll down to BloxStaking Card
3. Click "Get started"

### Expected behavior

Only list SaaS providers that are providing this service

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by Khemmie-Ray**
## Description

Remove the BloxStaking card from staking as a service

## Related Issue

- Fixes #13116

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
Looks good @Khemmie-Ray! We just also want to remove the `BloxstakingGlyphIcon.tsx` component (and it's references) which isn't being used anymore. See `src/components/icons/Icons.stories.tsx` and `src/components/icons/staking/index.ts` and remove the lines with `BloxstakingGlyphIcon`.

**Comment by Khemmie-Ray** [comment]
Alright, I will work on that too

**Review by wackerow — APPROVED** [review]
Looks great! Thanks @Khemmie-Ray!

**Comment by wackerow** [comment]
@all-contributors please add @Khemmie-Ray for maintenance

**Pull request merged**
