### PR TITLE
Add Kchannels to list of state channel projects

### PR DESCRIPTION
**Pull request by maurycyp**
## Description

 Add [Kchannels](https://www.kchannels.io/) to list of state channel projects

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
@maurycyp LGTM! Thanks for adding this 👍

**Comment by ryancreatescopy** [comment]
@tasdienes mind reviewing this addition to state channels on enterprise page?

**Comment by tasdienes** [comment]
@maurycyp I could not find a github link or anything else pointing to code on your web site. How can people use it?
Also, just fyi, http://kchannels.io does not work.  Only www.kchannels.io works.

**Comment by maurycyp** [comment]
@tasdienes Here's a link to a description of Kchannels on GitHub:   https://github.com/kchannelz/kchannels

However, we don't publish source atm.  This is a centralized service with a different approach to L2.

Here's a link to a simple UI (for dev testing), though it may be a bit tricky to navigate: https://rinkeby.kchannels.io/

Also, there's lots of info on https://docs.kchannels.io/ .

**Comment by maurycyp** [comment]
Also, thank for flagging the naked domain issue, we'll address it shortly.  But the links in the diff don't are tested and work well.

**Review by tasdienes — APPROVED** [review]

**Review by ryancreatescopy — APPROVED** [review]

**Comment by ryancreatescopy** [comment]
@all-contributors please add @maurycyp for content.

**Pull request merged**
