### PR TITLE
Whitepaper

### PR DESCRIPTION
**Pull request by samajammin**
## Description
Migrate Whitepaper to ethereum.org/whitepaper

## TODOs
- [x] Migrate markdown file from the [old wiki](https://github.com/ethereum/wiki/wiki/White-Paper) to ethereum.org/whitepaper
- [x] Add additional context at the top of the page, e.g. some pretext that explains this is a historical paper, Ethereum has evolved since, where to learn more or see latest status / updates
- [x] Add link to the footer (under developers section)
- [x] Add internal link to the whitepaper (e.g. from /learn)
- [x] Fix links & formatting
- [x] Migrate images
- [ ] Update the wiki Whitepaper to link to ethereum.org/whitepaper (GH 301 redirects are not possible)

## Related Issue
#1011

## Screenshots (if appropriate):
Image 2020-05-13 at 2 32 02 PM

### CODE REVIEW

**Comment by kavana321123** [comment]
What do you think about DRK Draken Coin of Draken Group? It seem they now own a technology that Ethereum aim to have on Ethereum 2.0 in 2022.

**Comment by samajammin** [comment]
@jjmstark @ChrisChinchilla - would appreciate reviews from both of you on this, particularly regarding the pretext blurb I added at the top of the page:

> _This introductory paper was originally published in 2013 by Vitalik Buterin, the founder of [Ethereum](/what-is-ethereum/), before the project's launch in 2015. It's worth noting that Ethereum, like many community-driven, open-source software projects, has evolved since it's initial inception._

> _While several years old, we maintain this paper because it continues to serve as a useful reference and an accurate representation of Ethereum and it's vision. To learn about the latest developments of Ethereum, and how changes to the protocol are made, we recommend [this guide](/learn/)._

**Comment by ChrisChinchilla** [comment]
@samajammin First up, do we all agree that the website should be the new home of the whitepaper? I think it should, but wanted to check. Second, so people created issues with the whitepaper (mostly images) on the wiki repository, so I should migrate those to here.

Next, some feedback on text…

**Comment by ChrisChinchilla** [comment]
And the text looks good!

**Comment by samajammin** [comment]
>  Second, so people created issues with the whitepaper (mostly images) on the wiki repository, so I should migrate those to here.
Sounds good! Thanks for thinking of that @ChrisChinchilla

**Comment by jjmstark** [comment]
Looks good to me!

**Comment by jpitts** [comment]
Is the idea here that you want to put the WP "front and center" amid the introductory and resource-linking parts of the website, rather than have it in a wiki or historical archive? 

Thinking about what the website is doing, the long WP would be an unusual addition. Many sections of the WP are much more detailed than any other content on ethereum.org, and there is not much linking to relevant resources.

Still, the structure of the WP, the topics covered, and the expansive nature of the paper could be really helpful to people learning about Ethereum on the website! 

IMO, there needs to be something like a foyer to the WP, a "whitepaper-introduction". This can be a distilled-down version that introduces its structure, quotes the important points, links to the full sections.

**Comment by samajammin** [comment]
> Is the idea here that you want to put the WP "front and center" amid the introductory and resource-linking parts of the website, rather than have it in a wiki or historical archive?

@jpitts I wouldn't necessarily say the goal is to make it "front and center" but definitely to make it easier to find for the folks who are looking for it (or broadly looking to learn more about Ethereum in detail). As mentioned in the issue (#1011), since we've added Algolia search to the website back in April, site search stats show that **"white paper"/"whitepaper" together are the 2nd most searched query on ethereum.org** (behind only "wallet"). We believe adding this directly to the website (& therefore directly linkable from site search) will greatly improve UX.

Also the WP (although quite detailed as you mentioned) is still a common early entry point into Ethereum for many users. I feel strongly that etherum.org has the potential to create a much better onboarding UX in terms of "where to go next" vs. the GH wiki.

> IMO, there needs to be something like a foyer to the WP, a "whitepaper-introduction". This can be a distilled-down version that introduces its structure, quotes the important points, links to the full sections.

I think that's a great idea! Perhaps something similar to [Bitcoin.com's Beginner's Guide to the Bitcoin Whitepaper](https://www.bitcoin.com/get-started/bitcoin-white-paper-beginner-guide/)? Another source of inspiration could be [Libra's White Paper](https://libra.org/en-US/white-paper/) - I think their "Cover letter" does a great job of accomplishing this high-level summary. 

I'm all for this idea - I'll add it to the backlog & welcome any contributions on it but I don't think it needs to be included in this first iteration. Please let us know if you have any specific thoughts on it.

**Comment by jpitts** [comment]
> As mentioned in the issue (#1011), since we've added Algolia search to the website back in April, site search stats show that **"white paper"/"whitepaper" together are the 2nd most searched query on ethereum.org** (behind only "wallet"). We believe adding this directly to the website (& therefore directly linkable from site search) will greatly improve UX.

This definitely shows how important this document is to people.

> Also the WP (although quite detailed as you mentioned) is still a common early entry point into Ethereum for many users. I feel strongly that etherum.org has the potential to create a much better onboarding UX in terms of "where to go next" vs. the GH wiki.

Definitely agree. The WP is this epic tour of everything that became "Ethereum", and w/ the website nearby this means people can then start to move toward those aspects of the platform that they are most interested in.

> Perhaps something similar to [Bitcoin.com's Beginner's Guide to the Bitcoin Whitepaper](https://www.bitcoin.com/get-started/bitcoin-white-paper-beginner-guide/)? Another source of inspiration could be [Libra's White Paper](https://libra.org/en-US/white-paper/) - I think their "Cover letter" does a great job of accomplishing this high-level summary.
> 

These are good suggestions, I'll have to look around to find good examples for the Ethereum WP (perhaps a lot of the needed content is already written). 

> I'm all for this idea - I'll add it to the backlog & welcome any contributions on it but I don't think it needs to be included in this first iteration. Please let us know if you have any specific thoughts on it.

👍

I was thinking that it should be very easy for the user to flip between the sections of the guide and the corresponding section within the WP itself (perhaps w/ a tab). Or the guide could even be a sort of navigation panel for the WP, w/ section titles and summaries and there would be a parallax scrolling effect.

I'd be interested in helping out with the writing if you need it.

**Comment by samajammin** [comment]
@jpitts FYI here's the issue: #1026 - please feel free to weigh in there with ideas or drop a comment with a link when you have a draft ready! Thanks.

**Pull request merged**
