### PR TITLE
Add Zmok

### PR DESCRIPTION
**Pull request by tomasbanik**
Adding Zmok's general links to the Backend API libraries list.

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @tomasbanik, thanks for the PR 💪

Can I check when Zmok when live to users? As part of our [product listing criteria](https://ethereum.org/en/contributing/adding-products/) we ask that a product that has been "live" (in production) for over 6 months.

**Comment by tomasbanik** [comment]
Hey @minimalsm 
sure, we launched in April 2021, so now it's 10 months. Currently having thousands of active users. You can check the RPC using a free profile too.
Thanks, Tomas

**Comment by minimalsm** [comment]
Awesome, thanks @tomasbanik

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
@all-contributors please add @tomasbanik for docs

**Pull request merged**
