### PR TITLE
Refactor/next mdx remote to v4

### LINKED ISSUE #6718: Mdx components mixing parsing/styling of children elements
**Describe the bug**
Markdown files that use imported components are parsing children to the component using a mixture of html and markdown

Seems that markdown parsing doesn't start until after an empty line has been used. "Patching" this by adding an empty line can add undesired space when rendered.

**Expected behavior**
Children of markdown components should ideally be all parsed similarly, without mixing styling

**Screenshots**

Without extra empty line:
image
After adding the empty line
image

**Additional context**

You can see the effect in the syntax highlighting, where initial lines ignore MD syntax until an empty line is added. 
image

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### LINKED ISSUE #9160: Upgrade mdx to v2
### Is your feature request related to a problem? Please describe.

Upgrade the mdx version to v2.

### Describe the solution you'd like

Upgrade `next-mdx-remote` to v4 #11938. This upgrade will force us to move to [the v2 of mdx](https://mdxjs.com/blog/v2/).

Resources:
- https://mdxjs.com/migrating/v2/

### Describe alternatives you've considered

None.

### Additional context

_No response_

### LINKED ISSUE #11938: Investigate & upgrade `next-mdx-remote` to v4
**Important:** we can't upgrade to v4 with the current code as it is. See ethereum/ethereum-org-fork#18 for more details about why we downgraded to v3.

Investigate how to fix the issues we have with `next-mdx-remote` v4 and upgrade it https://github.com/hashicorp/next-mdx-remote

We could potentially replace `gray-matter` since the new version can parse frontmatter as well and simplify a bit the code.

```ts
const mdxSource = await serialize(source, { parseFrontmatter: true })
```

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Description

This PR bumps `next-mdx-remote` to v4 and does the following modifications to `*.md` files for compatibility:

- Adds the `remark-custom-heading-ids` plugin to generate the ids without worry of syntax errors
  - Hard-coded ids are kept in the markdown files for now.
- For custom components with internal content in a block format, wrap in JSX expression to prevent extra injection of html tags
```md
Below will render a `p` tag that wraps around the content
<CustomComponent>
  Child content goes here
</CustomComponent>

Wrap in a JSX expression so that the `p` tag does not render. 
A tag used in the child content will render as normal.

{
  <CustomComponent>
    Child content goes here. <a href="#">This will render correctly</a>
  </CustomComponent>
}
```

### TODO
- [ ] Escape opening brackets or wrap in template literals in plain text content where unexpected character errors occur against JSX expressions
- [ ] Update docs to reflect new symtax conventions introduced in MDXv2

## Additional Info

Having the `public/content` folder exposed to Prettier allows the tool to do any automated formatting changes to the markdown files.

For future updates, consider converting `.md` files to `.mdx` files to allow for TypeScript and ESLint support.

## Related Issue

Closes #9160 
Closes #11938 
Closes #6718

### CODE REVIEW

**Comment by TylerAPfledderer** [comment]
@pettinarip Noting here Regarding this error:
`Unexpected character '0' (U+0030) before name, expected a character that can start a name, such as a letter, '$', or '_'`

This one is tricky, because it's based on how the compiler interprets JSX. This error instance above refers to the string `<0>` where it is not expecting the `0` but something else.

See the [MDX troubleshooting on this error type](https://mdxjs.com/docs/troubleshooting-mdx/#unexpected-character-at-expected-expect)

Doing some digging, I was led to [this Issue from a Kent Dodds repo](https://github.com/kentcdodds/mdx-bundler/issues/122).

This might take some testing to figure out the solution, but it could vary depending on the given string. No problem by me though to figure it out!

Side note: is there a reason why the content files are using the `.md` extension and not `.mdx`?

**Review by wackerow — COMMENTED** [review]
Hey @lukassim, could you do us a favor and test uploading one of these new markdown files to Crowdin? If so, please do me a favor and upload this as a `.mdx` file (change the extension before uploading)... we'd like to see if there is a difference in how Crowdin treats mdx files compared to .md... Thanks!

**Comment by lukassim** [comment]
> Hey @lukassim, could you do us a favor and test uploading one of these new markdown files to Crowdin? If so, please do me a favor and upload this as a `.mdx` file (change the extension before uploading)... we'd like to see if there is a difference in how Crowdin treats mdx files compared to .md... Thanks!

Sure, it worked fine and got uploaded like it should, I also checked and Crowdin does natively support MDX files
One thing I've noticed though is that it doesn't parse the file as well as with md files, here's a screenshot of the headings (the #about-ethereumorg and #a-note-on-names are hidden from translators with md files)

Screenshot 2024-04-23 at 19 00 55

**Comment by lukassim** [comment]
@wackerow Same with links, here's how they look in an md file vs. an mdx file

Screenshot 2024-04-23 at 19 08 14
Screenshot 2024-04-23 at 19 08 08

**Comment by TylerAPfledderer** [comment]
@pettinarip hmm what should be done here at this point?

**Comment by pettinarip** [comment]
> @pettinarip hmm what should be done here at this point?

I will close the PR for now.

Given the small benefits this upgrade will give us, the work we need to do to fix all the files, and the potential issues with crowdin, I do not think it is worth continuing to work on this effort.

Thanks for the work done though, I think we can reopen or take up the work done here when we see a more clear benefit from it.

**Pull request closed without merging**
