### PR TITLE
add NOWNodes in provider list

### PR DESCRIPTION
**Pull request by PolinaShanti**
Hi Ethereum Team!
Please, add NOWNodes in providers list. Thank you!

NOWNodes is a blockchain-as-a-service solution that lets users get access to full Nodes and blockbook Explorers via API. Instant access to 56 blockchain networks, including BTC, ETH, and BSC, which amount has over 1000 coins and tokens.

### CODE REVIEW

**Comment by PolinaShanti** [comment]
Hello Team!
@samajammin @wackerow @corwintines @pettinarip @minimalsm @jmcook1186 
Please, let me know if you have any questions

**Comment by PolinaShanti** [comment]
Hello everyone!
Are any updates on my request?
Thank you!!

**Review by minimalsm — APPROVED** [review]
Hey @PolinaShanti :-) I've moved NOWNodes to the correct position in the list. It's in alphabetical order, incase you hadn't noticed 😀

Thanks for the PR!

**Comment by minimalsm** [comment]
@all-contributors please add @PolinaShanti for docs

**Comment by PolinaShanti** [comment]
> Hey @PolinaShanti :-) I've moved NOWNodes to the correct position in the list. It's in alphabetical order, incase you hadn't noticed 😀

Oh, Sorry, I didn't notice, my bad 😓
Thank you!

I'm still in the process of exploring GitHub
Can you please tell me when the document will be updated?

**Pull request merged**
