### PR TITLE
added Ethereum in Tamil (தமிழ் மொழி) எதீரியம்

### PR DESCRIPTION
**Pull request by pontiyaraja**
## Description

Added ethereum in Tamil language(தமிழ் மொழி) எதீரியம்
ethereum = எதீரியம்

### CODE REVIEW

**Comment by sorumfactory** [comment]
@pontiyaraja Hello, Pontiyaraja
Thank you for your suggestions. We just added 3 new languages(Telugu, Tamil, Bengali) that are now available in CrowdIn! If you have any further questions or requests, please join our Slack Workspace and collaborate with other contributors by joining language groups :)

**Comment by samajammin** [comment]
Thanks for the addition! Hope you keep looking for way to contribute 😄

**Comment by samajammin** [comment]
@all-contributors please add @pontiyaraja for content & translation

**Comment by sorumfactory** [comment]
@pontiyaraja 
+) Below is the link to join the Tamil translation in Crowdin :)
https://crowdin.com/project/ethereumfoundation/ta#

**Pull request merged**
