### PR TITLE
♻️ Add further Sepolia links

### PR DESCRIPTION
**Pull request by pcaversaccio**
## Description

Adding the links to the new Sepolia Etherscan explorer as well as to an additional Sepolia faucet provider.

### CODE REVIEW

**Review by PatrickAlphaC — APPROVED** [review]

**Comment by PatrickAlphaC** [comment]
Ooops. Sorry! Accidental review.

**Review by corwintines — APPROVED** [review]
Thanks @pcaversaccio!

**Comment by corwintines** [comment]
@all-contributors can you add @pcaversaccio for content

**Comment by corwintines** [comment]
@pcaversaccio make sure to claim your POAP in the Discord if you haven't already :)

https://discord.gg/DYM2jSkb

**Pull request merged**
