### PR TITLE
Add Akula to execution client list

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
I would add Akula to `Client diversity` page with a note that it is experimental or in development. But I would avoid adding to `Nodes and clients` because this page is being significantly reworked for The Merge #7133 and aims to list only clients ready for it. 
This list should only include battle tested, production ready clients usable for an average user, as it states above it "All of them are actively maintained to stay updated with network upgrades, follow current specifications and pass [client tests](https://github.com/ethereum/tests)".

**Comment by vorot93** [comment]
"Battle-tested, production-ready" is a very vague criteria. On the other hand, Akula syncs on mainnet and all EF-endorsed testnets, including post-merge ones, and passes the consensus test suite.

**Comment by wilsoncusack** [comment]
Agree would be great to get more specific about how a client can be added to the nodes and clients page!

**Comment by taxmeifyoucan** [comment]
Thanks for clarifying @vorot93! I am running Akula and I can confirm it syncs mainnet and works smoothly, however I wasn't aware Akula is tested, ready for The Merge and considered production ready. With this in mind, I would merge the PR.

**Review by jmcook1186 — APPROVED** [review]
thanks for the PR!

**Review by wackerow — APPROVED** [review]

**Comment by wackerow** [comment]
@all-contributors please add @vorot93 for content

Thanks for raising this! Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. You can collect a second POAP (aside from the GitPOAP above) as well =)

**Pull request merged**
