### PR TITLE
Ethereum DeFi Ecosystem

### PR DESCRIPTION
**Pull request by sneg55**
as @jjmstark  suggested now it's a stand-alone page for [Ethereum products only](https://defiprime.com/ethereum)

### CODE REVIEW

**Comment by sneg55** [comment]
@jjmstark What do you think?

**Comment by sneg55** [comment]
@alancwoo  Do you mind to take a look at this PR?

**Comment by jjmstark** [comment]
thanks for adding this feature and re-submitting! 

I'm in favour of merging. This list includes many applications built on ethereum that aren't already included in the other lists already present. 

What do others think? @EvanVanNessEth, @Souptacular?

**Comment by EvanVanNessEth** [comment]
i'd be more likely to link to defipulse.

**Comment by sneg55** [comment]
> i'd be more likely to link to defipulse.

why not both? It's kinda different projects with a different approach.  Defipulse - tracking value locked in DeFi(for major apps/protocols), think coinmarketcap for decentralized finance apps on Ethereum.  Defiprime - curating a list of working Defi products on Ethereum, think producthunt for Defi.

**Comment by sneg55** [comment]
Any feedback? @jjmstark  @maurelian @CPSTL

**Comment by jjmstark** [comment]
> Why not both? It's somewhat different projects with a different approach. Defipulse - tracking value locked in DeFi(for major apps/protocols), think coinmarketcap for decentralized finance apps on Ethereum. Defiprime - curating a list of working Defi products on Ethereum, think producthunt for Defi

This makes sense to me - they are serving different needs. Defipulse gives the reader information about the most used (by one metric) defi projects, and defiprime is a longer and broader list of applications that fit into that category. 

@EvanVanNessEth unless you're still opposed, I'd suggest we create a new PR which adds both defiprime and defipulse.

**Comment by sneg55** [comment]
> I'd suggest we create a new PR which adds both defiprime and defipulse.

already updated this PR.

**Comment by sneg55** [comment]
@jjmstark care to take a look at updated PR?

**Pull request merged**
