### PR TITLE
Adds Spanish v2.1 and Malayalam v2.0 language versions

### LINKED ISSUE #3584: Site Translation: Update Malayalam to v2.0
**Is your feature request related to a problem? Please describe.**

Malayalam v2.0 has been translated!
https://crowdin.com/project/ethereum-org/ml-IN

**Describe the solution you'd like**

Download the files from Crowdin for v2.0 and add them to the site.

### LINKED ISSUE #3585: Site Translation: Update Spanish (Modern) to v2.1
**Is your feature request related to a problem? Please describe.**

Spanish (Modern) v2.1 has been translated!
https://crowdin.com/project/ethereum-org/es-EM

**Describe the solution you'd like**

Download the files from Crowdin for v2.1 and add them to the site.

### PR DESCRIPTION
**Pull request by wackerow**
## Description
Adds Spanish v2.1 and Malayalam v2.0 language versions

🎉 🎊 Again, a special **thank you** to the ethereum.org Crowdin community for making this possible!

For those interested in contributing, [learn more about our Translation Program](https://ethereum.org/en/contributing/translation-program/)

## Related Issue
[Closes #3584, Closes #3585]

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]

**Comment by samajammin** [comment]
@wackerow @minimalsm did you folks test out any of the translated pages here?

Not sure why yet but looks like some pages are still displaying the English version, e.g. https://deploy-preview-3592--ethereumorg.netlify.app/es/developers/docs/evm/

**Comment by samajammin** [comment]
Meanwhile some display as expected, e.g. https://deploy-preview-3592--ethereumorg.netlify.app/es/developers/docs/gas/

**Comment by wackerow** [comment]
I could rerun the Netlify deploy with cleared cache... not the first time this has happened, typically clears after a build without cache.

**Comment by minimalsm** [comment]
Just had a look at this in the local env I had and all the files are as expected. Not really sure what happened here. At first glance looks like the build is as expected also.

**Comment by wackerow** [comment]
Same... the `master <- dev` merge preview also showing it correctly:
image
Think we're good here

**Pull request merged**
