### PR TITLE
Update zero-knowledge-proofs with new resource

### LINKED ISSUE #11744: New Resource: Zero Knowledge Proof section
## Community Hub Resources

Futher Reading for https://ethereum.org/en/zero-knowledge-proofs/

Resource - [Why Zero Knowledge Proofs (ZKPs) is a Game Changer for Self-Sovereign Identity](https://frankiefab.hashnode.dev/why-zero-knowledge-proofs-zkps-is-a-game-changer-for-self-sovereign-identity)

### PR DESCRIPTION
**Pull request by frankiefab100**
Resolves #11744

- Added new resource under Further reading

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
LGTM, thanks @frankiefab100

**Comment by minimalsm** [comment]
@frankiefab100 I'm unable to merge this because we changed the file structure here. Could you open a new PR to the latest dev branch and i'll get this merged? Cheers!

**Comment by frankiefab100** [comment]
Alright, I'll do that

**Comment by frankiefab100** [comment]
@minimalsm sorry i haven’t been available. I just opened a new PR

**Pull request closed without merging**
