### PR TITLE
feat: Add Portuguese (v1.0) 

### LINKED ISSUE #1182: Site Translation: Add Portuguese (v1.0)
**Is your feature request related to a problem? Please describe.**
Portuguese translations have completed review & are ready to be added to the website!

**Describe the solution you'd like**

Portuguese translations have completed review & are ready to be added to the website!

1. Download the [files from CrowdIn](https://crowdin.com/project/ethereumfoundation/pt-PT#) for this version of the content (`Contents v.1.0`) - here's a [screenshot showing how](https://share.getcloudapp.com/ApujZjyn). You may need to sign up for Crowdin & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).
2. Create new directory: /src/content/translations/pt/
3. Copy in the v1.0 Crowdin files
- Copy the markdown files into the new /src/content/translations/pt/ directory, keeping the same directory structure as in Crowdin (i.e. the subdirectories & index.md filenames)
- Rename the /beginners/ directory to /what-is-ethereum/ (i.e. /src/content/translations/pt/what-is-ethereum/)
- Delete the root index.md file (i.e. /src/content/translations/pt/index.md)
- Copy the strings.json file (from Crowdin Contents v1.1) into the /src/intl/ directory & rename as pt.json (i.e. /src/intl/pt.json)
4. Within the frontmatter of each newly added markdown file...
  - Update the `lang` property (it should be `pt`)
	- Remove any `og:title` or `og:description` properties - replace with just `title` & `description`
  - Set all `sidebar` fields to `true` (vs. `auto`)
	- Increase all `sidebarDepth` fields by 1 (e.g. 0 --> 1, 1 --> 2)
5. Update all relative links of the new markdown files to include the language path by running our [script](https://github.com/ethereum/ethereum-org-website/blob/dev/scripts/updateInternalLinks.js), i.e. run `yarn update-internal-links ml` from the root of the project 
6. Add an object to the languageMetadata object within /src/translations/utils/:
```
pt: {
    version: 1.0,
    language: "Português",
    "language-english": "Portuguese",
  },
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by developerfred**
## Description
add Portuguese translation version 1.0.0

## Related Issue
close #1182

### CODE REVIEW

**Comment by samajammin** [comment]
Hey @developerfred - we appreciate you taking the time to open this PR!

Unfortunately, there's a couple issues with it:
- This issue was created to add [the European Portuguese](https://crowdin.com/project/ethereumfoundation/pt-PT#) translations, not to replace the exiting Brazilian Portuguese translations
- It's missing some configuration, which is why [the site build is broken](https://app.netlify.com/sites/ethereumorg/deploys/5f0f10dcf675b50008b37319)

I'm sorry for the lack of clarity with the issue (#1182) - I assigned it to myself so didn't put much effort into explaining what was needed in detail. In general, I advise against working on PRs that are already assigned to someone. To save time, comment on the PR to ask to be assigned before actually doing the work on it.

I've already started work on this issue & should have it finished today. I will tag you on that PR so you can see the steps needed to fix the site build.

I hope this doesn't discourage you from future contributions! We have a few additional language translations needed that we would love to have your help on 😄  - I'll tag you once I create those issues.

**Comment by developerfred** [comment]
@samajammin Let nothing be quiet, mark me yes! Thanks for the feedback.

**Comment by samajammin** [comment]
@developerfred thanks for understanding :)

Closing this out in favor of #1214

**Comment by samajammin** [comment]
FYI @developerfred this PR is probably a good reference for adding a v1.0 translation: https://github.com/ethereum/ethereum-org-website/pull/1219

**Pull request closed without merging**
