### PR TITLE
Prevent external link arrow from being wrapped around

### LINKED ISSUE #980: External link arrow icon wraps
### Prize Bounty
20 DAI

### Challenge Description
Fix the bug described below. 

### Submission Requirements
Update styles for all external links so that the arrow never wraps alone (should always wrap with the last word of the link).

### Judging Criteria
The prize will be awarded to the first valid submission.

***

**Describe the bug**

The arrow icon indicating external links sometimes wraps by itself, which may create confusion.

**To Reproduce**
See screenshot below
1. Go to any page (e.g. https://ethereum.org/developers/#getting-started)
2. Reduce width of browser until one of the external links wraps

**Expected behavior**

The arrow icon should not wrap by itself. It should wrap with the last word of the link

**Screenshots**
/about page desktop:
Image 2020-05-12 at 7 13 16 AM

/what-is-ethereum mobile:

Image 2020-04-22 at 10 45 02 AM

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

### PR DESCRIPTION
**Pull request by KiChjang**
Prevent external link arrow from being wrapped around.

## Related Issue
Fixes #980.

### CODE REVIEW

**Comment by KiChjang** [comment]
I ended up realizing that `white-space: nowrap` wasn't the answer because it'll just put the entire link to the next line. Instead, the arrow didn't need to have its own inline-block formatting context, so I gave it an inline display.

**Comment by KiChjang** [comment]
@samajammin That is strange, I checked the CSS on that page, and it looks like it didn't pick up the `display: inline` change that this PR modifies. Could it be because I force-pushed?

**Comment by KiChjang** [comment]
@samajammin Ok, I found out the reason why -- it's because there are multiple places where we style links, and I put it on the one that doesn't actually style the one on the page that you were looking at. I've pushed 2 new commits that properly styles ALL kinds of link arrows so now they should all wrap with their previous word.

**Comment by samajammin** [comment]
@all-contributors please add @KiChjang for code

**Pull request merged**
