### PR TITLE
fix: french typos

### PR DESCRIPTION
**Pull request by omahs**
fix: french typos

### CODE REVIEW

**Comment by nhsz** [comment]
maybe @isabelladebrito can help here

**Comment by wackerow** [comment]
Hey @omahs! Appreciate you posting these suggestions. Our challenge with updates such as these is we are limited in our ability to properly review these from GitHub.

We handle all of our translations through [our Crowdin project](https://crowdin.com/project/ethereum-org); Have you been over there by chance? (Here is [more information on our Translation Program](https://ethereum.org/en/contributing/translation-program/))

cc: @lukassim Is there anyone who could review these changes here? Or should we move these over to Crowdin first?

**Comment by omahs** [comment]
Hi @wackerow, yup I'm already on Crowdin and participated in the last Translatathon. I even received a Community Champion badge :)
I prefer Github for edits, with Crowdin I feel like this wouldn't be seen. I've seen some questions take months to get answers there.

**Comment by wackerow** [comment]
Oh that's awesome! Thank you for all your help so far and continued support...

> I prefer Github for edits, with Crowdin I feel like this wouldn't be seen. I've seen some questions take months to get answers there.

Appreciate the feedback about the process here. @lukassim How would you recommend going forward here?

@omahs Have you made these changes in Crowdin by chance? Would you be willing to if not?

@lukassim If we're comfortable with it we can pull these in on GitHub. In either case, we should also make sure Crowdin is updated to get these strings formally approved, so they won't get overwritten when the next round of imports occurs.

**Comment by omahs** [comment]
> Have you made these changes in Crowdin by chance? Would you be willing to if not?

Just tried to, but I can't always find the right file

**Review by wackerow — APPROVED** [review]
Okay great, thanks @omahs! I tried to update any that remained in Crowdin so we should be good here.

FWIW, to find these I've been using https://crowdin.com/editor/ethereum-org > French > Open file and search for the last directory of the index.md file, so `public/content/translations/fr/refi/index.md` => Search `refi` and it should revel the folder with the needed file inside > Double click > Search in file > Paste string snippet to find it.

You likely know this though, so if you're hitting other issues feel free to let @lukassim or I know and we can try to help resolve.

**Comment by wackerow** [comment]
@all-contributors please add @omahs for translation

**Pull request merged**
