### PR TITLE
Add WORLD3 Ethereum Social Room in Chat rooms

### LINKED ISSUE #13039: Suggest a tutorial (WORLD3)
### Tutorial title

WORLD3 Ethereum Social Room

### Tutorial description

Explore the Ethereum Exhibition Hall in WORLD3, an autonomous world offering browser-based, immersive 3D multiplayer experiences.

### Tutorial tags

NFT, METAVERSE

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted on ethereum.org

### For tutorials to be hosted on Ethereum.org: Tutorial Content

Instance Spaces
Instance Spaces are domains in our 3D interactive social hub where WORLD3 users and partners can create curated experiences for all to enjoy! While you can access these Instance Spaces through the elevator, you can also do so directly by entering the permalinks into your browser.

Ethereum Exhibition Hall

This was developed during our previous collaboration with Ethereum.

The Ethereum 3D Social Exhibition Hall was Matrix World’s first multi-chain pavilion project and located in an Instance Room in the Matrix Universe Building, and users will use an elevator to enter. It aims to provide users with an immersive virtual space to learn about the ETH ecosystem and culture. This space allows users to learn what ETH is, how to create an ETH wallet, how to stake and buy ETH, the history of ETH, the ETH community, ongoing events, and more! Our AI ETH guides will guide users through the entire exhibition hall and answer their questions.

How to get there? Press the interactive key ‘F’ in front of the elevator in WORLD3 Headquarters lobby and select 2F to enter the square of ETH Social Pavilion. The interior of the pavilion can be reached by the beam elevator in the central area.

How to Interact? Users can approach the smart screen in the venue and press the interaction key ‘F’ to interact, including using the ETH wallet to sign in, jump to the specified URL, chat with the AI robot, etc.

How to Leave? Take the beam elevator back to the Pavilion square, then press the interactive key ‘F’ near the portal to select another floor and leave.

### For tutorials hosted elsewhere: URL to tutorial

https://medium.com/@WORLD3_AI/an-instructional-guide-to-world3-and-matrix-world-7d522953c678

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by zrnju**
WORLD3 is an AI-powered Autonomous World that connects Bitcoin with all other Turing-complete blockchains. Play games and create immersive experiences with 2D and 3D dApps. Forge unforgettable memories, and begin your adventure in the next-generation Autonomous Intelligent World. This world is yours and ours for the making. ([https://world3.ai](https://world3.ai))

## Description

We added a link to the community page of Chat-rooms: a [WORLD3 Ethereum Social Room](https://world3.ai/spaces/ethroom) - Explore the Ethereum Exhibition Hall in WORLD3, an autonomous world offering browser-based, immersive 3D multiplayer experiences.

## Related Issue
- Closes #13039

### CODE REVIEW

**Comment by minimalsm** [comment]
hey @zrnju, thanks for the PR.

WORLD3 lists "Ethereum" and the Ethereum Foundation as collaborators on their website. 

Screenshot 2024-05-28 at 10 26 13

Could you elaborate on the nature of this collaboration?

**Comment by zrnju** [comment]
> hey @zrnju, thanks for the PR.
> 
> WORLD3 lists "Ethereum" and the Ethereum Foundation as collaborators on their website.
> 
> Screenshot 2024-05-28 at 10 26 13
> Could you elaborate on the nature of this collaboration?

Dear @minimalsm,
      We really appreciate your quick attention.
      WORLD3 is our recent rebranding from our MATRIX Brand. We served as a sponsor and partner to host ETHDubai ([https://www.ethdubaiconf.org/#sprs](https://www.ethdubaiconf.org/#sprs)) and ETHRiyadh (https://ethriyadh.com/#partnerships), and we are the co-host and actively preparing ETHRiyadh 2024 as well.
      We continue to promote and update the current Ethereum Social Room as the online social space for all Ethereum communities and activities, just as we did with information about ETHDubai.
      Here are some screenshots and videos to let you learn more about our project.
      Video: https://x.com/WORLD3_AI/status/1791303459456663932
      Screenshots:
image
image
image
image
image
image
image

**Comment by wackerow** [comment]
@zrnju Would it be fair to say that [ETH Global](https://ethglobal.com) is a collaborator then? To my knowledge ETH Global handles those events, not the Ethereum Foundation or "Ethereum" as a decentralized entity.

**Comment by zrnju** [comment]
> @zrnju Would it be fair to say that [ETH Global](https://ethglobal.com) is a collaborator then? To my knowledge ETH Global handles those events, not the Ethereum Foundation or "Ethereum" as a decentralized entity.

Dear @wackerow,
  Thank you for your quick attention.
  We've updated our WORLD3 homepage collaborators list with the ETH Global logo. (https://world3.ai/)
image
  We will continue to maintain a good collaboration with the ETH Global ecosystem.
  Hope to receive your response. Thank you.

**Comment by wackerow** [comment]
Hey @zrnju, not sure this is a fit for this page honestly, but more importantly I just spent quite some time trying to just log in to try it out without any luck. Tried multiple browsers, but the verification code was very buggy and was unable to even log in. Tried logging in with wallet, but still needed an email. I'm not sure listing this right now is likely to lead to a good experience for users so respectfully going to close this out. Best of luck with the project and please feel free to revisit in the future.

**Comment by wufengtao1** [comment]
Hi @wackerow , can I tell you what email suffix we use? In order to prevent Sybil Attack, we have disabled registration with many temporary email providers. Regarding the second question, email is a preferred method of communication for web2 users, and we use it as the root account for our users. Additionally, users can switch wallets on their root account, which is also a common practice in many web3 games. And I just registered a new Hotmail email account, and it can receive verification codes and log in successfully. Can you provide me with more information about this issue?

**Pull request closed without merging**
