### PR TITLE
Whitepaper Page: Removed dead link [Fixes #9083]

### LINKED ISSUE #9083: Bug report: Linked YouTube video removed
### Describe the bug

The Whitepaper page contains a link to a "Mike Hearn on Smart Property at Turing Festival" YouTube video which has since been removed.

image

### To reproduce

1. Go to https://ethereum.org/en/whitepaper/ and navigate to "Further Reading"
2. Click on "Mike Hearn on Smart Property at Turing Festival"
3. YouTube will open in a new tab
4. See error message

image

### Expected behavior

Able to view video

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xKai27**
## Description

The Whitepaper page contains a link to a "Mike Hearn on Smart Property at Turing Festival" YouTube video which has since been removed. PR to remove this dead link

## Related Issue

Fixes #9083

### CODE REVIEW

**Review by minimalsm — CHANGES_REQUESTED** [review]
Would prefer not to remove things from the whitepaper if we can avoid it. Tried searching but every instance of this seems to point to the removed YT video... 

Ideally, we could upload this video to a decentralized storage option. I'll ping Mike Hearn and see if he knows where we could find a copy of it.

**Comment by corwintines** [comment]
@minimalsm any update on the video?

**Comment by corwintines** [comment]
Adding this to grooming

**Comment by corwintines** [comment]
Great! Thanks @mikehearn for the updated link! Ill update and merge :)

**Review by corwintines — APPROVED** [review]

**Pull request merged**
