### PR TITLE
refactor(FeedbackWidget): Improve structure with Chakra UI

### LINKED ISSUE #12184: Feedback widget overflowing on Mobile
### Describe the bug

When using the FeedbackWidget on mobile, the thank you screen overflows off the screen on the left

### To reproduce

1. Go to https://deploy-preview-12182--ethereumorg.netlify.app/developers/docs on mobile
2. Go through feedback widget
3. 
Screenshot 2024-02-14 at 11 04 02 AM

### Expected behavior

Should be centered instead of overflowing over

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
## Description
This PR updates the `FeedbackWidget` to improve its usage with Chakra UI.
- Codesplits the "Dot" button into a separate component file.
- Abstracts away the logic to a useHook.
- Uses Chakra's `Modal` component for the structure
- Create a story for visual testing

## Related Issue
- Fixes #12184

## Summary by CodeRabbit

- **New Features**
	- Introduced a `FeedbackWidget` for collecting user feedback directly within the app.
	- Added a `FixedDot` component for easy access to the feedback widget, with dynamic styling and hover effects.
	- Implemented a custom hook `useFeedbackWidget` to manage the feedback widget's state and interactions.
	- Set up a Storybook story for the `FeedbackWidget`, showcasing its features and styling.

### CODE REVIEW

**Comment by F3n4nd0gm** [comment]
Robaron mis cuentas de github y cabiaron las contraseñas para borrar permanente a internet-star.net

**Comment by F3n4nd0gm** [comment]
Me mandaron esta foto y después borraron todos los archivos de internet-star.net

**Review by wackerow — APPROVED** [review]
Hey @TylerAPfledderer, I went ahead and updated this branch with `dev`, merging the changes each of us have brought to this component. I kept the AlertDialog approach used in a previous PR, and was able to utilize the useFeedbackWidget, FixedDot and story you have in this PR. The story may need to be updated though if you happen to have a moment to peak at that.

cc: @pettinarip I think this is good to go, but another set of eyes on this wouldn't hurt.

**Comment by TylerAPfledderer** [comment]
> Hey @TylerAPfledderer, I went ahead and updated this branch with `dev`, merging the changes each of us have brought to this component. I kept the AlertDialog approach used in a previous PR, and was able to utilize the useFeedbackWidget, FixedDot and story you have in this PR. The story may need to be updated though if you happen to have a moment to peak at that.
> 
> cc: @pettinarip I think this is good to go, but another set of eyes on this wouldn't hurt.

The story file for this is pretty simple, so no updating necessary. Though that timeout to show the text on the button seems pretty long! 😅

**Review by pettinarip — APPROVED** [review]
@TylerAPfledderer this looks great on the preview deploy. GJ!

Two minor things I see in SB:
1. The popover is not aligned with the button
image

2. Would be nice for snapshot testing, if we could add a story with the popover open. Right now, we are only taking the snapshot of the FixedDot
image

**Comment by TylerAPfledderer** [comment]
@pettinarip 
1. Weird, I'm not seeing that on my end.
From the SB preview (Brave browser)
image

> 2. Would be nice for snapshot testing, if we could add a story with the popover open. Right now, we are only taking the snapshot of the FixedDot

This could be done with an interaction test by [using a test assertion to delay snapshot capture](https://www.chromatic.com/docs/delay/#use-an-assertion-to-delay-snapshot-capture). However, I would recommend doing this in a separate PR that would include a global update to get interaction testing online proper. (There is currently a package missing to do this, and I would think it would be better suited to getting online in another PR that would include the Simulator component I showed in Discord)

Doing a successful interaction test to create the snapshot would avoid the need to do possibly add any unnecessary props or logic directly into the component.

So you can then view the snapshot as intended like so. Though obviously with a passing test so the `UI Tests` check doesn't fail! 😅 
image

> This also sounds like a project in itself in getting interaction testing active along with what I commented in the Chart text GH issue about [Chromatic modes](https://github.com/ethereum/ethereum-org-website/issues/12099#issuecomment-1933054201).

**Pull request merged**
