### PR TITLE
Fix discord links

### PR DESCRIPTION
**Pull request by omahs**
Fix discord links

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks @omahs!

**Comment by isabelladebrito** [comment]
Hi @omahs, thanks again for contributing to ethereum.org!

Besides GitPOAP, you're also eligible to claim an "onchain achievement token" (also known as "OAT") on Galxe 🏅

Here's how you can claim:

1. Head over to https://galxe.com/ethereumorg/campaign/GCDGSt4bSn
2. We have already assigned you a role on ethereum.org's Discord server, from where you should be able to claim your OAT on Galxe
3. Connect your wallet and Discord user
4. Check the OAT(s) you're eligible to claim et voilà! 

If you have any questions, don't hesitate to reply to this comment or reach out to me via ethereum.org's Discord server. Cheers!

**Comment by omahs** [comment]
Hi @isabelladebrito, thanks for this OAT!
I'm not sure if it's active yet, I had a look on Galxe and it says "Tasks Incomplete".
I couldn't find a channel on Discord to connect Galxe.

**Comment by isabelladebrito** [comment]
gm @omahs! These are the OATs you should be eligible to claim - let me know if it works:

https://galxe.com/ethereumorg/campaign/GCEWcttdx4
https://galxe.com/ethereumorg/campaign/GCprCttS2z

**Comment by omahs** [comment]
Awesome, yup it's working! Thanks again 🙌

**Pull request merged**
