### PR TITLE
Broken link fix

### PR DESCRIPTION
**Pull request by wackerow**
## Description
NFT page: `/staking/` fixed to `/eth2/staking/`
@ryancreatescopy

### CODE REVIEW

**Review by ryancreatescopy — APPROVED** [review]

**Review by ramsemune — APPROVED** [review]

**Comment by ramsemune** [comment]
{"result": "accepted"}

    2021 m. kovo 15 d., pirmadienis 20:08:02 GMT+2, ryancreatescopy ***@***.***> rašė:  
 
 


@ryancreatescopy approved this pull request.

**Comment by ramsemune** [comment]
.....................................

ramunas would like to stay in touch on LinkedIn.

ramunas radzisauskas
statybos 
Lithuania

View profile https://www.linkedin.com/comm/in/ramunas-radzisauskas-24b922201?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E6mljb3%7El0fpxmbi%7E8l-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BgDoRgZI6RGafWDgMhFtSFg%3D%3D

Confirm that you know ramunas https://www.linkedin.com/e/v2?e=-6mljb3-l0fpxmbi-8l&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BgDoRgZI6RGafWDgMhFtSFg%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=z6o6kBTh&invitationId=6906332490525749248


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-6mljb3-l0fpxmbi-8l&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQHNijpez0jXFAAAAX9g44cC7okCkbYrung-FyHCT1fWSXpO5-mSRGGvSR9I36gLNEc2ojr5f1SCcDqsIe5sE38Rz_Ssv7Vu7k53wwOLf8tIqN53nmXw5mtx5gstherxA9OxBZMq-4jjlw_UC5Gm3qaGwFincHpDEg&eid=-6mljb3-l0fpxmbi-8l

Help: https://www.linkedin.com/e/v2?e=-6mljb3-l0fpxmbi-8l&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BgDoRgZI6RGafWDgMhFtSFg%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ramsemune** [comment]
Hi ,

ramunas would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-6mljb3-l0lik462-qu&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BO9lrJip9Rt2DIx5T%2F5hLGA%3D%3D&t=suwj&ek=email_first_guest_reminder_03&li=20&m=hero&ts=accept_text

View ramunas’s profile: https://www.linkedin.com/comm/in/ramunas-radzisauskas-24b922201?trk=eml-email_first_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_first_guest_reminder_03-hero-2-prof%7Ename-null-%7E6mljb3%7El0lik462%7Equ-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BO9lrJip9Rt2DIx5T%2F5hLGA%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-6mljb3-l0lik462-qu&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_first_guest_reminder_03&li=17&m=unsub&ts=unsub&loid=AQEJzXdgUQmIiAAAAX91xl_1WePy5m8X8OxIVdkW-Z5Yeod6TKOT5LpphRjsgf0I-2C-sv1b8g7n2k_MlvsksiyBADuMhYt-JkRYIpSADkIrshv_vY7dUQLG87xyDOeHMVeuFI8NIY_g-ZzWd5Iw9Z0crE18lkfa0Lz94w&eid=-6mljb3-l0lik462-qu

Help: https://www.linkedin.com/e/v2?e=-6mljb3-l0lik462-qu&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BO9lrJip9Rt2DIx5T%2F5hLGA%3D%3D&a=customerServiceUrl&ek=email_first_guest_reminder_03&li=16&m=footer&ts=help&articleId=67


 LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ramsemune** [comment]
https://www.linkedin.com/e/v2?e=-6mljb3-l0vjjx7h-pf&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BKXGTQGF0T%2F6IN7XXMg4B2g%3D%3D&t=suwj&ek=email_second_guest_reminder_03&li=11&m=hero&ts=accept_text

 https://www.linkedin.com/comm/in/ramunas-radzisauskas-24b922201?trk=eml-email_second_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_second_guest_reminder_03-hero-2-prof%7Ename-null-%7E6mljb3%7El0vjjx7h%7Epf-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BKXGTQGF0T%2F6IN7XXMg4B2g%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-6mljb3-l0vjjx7h-pf&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_second_guest_reminder_03&li=8&m=unsub&ts=unsub&loid=AQE-nmNoSG7QhAAAAX-Z6j6mNOF4ld94L8ksrzezzm6SCH5YRy-wxzXwzSIQoaXRzCFtX9LZ2OZU07x85YhFWrwlNpe0wVPr3UAzzyA7Jcb6aONgH5Jn_4C9U4sLccsqD98tpIbuoZymx_o2TIbZL4dw5JHJNTLb2wR8FQ&eid=-6mljb3-l0vjjx7h-pf

Help: https://www.linkedin.com/e/v2?e=-6mljb3-l0vjjx7h-pf&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BKXGTQGF0T%2F6IN7XXMg4B2g%3D%3D&a=customerServiceUrl&ek=email_second_guest_reminder_03&li=7&m=footer&ts=help&articleId=67


You are receiving Invitation reminder email emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
