### PR TITLE
Addition to IDE list

### PR DESCRIPTION
**Pull request by amuck-gorilla**
Updated index.md to include the Truffle Development Suite.

## Description

I added the Truffle Development Suite to the list of Ethereum IDEs. The section contains links to their website homepage, their pages on their different tools, (Truffle, Ganache, and Drizzle), and their Github page.

### CODE REVIEW

**Comment by Remyelder99** [comment]
Review needed release entherium

**Review by Avijeetshah — APPROVED** [review]

**Review by corwintines — APPROVED** [review]
LGTM, thanks @amuck-gorilla! I think this is good to add @minimalsm but let me know what you think.

**Comment by samajammin** [comment]
Perhaps this is a matter of definitions but I don't view Truffle as an IDE. I view it as a suite of software packages that help developers build dapps - it's essentially a development framework, similar to Hardhat, which is why we list it on that page:
https://ethereum.org/en/developers/docs/frameworks/

I suppose "IDE" is a fairly vague term overall but I view it as a software _application_ (as opposed to packages/libraries) that developers use to write code, such as JetBrains or VSCode. The [Wikipedia page we link to](https://wikipedia.org/wiki/Integrated_development_environment) mentions features such as syntax highlighting, code completion, code search, visual programming... all aspects of essentially a code editor, which Truffle doesn't provide. I think the distinction between an IDE & code editor is debatable but I think it's fair to say Truffle is neither.

Maybe one action item is to make it clear the type of resources we aim to provide on the IDE pages is code editor plugins related to Ethereum development (e.g. like the Remix VSCode plugin).

Feel free to re-open if you feel strongly about this but I think including Truffle on the development frameworks page is adequate.

**Comment by corwintines** [comment]
After talking with the core team today, I agree wtih @samajammin on this decision.

**Pull request closed without merging**
