### PR TITLE
update withdraws -> withdrawals

### PR DESCRIPTION
**Pull request by MiConnell**
this pr updates the spelling of withdraws to withdrawals in the description of the eth2 staking withdrawals page

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
👍🏻 Thanks @MiConnell!

**Review by wackerow — CHANGES_REQUESTED** [review]
@MiConnell sorry, approved too soon... noticed this PR is targeting the `master` branch... mind changing this to `dev`? Everything has to go through `dev` branch first before getting pulled into `master` 🙏🏻 Please and thanks =)

**Comment by MiConnell** [comment]
oops, sorry don't know how I missed that @wackerow . updated!

**Review by wackerow — APPROVED** [review]

**Comment by wackerow** [comment]
@all-contributors please add @MiConnell for content patch

**Pull request merged**
