### PR TITLE
Add zkTube to layer 2 solutions

### PR DESCRIPTION
**Pull request by Dave2022**

### CODE REVIEW

**Comment by wackerow** [comment]
(copy/pasted below comment from #2986... @Dave2022 lets try to keep this to one PR and one conversation 🙏🏻 )

---
@Dave2022 Hey! Thanks for suggesting this... Mind providing a little more information on zkTube? The info asked for is below, thanks!

---
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

_Name of the product_

**Product description:**

_What does it do?_

**How long has it been around?**

_We prioritise products that are battle-tested._

**Where do you think it should go?**

_List the pages where you think this tool is most relevant on ethereum.org_

**GitHub URL**

_Please provide a link to the product's repo._

**Docs URL**

_Please provide a link to the product's docs._

**Is the product open source?**

_We prioritise open source projects when possible._

**Additional context**

_Add any other context or screenshots about the feature request here._

**Comment by Dave2022** [comment]
Before submitting this suggestion, be sure to read our listing policy for dev tools

Product name:

zktube

Product description:

ZKTube is a project built and developed on Layer2 using PLONK protocol based on ZK rollup technology. It can improve scalability by converting batch transfers into a single transaction. Its essence is to compress the user state on the chain and store it in a Merkle tree and transfer the user state change to the chain, while ensuring the correctness of the user state change process under the chain through a zero-knowledge proof mechanism. The cost of directly processing user state changes on the chain is relatively high, but only using the smart contract on the chain to verify the correctness of a zero-knowledge proof PROOF is relatively low. In addition, the required remittance information is transmitted to the contract along with the certificate, which is convenient for users to verify accounts.

How long has it been around?
4 months

Where do you think it should go?
Use ZK-rollups
Multiple implementations of ZK-rollups exist that you can integrate into your dapps:
zktube：https://zktube.io/

GitHub URL
https://github.com/zktube/zktube-in
Note: Since the mainnet has not yet been launched, we can only open source the front-end. After the back-end and the mainnet are online, we will open source immediately

Docs URL
https://zktube.medium.com/zktube1-0-whitepaper-8d942cbd30a3

Is the product open source?
We are an open source project. For security reasons, we will open source the front-end code first, and open source the back-end code after the mainnet is online.

Additional context

image

**Comment by wackerow** [comment]
@Dave2022 Just had to move this to the new rollups URL location as the scaling section has been revamped a bit recently... thanks for the suggestion!

**Comment by wackerow** [comment]
@all-contributors please add @Dave2022 for ideas

**Pull request merged**
