### PR TITLE
add css rule to Aside component to address vertical height bug #2583…

### PR DESCRIPTION
**Pull request by mic0des**
Added 'overflow-y: auto' CSS rule to the Styled Aside component in Eth2TableOfContents.js to attempt to address the vertical height bug flagged in #2583 

## Description

Unsure if this is what you guys had in mind. Saw this open issue a few days ago and decided to give it a go. Rather simple fix, but on sufficiently short screens, a scrollbar is now visible on the left-hand Aside component, and disappears on taller viewports. I only saw today prior to this PR that it had been assigned to @NilsKaden ... apologies if we doubled work, or if someone else had a different/better fix.

https://user-images.githubusercontent.com/4992682/111256600-d01a6200-85ef-11eb-9d40-fb1e9df25de0.mp4

## Related Issue

#2583

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
@mic0des Hey, thanks for helping out with this =) as you alluded to, just try to comment on an issue if you'd like to be assigned to it, just to try and limit stepping on each others toes. 

I think this is a good start, but wondering if we may want to instead apply this styling property to the `InfoColumn` component in the `use-cases.js` template, which would cause the whole panel to slide instead of just the links.
Additionally, personally feel we should remove the scrollbar for this scrollable region, ie
```
  overflow-y: auto;
  scrollbar-width: none;
  ::-webkit-scrollbar {
    display: none;
  }
```
@ryancreatescopy thoughts on this?

(@NilsKaden ok if @mic0des takes this one? we'll try to get you involved on another issue if you're still down.. feel free to take a look and comment 👍)

**Review by samajammin — APPROVED** [review]

**Comment by samajammin** [comment]
Thanks for the input @wackerow - as discussed, let's just merge this as-is.

Thanks for this @mic0des!

**Comment by samajammin** [comment]
@all-contributors please add @mic0des for code.

**Comment by mic0des** [comment]
Noted @wackerow - will comment on an issue before jumping in next time now that I know! Thanks guys.

**Pull request merged**
