### PR TITLE
Update oracle title to spanish

### PR DESCRIPTION
**Pull request by frxncismor**
## Description

Updated the "Oracles" title to "Oráculos" which is a better Spanish title

### CODE REVIEW

**Review by pettinarip — APPROVED** [review]
Nice! thanks @frxncismor

**Comment by samajammin** [comment]
Thanks for the PR!

@lukassim @minimalsm we should update these strings in Crowdin as well so this doesn't get overwritten in the future 😄

**Comment by minimalsm** [comment]
Thanks for spotting and fixing this @frxncismor✌️.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @frxncismor for translations, docs

**Pull request merged**
