### PR TITLE
Rearrange order of gas page links

### PR DESCRIPTION
**Pull request by audieleon**
Since it said many different tools, I put the gas trackers right next to Etherscan and added GasNow. Pulled ETH Gas Station up to that list as well. Kept the related tools for analytics and apis.

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey! Thanks for the PR @audieleon 😄 

I agree the re-ordering is better UX (keeps closely related topics together).

On adding GasNow - we actually recently removed GasNow over unresolved security concerns. [See this review](https://chrome.google.com/webstore/detail/gasnow-eth-gasprice-forec/ccnipbjnnkophfgnkmhdongajmkhijbl?hl=en) on the chrome web store:

> This was a 5 star extension until the recent update that disabled the GasPrice forecast unless you grant the app permissions to modify data in your clipboard (and also read & change all data on websites that you visit). 
> This is egregious for a crypto related extension. A common attack vector is malware that replaces data in your buffer during copy and paste - swapping your intended receipt address with a new address. 
> The fact that you're asking for similar permissions through this extension is unbelievable.

Happy to remove GasNow from the list and merge this if you're good with that @audieleon?

**Comment by audieleon** [comment]
> Happy to remove GasNow from the list and merge this if you're good with that @audieleon?

I didn't see that, and must have installed before that comment. I've removed it from my browser, and will remove it from the list. Thanks for the heads up.

**Comment by minimalsm** [comment]
Great, merging now! Thanks again ✌️! 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
Hey @audieleon I've just [opened a PR](https://github.com/ethereum/ethereum-org-website/pull/3828) to add [BlockNative's new gas estimation chrome extension](https://chrome.google.com/webstore/detail/blocknative-eth-gas-estim/ablbagjepecncofimgjmdpnhnfjiecfm). Similar to GasNow but it supports both Type 0 legacy transactions and Type 2 EIP-1559 transactions, in case you wanted a replacement.

**Comment by audieleon** [comment]
Thanks @minimalsm, you read my mind. I've moved to BlockNative as well.

**Pull request merged**
