### PR TITLE
Add dapptools to list of frameworks

### PR DESCRIPTION
**Pull request by mds1**
Adds [Dapptools](https://dapp.tools/) to the frameworks and local environment pages

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @mds1, if you or someone else could do us a favor and fill out an issue with the new product request below so we can take a closer look and we can get back to you 👍🏻 Thanks 😀

```
Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

**Product name:**

<!-- Name of the product -->

**Product description:**

<!-- What does it do? -->

**How long has it been around?**

<!-- We prioritise products that are battle-tested. -->

**Where do you think it should go?**

<!-- List the pages where you think this tool is most relevant on ethereum.org -->

**GitHub URL**

<!-- Please provide a link to the product's repo. -->

**Docs URL**

<!-- Please provide a link to the product's docs. -->

**Is the product open source?**

<!-- We prioritise open source projects when possible. -->

**Additional context**

<!-- Add any other context or screenshots about the feature request here. -->
```

**Comment by mds1** [comment]
@minimalsm Done in https://github.com/ethereum/ethereum-org-website/issues/3613!

**Review by wackerow — APPROVED** [review]
@mds1 Looks good! Thanks for putting the PR together 👍🏻  

(Made one small adjustment to get our GitHub link parser to work properly)

**Comment by wackerow** [comment]
Sorry, reordered this as well on the `frameworks/index.md` page (ref: #3594)

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
Thanks for the PR @mds1 ✌️.

And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @mds1 for content

**Review by jley81 — APPROVED** [review]

**Review by jley81 — APPROVED** [review]

**Pull request merged**
