### PR TITLE
Update to the new DAppNode brand [Fixes #9255]

### LINKED ISSUE #9255: Update to the new DAppNode brand
### Describe the bug

DAppNode change its brand last year. This website still show its previous brand

### To reproduce

>  1. Go to https://ethereum.org/en/run-a-node/#getting-started
>  2. See old DAppNode branding

>  1. Go to https://ethereum.org/en/staking/solo/#node-and-client-tools
>  2. See old DAppNode branding

### Expected behavior

New brand can be found at [https://dappnode.com](https://dappnode.com)

### Screenshots

image

image

### PR DESCRIPTION
**Pull request by mgarciate**
## Description

This PR changes 2 logos and a background color here:
https://ethereum.org/en/run-a-node/#build-your-own
https://ethereum.org/en/staking/solo/#node-and-client-tools

## Related Issue

Fixes #9255

### CODE REVIEW

**Comment by wackerow** [comment]
Thanks @mgarciate! I know this is overdue... Couple initial thoughts
- I think we should trim out "dappnode" from the logo image on the `run-a-node` page, similar to how the old one just had the glyph. It's been mentioned that this page is already quite DAppNode heavy, and I'd rather not push this more than it already is until we get to revisit this section of the site in more detail.
- The button colors were actually branded to DAppNode too (the "Shop DAppNode" and "DAppNode Setup" buttons). We may want to update these as well, although they're likely to change eventually as the design system continues to get rolled out.

**Comment by mgarciate** [comment]
> Thanks @mgarciate! I know this is overdue... Couple initial thoughts
> 
> * I think we should trim out "dappnode" from the logo image on the `run-a-node` page, similar to how the old one just had the glyph. It's been mentioned that this page is already quite DAppNode heavy, and I'd rather not push this more than it already is until we get to revisit this section of the site in more detail.
> * The button colors were actually branded to DAppNode too (the "Shop DAppNode" and "DAppNode Setup" buttons). We may want to update these as well, although they're likely to change eventually as the design system continues to get rolled out.

Hey @wackerow thanks for your fast review. I just changed what you pointed out. Screenshots below:

image
image

**Review by wackerow — APPROVED** [review]
Awesome, thanks @mgarciate! LGTM!

**Comment by Pol-Lanski** [comment]
Great stuff! Thanks @mgarciate and @wackerow 🙏 . Needed refresh :)

**Review by corwintines — APPROVED** [review]

**Pull request merged**
