### PR TITLE
Adds Italian v2.1 and Polish v2.0 language versions [Closes #3651, Closes #3652]

### LINKED ISSUE #3651: Site Translation: Update Polish to v2.0
**Is your feature request related to a problem? Please describe.**

Polish v2.0 has been translated!
https://crowdin.com/project/ethereum-org/pl

**Describe the solution you'd like**

Download the files from Crowdin for v2.0 and add them to the site.

### LINKED ISSUE #3652: Site Translation: Update Italian to v2.1
**Is your feature request related to a problem? Please describe.**

Italian v2.1 has been translated!
https://crowdin.com/project/ethereum-org/it#/v2.1

**Describe the solution you'd like**

Download the files from Crowdin for v2.1 and add them to the site.

### PR DESCRIPTION
**Pull request by wackerow**
## Description
Adds Italian v2.1 and Polish v2.0 language versions

🎉 🎊 **Special thanks** to the ethereum.org Crowdin community for all their hard work to make this possible!

For those interested in contributing, [learn more about our Translation Program](https://ethereum.org/en/contributing/translation-program/)

## Related Issue
[Closes #3651, Closes #3652]

Also adds a patch to the translated `shard-chains` pages fixing the links to the `beacon-chain` page (were previously all linking to English version)

### CODE REVIEW

**Comment by minimalsm** [comment]
In the developer docs, for translated Italian pages, none of last edit information is showing for me.

Screenshot 2021-08-19 at 10 02 07

**Comment by minimalsm** [comment]
Not directly related (but noticed through Italian V2.1) that CrowdIn has a blank md file uploaded for data-and-analytics page. (so showing as translated when it isn't)

Screenshot 2021-08-19 at 10 17 20

**Review by minimalsm — CHANGES_REQUESTED** [review]
Left a comment below but the last edit info doesn't show for me in the Italian developer docs. Looks good other than that 😀

**Comment by wackerow** [comment]
@minimalsm Yeah, the contributor component pulls info on commits from the `master` branch. These files are brand new and not yet committed to `master` so this component won't work yet... shouldn't be an issue once merged. 

And yes, noticed that on the `data-and-analytics` page. Pulled the broken page from all intl docs for now, working to get this fixed over on Crowdin. 👍🏻

**Comment by minimalsm** [comment]
Ahhh okay, good to know thanks @wackerow!

**Pull request merged**
