### PR TITLE
Simple correction: has -> have

### PR DESCRIPTION
**Pull request by mcmoodoo**
Just spotted a wrong verb used and decided to correct. Much love for Ethereum!

## Summary by CodeRabbit

- **Documentation**
	- Updated the explanation of the block finalization process in the roadmap documentation, highlighting the role of validators and the trade-offs between decentralization, time to finality, and computational overhead.

### CODE REVIEW

**Comment by mcmoodoo** [comment]
@coderabbitai review

**Comment by mcmoodoo** [comment]
@minimalsm please merge. Just a simple change involving two letter changes. Thanks

**Review by minimalsm — APPROVED** [review]
Thanks for the PR @mcmoodoo <3

**Comment by minimalsm** [comment]
@all-contributors please add @mcmoodoo for docs

**Pull request merged**
