### PR TITLE
A Different Take

### PR DESCRIPTION
**Pull request by mirshko**
### The Different Take: [ethereum.org.deepwork.studio](https://ethereum.org.deepwork.studio/)

This is a different and bold take on a new look for ethereum.org. Something the community can really look on with splendor, as something for the new people to the space, for existing creators of all fields, and for everyone.

This bit here will be expanded upon by @helsf

### CODE REVIEW

**Comment by helsf** [comment]
This is our proposition. It will still be a community project, even more so. We call upon a different part of the community, designers, comms people and creatives, those whose skills and experience seemed to be under-appreciated or ignored, and actually have the skills to execute this in a slick and timely manner. Also as this will be a portal for those who may be new to the space or want to learn more the content and design needs to be in such a way in which it can be easily digestible and navigated around.

I surely don't need to explain why a website is the most important aspect of branding after a logo?! The importance for a website can not be overstated when it comes to onboarding new members of the community in order to reach our goal of decentralisation… In our lifetime.

Finally, with all this talk about diversity… Why are we still looking to our technologists and coders to redesign our website. Clearly anyone with basic communications or business knowledge is aware that your website is essentially a major part of your reputation. I think our community is diverse enough now to reach out to the non devs and give them a chance to shape our technology too. I personally don’t remember learning about coding while I was studying communications, and I’m sure as hell computer science doesn’t have a module on branding and public relations. Correct me if i’m wrong. 

Egos aside. Devs need to dev. How we gonna build if our devs are too busy trying to design our website. And at this rate, by the time it is finished we will be on ETH 5.0. So just use this design template that the team put all their hard work into, and let us shape it into the masterpiece the community really needs.

**Comment by charlieellington** [comment]
The Deep Work Studio hot take on a community driven approach. It could be done by:

Rapidly prototyping through Design Sprints with key stakeholders 
-> 
Community Feedback and Listening To Users 
-> 
Iterating. 

In my opinion the directive approach is better than asking the community to do the hard work for you. Co-ordination is necessary. Giving the website to the community is decentralized idealism and it hasn't changed in a week. 

-- 

**How could you approach a full redesign?**

_Stage 1: Design Sprint with the key foundation members_

The outcome would be a high fidelity prototype outlining the goals, key user stories and features that are required in the site. The user feedback would justify and help understand the importance of each feature.

_Stage 2: Community Input_

Collaborative sessions engaging the community to get input to content and design of the site. These could focus are the key areas identified in Stage 1.

_Stage 3: Design Sprints to go into the key sections in detail_

Identifying the key players and those with specific expertise (in the Foundation and community) we could run further design sprints to prototype and test each area or feature of the site.

_Stage 4: Designing the Interface_

From the prototype and community feedback. A design team could focus on the graphics, user interface and front-end.

-- 

This was part of a larger post exploring how we could re-design the old Ethereum.org: https://medium.com/deep-work-studio/redesigning-the-ethereum-website-e418cadd158a

**Comment by oovg** [comment]
This process reads right to me!

Moving forward, would we say that 'Stage 1' would be to review current state of this design together (with stakeholders), identify possible enhancements, explore divergent solutions, review and merge into next iteration?

**Comment by mirshko** [comment]
@oovg how do you suggest we go about ~Stage~ Phase 1?

@helsf ? thoughts?

**Comment by charlieellington** [comment]
@oovg - Yes! Something along those lines. I think the Sprint process would be great. 

Stage 1: 

**Identify possible enhancements:** We can review the goal and start asking "How Might We ... " questions on the current design. Vote and prioritise to find the most valuable improvements. 

**Divergent solutions:** Solution sketching, user maps and storyboarding. 

**Review and Merge:** Vote on the best solutions and gather user feedback. The only thing I would change is getting feedback before merging. 

More info on the Sprint process: https://medium.com/deep-work-studio/google-ventures-design-sprints-for-defi-dapps-and-blockchain-teams-3c292585f9a6

**Comment by oovg** [comment]
@charlieellington prrrfect! 

RE: feedback before merging, I just meant merge design-work (visual solutions), not code, to ease the load on the decision-makers (product-owners). 

Def feedback before code merge!(!!!)

**Comment by alexvandesande** [comment]
I like this. The whole design sprint process unfortunately I doubt will work for a simple reason: the site underwent a dozen of those before arriving in this WIP “compromise” version. 

So the best bet we have for a better design is doing what you’re doing: getting out and making PRs. I recently published one for a small redesign too but I’ll be happy to test yours too!

**Comment by ethjoe** [comment]
Hey @mirshko @helsf @charlieellington @oovg 

Thanks for all of the work on the Deepwork version of the site. A few of us saw it go up days before the MVP launched and it does tackle the "learn, build" in a similar way. 

There are elements here that definitely deserve consideration, and addressing them bit by bit would help to keep the process iterative. Specifically, the sub-header designs, articles/resources, prism color-selection, and a new news page all stand out. We'll notify as soon™ as submission process for subpages are online.

There is a plan to take submissions from professional designers for designs of whole subpages, and to maintain some consistency with the rest of the site (rather than 'full design by individual-PR' -- hence not accepting the redesign here, but we'll communicate this more clearly going forward). 

That said, _please_ keep pushing existing elements that need work, especially on subpages (this input is valuable for driving the long-term direction of the site) and I'm sure that the change-log will grow pretty quickly.

**Comment by charlieellington** [comment]
Thank you @alexvandesande and @ethjoe for the kind words! 

For clarity, our design is not the best in the world. It was produced at speed to suggest a process behind re-designing the old Ethereum site. We did not expect it to be the live final result. 

The most important approach for ethereum dot org is the process which is it redesigned. Not the look and feel. 

The suggestion of individual pages by different designers will turn into a weird amalgamation of design language, type and spacing. Not the representation we'd expect from the largest and greatest open source project in the world. 

I'm surprised this PR was closed. 

We're not suggesting our process is best. But, the process which is used needs a community debate and input from designers to reach the best solution.

**Comment by ethjoe** [comment]
@charlieellington The tl;dr here was to implement pieces of this in parts rather than as submitted.

The "please keep pushing existing elements that need work" referred to resubmitting individual pieces and PRs that can be pushed through since the full overhaul wouldn't fit.

**Comment by kischiman** [comment]
Hey @ethjoe, you are definitely right in that the website needs extensive work and an agency or cooperative that can realise this.

But - just to make sure it's clear: this shouldn't be us and this is not our point.

We are merely leaving a statement, that the way the design front of ethereum has been approached in an unproductive way, while there are better known approaches, leading to better results, in a shorter amount of time.

Firstly, spreading the tasks/subpages across many different designers runs the risk of heterogeneous visual design across the site (this approach is close to what happened to the current version of Windows). nobody wants that and nobody should see it.

Secondly, we DO NOT want to design the website. We could, but the issue we are trying to point towards is a very different and fundamental one - the approach defines the result. And if the result doesn't look acceptable, there is probably a better way to structure the collaborative work. It took 3 people less than a week to achieve a result that took the biggest open source community in the world more than two years. Our design is not good, but the community appears to agree that's it's better.

We want to demonstrate that the biggest open source community in the world shouldn't be represented by something not coming from it's inherent collaborative structure. And we are there, and that there is huge potential in the community, which is not being used at the moment.

I hope this makes a little bit more sense now.

**Comment by ethjoe** [comment]
Got it. Community-powered doesn't have to mean heterogeneous, but I guess we'll have to see how it plays out over time. And as for there being better design, we're sort of agreeing with each other in circles. People are submitting their own paths in parts, and hopefully content managers rise up with some oomph too.

**Comment by kischiman** [comment]
Community powered is not heterogeneous, that's right, but again, depends on the management - "people submitting their own paths in parts" does sound like total chaos. 

With a project like this you can't split it up and delegate different parts to different people. Or am I misunderstanding something?

**Comment by oovg** [comment]
My 2 gwei ... As a designer who has worked on digital products for many years, I too was skeptical of this path to improvement. 

However, I have embraced the 'community-powered' ethos as an experiment in distributed product improvement and creative coordination. I've begun pushing incremental changes and that seems to be working so far. I'm very interested in testing/discovering this process out for awhile and seeing how far we can take it (i.e. how close we can get it to what we Designers know it needs to be in order to perform).

The main issue I see is "Who validates an improvement?"
And there are two different types of improvement validations needed.
1. Validated incremental improvement
2. Validated 'holistic' improvement (i.e. validating that any change fits within the whole system)

**Pull request closed without merging**
