### PR TITLE
chore: Adding references to exchanges for the UAE #1283

### LINKED ISSUE #1283: Adding references to exchanges for the UAE
**Is your feature request related to a problem? Please describe.**
No. its just adding an information.

Adding exchange references under "[Where to buy ETH?](https://ethereum.org/en/get-eth/#country-picker)", 

**Describe the solution you'd like**
Could you please add the following exchanges that are available for the United Arab Emirates: [BitOasis](https://bitoasis.net/) & [Rain](https://www.rain.bh/)
They are reputed places and safe to deal with. 

**Describe alternatives you've considered**
N/A

**Additional context**

if you need anymore information. please let me know.

### PR DESCRIPTION
**Pull request by developerfred**
## Related Issue
close #1283

## Screenshots (if appropriate):
https://5f21b3699213e90008997849--ethereumorg.netlify.app/en/get-eth/#country-picker
Screen Shot 2020-07-29 at 14 46 06

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Hi there @developerfred we'll need a bit of time to refine our policy for listing exchanges. We just want to let you know we've seen this and it's on our radar to discuss and decide very soon! Thanks for contributing.

**Comment by developerfred** [comment]
@ryancreateacopy no problems, thanks when you decide let me know.

**Comment by samajammin** [comment]
Waiting on exchange info - see discussion in #1283

**Comment by samajammin** [comment]
Closing this out in favor of #1595. Thanks again for the PR @developerfred!

**Pull request closed without merging**
