### PR TITLE
`data` is the appropriate key not `input`

### PR DESCRIPTION
**Pull request by Amit0617**
`data` is expected as key in `eth_sendTransaction`

### CODE REVIEW

**Comment by corwintines** [comment]
@Amit0617 is this the case? When looking at the execution APIs specs it takes input

https://ethereum.github.io/execution-apis/api-documentation/

**Comment by Amit0617** [comment]
Ok so probably that too is wrong. Here are some sets of commands I tried in a hardhat environment with output. Decide yourself.

1. First trying contract deployment
```bash
curl --data '{"jsonrpc":"2.0","method": "eth_sendTransaction", "params": [{"from": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "gas": "0x1c31e", "input": "0x6060604052341561000f57600080fd5b60eb8061001d6000396000f300606060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063c6888fa1146044575b600080fd5b3415604e57600080fd5b606260048080359060200190919050506078565b6040518082815260200191505060405180910390f35b60007f24abdb5865df5079dcc5ac590ff6f01d5c16edbc5fab4e195d9febd1114503da600783026040518082815260200191505060405180910390a16007820290509190505600a165627a7a7230582040383f19d9f65246752244189b02f56e8d0980ed44e7a56c0b200458caad20bb0029"}], "id": 6}' -H "Content-Type: application/json" localhost:8545

```
```console
```

**Comment by Amit0617** [comment]
It can be of two types one contract creation and another interacting with contract. I also tried verifying whether there is any difference depending upon that. Looks like nope `data` is the expected key in all situations. Tried request and responses shown below
First getting transaction receipt for obtaining contract address
```bash
curl --data '{"jsonrpc":"2.0","method": "eth_getTransactionReceipt", "params": ["0x6b10bf0cc0dcf31496324fd40d14dd8ec14d55566ebf57b02ef9d40f29fe1fca"], "id": 7}' -H "Content-Type: application/json" localhost:8545
```
```console
{
  "jsonrpc": "2.0",
  "id": 7,
  "result": {
    "transactionHash": "0x6b10bf0cc0dcf31496324fd40d14dd8ec14d55566ebf57b02ef9d40f29fe1fca",
    "transactionIndex": "0x0",
    "blockHash": "0xdd1f661b32b4f4ab7e7c1c0a80cd10262e32066ea09f1d7f48034a6ed9a1fd43",
    "blockNumber": "0x1",
    "from": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
    "to": null,
    "cumulativeGasUsed": "0x195b0",
    "gasUsed": "0x195b0",
    "contractAddress": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "type": "0x2",
    "status": "0x1",
    "effectiveGasPrice": "0x6fc23ac0"
  }

```
Now trying to interact with it
```bash
 curl --data '{"jsonrpc":"2.0","method": "eth_sendTransaction", "params": [{"from": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "to": "0x5fbdb2315678afecb367f032d93f642f64180aa3", "input": "0xc6888fa10000000000000000000000000000000000000000000000000000000000000006"}], "id": 8}' -H "Content-Type: application/json" localhost:8545

```
```console
{"jsonrpc":"2.0","id":8,"error":{"code":-32603,"message":"Error: Transaction reverted without a reason string","data":{"message":"Error: Transaction reverted without a reason string","txHash":"0x011429615c2bfd06b96253e39731bf3ae3dd68fb9201bc555856cbd9ff0e40a9","data":"0x"}}}  
```
Now Trying same with `data` 
```bash
curl --data '{"jsonrpc":"2.0","method": "eth_sendTransaction", "params": [{"from": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "to": "0x5fbdb2315678afecb367f032d93f642f64180aa3", "data": "0xc6888fa10000000000000000000000000000000000000000000000000000000000000006"}], "id": 8}' -H "Content-Type: application/json" localhost:8545 

```
```console
{"jsonrpc":"2.0","id":8,"result":"0xcb7e8a5193a8d3128d9fa23a1a66f6bde2a5954d64041a760d97e031750430ee"}                                                                       
```

**Comment by Amit0617** [comment]
bump

**Pull request closed without merging**
