### PR TITLE
Added a simple brownie tutorial

### PR DESCRIPTION
**Pull request by PatrickAlphaC**
Adding python and brownie tutorial

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/2257

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
Thanks for posting this! Any chance the referral code could be removed?
ie: https://codeburst.io/deploy-a-smart-contract-using-python-how-to-b62de0124b

**Comment by PatrickAlphaC** [comment]
Oh it's not a referral code, it's a "friend link". It lets people view it without getting paywalled by medium :)

**Review by wackerow — APPROVED** [review]

**Review by samajammin — CHANGES_REQUESTED** [review]
Hey @PatrickAlphaC - thanks for submitting this!

Even when I try to access this via the "friend" URL, I'm blocked by the paywall:
https://share.getcloudapp.com/L1uNnbnb

Do you have a consistently accessible version of this? We'd prefer to only link to content that's not behind a paywall.

**Comment by PatrickAlphaC** [comment]
> Hey @PatrickAlphaC - thanks for submitting this!
> 
> Even when I try to access this via the "friend" URL, I'm blocked by the paywall:
> https://share.getcloudapp.com/L1uNnbnb
> 
> Do you have a consistently accessible version of this? We'd prefer to only link to content that's not behind a paywall.

Hmm... Odd... Well I just published on another site (dev.to) that doesn't have a pay wall. Hopefully that one is better!

**Review by samajammin — APPROVED** [review]
Nice! Thanks for the update.

**Pull request merged**
