### PR TITLE
Add CryptoJobs.co to jobs section

### PR DESCRIPTION
**Pull request by seanlakers**
I've added CryptoJobs.co to the job board list - The site has been live for close to a year now so should fit the criteria this time round. Thanks!!

### CODE REVIEW

**Comment by minimalsm** [comment]
Thanks @seanlakers. Will try to get this reviewed soon.

**Comment by corwintines** [comment]
Thanks, @seanlakers :)

I was wondering if you knew the job posting life cycle. I noticed some dated job postings on many companies.

Ex: https://www.cryptojobs.co/crypto-jobs-at-aave vs https://apply.workable.com/aave/

**Comment by seanlakers** [comment]
Hey,Jobs are checked every day and updates if expired. The Aave example shows our site and the aave careers page in sync - 12 identical open roles on each. Did you notice a discrepancy?CheersSeanOn 14 Nov 2022, at 23:13, Corwin Smith ***@***.***> wrote:﻿
Thanks, @seanlakers :)
I was wondering if you knew the job posting life cycle. I noticed some dated job postings on many companies.
Ex: https://www.cryptojobs.co/crypto-jobs-at-aave vs https://apply.workable.com/aave/

**Comment by corwintines** [comment]
I do notice differences yes. https://jobs.eu.lever.co/aave/ is the new careers board for Aave in this example. None of the jobs that are on this board are currently posted on cryptojobs.co, and vice versa.

**Comment by corwintines** [comment]
A lot of the postings on the Top Global Crypto Jobs section on the homepage dont exists either for these companies when digging deeper too. Im going to close this out. I appreciate the suggestion though for this. 

@all-contributors can you add @seanlakers for ideas

**Pull request closed without merging**
