### PR TITLE
Add a link to explain the term "blockchain"

### PR DESCRIPTION
**Pull request by tasdienes**
My parents reviewed this page and one comment was that the term "blockchain" is dropped without explaining what it means.  I added a link to one of the most simple and low-tech explanations that I could find.

### CODE REVIEW

**Comment by maurelian** [comment]
I'm curious why that particular link was chosen?
Linking to wikipedia seems like the more obvious default option: https://www2.deloitte.com/ch/en/pages/strategy-operations/articles/blockchain-explained.html

**Comment by tasdienes** [comment]
Wikipedia is good, but I was looking for something that my parents could understand, and I think they would have a hard time with the Wikipedia definition.  Multiple references might be even better.

**Comment by jjmstark** [comment]
@maurelian agree that wikipedia would be a better link.

**Comment by maurelian** [comment]
Feel free to reopen if the link is changed.

**Pull request closed without merging**
