### PR TITLE
Remove "inspired by Python" in Solidity's description

### PR DESCRIPTION
**Pull request by fubuloubu**
## Description
Every time I look at this page, I see "Solidity is inspired by C++, *Python* and JavaScript" and think to myself "where's the Python influence?"

Thinking about it further, it also seems kind of weird to have that there, and then mention another language that is also "Pythonic" (aka Vyper) right below it. It really just seems confusing to me. "Which language should I try if I really like Python?", the natural answer should be Vyper I would think.

Feel free to accept or reject this PR, but I just finally decided to do something about my cognitive dissonance.

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
@fubuloubu thanks for making this PR. I believe this was originally in the content because this is how Solidity describes themselves (see second paragraph here: https://docs.soliditylang.org/en/latest/) However I agree that this is confusing as python is a great differentiator from vyper.

**Review by ryancreatescopy — APPROVED** [review]

**Comment by ryancreatescopy** [comment]
@all-contributors please add @fubuloubu for content.

**Comment by leonardoalt** [comment]
Considering the discussions in https://github.com/ethereum/solidity/pull/3195#issuecomment-344264124 and https://github.com/ethereum/solidity/pull/11021#issuecomment-787814267, I think this was merged prematurely.

**Comment by fubuloubu** [comment]
@leonardoalt I think for the context of this webpage, it's more confusing to leave it in, even if you see it as more technically correct. We can discuss the change in the Solidity docs more, but I think not having every single language as "derived from Python" in this document will make it clearer to casual users which language has the _feel_ they're looking for, and don't necessarily care about the technical specifics of how the language's inheritance structure works or how the _idea_ of modifiers is similar to a construct in that language (which works in a much different way).

**Comment by leonardoalt** [comment]
Well, it said "influenced" and not "derived", and that's much more subtle than what the basic syntax looks like, which seems to be what you refer by "the feel they're looking for". If removing Python because of `def` and indentation makes sense, then removing JS because of `var`, `let`, scoping rules, etc etc makes even more sense.

**Comment by fubuloubu** [comment]
> @fubuloubu Well, it said "influenced" and not "derived", and that's much more subtle than what the basic syntax looks like, which seems to be what you refer by "the feel they're looking for". If removing Python because of `def` and indentation makes sense, then removing JS because of `var`, `let`, scoping rules, etc etc makes even more sense.

Most people comfortable with Javascript find Solidity more comfortable. The point of this website is to be a resource to newcomers, and pointing them at Solidity if they are looking for a Javascript-like language is the right way to go. Pointing them at Vyper if they really enjoy Python is also the right way to go.

**Pull request merged**
