### PR TITLE
tutorial - a guide to metamask

### PR DESCRIPTION
**Pull request by blakewood84**
## Description

This tutorial is to help others learn the basics of using MetaMask with their decentralized application and some helpful tips on how to make transactions as well as use MetaMask for user Authentication.

## Related Issue

No issue

## Preview:

[https://ethereumorgwebsitedev01-blakewood84ethereumorgwebsitet.gtsb.io/en/developers/tutorials/a-guide-to-metamask/](https://ethereumorgwebsitedev01-blakewood84ethereumorgwebsitet.gtsb.io/en/developers/tutorials/a-guide-to-metamask/)

### CODE REVIEW

**Comment by blakewood84** [comment]
I've also submitted an [Issue here](https://github.com/ethereum/ethereum-org-website/issues/4910) that is linked to the PR:

**Review by BigsteppA1 — APPROVED** [review]

**Comment by blakewood84** [comment]
hey guys, I've been able to get one approval so far! Was wondering if I could somehow get this through? @minimalsm @corwintines @pettinarip @samajammin @wackerow Thanks so much!

**Comment by corwintines** [comment]
I feel like this is covered in: https://ethereum.org/en/developers/docs/apis/javascript/ with a more standard library (ethers). Curious what others think.

**Comment by minimalsm** [comment]
Hey @blakewood84 just wanted to say thanks for submitting this.

Personally I won't have capacity to review for this the next week or so but looking forward to reading it :-)

**Comment by blakewood84** [comment]
> Hey @blakewood84 just wanted to say thanks for submitting this.
> 
> Personally I won't have capacity to review for this the next week or so but looking forward to reading it :-)

no worries, thanks @minimalsm !

**Comment by minimalsm** [comment]
Hey @blakewood8, sorry for the delay on this. Nice article but I have to agree with Corwin, this is already covered pretty well in our documentation already.  One thing we're becoming increasingly aware of is (as per our listing policy) — 'Does this now paralyse the user with choices?' I feel like adding this would contribute to that when our goal is to establish best practices instead. Thanks again for the PR and apologies for the delay in reviewing.

**Pull request closed without merging**
