### PR TITLE
desktop and mobile 16 px font

### PR DESCRIPTION
**Pull request by nloureiro**
Testing the font size more prominent on mobile for accessibility

### CODE REVIEW

**Review by wackerow — COMMENTED** [review]
Just curious, why would we suddenly make the mobile text larger than desktop?

**Comment by wackerow** [comment]
(And just flipping to draft while "WIP"; flip back when ready)

**Comment by nloureiro** [comment]
> Just curious, why would we suddenly make the mobile text larger than desktop?

The idea was to flip back to 16 on both screen sizes, but then @konopkja "pushed" me to test with 18

What do you think? Could you test it on your phone and tell us how it feels? Is it better to read on the phone?

**Comment by nloureiro** [comment]
@wackerow, let's push this on the next deployment with a 16px on all screens and discuss the 18px later... so, ready for review :)

**Comment by konopkja** [comment]
> @wackerow, let's push this on the next deployment with a 16px on all screens and discuss the 18px later... so, ready for review :)

actually thats next thursday no? id say thats a bit long waiting time

**Review by wackerow — APPROVED** [review]
Pulling this into `dev`. Can hot fix separately if we feel it's warranted.

**Pull request merged**
