### PR TITLE
Add DismissibleCard [Fixes #1837]

### LINKED ISSUE #1837: Make Eth2 service announcement dismissible
**Is your feature request related to a problem? Please describe.**

We show this prominently on every upgrade page (eth2.js template), particularly on mobile where it's the first piece of content.

This should be dismissible so it's not popping up on every single upgrade page.

**Describe the solution you'd like**

Make the card dismissible
- Use local storage to lookup/create item when dismissed

**Describe alternatives you've considered**
Keep as is

**Additional context**
None

### PR DESCRIPTION
**Pull request by samajammin**
## Description
- Refactor AnnouncementCard to DismissibleCard
- Stores key in local storage to track dismiss history

## Related Issue
#1837

### CODE REVIEW

**Comment by samajammin** [comment]
@ryancreatescopy note - this will look wonky on mobile until #1836 is merged.

**Review by ryancreatescopy — COMMENTED** [review]
Awesome! Will that other issue fix the fact that the page top-padding doesn't change? In this PR, I close the banner and there remains a lot of padding at the top of the page rather than the page's content shifting up to fill the space.

**Comment by samajammin** [comment]
@ryancreatescopy it should. I'll rebase off `dev` & we can test to confirm.

**Comment by samajammin** [comment]
@ryancreatescopy works for me! Tested on my iPhone.

**Review by ryancreatescopy — APPROVED** [review]
LGTM :+1:

**Pull request merged**
