### PR TITLE
Migrate Tabs to Chakra

### LINKED ISSUE #8639: Migrate `Tabs.tsx` to Chakra
*This is part of our [2nd wave of migration](https://github.com/ethereum/ethereum-org-website/issues/8632) of the [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

**Things to consider**

- Delete the current `Tabs.tsx` file
- Replace it with the native [Chakra Tabs component](https://chakra-ui.com/docs/components/tabs/usage)
- Probably we will need to create a new `Tabs` file under https://github.com/ethereum/ethereum-org-website/tree/dev/src/%40chakra-ui/gatsby-plugin/components to apply the current styles to it

Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) & the [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for more information.

### PR DESCRIPTION
**Pull request by amit-ksh**
## Description

Migrate the Tabs component from emotion to chakra

## Related Issue

Closes #8639

### CODE REVIEW

**Review by pettinarip — CHANGES_REQUESTED** [review]
Hey @amit-ksh thanks for the PR.

I think the styles are correct for this but for the `Tabs` case, we wanted to completely remove this component and start using the Chakra's Tabs instead. Declaring a new theme under https://github.com/ethereum/ethereum-org-website/tree/dev/src/%40chakra-ui/gatsby-plugin/components as it was described in the issue #8639

You can take as an example how we did this with the `Button` component here https://github.com/ethereum/ethereum-org-website/blob/dev/src/%40chakra-ui/gatsby-plugin/components/Button.ts

LMK if you need help on defining the new variant for this case. I think we should override the `enclosed` variant as it is pretty similar to our implementation.

**Comment by amit-ksh** [comment]
Hey @pettinarip! I tried overriding the `enclosed` variant, but it removes the bottom border when a `Tab` is selected. And adding border style for selected `Tab` was not overriding it, so should I create a brand new variant like `primary` for the custom style and use it as the default variant for `Tabs`?

**Comment by pettinarip** [comment]
Yes @amit-ksh please, that sounds good. We can refactor the name later if we need to.

**Review by pettinarip — APPROVED** [review]
🚀 nice!

**Pull request merged**
