### PR TITLE
Withdrawals page updates

### LINKED ISSUE #9456: Horizontal scroll on Withdrawals page
### Describe the bug

On mobile, the withdrawals page has a horizontal scroll

### To reproduce

1. Go to https://ethereum.org/en/staking/withdrawals
2. go to mobile view if not on a mobile device
3. See the horizontal scroll

### Expected behavior

There should be no horizontal scroll when on this page

### Screenshots

withdrawals

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Few bug patches an fix-ups related to the new /staking/withdrawals page
- Enables matomo event tracking for internal hash links
- Adds matomo tracking to contents of withdrawals page, including custom hash link events taking advantage of the modification to the `Link` component.

## Preview link
https://ethereumorgwebsitedev01-withdrawalsv2.gatsbyjs.io/en/staking/withdrawals/

## Related Issue
- #9101
- Fixes #9456

### CODE REVIEW

**Review by corwintines — CHANGES_REQUESTED** [review]
@wackerow i'm still getting the horizontal scroll on mobile. I do think it has something to do with the hero image. Let me know if you'd like me to take a look. Everything else looks good though.

**Comment by wackerow** [comment]
Local:
image
Preview: 
image


Removing entire hero doesn't change anything. Removing this Table fixes it. For some reason it likes to wrap and have a max width locally, but in the preview build it doesn't.

**Comment by wackerow** [comment]
The bugs noted should be patched now... Ready for another review

**Review by corwintines — APPROVED** [review]
Nice, thanks @wackerow!

@konopkja could you confirm these Matomo events? Good to go on my end.

**Comment by konopkja** [comment]
> Nice, thanks @wackerow!
> 
> @konopkja could you confirm these Matomo events? Good to go on my end.

cant really test events as i dont think they trigger on test env, pls go ahead.

**Pull request merged**
