### PR TITLE
Updating title of this tutorial to indicate pt. 1 of larger "Hello World dApp" tutorial series

### PR DESCRIPTION
**Pull request by nstrike2**
As a Go-To-Market engineer at Alchemy, I will be adding part two to this tutorial as a PR to the Ethereum foundation. Thus, I wanted to signal that this is only part 1 via the title change "Hello World Smart Contract for Beginners" to "Hello World Smart Contract for Beginners (Part 1/4 of Hello World dApp Series)".

Thank you and let's go builders!!!

## Description

As a Go-To-Market engineer at Alchemy, I will be adding part two to this tutorial as a PR to the Ethereum foundation. Thus, I wanted to signal that this is only part 1 via the title change "Hello World Smart Contract for Beginners" to "Hello World Smart Contract for Beginners (Part 1/4 of Hello World dApp Series)".

## Related Issue

Continuation of https://github.com/ethereum/ethereum-org-website/pull/4157, which has now been closed due to inaccessibility.

### CODE REVIEW

**Comment by nstrike2** [comment]
Hey @minimalsm ! I just approved all your changes to this pull request. Should be ready to merge.

If we can, can we also go through https://github.com/ethereum/ethereum-org-website/pull/4280, https://github.com/ethereum/ethereum-org-website/pull/4281, https://github.com/ethereum/ethereum-org-website/pull/4279, and https://github.com/ethereum/ethereum-org-website/pull/4282? These were pull requests we here at the Alchemy team submitted a while ago that we're still waiting for feedback on. We'd love for folks to get access to the magic these tutorials can bring to them as soon as we can!

cc: @elanh @thatguyintech

**Comment by minimalsm** [comment]
Hey @nstrike2, thanks for getting these changes in. Could you check out the other 3 tutorials and update accordingly. We can't go live with part 1/4 without having the other 3 parts ready to go also 😀

**Comment by minimalsm** [comment]
Seems we're still missing a bunch of header-ids. Could you get these added @nstrike2 🙏

**Comment by nstrike2** [comment]
> Seems we're still missing a bunch of header-ids. Could you get these added @nstrike2 🙏

Just added all of them @minimalsm !

**Comment by nstrike2** [comment]
> Hey @nstrike2, thanks for getting these changes in. Could you check out the other 3 tutorials and update accordingly. We can't go live with part 1/4 without having the other 3 parts ready to go also 😀

@minimalsm went ahead and updated the other three tutorials accordingly!

**Comment by nstrike2** [comment]
@minimalsm wanted to follow up to get these all pushed!

**Comment by nstrike2** [comment]
@minimalsm can we merge this? I'll be leaving Alchemy in 3 days to go back to school and then can't do much from here to continue on this after the holidays, so would love to have these be mutually beneficial to both you and us! Have made all the changes — should be ready to go.

**Comment by nstrike2** [comment]
@minimalsm wanted to follow up here to see if we could get these pushed! Hope you have a happy holidays :)

**Comment by nstrike2** [comment]
@minimalsm wanted to follow up here to see if we could get this as well as https://github.com/ethereum/ethereum-org-website/pull/4280, https://github.com/ethereum/ethereum-org-website/pull/4281, https://github.com/ethereum/ethereum-org-website/pull/4279, and https://github.com/ethereum/ethereum-org-website/pull/4282 merged! I've made all the necessary edits. Hope you all have a happy holidays :)

**Comment by nstrike2** [comment]
@minimalsm @matthieu @shazow @remi I wanted to follow up here to see if we could get this as well as #4280, #4281, #4279, and #4282 merged! I've made all the necessary edits. Hope you all have a happy holidays :)

**Review by jley81 — APPROVED** [review]
Looks good

**Comment by minimalsm** [comment]
Hey @nstrike2.

So the biggest problem with this tutorial is that it is trying to implement functionality that ethereum.org does not support (multiple 'paths' through each tutorial). Seems to be poor UX to have one after another in the same document so we're not happy with the approach. With that in mind, we decided that this tutorial should be broken up into separate tutorials. For simplicity (and to get this in quicker) we've done this in #5301 by extracting Hardhat. If you are motivated to do so, you are welcome to do the same with the Truffle side of things 🙏.

We've also agreed that as each tutorial is tightly coupled to the previous, these tutorials should be combined into one single tutorial (also done in #5301).

Sorry for the delay on this, closing this out but hopefully #5301 should be in soon 💪 thanks again for all your work on this.

**Comment by thatguyintech** [comment]
thanks for the update!

**Pull request closed without merging**
