### PR TITLE
Add ETH-Vietnam to community-events.json

### PR DESCRIPTION
**Pull request by Tuongg2312**
We need to add pull request for our event ETH-Vietnam into community-events.json

## Description

We need to add pull request for our event ETH-Vietnam into community-events.json, please check it out

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Thanks @Tuongg2312! :-)

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @Tuongg2312 for docs

**Comment by Tuongg2312** [comment]
Hi Joshua, thanks for supporting us.
I see the label change to MERGED and i wondering when will our event be
appearing on ETH website like this.
[image: image.png]

Vào Th 2, 18 thg 7, 2022 vào lúc 16:14 Joshua ***@***.***>
đã viết:

**Comment by Tuongg2312** [comment]
Hi @joshua, thanks for supporting us.
I see the label change to MERGED and i wondering when will our event be
appearing on ETH website like this.

---------- Forwarded message ---------
Từ: Tuong | Coincu ***@***.***>
Date: Th 2, 18 thg 7, 2022 vào lúc 18:11
Subject: Re: [ethereum/ethereum-org-website] Add ETH-Vietnam to
community-events.json (PR #7101)
To: ethereum/ethereum-org-website <
***@***.***>


Hi Joshua, thanks for supporting us.
I see the label change to MERGED and i wondering when will our event be
appearing on ETH website like this.
[image: image.png]

Vào Th 2, 18 thg 7, 2022 vào lúc 16:14 Joshua ***@***.***>
đã viết:

**Pull request merged**
