### PR TITLE
ChainShot 'Learn by coding' description change + remove translations

### PR DESCRIPTION
**Pull request by AlvaroLuken**
## Description

Hi all! My name is Al, I work over at ChainShot (https://www.chainshot.com/) - we are currently listed in your 'Learn by coding' section...

We respectfully submit this PR in hopes that the description in this section: https://gateway.pinata.cloud/ipfs/QmaFRUdYtqwPUuo3ESYPC5qiZ6m4pxtCXTSNJauXz5oyVf of your website be updated to reflect out more recent course offerings/resources.

Please email us at team@chainshot.com if you would like to confirm this change!

**All in all, this is just an edit from the previously listed description to the string: "Remote, instructor-led Ethereum developer bootcamp and additional courses." translated into relevant .json file language.**

Thank you, team!!

### CODE REVIEW

**Comment by AlvaroLuken** [comment]
@Dan-Nolan can also attest to this change!

**Comment by minimalsm** [comment]
Hey thanks for this! Happy to update this for you. 

Can I confirm how you sourced the translations? (We have a translation program in order to ensure high quality translations, so if they're machine translate we could remove them and get them redone for you?)

**Review by corwintines — APPROVED** [review]
Thanks @AlvaroLuken! I think this looks good pending @minimalsm comment.

**Comment by AlvaroLuken** [comment]
> Hey thanks for this! Happy to update this for you.
> 
> Can I confirm how you sourced the translations? (We have a translation program in order to ensure high quality translations, so if they're machine translate we could remove them and get them redone for you?)

I used Google Translate for all of them! Please feel free with whichever translation method is best!

**Comment by minimalsm** [comment]
Hi @AlvaroLuken thanks for this and appreciate the effort you've put into this. We try to avoid machine translations like Google Translate because they often provide low-quality translations. I've kept the English translation and removed the other translations so the correct information gets shown across languages. These changes will be highlighted in our translation program and should be re-translated and updated in a short while. 

Thanks again! Merging now.

**Pull request merged**
