### PR TITLE
First swing at persona page re-org

### PR DESCRIPTION
**Pull request by samajammin**
## Description
Restructure homepage & site navigation around 3 core users: individuals, developers & enterprise

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/328

## Screenshots (if appropriate):
persona-reorg

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by samajammin** [comment]
Simple first swing at this, feedback welcome. Changes apply to English only.
- Move /beginners to /what-is-ethereum
- Add /individuals (a combination of /use and /learn content)
- Update site navigation
  - Remove /beginners, /use & /learn
  - Add /individuals & /enterprise
- Update homepage
  - Remove /beginners, /use & /learn sections
  - Add /individuals section
  - Add button link to /what-is-ethereum

cc @jjmstark

**Comment by jjmstark** [comment]
I was imagining an even simpler change to the existing structure & content, where we keep most of the pages as they are (for now), and simply re-organize them into our new top-level structure.

Here's how I think this first PR should work:

The three top-level personas (Individuals, Developers, Enterprise) have top-bar menu items, and each has a dropdown menu on mouseover that reveals the pages within that category:

*Individuals*
 - What is Ethereum? (Same content as /Beginners, but with new title)
 - Use Ethereum (Same content as /Use)
 - Guides & Resources (Same content as /Learn)

*Developers*
- Get started (our new getting started page)
- Ethereum Studio (link to our new studio)
- Developer Resources (same content as /Developers)

*Enterprise*
- Ethereum for Enterprise


*Rationale for the above*
- Yes, some existing content (Use & Learn in particular) need to be rethought - but let's introduce those changes in a separate PR from one that simply introduces a new overall structure
- Might make sense to wait on content changes until we have a more scalable translation system in mind

*Other requested changes*

- On the front page under "Individuals", the first bullet point which is highlighted should be "What is Ethereum?" and not "How does Ethereum work?"

**Comment by samajammin** [comment]
@jjmstark what about the homepage section content for "individuals"? Should it be the same as the dropdown links? i.e.
> Individuals
What is Ethereum? (Same content as /Beginners, but with new title)
Use Ethereum (Same content as /Use)
Guides & Resources (Same content as /Learn)

**Comment by samajammin** [comment]
@jjmstark updated - LMK what you think.

**Comment by jjmstark** [comment]
Great! A couple notes:

- Under the `developers` drop down menu, there should be 3 items in the following order: `Getting Started`, `Ethereum Studio`, and `Developer Resources`.
- Yes, the bullet points you have under `Individuals` on the index are fine
- Under the `Developers` bullet points, maybe "getting started" should link to the new `Getting Started` page, rather than a section of the `Developer Resources` page?
- On the `Developer Resources` page, we should add prominent links to the `Getting Started` page and `Ethereum Studio`. Any thoughts on how to do that? The simple UI element you've added to the languages v2 (#333) page could be an option - maybe two of those, near top of the page?

**Comment by samajammin** [comment]
@jjmstark thanks for the review! Agree w/ all your points & should have clarified - those are missing because the `Getting Started` page (https://github.com/ethereum/ethereum-org-website/pull/322) hasn't been merged yet. Once that's done, I can make these updates.

Would you like to merge this first, as is? Or wait until https://github.com/ethereum/ethereum-org-website/pull/322 is merged so I can address your comments?

**Pull request merged**
