### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by EthanSK**
trie -> tree

### CODE REVIEW

**Comment by wackerow** [comment]
@EthanSK Thanks for catching this discrepancy... Wondering though if this should go the other way, using "trie" instead of the instances of "tree"...

https://eth.wiki/en/fundamentals/patricia-tree
This eth wiki entry uses "trie" throughout when discussing the modified Merkle Patricia trie specs

@samajammin thoughts here?

**Comment by ryancreatescopy** [comment]
In all the technical docs I've seen it uses `trie`, but I defer to the more technical among us. I didn't even realise the two were interchangeable in this context!

**Comment by wackerow** [comment]
hah, yeah a "trie" is a type of "tree", so it's a bit more specific. My vote would be to switch the three instances on the `accounts` page to "trie"

**Comment by ryancreatescopy** [comment]
@EthanSK do you mind changing all instances of `tree` to `trie` and we can approve/merge. Thanks!

**Comment by EthanSK** [comment]
The new PR is here https://github.com/ethereum/ethereum-org-website/pull/2466

I changed tree to trie in a few other places

**Pull request closed without merging**
