### PR TITLE
Add Status to the Ethereum Wallets page

### PR DESCRIPTION
**Pull request by jinhojang6**
Thank you for adding me to the list of contributors [last time](https://github.com/ethereum/ethereum-org-website/pull/694)! The Status Network would like to add Status to the https://ethereum.org/wallets/ page.

## Description

Status integrates multiple wallets into a single Status account enabling users to manage their assets more conveniently. For ultimate privacy, a chat key of a Status account is entirely decoupled from wallets so random people cannot find our wallet addresses until we add the user to our contacts.

Also, users can choose a wallet to send their ETH or ERC-20 assets to others in chat.

Please find more details [here](https://our.status.im/what-is-status-multi-account/) if you'd like to learn more about these features.

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/791

## Screenshots (if appropriate):
Picture1

### CODE REVIEW

**Comment by samajammin** [comment]
Hi @jinhojang6 - thanks for the PR!

For the time being, I'm going to reject this change. As you can see in other recent PRs (#683 #342 #316), we've chosen to pause adding new wallets to this list but we've have taken note of this submission for the future. We are considering ways to expand or rotate this list to include more options, while also ensuring a simple & clear process that doesn't overwhelm our users.

I encourage you to weigh into the discussion on #743 of how we could implement an objective process to add wallets.

**Comment by jinhojang6** [comment]
Thank @samajammin for letting me know that! Okay, I've understood your point on this so will look into the discussion and check the submission policy in the future.

**Comment by Flazky** [comment]
I have been using the status wallet to manage my crypto funds for a month now. How can it not be added to the ethereum page? Thats crazy to me considering its one of the oldenst projects that even vitalik is using himself..."facepalm"

**Comment by samajammin** [comment]
Hi @NevermoreAK - I encourage you to weigh in on #743

**Pull request closed without merging**
