### PR TITLE
Adds NFT School to learning tools [Fixes #4093]

### LINKED ISSUE #4093: Add NFT school to developer learning tools
**Describe the solution you'd like**

Add [NFT school](https://nftschool.dev/) to our [developer learning tools page](https://ethereum.org/en/developers/learning-tools/) under the bootcamp section.

**Describe alternatives you've considered**

We should probably separate bootcamps and courses into their own sections.

**Additional context**

[This is a similar PR](https://github.com/ethereum/ethereum-org-website/pull/3966) to use as a reference

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

### PR DESCRIPTION
**Pull request by pranavvdesai**
Added NFT school to the developer learning tools page under the Bootcamp section.

## Related Issue
#4093

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
Thanks @pranavvdesai! Appreciate you adding this... only thing is the `.env.example` file should not be removed, any chance we could revert this? Otherwise looks good!

**Comment by pranavvdesai** [comment]
> Thanks @pranavvdesai! Appreciate you adding this... only thing is the `.env.example` file should not be removed, any chance we could revert this? Otherwise looks good!

done 👍

**Review by wackerow — APPROVED** [review]

**Comment by wackerow** [comment]
@pranavvdesai Thanks! Just capitalized "School" before merging. Appreciate the help! Stop by our Discord if you care to contribute more and to collect your POAP!

**Comment by wackerow** [comment]
@all-contributors please add @pranavvdesai for content listing

**Comment by pranavvdesai** [comment]
> @pranavvdesai Thanks! Just capitalized "School" before merging. Appreciate the help! Stop by our Discord if you care to contribute more and to collect your POAP!

Thank you! excited to contribute more to this community🙌

**Pull request merged**
