### PR TITLE
Fix: minor typo

### PR DESCRIPTION
**Pull request by vinhloc30796**
## Description

Minor change to fix typo

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks, @vinhloc30796!

**Comment by corwintines** [comment]
@all-contributors can you add @vinhloc30796 for content

**Comment by corwintines** [comment]
@vinhloc30796 make sure you join the Discord server and come claim your POAP!

https://discord.gg/JUPn4ejq

**Comment by vinhloc30796** [comment]
Didn't expect the code to be merged that fast!

**Pull request merged**
