### PR TITLE
Add WIP Swedish translations

### PR DESCRIPTION
**Pull request by samajammin**
## Description
Building off the translation work in #315 (thanks @ExodusActual! ❤️ ), this gets the initial translations in shape for review & to be input into the CrowdIn project:
https://crowdin.com/project/ethereumfoundation/sv-SE#

## Related Issue
#222

### CODE REVIEW

**Comment by samajammin** [comment]
@sorumfactory - here are the relevant pages to review:
- https://deploy-preview-398--ethereumorg.netlify.com/sv/ (missing most of the content)
- https://deploy-preview-398--ethereumorg.netlify.com/sv/beginners/
- https://deploy-preview-398--ethereumorg.netlify.com/sv/use/
- https://deploy-preview-398--ethereumorg.netlify.com/sv/learn/
- https://deploy-preview-398--ethereumorg.netlify.com/sv/developers/

**Comment by samajammin** [comment]
@sorumfactory - checking in, have we received approval on this?

**Comment by sorumfactory** [comment]
> @sorumfactory - checking in, have we received approval on this?

Not yet. The Swedish translation has been delayed due to the fact that a lot of the Developer page is totally untranslated, with the exception of headings in the right sidebar. I think the SV volunteers haven’t touched that part from the beginning.

So there were two options we had at that time. one is asking Lionbridge to translate from scratch which requires more time allocation. Or waiting until SV volunteers to complete the translation.

However, at that moment, we were struggling hard with the contents version update which caused the synchronization issue. So we decided to pause the SV translation until we solve the better contents version management.

**Comment by samajammin** [comment]
@sorumfactory the decision has been made for Lionbridge to complete this translation, correct? 

Thanks & please keep us posted on progress here.

**Comment by samajammin** [comment]
Closing this out in favor of the updated translations in #779

**Pull request closed without merging**
