### PR TITLE
Remove all occurrences of Etherlime (deprecated) from docs

### PR DESCRIPTION
**Pull request by himanshu3w**
Edited Etherlime Docs Page Link To An Appropriate Link

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @himanshu3w thanks for all these PRs 😍 really appreciate the effort you've put in to do this - I've merged the others.

On this one, I wonder if we should remove Etherlime from the site as it [seems to be deprecated](https://github.com/LimeChain/etherlime). @perseverance could you confirm? And has it been superseded by anything else? Thanks.

**Review by samajammin — COMMENTED** [review]
Hey thanks for the PR @himanshu3w!

Agree if this tool has been deprecated that we should remove from the site. We should also remove it from translated pages as well (if you search the codebase for "etherlime" you'll find the other mentions of this).

**Comment by minimalsm** [comment]
Sounds good. Can you add a commit to this PR to remove all instances of Etherlime @himanshu3w?

Thanks again 👍

**Comment by himanshu3w** [comment]
Surely I Will

**Comment by minimalsm** [comment]
Hey @himanshu3w ☺️

Thanks for highlighting this issue to us. Noticed you've opened separate PRs (#3991 #3992 #3994 #3994 #3995) to remove each occurrence of this. Where possible we try to keep related jobs (like removing all occurrences of a broken link) to a single PR. You can do this by adding and pushing commits to your existing branch (see [this StackExchange answer](https://stackoverflow.com/questions/10147445/github-adding-commits-to-existing-pull-request) for more info on that) 

We do this because we have a [Release log](https://github.com/ethereum/ethereum-org-website/releases) to allow people to see what has gone into the latest version of ethereum.org and having a bunch of duplicate or similar entries isn't the best reading experience. 

Really appreciate you trawling through ethereum.org and finding all these issues 🙏🙌 If you need a hand with this in the future feel free to ping us on discord 😬👍

**Comment by himanshu3w** [comment]
sure

thanks

**Pull request merged**
