### PR TITLE
Fixed paddings of what is etherium page [Fixes #11361]

### LINKED ISSUE #11361: Wrong paddings on What is ethereum page (mobile)
### Describe the bug

wrong aligment:

 too much white space in cards (https://ethereum.org/en/what-is-ethereum/)
Screenshot 2023-10-03 at 22 03 25

expected design: (see https://ethereum.org/en/get-eth/)
Screenshot 2023-10-04 at 16 46 53

### To reproduce

1. use mobile device
2.  Go to https://ethereum.org/en/what-is-ethereum/

### Expected behavior

see other comments

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by oleksandr-hyriavets**
## Description

- Added extra margin for a header image
- Moved card to separate component
- Reduces x-axis padding for a section with cards

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/11361

### CODE REVIEW

**Comment by konopkja** [comment]
hello @oleksandr-hyriavets  still see issue with padding on https://ethereumorgwebsitedev01-oleksandrhyriavetsethereumorgw.gatsbyjs.io/en/learn/  mobile

**Comment by konopkja** [comment]
can u fix that in this PR too?

**Comment by TylerAPfledderer** [comment]
Hey @konopkja! Addressed the learn page padding in #11132 per @nloureiro request.

**Review by corwintines — APPROVED** [review]
Thank you @oleksandr-hyriavets!

We brought in a few PR's that fixed this, but wanted to credit you still for this PR :)

**Comment by corwintines** [comment]
@all-contributors can you add @oleksandr-hyriavets for code

**Pull request merged**
