### PR TITLE
Optimizing code overall

### PR DESCRIPTION
**Pull request by thouravi**
## Description

1. removed the unused __req parameter in the handler function.
2. destructured the statusCode and body properties from the lambda function call in the handler function.
3. simplified the handler function by using the json method on the res object, which sends a JSON response with the appropriate content-type header.

### CODE REVIEW

**Comment by corwintines** [comment]
Thanks for pointing this out @thouravi. I notice we dont use this lamda function anywhere in the codebase, so I think we can just remove this. Ill push that up.

**Review by corwintines — APPROVED** [review]
Thanks @thouravi!

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. We are in the process of getting our 2023 POAPs ready, but once they are you can [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳

**Comment by corwintines** [comment]
@all-contributors can you add @thouravi for code

**Comment by thouravi** [comment]
Hi @corwintines, thanks. Happy to contribute.

**Pull request merged**
