### PR TITLE
delete dydx as it is leaving ethereum

### PR DESCRIPTION
**Pull request by EvanVanNessEth**

### CODE REVIEW

**Comment by corwintines** [comment]
Agree with the PR, but need to do a bit more work to remove dydx. Will get that done this week.

**Comment by corwintines** [comment]
@minimalsm @wackerow if you don't mind taking a second look at this, lots of changes to remove dydx.

**Review by wackerow — APPROVED** [review]
Looks good!... Only thing I'm noticing is the search index isn't updated yet, but that should resolve on its own.

**Comment by corwintines** [comment]
Yeah, I think that happens on deploy

**Pull request merged**
