### PR TITLE
multiple personas clickable [Fixes #12645]

### LINKED ISSUE #12645: Feature request: multiple personas clickable on list of wallets
### Is your feature request related to a problem? Please describe.

With rising popularity of personas, during user testing several users requested having the option to select multiple personas to filter down list of wallets to a narrower list that tailors to their needs.

https://ethereum.org/en/wallets/find-wallet/

Screenshot 2024-04-03 at 12 03 04

### Describe the solution you'd like

Switch logic to "AND" and allow users to select multiple personas.

Change radio buttons to checkboxes in UI

### Describe alternatives you've considered

 NA

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by bhargavkakadiya**
## Description

Allows multi select for personas
image

For display of wallet tables, when multiple personas are selected, filters are applied after applying AND on all persona preset filters from useWalletPersonas.tsx

The current filtering logic for displaying results is open for review. I welcome any suggestions or requirements for adjustments to ensure the functionality meets our needs

## Preview link

https://deploy-preview-12753--ethereumorg.netlify.app/en/wallets/find-wallet

## Related issue

- Fixes #12645

### CODE REVIEW

**Comment by konopkja** [comment]
> Thanks @bhargavkakadiya! First glance looks like a great start, but per original issue (#12645):
> 
> > Switch logic to "AND" and allow users to select multiple personas.
> 
> Looks like the logic here results in an "OR" result where it'll filter wallets that match a persona OR filters that match another persona (widening results with more checks)...
> 
> @konopkja Am I correct that we want to _narrow_ the results as more checkboxes are added?

Thanks for the contribution!!! yeas our goal is to narrow down

**Comment by bhargavkakadiya** [comment]
@wackerow @konopkja 
Thanks for the review and inputs, I will update the logic

**Comment by bhargavkakadiya** [comment]
@wackerow I have updated to show narrowed results, can you please review it again?

**Comment by nhsz** [comment]
@bhargavkakadiya in this example, end result should be 4 wallets or less, as it was narrowed to 4 when clicking the mobile filter

Kapture 2024-04-30 at 14 21 44

**Comment by wackerow** [comment]
So close! This is definitely nuanced logic... @bhargavkakadiya Replicated Nico's steps above and it kept narrowing down appropriately, but when I uncheck the "Finance" persona, the filters do not broaden again, and the results stay filtered to only three:

https://github.com/ethereum/ethereum-org-website/assets/54227730/3b70f5b4-6ac8-47e6-8c85-f93f63d0e8f2

**Comment by bhargavkakadiya** [comment]
In this current version, the broadening is working upon deselecting persona. 

Also, based on the example below, when mobile is checked, it checks Android and iOS, which is fine.
But, when persona **Finance** is unchecked, it unchecks Android and iOS as well, but mobile is still checked. I will have to work on this yet, haven't figured easy fix for that yet

[Screencast from 05-14-2024 09:46:36 AM.webm](https://github.com/ethereum/ethereum-org-website/assets/26486494/a802f578-8d6e-43b4-9164-4f694b3e3f9b)

**Comment by wackerow** [comment]
Hey @bhargavkakadiya, just circling through. Any luck here? Can open this up to others in the community if needed

**Comment by wackerow** [comment]
Flipping to draft for now, please flip to "Ready for review" when ready

**Comment by corwintines** [comment]
Just going to leave my 2 cents here. 

I think as far as the multiple personas standpoint, I think this works great. Nice work @bhargavkakadiya.

One thing that needs to be ironed out is what happens if someone selects a filter after a persona. IMO, I think the personas should deselect, but keep the applied filters. @konopkja what do you think?

I will bring this up in grooming next week to get on the same page here so we can get this across the finish line, but Just wanted to say great work @bhargavkakadiya.

**Comment by konopkja** [comment]
> Just going to leave my 2 cents here.
> 
> I think as far as the multiple personas standpoint, I think this works great. Nice work @bhargavkakadiya.
> 
> One thing that needs to be ironed out is what happens if someone selects a filter after a persona. IMO, I think the personas should deselect, but keep the applied filters. @konopkja what do you think?
> 
> I will bring this up in grooming next week to get on the same page here so we can get this across the finish line, but Just wanted to say great work @bhargavkakadiya.

Hi, its great to see progress here!

I think from clarity perspective it is not a good experience to deselect personas because there is no indication the system would behave this way. Instead expected system behavior is to keep persona on and ADD to it another filter ("and" logic)

**Comment by bhargavkakadiya** [comment]
Thanks for the kind words; please do let me know if you want me to make any additional changes

**Comment by corwintines** [comment]
Hey @bhargavkakadiya.

Thanks for everything you've done so far here, this is close. Chatted with @konopkja to scope out last bit of functionality here to get this over the finish line. 

At the moment the selection and deselection of personas works great. 

What functionality needs to be added now is just around what happens if someone adds or removes other filters. 

- [ ] If user deselects something that is supposed to be true for a persona(s), then we deselect persona(s). Otherwise, we keep personas selected. You can add to filters for a persona, but can't have less. For example: NFT's wallet has nft_support, connect_to_dapps, and layer_2 true. If I were to select the filter swaps as well for example, the NFT persona would stay selected. But, if I remove either nft_support, connect_to_dapps, or layer_2, then the NFT persona gets deselected.
    - [ ] edge cases: If we have multiple personas selected, and we deselect a filter, the persona with that filter should be deselected, but keep the other one selected.
- [ ] New to crypto persona make all filters false, except `new_to_crypto` in https://github.com/bhargavkakadiya/ethereum-org-website/blob/3ca6c7fa1992f900a81b5dcfc0672e7123d7a905/src/hooks/useWalletPersonas.tsx#L7
- [ ] Confirm the New to crypto persona is working. Noticing this isn't matching production in this PR. 

Let me know if you have any questions around this, or if anything is unclear.

**Comment by bhargavkakadiya** [comment]
@corwintines I have pushed the requested changes. There was a bug for new to crypto persona selection; should be fine now. Please review and let me know if needs more fix

**Comment by konopkja** [comment]
lgtm! @corwintines  what should be the next steps?

**Review by corwintines — APPROVED** [review]

**Comment by bhargavkakadiya** [comment]
thank you @konopkja @corwintines @wackerow for your patience. Appreciate all your feedback and helping with the contribution

**Pull request merged**
