### PR TITLE
No errors in prod

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Description

Prevents missing translation errors from being thrown in production.

Putting this PR out to get feedback on the changes, then happy to track down all the `console.error` calls this way.

Adds a `consoleError` export in utils that will only throw errors if running in development.

## Related Issue

Solves https://github.com/ethereum/ethereum-org-website/issues/2390.

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
@yakkomajuri Hey, thanks for giving this a go! Looks like it should do the trick. 
@samajammin Curious your thoughts on expanding something like this... I suppose I'm hesitant to suppress too many warnings/errors. These specifically are known errors at this point and we're taking a look at ways to prevent them.
If we're not going to reuse this, perhaps it's best to just put this function directly within `translations.js`

**Comment by yakkomajuri** [comment]
Will wait on @samajammin here to determine if I should expand to suppress more of the explicit `console.error` calls or move this to `translations.js`

**Comment by yakkomajuri** [comment]
@wackerow @samajammin moved it over to `translations.js`

**Review by wackerow — APPROVED** [review]
@yakkomajuri LGTM! Thanks for your help with this 👍

**Review by samajammin — APPROVED** [review]
Thanks for this!

**Comment by samajammin** [comment]
@all-contributors please add @yakkomajuri for code.

**Pull request merged**
