### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by maxxflyer**
I just translated to italian only the welcome page so far. I guess we need a way in the home page to reach any kind of language translations.  How are we going to manage this and the website for translations?

### CODE REVIEW

**Comment by nihal9ns** [comment]
I believe it would be a good option to have a translation service integrated into the website, so we can simply add the strings in `key: value` pairs and then on the web, use the keys. The benefit of this is that we can have the strings translated to any language that we require.

**Comment by alancwoo** [comment]
@maxxflyer This is wonderful, thank you! Maybe we can work out a plan to structure translations sitewide so any contributor can indeed PR translations via https://vuepress.vuejs.org/guide/i18n.html#site-level-i18n-config

My only concern is that links/items could fall out of sync between languages causing quite a fragmented experience.

However, maybe if we pull out 'lists' into JSON objects as proposed in #63 we could avoid this issue.

**Comment by jjmstark** [comment]
Hey @maxxflyer - this is awesome! We are currently in the midst of a large translation effort, which will be announced soon. Would you like to be involved in the Italian translation program? Send us an email at website [at] ethereum.org, and we'll put you in touch with the team managing this project.

**Comment by jjmstark** [comment]
Closing since this is now already underway on Crowdin

**Comment by maxxflyer** [comment]
I found the crowdin translation. Not sure how I can help, I see some work is already done for the website

**Pull request closed without merging**
