### PR TITLE
Update new sidechain info

### PR DESCRIPTION
**Pull request by Devin-Han**
## Description
Update new information for sidechain provider who provides eth protocols

## Related Issue
- x

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks for the PR @Devin-Han! We have a listing policy when it comes to adding developer tools:
https://ethereum.org/en/contributing/adding-developer-tools/

Could you please address these questions from our [issue template](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=Type%3A+Feature&template=suggest_dev_tool.md&title=)?

Before submitting this suggestion, be sure to read our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/)

```
**Product name:**

<!-- Name of the product -->

**Product description:**

<!-- What does it do? -->

**How long has it been around?**

<!-- We prioritise products that are battle-tested. -->

**Where do you think it should go?**

<!-- List the pages where you think this tool is most relevant on ethereum.org -->

**GitHub URL**

<!-- Please provide a link to the product's repo. -->

**Docs URL**

<!-- Please provide a link to the product's docs. -->

**Is the product open source?**

<!-- We prioritise open source projects when possible. -->

**Additional context**

<!-- Add any other context or screenshots about the feature request here. -->
```

**Comment by BManess910** [comment]
$ git status
    [...]
    # Untracked files:
    [...]
    #       Documentation/foo.html
    #       Documentation/gitignore.html
    #       file.o
    #       lib.a
    #       src/internal.o
    [...]
    $ cat .git/info/exclude
    # ignore objects and archives, anywhere in the tree.
    *.[oa]
    $ cat Documentation/.gitignore
    # ignore generated html files,
    *.html
    # except foo.html which is maintained by hand
    !foo.html
    $ git status
    [...]
    # Untracked files:
    [...]
    #       Documentation/foo.html
    [...]

**Comment by BManess910** [comment]
$ git status
    [...]
    # Untracked files:
    [...]
    #       Documentation/foo.html
    #       Documentation/gitignore.html
    #       file.o
    #       lib.a
    #       src/internal.o
    [...]
    $ cat .git/info/exclude
    # ignore objects and archives, anywhere in the tree.
    *.[oa]
    $ cat Documentation/.gitignore
    # ignore generated html files,
    *.html
    # except foo.html which is maintained by hand
    !foo.html
    $ git status
    [...]
    # Untracked files:
    [...]
    #       Documentation/foo.html
    [...]

**Review by ramsemune — APPROVED** [review]

**Comment by wackerow** [comment]
@Devin-Han Following up on this, please let us know if you'd like us to look into this listing by providing the above information, thanks!

**Comment by wackerow** [comment]
Hey @Devin-Han, going to close this for now given that we haven't heard back. Please feel free to reply with info and we can re-open and address

**Pull request closed without merging**
