### PR TITLE
Improved Prerequisites Content

### PR DESCRIPTION
**Pull request by himanshu3w**
Improved Prequsites Content

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @himanshu3w thanks for the PR on this 😬

Open for discussion but I don't see this as an improvement. In its current form, it lists the prerequisites in order of importance and order of difficulty. Flipping it to add JavaScript to the end makes less sense to me.

**Comment by himanshu3w** [comment]
Agreed The Order Of Javascript is at the last what I Mentioned There


Because The starting  1st line was not properly mentioned there.

Maybe you can correct the 1st line properly.
It will be great.
@minimalsm

**Comment by minimalsm** [comment]
Sure, I can have a look. What do you think the problem is with the first line at the moment @himanshu3w?

**Comment by himanshu3w** [comment]
The Beginning Starts with 
=>As well as understanding JavaScript.
and It Seems dramatically Wrong To Me.
If that part is okay, Let me know I will Close This PR.
@minimalsm

**Comment by himanshu3w** [comment]
I am withdrawing this PR

**Comment by minimalsm** [comment]
Yeah, I think grammatically it is correct as is. Thanks for the suggestion 😬

@all-contributors please add @himanshu3w for ideas

**Comment by himanshu3w** [comment]
Thanks for adding me for ideas @minimalsm

**Pull request closed without merging**
