### PR TITLE
Add checksum to deposit contract address

### LINKED ISSUE #5448: Deposit contract address should have checksum
The [staking deposit contract address](https://ethereum.org/en/staking/deposit-contract/) "copy to clipboard" button should have [mixed-case address checksum](https://eips.ethereum.org/EIPS/eip-55) encoding. Currently, the address (put in the clipboard) is all lowercase (no checksum). This is a simple thing we could do to prevent potential errors.

More specifically, change the address in the following way:
```
- 0x00000000219ab540356cbb839cbe05303d7705fa
+ 0x00000000219ab540356cBB839Cbe05303d7705Fa
```

This new address comes from [the contract address](https://etherscan.io/address/0x00000000219ab540356cbb839cbe05303d7705fa) on Etherscan.

### PR DESCRIPTION
**Pull request by jtraglia**
The staking deposit contract address "copy to clipboard" button should have mixed-case address checksum encoding as defined in EIP-55. Before this change, the address (put in the clipboard) is all lowercase (no checksum).

Fixes #5448.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
LGTM! Thanks @jtraglia!

**Comment by corwintines** [comment]
@all-contributors can you add @jtraglia for content

**Comment by corwintines** [comment]
@jtraglia make sure to come claim your POAP from the ethereum.org discord :)

https://discord.gg/zCHhRAgQ

**Comment by jtraglia** [comment]
Will do, thanks guys!

**Pull request merged**
