### PR TITLE
Added Zero Services GmbH to "nodes-as-a-service"

### PR DESCRIPTION
**Pull request by zeroservices**
## Description

Added Zero Services GmbH to "nodes-as-a-service"

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/7607

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Thanks @zeroservices

**Comment by minimalsm** [comment]
Info iin the PR looks good, but [looking at the website](https://www.zeroservices.eu/#contact) I'm a bit confused. Do users have to contact you to use your service? It seems that is the only option they have, which seems a little odd/high friction. Is this intended for Enterprise level customers?

**Comment by zeroservices** [comment]
> Info iin the PR looks good, but [looking at the website](https://www.zeroservices.eu/#contact) I'm a bit confused. Do users have to contact you to use your service? It seems that is the only option they have, which seems a little odd/high friction. Is this intended for Enterprise level customers?

Thanks for your feedback @minimalsm . Indeed, our website needs a major overhaul which is currently ongoing and will them come with more direct ordering functions. Also, we mainly target enterprise customers atm.

**Comment by minimalsm** [comment]
With that being the case, I think we should add it to the Enterprise page [under Products and services](https://ethereum.org/en/enterprise/#products-and-services) instead. We'd like to keep a clear separation between regular and business users where we can.

**Comment by minimalsm** [comment]
Sorry for the delay on this, feel free to open a new PR to add to the above page, and I'll get it merged asap. Closing this PR in favour of the new one.

**Pull request closed without merging**
