### PR TITLE
Modify solidity version to ^0.8.1 [Fixes #2357]

### LINKED ISSUE #2357: Update homepage smart contracts to Solidity 0.8.x
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Good spot from @franzihei
> It would be nice if you could use a version from the current Solidity series with is 0.8.x. It is super hard to motivate the ecosystem to use the latest versions (while that is super important for secturity reasons!) hence we do not want to encourage using outdated versions by putting them on the ethereum.org website. : )

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by MonarthS**
## Description
Modified solidity version from `^0.7.0` to `^0.8.1` on homepage.

## Related Issue
#2357

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
👍 Thanks @MonarthS for updated this!

**Review by samajammin — APPROVED** [review]
Thanks for this!

**Comment by samajammin** [comment]
@all-contributors please add @MonarthS for code.

**Comment by samajammin** [comment]
@all-contributors please add @MonarthS for code.

**Comment by Monarth-s** [comment]
@samajammin I found that there are still many codes(in developer docs & tutorial) that contains old solidity version, should we upgrade them to latest version too?

**Comment by MonarthS** [comment]
@samajammin I found that there are still many codes(in developer docs & tutorial) that contains old solidity version, should we upgrade them to latest version too?

**Comment by wackerow** [comment]
@samajammin What do you think about this? I'd be hesitant to overhaul the tutorials to start, but updating the documentation sounds like a great idea to me

**Pull request merged**
