### PR TITLE
English TimeToRead for Chinese Tutorials #4083

### PR DESCRIPTION
**Pull request by SNikhill**
## Description

Make the Chinese developer Tutorials Page use English TimeToRead till [this PR](https://github.com/gatsbyjs/gatsby/pull/25533) is merged.

Please, keep in mind that this is just a temporary fix.

## Related Issue

- #4083 
- https://github.com/gatsbyjs/gatsby/issues/25532

### CODE REVIEW

**Comment by SNikhill** [comment]
> Hey @SNikhill this is looking good muscle
> 
> We probably want to implement this for all logographic languages (i.e. Chinese (simplified and traditional), Japanese, Korean, etc)

Greetings,

Okay, so all the Logographic languages will be supported.
This is the first time that I have heard the word.

**Comment by minimalsm** [comment]
> > Hey @SNikhill this is looking good muscle
> > We probably want to implement this for all logographic languages (i.e. Chinese (simplified and traditional), Japanese, Korean, etc)
> 
> Greetings,
> 
> Okay, so all the Logographic languages will be supported. This is the first time that I have heard the word.

As per @wackerow's comment I think the best fix here would have **all** languages default to whatever the English time to read is. This allows us to be future-proof for any other languages that might be broken by this same issue.

**Comment by SNikhill** [comment]
@https://github.com/minimalsm

Okay, so, if timeToRead doesn't exist, timeToRead for English Language will
be used. But, for Logographic languages specifically, the timeToRead will
be overwritten and en-timeToRead will be used (till the issue with the
gatsby plugin being used, is fixed).

**Comment by wackerow** [comment]
@SNikhill Would just simplify that to using the english timeToRead for every language (even if one already exists, so we don't have to maintain a list of overrides).

**Comment by SNikhill** [comment]
> @SNikhill do you need anything to help get this over the line?

@minimalsm Apologies for the delay. I have been slightly under the weather. I shall ensure that the same gets done by the end of this week.

**Comment by SNikhill** [comment]
@minimalsm 

So, all the Internal Tutorials will display the English Time to read.

I do have a question, for the page where the tutorial's content is displayed (Generated Programatically using the `tutorial` template), incorrect Time to Read is being displayed.
I was wondering if there is a way I could send the English time to read as a prop to the `tutorial.js` template?

**Comment by minimalsm** [comment]
Thanks @SNikhill. I don't immediately see the best way to get around this. 

@corwintines any ideas here?

**Comment by samajammin** [comment]
My 2 cents - I like the idea of solving this issue via the community plugin @pettinarip mentioned here: https://github.com/ethereum/ethereum-org-website/issues/4083#issuecomment-980791293

Seems like a good solution until the issue with the official Gatsby plugin (https://github.com/gatsbyjs/gatsby/issues/25532) is resolved.

**Comment by SNikhill** [comment]
Okay, Sir. I shall test the same by this week and let you know.

**Comment by minimalsm** [comment]
Thanks @SNikhill. Sorry for dragging you all over on this solution but we appreciate you iterating towards a more complete solution 😬❤️

**Comment by SNikhill** [comment]
I just forced push certain changes with an update to gatsby config to use the remark-reading-time.

I can verify that the reading time for the Logographic Languages is no longer 1.
I am rounding off the time to the nearest integer since the plugin got too specific (like 7.349)

> Thanks @SNikhill. Sorry for dragging you all over on this solution but we appreciate you iterating towards a more complete solution

@minimalsm No sorry necessary. I learn every time I contribute. :)
Please, let me know if I could be of further assistance.

**Review by pettinarip — APPROVED** [review]
LGTM @SNikhill! thanks for the contribution!

**Review by wackerow — APPROVED** [review]
Lookin good! Thanks @SNikhill !

(Good to merge into dev after current deploy is resolved and merged into master)

**Comment by SNikhill** [comment]
Okay, I just saw the merge conflicts.

Let me fix them.

**Review by minimalsm — APPROVED** [review]

**Review by corwintines — APPROVED** [review]

**Pull request merged**
