### PR TITLE
add meeds to dapps

### LINKED ISSUE #13021: Suggest a dapp : Meeds
### Name

Meeds

### Description

Fair and transparent rewards for Web3 contributors

### Logo

meeds-256x256

### Brand color

#D26561

### Is your dapp open source?

Yes

### If open source, what is the repo for the dapp?

https://github.com/Meeds-io/

### Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible

- [Smart contracts code](https://github.com/Meeds-io/deeds-dapp/tree/develop/deeds-dapp-contract/src/main/resources) uses standards and [OpenZeppelin libraries](https://www.openzeppelin.com/contracts)
- self-audited with [MythX](https://consensys.io/mythx/about)
- informal reviews by [Black Paper](https://www.black-paper.xyz/) auditors : 

### Can a user access the dapp without creating an account?

No. Users can use Metamask  to create an account on a Meeds Hub using their Ethereum address

### Are dapp funds non-custodial?

Yes. 
Rewards target wallets can use Metamask (recommended), or if a user does not have Metamask installed, they are offered to generate a non-custodial Meeds wallet and back up their private key.User wallets can be self-custodial using Metamask (recommended), or if a user does not have Metamask installed, they are offered to generate a non-custodial Meeds wallet and back up their private key.

### Do you offer community support?

Yes, through Discord: https://discord.gg/8bfU2NuFb9

### Describe any geographical restrictions on usage of your dapp

global. Access through https://meeds.io

### Would you like to work on this issue?

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by plamarque**
## Description

Add meeds logo and description in dapps page in category finance/payments

## Related Issue
- Closes #13021

### CODE REVIEW

**Review by wackerow — CHANGES_REQUESTED** [review]
Hey @plamarque, as noted in https://github.com/ethereum/ethereum-org-website/issues/13021#issuecomment-2192424954 go ahead and move this to a new "Community" section within "Social"... let me know if you have issues with this change, happy to help

**Review by wackerow — APPROVED** [review]
Thanks @plamarque! Looks good. I added a commit to just move this into it's own row per convention on that page. Bringing in

**Comment by wackerow** [comment]
@all-contributors please add @plamarque for tool

**Comment by plamarque** [comment]
Awesome, thanks @wackerow !

**Pull request merged**
