### PR TITLE
Merge pull request #1 from ethereum/KunKaxx.patch

### PR DESCRIPTION
**Pull request by KunKaxx**
Thank.patch

### CODE REVIEW

**Review by KunKaxx — COMMENTED** [review]
.

**Comment by KunKaxx** [comment]
Thank

**Comment by samajammin** [comment]
Hey @KunKaxx! Could you please explain the purpose of this PR?

**Comment by KunKaxx** [comment]
Sorry if I make you feel bad. I don’t know any thing , I want to see and do all with my thinking’s in my head. Can’t explain, you can believe me , it’s so sad because of your locked. Thank for all, please teach me if you have time . Have a nice day. Important! I don’t know about your contribution, so if I do some mistake, please fix it and say me thank

**Review by KunKaxx — COMMENTED** [review]
.patch

**Pull request closed without merging**
