### PR TITLE
Add Terminal to "Other Tools" section

### PR DESCRIPTION
**Pull request by kinrezC**
Would love to have Terminal be listed on here.  We provide a plethora of tools that would be useful for Ethereum developers.  Examples of what Terminal provides:

- Hosted ganache instances forked from any block
- Folder structure for organizing smart contracts alongside adjacent infrustructure
- Ethereum DB to construct complex queries for historical ETH data (see https://ethcarbonfootprint.me/ and https://uniswapstats.com/ for example usage)
- Hosted database infrastructure
- Event, function, and transaction webhooks
- Logging for dapps

Give the PR a look-over and if there's anything you'd like me to change, do let me know.

Thanks!

### CODE REVIEW

**Comment by samajammin** [comment]
Thoughts on this @CPSTL ?

**Comment by samajammin** [comment]
@CPSTL circling back on this, please let us know what you think! Thanks.

**Comment by CPSTL** [comment]
> @CPSTL circling back on this, please let us know what you think! Thanks.

LGTM. @kinrezC In order to keep treatment of community additions consistent, we ask that new additions are added to the bottom of each list. Please make that update and we will get this merged!

**Comment by samajammin** [comment]
@kinrezC - checking in. Please update that addition & resolve the conflicts. Then we'll get this merged ASAP. Thanks!

**Comment by kinrezC** [comment]
Thanks all. Passing this off to @blockchainbrett :+1:

**Comment by samajammin** [comment]
Hey @Blockchainbrett - friendly nudge on this in case this fell off your radar.

**Comment by samajammin** [comment]
@kinrezC @Blockchainbrett - looks like the Terminal site has been updated? I don't see any of the features you listed in this original description on the website. Looks like it's now solely focused on website deployments for IPFS?

I'm going to close this out. Please feel free to re-open if there's something I've missed or submit a separate PR to reflect the changes of this tool. Thanks.

**Pull request closed without merging**
