### PR TITLE
lowered etherlime due to its outdated nature and bumped up hardhat an…

### PR DESCRIPTION
**Pull request by PatrickAlphaC**
…d brownie

## Etherlime is tightly coupled with an outdated version of Infura and seems to be a bad developer experience if a newer developer starts with it. Hardhat and brownie seem to be amazing choices so I moved them up. 

Full writeup can be found [here](https://github.com/PatrickAlphaC/smart-contract-frameworks).

Related to https://github.com/ethereum/ethereum-org-website/issues/2235

### CODE REVIEW

**Review by ryancreatescopy — APPROVED** [review]
Thanks for updating!

**Comment by ryancreatescopy** [comment]
@all-contributors please add @PatrickAlphaC for content.

**Comment by ryancreatescopy** [comment]
Fixes #2235

**Comment by PatrickAlphaC** [comment]
Thanks all! I didn't want to remove parasol or etherlime yet, but in the future we might want to remove them as they are over a year's worth of inactivity and are already outdated. 

Thanks for this project and adding me as a contributor!

**Pull request merged**
