### PR TITLE
Add Link to developer learning tools to pull request

### PR DESCRIPTION
**Pull request by timhc22**
Any reason not to have this on here?

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Thanks for the pr @timhc22 – so we link to cyptozombies from our developer resources (https://ethereum.org/en/developers/learning-tools/) so I'd prefer not to have this linked to twice for link management overhead. 

Perhaps we could transition this PR to adding a callout to our developer resources from the Learn page, e.g.:

```
**Aspiring Ethereum developer?**
Check out our developer portal. We've got documentation, tutorials, and other resources for learning how to build Ethereum products. [View developer portal](/developers/learning-tools/)
```

**Review by ryancreatescopy — CHANGES_REQUESTED** [review]
See above comment

**Comment by timhc22** [comment]
@ryancreatescopy that should be added now, I'm still learning how to do proper pull requests, so please let me know if there are any issues. Thanks.

**Comment by ryancreatescopy** [comment]
Awesome @timhc22 I made a quick edit but this looks good to merge!

**Comment by ryancreatescopy** [comment]
@all-contributors please add @timhc22 for content.

**Pull request merged**
