### PR TITLE
Fix possible grammatical mistake

### PR DESCRIPTION
**Pull request by blackblather**
## Description

I believe there was a simple mistake in the text of the _Scaling_ page, in the chapter of _State Channels_.
I think the author meant to use "thus" instead of "this".

### CODE REVIEW

**Review by minimalsm — CHANGES_REQUESTED** [review]
Nice spot. Personally, I think using simpler language here is preferable.

```diff
+++ This minimizies network congestion, fees and delays. The two types of channels are currently state channels, and payment channels.
```

**Comment by brettsmentek** [comment]
> Nice spot. Personally, I think using simpler language here is preferable.
> 
> ```diff
> +++ This minimizies network congestion, fees and delays. The two types of channels are currently state channels, and payment channels.
> ```

I agree with this phrasing. Typo in `minimizes`, though. I also don't believe there should be a comma in the second sentence, `The two types of channels are currently state channels and payment channels.`

**Comment by blackblather** [comment]
Thank you guys 👍
Yeah, I agree with Brett. The new phrase is simpler, but would also remove the comma at the end.

**Comment by ryancreatescopy** [comment]
@all-contributors please add @blackblather for content and bugs.

**Comment by ryancreatescopy** [comment]
@all-contributors please add @brettsmentek for content.

**Pull request merged**
