### PR TITLE
Eth2 images

### PR DESCRIPTION
**Pull request by ryancreatescopy**
## Description

Updating eth2 pages with illustrations.

**TODO**
- [x] Hero images should align right, bullet box should overlay
- [x] Fix desktop upgrades dropdown menu: width issue

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
- [ ] update alt tag images
- [ ] refactor ActionCard
- [ ] add header to upgrade page template?

**Comment by samajammin** [comment]
@wackerow assigning this to you as discussed.

**Comment by samajammin** [comment]
@ryancreatescopy FYI - @wackerow got the images loading into the template (thanks @wackerow) - it just needs some tweaks on the sizing of the images. Feel free to play around with a sizing you like. I'm also happy to jam on it with you 🎸

**Comment by wackerow** [comment]
@samajammin Passed the build on the first push, then encountered that same build error on the next push about 40min later.

That aside, this should be ready, just can't preview it with Netlify at this moment
cc @ryancreatescopy

**Pull request merged**
