### PR TITLE
Added Smart contract design and UX Doc

### LINKED ISSUE #13656: Content request: Smart contract design and UX
This is a content request for anyone with relevant experience to write an article explaining overlap between UX and designing smart contract logic. 

Whoever wants to write the article, please first comment on this issue and we will assign it to you.

Smart contract development can be scary, its publishing to a network is final. Poorly designed contracts can be costly to users or lack important functionality.

- At what stage should the designer be part of the conversation? 
- What validation techniques can be provided to ensure good results?
- What should developers take into consideration from a UX perspective when designing contract logic?
- How should the process look like?

- provide examples and best practices 

This article will be published to https://ethereum.org/en/developers/docs/design-and-ux/ documentation.

### PR DESCRIPTION
**Pull request by harshitdabra**
This PR is for the new documentation of "Smart contract design and UX". New content is added and is required to be merged.

fixes #13656

### CODE REVIEW

**Comment by konopkja** [comment]
Hi @harshitdabra, was this generated by AI?

Using AI isn’t an issue as long as it’s done thoughtfully, but the draft could benefit from some editing to improve clarity and flow.

	1.	There are excessive sentences and paragraphs that don’t add much value and should be trimmed.
	2.	The first two sections can likely be removed to create a smoother structure.
	3.	Some topics feel too broad, and more detailed, practical insights would be helpful.

There are good starting points, but the overall length is a bit much, and the quality could be refined.

**Comment by harshitdabra** [comment]
Only 2-3 snippets were AI generated but overall tried to align in as per requirements. Will update another version shortly as per your review @konopkja

**Comment by konopkja** [comment]
> Only 2-3 snippets were AI generated but overall tried to align in as per requirements. Will update another version shortly as per your review @konopkja

Ok, thank you. Happy to provide more in depth review and comments on the next version and get this ready to be published.

Also a side note, this should not replace content on "developers/docs/design-and-ux/" , rather it should be a new subpage in this section. 

For example "developers/docs/design-and-ux/smart-contract-ux"

**Comment by corwintines** [comment]
@harshitdabra closed the new PR you opened for changes to this PR. Please keep any changes within this pull request so we have context of previous discussion.

**Comment by corwintines** [comment]
@harshitdabra bump here, wondering if you were still planning to work on this.

**Pull request closed without merging**
