### PR TITLE
Add charts at homepage [Fixes #2319]

### LINKED ISSUE #2319: Build charts for homepage stats section
Dependency: #2124

- [ ] Confirm each data source provides time series info (& range they provide)
- [ ] Select charting library to use
- [ ] (depending on above) add toggles to view (e.g. all / 1yr / 90 / 30 day)
- [ ] Add background trendline to each datapoint:
Image 2021-03-08 at 9 38 00 AM

### PR DESCRIPTION
**Pull request by Andrew-Sofos**
Build charts for homepage stats section

## Description
Get data with API calls and display the data in form of charts with the use of recharts library 

## Related Issue
[issue](https://github.com/ethereum/ethereum-org-website/issues/2319)

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @Andrew-Sofos, any update on this? Or anything I can do to help?

**Comment by Andrew-Sofos** [comment]
Hi @minimalsm I am waiting for some changes to be made on netlify lambda functions in order to achieve less API calls. I don't think that I need any help on my part for the charts but I would appreciate an update regarding the lambda functions.

**Comment by minimalsm** [comment]
@Andrew-Sofos okay, thanks for trying it isn't ideal without access to the lambda functions... there is currently an open issue for configuring the Netlify functions to work for contributors, hopefully, that will be solved quite soon (added a note to reopen this PR when it is solved).

Closing this out, for now, will ping you when we can get you unblocked ✌️

**Comment by wackerow** [comment]
Given difficulties with using our lambda functions which utilize protected API keys, I took a closer look at this and have made some progress. Reopening and will push changes.

**Comment by wackerow** [comment]
Getting this locally with `netlify dev`
image

But the preview deploy at https://deploy-preview-3354--ethereumorg.netlify.app/en/ doesn't want to load
image

Will take a closer look tomorrow.

**Comment by Andrew-Sofos** [comment]
Hello, @wackerow I think the cause of the problem is the ResponsiveContainer, I had this issue before and it was solved after I removed the ResponsiveContainer attribute. I know that it is really important but for some reason it doesn't want to cooperate.

**Comment by minimalsm** [comment]
Closing this in favour of #2319 

Thanks for all the work you've put into this @Andrew-Sofos ☺️❤️ if you haven't already, be sure to stop by and collect your POAP! 🎉

**Comment by minimalsm** [comment]
@all-contributors please add @Andrew-Sofos for code

**Comment by wackerow** [comment]
Yes, thank you again @Andrew-Sofos! The help is definitely appreciated, and we probably should've seen these blockers coming given how these lambda functions are set up, so my apologies for setting you down that path, and for the delayed communication on this. Definitely claim your POAP on Discord, you certainly earned it 😃

**Comment by Andrew-Sofos** [comment]
Thank you too @wackerow, it was really fun working on this, hope our paths cross again.

**Pull request closed without merging**
