### PR TITLE
added ethercluster

### PR DESCRIPTION
**Pull request by virgil**

### CODE REVIEW

**Comment by YazzyYaz** [comment]
@samajammin the working demo is specific for ETC, but Ethercluster works with any network, like ETH, because it's running Parity containers at the end.

The only requirement needed from the user is to modify the network config in their parity container to whatever network they require.

Geth and MultiGeth and Hyperledger Besu to be added soon in the future with the code and guide needed.

Let me know if you have any questions, cheers!

**Comment by virgil** [comment]
@YazzyYaz Get the ethercluster.com site to more prominently mention working with ETH (ideally with a button demo’ing for eth mainnet/goerli) and we’ll see what we can do.  If you could include several configuration files for typical configurations, and one of those configuration files having the settings for working with ETH, that would be very thoughtful.

**Comment by YazzyYaz** [comment]
> @YazzyYaz Get the ethercluster.com site to more prominently mention working with ETH (ideally with a button demo’ing for eth mainnet/goerli) and we’ll see what we can do. If you could include several configuration files for typical configurations, and one of those configuration files having the settings for working with ETH, that would be very thoughtful.

Will do!

**Comment by samajammin** [comment]
Great - thank you both! @YazzyYaz just ping me here when those updates are made & we'll work to get this merged. Cheers.

**Comment by samajammin** [comment]
@YazzyYaz checking in on this - looks like you've made updates?

**Comment by YazzyYaz** [comment]
Hi @samajammin sorry for the late reply, was taking a few days off. 

Yes it has changed to support ETH and Goerli. I also have the configuration files for both added to my github repository.

Let me know if you have any questions.

**Comment by samajammin** [comment]
Hey @YazzyYaz - sorry for the delay on this. This LGTM, please fix the merge conflicts & we'll get this merged ASAP! Thanks!

**Comment by samajammin** [comment]
@YazzyYaz checking in. Please rebase at your earliest convenience & we'll get this merged. Thanks!

**Comment by YazzyYaz** [comment]
I can't pull in a branch that's unknown for this PR, see screenshot below:
Screen Shot 2020-01-21 at 12 15 45 PM

Made a new PR instead: https://github.com/ethereum/ethereum-org-website/pull/697

We can close this one.

**Comment by CPSTL** [comment]
Closing this PR as the branch is unknown/deleted, therefore can't be pulled. New PR can be found here #697.

**Pull request closed without merging**
