### PR TITLE
Add ETHMail and Cryptoauth

### PR DESCRIPTION
**Pull request by gkapkowski**
Add ETHMail and Cryptoauth to developer resources at https://ethereum.org/en/developers/

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks for the PR @gkapkowski! @CPSTL please review when able.

In the meantime, if there's any additional info you can provide related to our [listing policy for dev tools](https://ethereum.org/en/contributing/adding-developer-tools/), that's always appreciated.

Cheers

**Comment by gkapkowski** [comment]
@samajammin thanks for pointing out the policy, I haven't seen it before.

## Is it meaningfully differentiated from tools already listed?

I think so. ETHMail is definitely. Cryptoauth is similar to https://github.com/pelith/node-eauth-server but it's a hosted service so developers don't have to setup their own server.

### New categories or types of tools

I think ETHMail and Cryptoauth don't match exact definition of a developer tool. Both are hosted services that developers can integrate in their projects, but I haven't found better category to put them.

### New features compared to existing similar tools

ETHMail - providing email communication capability for developers and their communities
Cryptoauth - managed OpenID Connect service  for login with ethereum wallet

### Targeted at a distinct use-case not covered by existing similar tools

ETHMail - as above, email communication use-case
Cryptoauth - allow login with ethereum wallet to existing software implementing OpenID Connect support

### Is the tool well documented?

ETHMail- not really
Cryptoauth - definitely not, sorry about it :(

## Does documentation exist?

ETHMail - not beyond couple of how-to entries and FAQ answers
Cryptoauth - none that would be meaningful in Cryptoauth context (there are external docs on OpenID Connect protocol and various libraries)

### Is it sufficient to use the tool?

ETHMail - for basic use cases, yes, for more advanced, no.
Cryptoauth - no, developers would need to contact me to get credentials to use cryptoauth

### Has it been recently updated?

Last update to the docs was 3 months ago

### Is the tool widely used?

ETHMail - somewhat, it serves ~400 users currently
Cryptoauth - it's used only internally by ETHMail and other services I've build

## Is the tool of sufficient quality?

I haven't had any complaints from ETHMail users about it's performance or stability. 

### Are there recurring bugs?

ETHMail - not that I know of
Cryptoauth - has issues mostly with mobile wallets web views

### Is the tool reliable?

ETHMail - I'm using it for my own communication and it has been working great
Cryptoauth - It serves ETHMail login page since the beginning and except for mobile wallets it haven't had any issues  

### Is the tool actively maintained?

Yes

------

Maybe it would be good to create new category like "Useful services" ?

**Comment by ryancreatescopy** [comment]
@CPSTL mind taking a look at this? thanks!

**Comment by CPSTL** [comment]
Hello, @gkapkowski @ryancreatescopy. Unfortunately, due to the lack of documentation, the closed source nature of the product, and that it is not directly a developer tool, I don't think ETHMail is an appropriate fit for the developers' page on Ethereum.org. As a result, I'm going to close this PR but please feel free to re-open it if either of you have any questions or can make changes to address the above-listed concerns.

**Comment by gkapkowski** [comment]
Got it. Thanks for looking into it!
I'll be working towards better documentation and open sourcing ETHMail, I'll let you know after it's done.

**Pull request closed without merging**
