### PR TITLE
Fix typo, remove duplicate 'can'

### PR DESCRIPTION
**Pull request by z3zzz**
## Description

There was a duplicate 'can' in the article, therefore removed one 'can'.

## Related Issue

There is no related issue.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Thanks @z3zzz !

**Comment by corwintines** [comment]
@all-contributors can you add @z3zzz for content

**Comment by corwintines** [comment]
@z3zzz make sure you come join the Discord server to claim your POAP!

https://discord.gg/w7FpSTNy

**Comment by z3zzz** [comment]
I have joined Discord, Thanks, @corwintines !!

**Pull request merged**
