### PR TITLE
Add Rivet to Developer Resources under Backend APIs [Fixes #1419]

### LINKED ISSUE #1419: Add Rivet to Developer Resources > Backend APIs
[Rivet](https://rivet.cloud/) offers a backend API that includes 500k free requests/month and pay-as-you-go service at a flat rate of $1/100,000 requests after that. It will also soon allow developers to purchase request capacity with ETH and DAI.

This ticket is to add Rivet to the list of available Backend API providers on the Developer Resources page.

### PR DESCRIPTION
**Pull request by designheretic**
## Description

[Rivet](https://rivet.cloud) offers a backend API that supports Ethereum mainnet, the Goerli, Rinkeby, and Ropsten testnets, and Ethereum Classic's mainnet. The service includes 500k free requests/month and pay-as-you-go service at a flat rate of $1/100,000 requests after that. It will also soon allow developers to purchase request capacity with ETH and DAI.

This PR adds [Rivet](https://rivet.cloud) to the **Backend APIs** section of the [Developer Resources page](https://ethereum.org/en/developers/), along with links to Rivet's [Documentation](https://rivet.cloud/docs/) and the [Github repository for the open source code that powers Rivet](https://github.com/openrelayxyz/ethercattle-deployment).

## Related Issue

The related issue can be found here: [Issue #1419](https://github.com/ethereum/ethereum-org-website/issues/1419).

### CODE REVIEW

**Comment by samajammin** [comment]
Hey @CPSTL could you please review when able? Thanks!

**Review by CPSTL — APPROVED** [review]
LGTM 👍

**Review by samajammin — APPROVED** [review]

**Review by samajammin — CHANGES_REQUESTED** [review]
Hey @designheretic - sorry to say that because we took so long to review, there's now merge conflicts that need to be resolved.

We no longer have this src/content/developers/index.md page. In an effort to expand our developer resources, we've broken out these topics into many standalone pages. Could you please update this PR (or open a new PR) to add Rivet to our "Backend APIs" page instead? Seems it would be most relevant there. You can find it here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/apis/backend/index.md

Thanks in advance & sorry we took so long!

**Comment by samajammin** [comment]
Hey @designheretic - I resolved the merge conflicts in #1597. I'm going to close out this PR in favor of #1597.

Thanks again for your contribution!

**Comment by samajammin** [comment]
@all-contributors please add @designheretic for content.

**Pull request closed without merging**
