### PR TITLE
Fix broken link to RimbleUI in dapps docs page

### LINKED ISSUE #3734: Broken Link - Rimble URL not working
**Describe the bug**
In the `Intro to Dapp` section the link [https://rimble.consensys.design](url) is not working.

```
## Dapp tools {#dapp-tools}
**Rimble UI** **_- Adaptable components and design standards for decentralized applications._**
- [rimble.consensys.design](https://rimble.consensys.design)
```

**To Reproduce**

1. Go to  [https://ethereum.org/en/developers/docs/dapps/](url)
2. Scroll down to [https://ethereum.org/en/developers/docs/dapps/#dapp-tools](url)
3.  Click on `rimble.consensys.design`

**Expected behavior**
It should take to the home page of `rimble.consensys.design`

**Desktop (please complete the following information):**
Not required

**Smartphone (please complete the following information):**
Not required

**Additional context**
None

### PR DESCRIPTION
**Pull request by NotManyIdeasDev**
## Description

Changed old broken link from "https://rimble.consensys.design" to "https://consensys.github.io/rimble-app-demo/"

## Related Issue

Related [#3734](https://github.com/ethereum/ethereum-org-website/issues/3734)

### CODE REVIEW

**Comment by samajammin** [comment]
Hey thanks for the PR!

Hmmm ya looks like the Rimble site is no longer up. On thought - it might be better to remove that link entirely vs. adding the link to a demo app. The demo app doesn't do much to explain what Rimble is. Best place might be to just link to the Rimble GitHub (which we already do in the line below).

A separate question is if Rimble is at all maintained. Is it still a good UI framework to recommend? If they took their site down, that leads me to believe there's no active development on this project. Looking at [their GitHub activity](https://github.com/ConsenSysMesh/rimble-ui/graphs/contributors), there's hardly been any activity on this project since 2019. Perhaps we should remove this resource entirely? Open to what folks think about this. cc @ryancreatescopy

**Comment by samajammin** [comment]
More relevant tools to list on this page might be frontend dapp templates that are more actively maintained, e.g.
- https://github.com/paulrberg/create-eth-app
- https://github.com/austintgriffith/scaffold-eth

**Comment by enriavil1** [comment]
> Hey thanks for the PR!
> 
> Hmmm ya looks like the Rimble site is no longer up. On thought - it might be better to remove that link entirely vs. adding the link to a demo app. The demo app doesn't do much to explain what Rimble is. Best place might be to just link to the Rimble GitHub (which we already do in the line below).
> 
> A separate question is if Rimble is at all maintained. Is it still a good UI framework to recommend? If they took their site down, that leads me to believe there's no active development on this project. Looking at [their GitHub activity](https://github.com/ConsenSysMesh/rimble-ui/graphs/contributors), there's hardly been any activity on this project since 2019. Perhaps we should remove this resource entirely? Open to what folks think about this. cc @ryancreatescopy

I agree after checking their Github activity, I concluded the same that the UI framework is not being maintained. I would consider taking off the link in general, but I was wondering if there is any way to check how popular is the framework in dapp development. If the framework is relatively popular, then I think it is good to recommend the Github. I would completely take out the URL to the demo area. As you said the demo URL doesn't help people understand what Rimble is. Sorry, but I am fairly new to the ethereum environment, so I can't precisely say I am aware of Rimble

**Comment by minimalsm** [comment]
Is [the dapp](https://consensys.github.io/rimble-app-demo/) working for anyone else? The UI doesn't even update for me. 

> Perhaps we should remove this resource entirely?

Yeah, probably should. Doesn't seem to be actively maintained, example dapp is broke and no large community behind to go to for support questions.

**Comment by minimalsm** [comment]
> If the framework is relatively popular, then I think it is good to recommend the Github. I would completely take out the URL to the demo area. As you said the demo URL doesn't help people understand what Rimble is. Sorry, but I am fairly new to the ethereum environment, so I can't precisely say I am aware of Rimble

@enriavil1 You can see the [weekly download stats here](https://www.npmjs.com/package/rimble-ui). Because things on Ethereum are generally pretty bleeding-edge technology I err on the side of removing unmaintained projects unless they are reaaaally popular. (If we don't remove it now we are just kicking the can down the round to remove it later.)

**Comment by enriavil1** [comment]
> > If the framework is relatively popular, then I think it is good to recommend the Github. I would completely take out the URL to the demo area. As you said the demo URL doesn't help people understand what Rimble is. Sorry, but I am fairly new to the ethereum environment, so I can't precisely say I am aware of Rimble
> 
> 
> 
> @enriavil1 You can see the [weekly download stats here](https://www.npmjs.com/package/rimble-ui). Because things on Ethereum are generally pretty bleeding-edge technology I err on the side of removing unmaintained projects unless they are reaaaally popular. (If we don't remove it now we are just kicking the can down the round to remove it later.)

@minimalsm I agree you are right. If we don't remove it, then we are just going to have to do it at a later point

**Comment by minimalsm** [comment]
No harm done in merging this fix for now! 

I've left the linked issue open and asked the original contributor if they want to contribute to removing these instances from the site.

@all-contributors please add @NotManyIdeasDev for docs

**Comment by NotManyIdeasDev** [comment]
> No harm done in merging this fix for now!
> 
> I've left the linked issue open and asked the original contributor if they want to contribute to removing these instances from the site.
> 
> @all-contributors please add @NotManyIdeasDev for docs

Thanks :D I'll keep contributing whenever I can!

**Comment by minimalsm** [comment]
Solved in #3779.

I've created an issue (#3782) to add some additional dapp tools in place of RimbleUI [as suggested here](https://github.com/ethereum/ethereum-org-website/pull/3740#issuecomment-907864560).

**Pull request merged**
