### PR TITLE
Uniswap v2 annotated code

### PR DESCRIPTION
**Pull request by qbzzt**
## Description

Uniswap v.2 annotated code. This is a very long (~50 pages) article because it's a real life application, not a 
sample like my previous two annotated code articles.

## Related Issue

#1785 requests this kind of article. This is the third one, and the first to deal with a complete system.

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Wow, thanks @qbzzt ! We're currently very busy on another project so it may take a little while longer than usual to review this. But thanks again for putting this together! 

As always we welcome feedback from any community contributors that want to read through this.

**Comment by qbzzt** [comment]
> Wow, thanks @qbzzt ! We're currently very busy on another project so it may take a little while longer than usual to review this. But thanks again for putting this together!
> 
> As always we welcome feedback from any community contributors that want to read through this.

You're welcome. Is there anything else you'd like me to write?

**Comment by wackerow** [comment]
@qbzzt Haven't forgotten this... 2000+ lines requires a little time hah 😂 , thanks for bearing with us. If there are any other members of the community who would like to give it a read and drop feedback in the meantime that would certainly be appreciated.

**Comment by qbzzt** [comment]
> @qbzzt Haven't forgotten this... 2000+ lines requires a little time hah 😂 , thanks for bearing with us. If there are any other members of the community who would like to give it a read and drop feedback in the meantime that would certainly be appreciated.

It took a long time to write, it will take a long time to review.

In the meanwhile, anything else you'd like me to write? Maybe find an insecure ERC20 implementation and go through the reasons it is insecure?

**Comment by wackerow** [comment]
@qbzzt hm, I'm sure something related to the upcoming changes could be beneficial. We don't have a lot on EIP-1559, and there is an open issue #3022 about this if you want to take a look.

**Comment by minimalsm** [comment]
Hey @qbzzt. 

Sorry that this has been left unreviewed so long 😓. I'm going to try to make some time, probably next week, to review. 

Can I just check on your end that as far as you know everything should still be working in the tutorial (just because everything has been moving quite fast and I'm not 100% familiar with the technologies covered in this).

**Comment by qbzzt** [comment]
> Hey @qbzzt.
> 
> Sorry that this has been left unreviewed so long 😓. I'm going to try to make some time, probably next week, to review.
> 
> Can I just check on your end that as far as you know everything should still be working in the tutorial (just because everything has been moving quite fast and I'm not 100% familiar with the technologies covered in this).

This article explains the Uniswap V2 contracts, which are a static target. No changes in that field.

**Comment by minimalsm** [comment]
@qbzzt Thanks so much for your patience on this 🙏 Made a few fixes to the markdown but overall awesome tutorial. Bringing it in now! 🕺🎉💃

**Pull request merged**
