### PR TITLE
Tweak 'proof-of-stake and security' section

### PR DESCRIPTION
**Pull request by randomishwalk**
Is it worth laying out more explicitly:

1) What the key staking threshold percentage numbers are: 33%, 51%, 66%
2) What the implications are if a malicious/inactive/incompetent party (or set of colluding or correlated parties) achieves each of those thresholds? i.e. 33% = inability to reach finality, 51% = fork choice rule, 66% = reorgs and double spends 
3) and more critically, how does the protocol use consensus rules + potentially social coordination to recover from each of these scenarios?

Ben Edgington's eth2book may have some of these details or if someone here can write up a draft off the top of their head we can all contribute + add.

Also, do we need a more explicit section that lays out slashing in more detail? Aka what is it? And how does it get triggered?

### CODE REVIEW

**Comment by jmcook1186** [comment]
hi @randomishwalk, yep I tend to agree this could be fleshed out a bit - thanks for bringing it up - want to keep working on the PR and we can iterate on it in review?

**Comment by wackerow** [comment]
@randomishwalk This is great, appreciate you bringing this up and opening a PR for it! At a glance I like where this is going 🔥

And noticing your a first-time contributor here—thank you and welcome! Small housekeeping notes, going to flip this to "Draft" mode while it's still being fleshed out. Please go ahead and switch this back to "Needs review" when it's ready for more eyes. Also, filing an issue ahead of time to link a PR to can help keep things organized for us... no worries here, just mentioning for in the future 🙂 Thanks again!

**Comment by randomishwalk** [comment]
Ah that's my bad! I should have gone through the readme file first on contribution best practices. Noted for the future!

**Comment by minimalsm** [comment]
Hey @randomishwalk, any update on this?

**Comment by randomishwalk** [comment]
Sorry Joshua haven’t had time…someone else should take over and tackle if they can
________________________________

**Comment by corwintines** [comment]
I think we can consider this complete with the work done by @jmcook1186 in https://github.com/ethereum/ethereum-org-website/pull/8286. Going to close this PR.

**Comment by randomishwalk** [comment]
Sounds good 👍
________________________________

**Pull request closed without merging**
