### PR TITLE
revert: removal of old page-languages ns strings

### PR DESCRIPTION
**Pull request by wackerow**
## Description
The `page-languages.json` namespace was recently merged into `common.json` in PR:

- #12428

The Crowdin imports in 

- #12611
- #12610
- #12613

are not yet updated with these changes, which accidentally removed these strings.

Affects strings with keys beginning with `language-` or `page-languages-` -- see [diff](https://github.com/ethereum/ethereum-org-website/pull/12428/files#diff-c79b5a32828cff7e979c627dcbbce26ee696bf39fb5ccaaba35772712eba08b9), file `src/intl/en/page-languages.json`

(Sorting applied)

## Related Issue
- Bug created in #12610, #12611, #12613

### CODE REVIEW

**Review by pettinarip — COMMENTED** [review]
@wackerow shouldn't we also remove the `src/intl/cs/page-languages.json` file that was created?

**Comment by wackerow** [comment]
Yes... I also updated this to do the same for `fr` and `zh`.

**Comment by pettinarip** [comment]
@wackerow I see some conflicts with the deleted json files. Let me see if I can resolve them.

**Review by pettinarip — APPROVED** [review]
@wackerow fixed the conflicts. Once it finishes building I think we should be good to go.

**Pull request merged**
