### PR TITLE
Update sharding date to ~2023

### PR DESCRIPTION
**Pull request by minimalsm**
## Description
Changes sharding date to ~2023 as per Trent's predictions

## Related Issue
None

### CODE REVIEW

**Review by samajammin — CHANGES_REQUESTED** [review]
Thanks for updating this!

I'm noticing at least a couple other places where this is listed & still needs to be updated. Both of these are on the Eth2 homepage:
Image 2021-12-05 at 9 03 04 AM

Image 2021-12-05 at 9 02 52 AM

Please do another sweep & ensure we catch all instances.

**Review by wackerow — APPROVED** [review]
Updated the others in the images posted above for all languages. Should be good to go now

**Comment by wackerow** [comment]
Pulled in, lemme know if any more "2022" (or "2021" 😬) are spotted

**Comment by minimalsm** [comment]
Sorry, never got round to this! Thanks for cleaning up @wackerow. I'll put it on my list today to double check.

**Pull request merged**
