### PR TITLE
add Status to the Developer Resources page

### PR DESCRIPTION
**Pull request by jinhojang6**
## Description
A pull request to add Status to the Developer Resources page(https://ethereum.org/developers/#other-tools)

Status is a multi-purpose communication tool that combines a peer-to-peer messenger, decentralized crypto-wallet, and Web3 browser using the Ethereum tech stacks.

The Dapp Integration Center is a step by step guide to optimize dapps for use in Status. This includes mobile first best practice, security and privacy requirements, leveraging the Status API, and how to submit to [dap.ps](https://dap.ps/).

## Related Issue
A PR applying the feedback from https://github.com/ethereum/ethereum-org-website/pull/594

## Screenshots (if appropriate):
Screen Shot 2020-01-21 at 10 18 09 PM

### CODE REVIEW

**Comment by jinhojang6** [comment]
@samajammin @CPSTL 

Thank you for your feedback! I closed the previous PR and create this new one with all the suggestions.

**Comment by CPSTL** [comment]
@all-contributors please add @jinhojang6 for content

**Comment by samajammin** [comment]
Nice! Thank you both.

**Comment by jinhojang6** [comment]
Thank you all very much!

**Pull request merged**
