### PR TITLE
Add WELLDONE Code to IDEs

### PR DESCRIPTION
**Pull request by 0xhsy**
add welldone code to ides

### CODE REVIEW

**Comment by corwintines** [comment]
Is this just a remix fork? The logo isn't even changed.

**Comment by corwintines** [comment]
Can you clarify how this expands on Remix. This just looks like a Remix fork.

**Comment by 0xhsy** [comment]
>  @corwintines This is not a Remix fork :) It's an officially registered plugin for Remix. If you activate this plugin in Remix IDE, it allows for multi-chain contract development through Remix IDE. 

Please refer to the manual here.
https://docs.welldonestudio.io/code/getting-started

You can also refer to the Remix tweet.
https://twitter.com/EthereumRemix/status/1663571908322013185

**Review by Aniket-Engg — APPROVED** [review]

**Comment by minimalsm** [comment]
Hey @0xhsy! Cool product, great that you folks made this to enhance Remix! I believe I actually used this a little when playing around with Sui. 

As far as listing it here goes, I don't think it's particularly additive to include this IDE on ethereum.org as we're focused on EVM development (Ethereum and L2s). Perhaps focusing on getting it listed on other L1 websites makes more sense?

Going to close this issue out. Thanks again!

**Comment by minimalsm** [comment]
@all-contributors please add @0xhsy for ideas

**Pull request closed without merging**
