### PR TITLE
[WIP] Nav menu redesign

### PR DESCRIPTION
**Pull request by wackerow**
## Preview link
- https://deploy-preview-11952--ethereumorg.netlify.app/

## Related issue
- #11955

### CODE REVIEW

**Comment by TylerAPfledderer** [comment]
Should go ahead and close #10075 , correct?

**Comment by wackerow** [comment]
@TylerAPfledderer Ahh.. I hate to drop the work you've already done, but with the recent redesign of this entire menu that's probably best. @pettinarip would you agree or do you see a use for those changes?

**Comment by wackerow** [comment]
Current plan is to deprecate this branch in favor of the Ark-UI implementation in #12054... will likely close this soon.

**Comment by wackerow** [comment]
Closing in favor of Radix-UI approach in #12125

**Pull request closed without merging**
