### PR TITLE
Update ethereum stack docs (Chinese)

### PR DESCRIPTION
**Pull request by luozhanxin**
## Description
fix wrong text

### CODE REVIEW

**Comment by Riely007** [comment]
Thanks!

**Comment by minimalsm** [comment]
Thanks for spotting and fixing this @luozhanxin ✌️.

Remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @luozhanxin for translations, docs

**Comment by minimalsm** [comment]
(I've also made sure this is up to date in CrowdIn)

**Review by minimalsm — APPROVED** [review]

**Pull request merged**
