### PR TITLE
Removed missing resource

### PR DESCRIPTION
**Pull request by SavPhill**
The reference site no longer exists:

https://stat.bloxy.info/

## Description

Removed the link to the missing resource

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
Nice catch! Thanks, @SavPhill!

**Comment by corwintines** [comment]
@all-contributors can you add @SavPhill for content

**Comment by corwintines** [comment]
Thanks again @SavPhill! Make sure you join the Discord server and come claim your POAP!

https://discord.gg/JUPn4ejq

**Comment by SavPhill** [comment]
> Nice catch! Thanks, @SavPhill!

Thank you @corwintines . I'm looking forward to contributing more in the future.

**Comment by SavPhill** [comment]
> Thanks again @SavPhill! Make sure you join the Discord server and come claim your POAP!
> 
> 
> 
> https://discord.gg/JUPn4ejq

Thank you. This link invite was invalid. Do you have the correct one?

**Pull request merged**
