### PR TITLE
EVM opcodes: Add a quick tip to resolve reading inconvenience

### PR DESCRIPTION
**Pull request by SebastianSupreme**
## Description

Implementation proposal for an idea by @vdusart.

Please view the related issue for further information.

## Related Issue
#7163

### CODE REVIEW

**Comment by vdusart** [comment]
Nice @SebastianSupreme 😁
I had completely forgotten !

**Comment by SebastianSupreme** [comment]
> Nice @SebastianSupreme 😁 I had completely forgotten !

Fear not, for your savior in shining armor has arrived 😉

**Comment by SebastianSupreme** [comment]
@vdusart 
Fear not, for your savior in shining armor has arrived 😉

**Comment by SebastianSupreme** [comment]
@corwintines 
Could you please add me as a contributor of code because of my previously merged PR:
https://github.com/ethereum/ethereum-org-website/pull/8401

**Review by corwintines — APPROVED** [review]
Looks like a good change. Going to keep the issue open to check with @jmcook1186, but agree with bringing this in.

**Pull request merged**
