### PR TITLE
The Great Hardware Wallet Expansion

### PR DESCRIPTION
**Pull request by Pandapip1**
## Description

Adds data for 17 hardware wallets.

## Related Issue

N.A.

### CODE REVIEW

**Comment by Pandapip1** [comment]
Note: it was agreed that getting data onto the website in the first place is a priority over having perfect info (https://discord.com/channels/714888181740339261/1009880767381393458/1010233299316256869)

**Comment by Pandapip1** [comment]
CC Reviewers: @samajammin @wackerow @corwintines @pettinarip @minimalsm @jmcook1186

This is ready for review.

**Review by minimalsm — COMMENTED** [review]
Amazing ❤️ 😍 

@corwintines could you check this out when you get the chance?

**Comment by corwintines** [comment]
Hey @Pandapip1, ill get started on looking at this. I'll [fill out issues](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet) for each of these as I look at this, but if you are able to help with that it would go a long way. I still want to go through the process of filling out issues for each of these as typically want to review those before a PR.

**Comment by corwintines** [comment]
Thanks for submitting this @Pandapip1!

@minimalsm reached out to you, but we are going to tackle this in smaller chunks of work.

**Pull request closed without merging**
