### PR TITLE
Add Metis to list of optimistic rollups

### PR DESCRIPTION
**Pull request by desolateline**

### CODE REVIEW

**Comment by minimalsm** [comment]
Hey @desolateline, thanks for the PR. We'll try to get around to reviewing this during this week :-)

**Comment by corwintines** [comment]
@desolateline could you share a bit more information on Metis? I havent heard of this project yet.

**Comment by desolateline** [comment]
> 

@corwintines @minimalsm - So MetisDao is a fork of optimism (Layer2) protocol. Also featured on www.l2beat.com (the layer2 tracker). However they're unique in that they're rolling out onchain storage via IPFS, as well as a more robust DAO functionality they refer to as Decentralized Autonomous Companies (DACs) which go beyond the traditional capability of offering traditional DAO voting/governance solutions but also Communication, Task Management, and Knowledge Management functionalities. Additionally, everyone knows the current draw back to arbitrum/optimism is that it takes several days to bridge back to layer1. However with their particular implementation of sequencers/validators they plan to have sped up that process to a few hours rather than days by the end of Q1/2022. Their official website is https://www.metis.io

Their mainnet Andromeda just went live 2 or 3 weeks, and it seems like every day there's a new announcement about someone joining their ecosystem. I really like the project a lot.

**Comment by minimalsm** [comment]
Hey @desolateline :-) just to update we're still collecting community feedback on this.

One thing that has come up is whether or Metis would technically be classified as an L2 rollup or a sidechain as it doesn't seem to inherit from Ethereum's L1 security. Instead (correct me if I'm wrong) Metis is relying on a majority of L2 Rangers to be truthful.

**Comment by desolateline** [comment]
> rangers are only there to incentivize the verifiers so that the transaction finalization window can be shortened. It doesn’t change how fraud proof works (which rely on ethereum/Layer1)

**Comment by minimalsm** [comment]
> > rangers are only there to incentivize the verifiers so that the transaction finalization window can be shortened. It doesn’t change how fraud proof works (which rely on ethereum/Layer1)

@desolateline can you provide a source for this?

**Comment by bossyuansu** [comment]
Hey, this is Peter from the metis team. What @desolateline said is true. In the current form, metis is based on the great work that Optimisms has done. In a future release, rangers will be implement to provide incentives to verifiers and also grant visibilities to the verifier's progress. The community then can use this information to adjust the finalization window. the actual fraud proof process during the finalization window is the same as the classic optimistic rollup construct.

**Comment by minimalsm** [comment]
@bossyuansu Thanks for the clarification Peter. So just to double-check is implementing interactive fraud proofs (like Arbitrum has now and Optimism plans to do) on the roadmap for Metis?

**Comment by bossyuansu** [comment]
> @bossyuansu Thanks for the clarification Peter. So just to double-check is implementing interactive fraud proofs (like Arbitrum has now and Optimism plans to do) on the roadmap for Metis?

the answer is yes. It is essential for a layer2 solution.

**Comment by minimalsm** [comment]
Thanks for clarifying @bossyuansu. We're struggling to find any information regarding this. Could you help? Would be useful if you could link to the roadmap/doc/section of the whitepaper that discusses this point.

**Comment by bossyuansu** [comment]
> Thanks for clarifying @bossyuansu. We're struggling to find any information regarding this. Could you help? Would be useful if you could link to the roadmap/doc/section of the whitepaper that discusses this point.

Hi, I understood your struggle. and we are partial at blame too. there are many reasons why you don't see related info in the WP. but it is primarily because we originated from the optimism's code base. Initially, optimism uses tx re-execution fraud proofing. So we inherited it until recently both optimism and us moved away from the re-execution model due to the complexity of the compatibility.  The interactive fraud proof mechanics is still in research and development. it was not in the original roadmap, again because we directly used Optimism's re-execution model. And we won't have much details until we are  close to finish that R&D effort. Hope it clarifies things a bit.

**Comment by minimalsm** [comment]
Thanks for clarifying @bossyuansu. Until fraud proofs are implemented or declared in Metis' public roadmap we couldn't add Metis as an optimistic rollup. Going to close this out but please feel free to re-open once this changes. 

Until that time, we would be happy to list Metis on our [sidechains](https://ethereum.org/en/developers/docs/scaling/sidechains/) page, if you'd like? Feel free to open a PR for this if you'd like Metis listed there.

**Comment by bossyuansu** [comment]
thanks and understood. @minimalsm  we have declared that our fraud proof implementation is underway. https://twitter.com/MetisDAO/status/1491516382844006401?s=20&t=H6YhDnCPJ8k3R1EFOqSK2g

please let me know if it is a sufficient statement. thanks.

**Comment by bossyuansu** [comment]
perfect @corwintines  thanks so much.

**Pull request closed without merging**
