### PR TITLE
add ChainIDE

### LINKED ISSUE #9042: Suggest a developer tool
### Dev tool name

ChainIDE

### Dev tool description

ChainIDE is a cloud-based IDE for creating decentralized applications to deploy on blockchains such as Ethereum, BNB Chain, Polygon, Conflux, Nervos, Dfinity, Flow, Chain33, FISCO BCOS, Atpos, etc. It fasts the development cycle and has pre-installed plugins that save users time and effort. It provides a complete and ready-to-use environment for innovative contract development and detailed documentation for learning purposes. ChainIDE is a powerful open-source cloud-based IDE that helps you write smart contracts in different programming languages and deploy them to other blockchains. It has modules for writing, compiling, debugging, testing, deploying a smart contract, and much more.

### When did the dev tool go live?

2019-02

### Where do you think this page should be shown?

https://ethereum.org/en/developers/learning-tools/

### Is the product open source?

No

### GitHub URL

https://github.com/WhiteMatrixTech/chainide-plugin-doc (Although chainide is not open source, it has an open source plugin development manual, which developers can use to develop the desired plugin on chainide.)

### Documentation URL

https://chainide.gitbook.io/chainide-english-1/

### Additional context

image

image

image

### PR DESCRIPTION
**Pull request by feibowei**
## Description

Suggest a developer tool[Fixes #9042]

### CODE REVIEW

**Comment by corwintines** [comment]
Thanks for opening this. Im going to remove the changes to the non english files since we use crowdin to do this, but will approve the rest :)

**Comment by corwintines** [comment]
Hmm, I do not have access to push these changes. @feibowei can you remove all translation changes other than in en :)

**Comment by feibowei** [comment]
> Hmm, I do not have access to push these changes. @feibowei can you remove all translation changes other than in en :)

OK, I've removed the non-English changes

**Review by corwintines — APPROVED** [review]
Thanks @feibowei!

**Comment by corwintines** [comment]
Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. We are in the process of getting our 2023 POAPs ready, but once they are you can [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳

**Comment by corwintines** [comment]
@all-contributors can you add @feibowei for content

**Pull request merged**
