### PR TITLE
WIP Javascript page

### PR DESCRIPTION
**Pull request by samajammin**
## Description
Dedicated page for ethereum.org/javascript - see more info in the related issue.

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/224

## How Has This Been Tested?
Locally

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GregTheGreek** [comment]
Once this added I'll pr against it for some ETH2 related materials

**Comment by faraggi** [comment]
@samajammin This is great. I had a local version as well. I'll add the content I had in the coming couple of days.

**Comment by ChrisChinchilla** [comment]
In theory… It's "JavaScript"

**Comment by samajammin** [comment]
@ChrisChinchilla thanks for catching 😅

**Comment by samajammin** [comment]
Merging this in so we have a basic page out the door. I welcome any additional PRs! @GregTheGreek @ChrisChinchilla @marcgarreau

**Pull request merged**
