### PR TITLE
Update Spanish Python developer doc 

### PR DESCRIPTION
**Pull request by ismaventuras**
updated ES version to be the same as the EN version because there were some dead links and some other useful links missing

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
Wow, thanks for the PR @ismaventuras ❤️❤️❤️

Please note that changes to translated content are usually handled in Crowdin (the localization tool we use) since all the content there gets reviewed by our language service provider. We will review your suggestion and merge the PR, but if you want to get involved with the Translation Program, you can [join the translation project in Crowdin.](https://crowdin.com/project/ethereum-org/invite/)

You can find more information about the program and using Crowdin on the [Translation Program page on the website](https://ethereum.org/en/contributing/translation-program/).

**Comment by minimalsm** [comment]
Also, sorry for the delay in reviewing this (I was on vacation)

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

**Comment by minimalsm** [comment]
@all-contributors please add @ismaventuras for docs, translations

**Comment by ismaventuras** [comment]
Thank you Joshua!! No problem for delay :)

**Pull request merged**
