### PR TITLE
Performance: fix compression issues by adjusting middleware matcher

### PR DESCRIPTION
**Pull request by pettinarip**
Our current implementation has odd behavior when serving static files that are compressed. Depending on the browser, it will serve files using `gzip` or `br`, since the same browsers support both algorithms (same req header in all these browsers: `Accept-Encoding: gzip, deflate, br, zstd`).

We would like to always serve the `br` version as it is much lighter than the `gzip` version. For example, the `_app.js` bundle size drops from ~330kb to ~215kb when using Brotli.

The issue is related to the custom middleware we use to redirect requests to different locales. Currently, we process all incoming requests (which is not necessary) and for some reason this seems to cause a conflict with the netlify server which ends up serving `gzip` files instead.

## Description

This PR adds a custom `matcher` to the exported middleware config to only process the matched paths and ignore the rest.

## Summary by CodeRabbit

- **New Features**
  - Enhanced middleware to handle locales and redirects more effectively.
  - Introduced configuration to exclude specific paths from middleware processing.

### CODE REVIEW

**Review by minimalsm — CHANGES_REQUESTED** [review]
Images aren't loading for me on iOS.

**Review by corwintines — CHANGES_REQUESTED** [review]
Screenshot 2024-05-13 at 8 12 22 PM

Using MacOS, Brave browser, not able to get images here as well.

**Comment by pettinarip** [comment]
@minimalsm @corwintines good catch, there seem to be a few weird things going on with redirects/middleware/trailingslashes with Next 14. Investigating...

**Comment by minimalsm** [comment]
@coderabbitai review

**Review by corwintines — APPROVED** [review]
Working for me now, LGTM

**Review by minimalsm — APPROVED** [review]
LGTM now :) 

Images fixes, and seeing br encoding on js and css files.

**Pull request merged**
