### PR TITLE
Edited an grammatically incorrect sentence for the 'deploy first contract' tutorial

### PR DESCRIPTION
**Pull request by l-armstrong**
## Description
I fixed a grammatically incorrect sentence for the 'deploy first contract' tutorial.

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
@samajammin you mind checking this? I can check the grammar, but feel like I need to some technical chops to actually approve it.

**Review by samajammin — APPROVED** [review]
Thanks for catching & updating!

**Comment by samajammin** [comment]
@all-contributors please add @l-armstrong for content.

**Comment by l-armstrong** [comment]
Anytime !

**Pull request merged**
