### PR TITLE
Blockchain Conference in Quito

### PR DESCRIPTION
**Pull request by sleonp-dev**
Ethereum Ecuador event, conference in Quito, 15-20 May!

### CODE REVIEW

**Comment by sleonp-dev** [comment]
Hey @nhsz sorry to bother you again... now requesting an event update to include it on the event timeline :), please help me or approve it if you see no issues... also when will the page update with the pull requests? Gracias friend

**Review by nhsz — APPROVED** [review]
LGTM!

**Comment by nhsz** [comment]
> Hey @nhsz sorry to bother you again... now requesting an event update to include it on the event timeline :), please help me or approve it if you see no issues... also when will the page update with the pull requests? Gracias friend

Hey, no problem. We usually do deploys twice a week, tuesdays and thursdays, sometimes it can get delayed because of our different timezones. Next deploy will be today so expect it to be live in a couple of hours.

**Comment by sleonp-dev** [comment]
@nhsz me encanta no tener reuniones y que todo funcione! Gracias Che

**Pull request merged**
