### PR TITLE
feat: added accordion for mobile nav

### LINKED ISSUE #10751: Header mobile - Menu and Dropdowns
[Mobile version]

Implement the [new DS styles](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=248%3A507) in the [Menu Mobile](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Nav/Mobile.tsx) component.

image

### PR DESCRIPTION
**Pull request by ameeetgaikwad**
## Description
Updates the `mobile` component to the new DS specifications

## Related Issue
Part of [Implementation of new DS specifications](https://github.com/ethereum/ethereum-org-website/issues/9548)

fixes #10751

### CODE REVIEW

**Review by nnnnnnsssss — CHANGES_REQUESTED** [review]
Recheck

**Comment by ameeetgaikwad** [comment]
@nnnnnnsssss what changes should I make?

**Review by nnnnnnsssss — CHANGES_REQUESTED** [review]
Recheck

**Comment by ameeetgaikwad** [comment]
@pettinarip any changes required?

**Comment by wackerow** [comment]
Hey @ameeetgaikwad! Appreciate your contribution here and apologies that this didn't end up progressing. When you posted this pretty much the whole dev crew on the team was all-hands-on-deck getting the site migrated to Next.js, and several PRs ended up piling up in the meantime; my apologies for that.

I the meantime we had an epic that overhauled the menu navigation for the site on both desktop and mobile, which included the migration to using the Accordion component for the mobile. Given that, going to close this on out as it does not appear necessary anymore. Thank you again!

**Pull request closed without merging**
