### PR TITLE
Add Chainstack

### PR DESCRIPTION
**Pull request by easeev**
## Description

- Add Chainstack to Backend APIs in Developers
- Add Chainstack tutorials to Developer Support & Training in Developers
- Add Chainstack to Protocol and Infrastructure in Enterprise
- Fix the link to Hyperledger Burrow
- Fix the capitalization in platform names
- Add Chainstack Gitter to Enterprise Developer Community

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by virgil** [comment]
I’m not sure the exact policy, but historically I think we’re only listed free options on the ethereum.org site.

**Comment by easeev** [comment]
> I’m not sure the exact policy, but historically I think we’re only listed free options on the ethereum.org site.

I don't think it's the case especially with services listed at https://github.com/ethereum/ethereum-org-website/blob/dev/docs/enterprise/index.md. Also, Chainstack is completely free for 2 weeks.

**Comment by easeev** [comment]
> Also, Chainstack is completely free for 2 weeks.

Now always free for shared Ethereum nodes: https://chainstack.com/announcing-unlimited-free-access-to-ethereum-nodes/

**Comment by samajammin** [comment]
Thoughts on this @CPSTL?

**Pull request merged**
