### PR TITLE
Added FLOC* to design and ux docs in the Design DAOs and communities, and MetaCartel Ventures as Web3 Design Case Studies. FLOC* Joins the Battle!

### PR DESCRIPTION
**Pull request by mrsalitre**
## Description
Add within DESIGN DAOS AND COMMUNITIES the studio where I am the lead web3 developer. And added MetaCartel Ventures as Web3 Design Case Studies made by FLOC*

It is a studio with a decentralised philosophy that implements brand3 strategies for this ecosystem.

## Related Issue
Added links to the design and ux developer documentation

### CODE REVIEW

**Comment by nhsz** [comment]
I think the idea of this page is not to promote any particular studio/agency but general useful resources for people interested in these topics. @konopkja could you check these? thx

**Comment by mrsalitre** [comment]
Who's the central authority that dictates what is the purpose of the documentation? And why the purpose of the documentation it's not clearly defined? I'm a autistic persons my questions are real, sorry if they may sound accusative but I could not find what is the purpose of documentation. FLOC* is the only web3 studio in Spain so adding that to documentation could benefit spanish devs to find their community, that happens to me and it's the only reason I like to talk about web3 to web2 people and devs.

**Comment by konopkja** [comment]
Hello @mrsalitre, those are valid questions.  I think its great that you have raised them and brought this into attention. We will share the listing policies soon so that there is clarity.

**Comment by wackerow** [comment]
Hey @mrsalitre, thanks for the PR and the feedback!

We have listing policies under the [community](https://ethereum.org/en/community/) section, but these are not exhaustive and don't cover every type of listing request. Currently we do not yet  have a strict policy regarding listings within the developer documentation, but the [product listing](https://ethereum.org/en/contributing/adding-products/) policy can help as a guide here in the meantime.

In general, the ethos is to try and provide value to the users of the site and to minimize harm and distraction, placing an emphasis on open source values, education, and minimizing commercial pressures. In the developer docs this usually means staying away from things that could be construed as advertisements.

Looking at where you're listing this, I see we do list Deep Work as well, who to my knowledge sells a service but also opens all of their case studies publicly. I see a couple other cases studies on your site on `/projects`—is there a place users can go to see other case studies from FLOC* to learn from? Is this primarily a service for sale, or more of a community driven effort?

I don't necessarily see an issue with listing under the "Design DAOs and communities" section, although some clarity on community benefit would also be appreciated. Under "Web3 design case studies", if we're going to list this I would suggest linking to a part of the site that shows multiple examples, and renaming to your name, instead of naming a single case study.

**Comment by minimalsm** [comment]
Closing this out as it has gone stale. Generally agree w/ comments above that this doesn't make sense.

**Pull request closed without merging**
