### PR TITLE
Add MyEtherWallet (MEW)

### PR DESCRIPTION
**Pull request by kvhnuke**

### CODE REVIEW

**Comment by kvhnuke** [comment]
@jjmstark when do you think you can merge in this PR?

**Comment by jjmstark** [comment]
hey @kvhnuke! Thanks for submitting this, just two small changes requested:

- We generally follow a "first in, first out" approach when adding apps or tools to a list. Can you change such that MEW is added to the end of the list, not the top?
- Capitalize "Ethereum" in the description of MEW

**Comment by kvhnuke** [comment]
Hi @jjmstark
Thanks for the quick response, 
If you look at popularity and reputation of the listed wallets in the Eco system I believe metamask and mew are at the same level. Adding, MEW (most used ethereum wallet interface) all the way in the bottom unfortunately can imply it is not an integral part of ethereum eco system. Will it be ok, if I add it after metamask?

Thank you

**Comment by jjmstark** [comment]
I get your point, but we're going to stick with "first in first out" for now. The order of the wallets presented are not intended to be a ranking, and even if they were viewed that way, it is obviously difficult to make an objective determination about what that order should be. 

We're open to suggestions about how to improve this list in the future, in order to make it as fair as possible to all of the wallets listed, but for now we'll stick with this. 

Given that there are only 5 wallets listed, I am sure users will still see this and understand MEW is a widely used wallet throughout the ecosystem.

Thanks! If you can submit an edited PR, I'll merge right away.

**Comment by kvhnuke** [comment]
Hi @jjmstark 
but there is no first in first out since you were the one who added all the listed wallets as of now. I am not sure why MEW wasnt included in the first place. Thank you for consideration, let us know once you figure out the `We're open to suggestions about how to improve this list in the future, in order to make it as fair as possible to all of the wallets listed`. I'll close the PR since I dont think it is beneficial for anyone the way you are suggesting it

Thank you

**Comment by jjmstark** [comment]
Yes, MEW definitely should have been included in the first place. Enabling people to catch our mistakes and add missing apps, tools, and content through PRs is one of the goals of making the website open source. 

I'm going to add MEW to this list in the way I suggested, in a fresh PR - I think its valuable for users of Ethereum to have it as an option.

**Comment by kvhnuke** [comment]
Thanks @jjmstark even though it is not the way I wanted, I really appreciate including us. Thanks again! Sorry if I came out little strong!

**Comment by jjmstark** [comment]
No problem :) Apologies for not including MEW in the first place, and congrats on the new site!

**Pull request closed without merging**
