### PR TITLE
Add Trust Wallet

### PR DESCRIPTION
**Pull request by corwintines**
## Description

- Add Trust Wallet logo
- Add Trust Wallet data

## Related Issue

Fixes https://github.com/ethereum/ethereum-org-website/issues/10692

### CODE REVIEW

**Review by minimalsm — APPROVED** [review]
LGTM

**Comment by wackerow** [comment]
@corwintines Are we waiting on anything here? @nhsz Any issues you foresee with this and #12299?

**Comment by nhsz** [comment]
> @corwintines Are we waiting on anything here? @nhsz Any issues you foresee with this and #12299?

No issues, data wallets type has changed a bit in the new version so I'll need to update this manually on the PR but we can merge this one now

**Comment by wackerow** [comment]
Ok, #12299 has been merged... this should be ready to be updated before merging in

**Review by wackerow — APPROVED** [review]

**Pull request merged**
