### PR TITLE
Migrate `upgrades/vision` page to Chakra

### PR DESCRIPTION
**Pull request by amit-ksh**
## Description

Migrate the `upgrades/vision.tsx` page from emotion to Chakra

## Related Issue

#9353

### CODE REVIEW

**Comment by vishal590** [comment]
how can I participate in writing code ?
do we have discord server ?
what is the proecedure to participate in writing code ?

**Review by pettinarip — APPROVED** [review]
Nicely done @amit-ksh 🚀 🚀  lgtm

**Comment by pettinarip** [comment]
> how can I participate in writing code ? do we have discord server ? what is the proecedure to participate in writing code ?

Hi @vishal590 👋🏼 

There are multiple ways you can contribute on ethereum.org. You can take a look at [this page](https://ethereum.org/en/contributing/).

If you are asking specifically about this contribution in this PR, this is part of #9353. You can go to that issue and read the "How to contribute" section.

I encourage you to join [our Discord server](https://discord.gg/CetY6Y4). You will find there a "How to contribute" channel as well and you could ask questions on the website channel.

**Comment by vishal590** [comment]
@pettinarip could you assign this task to me?

**Pull request merged**
