### PR TITLE
Vietnamese (vi): Update translation

### PR DESCRIPTION
**Pull request by xcaro**
## Description
Updates Vietnamese (vi) translation

### CODE REVIEW

**Comment by minimalsm** [comment]
Thanks @xcaro; looks good to me.

Waiting on a second approval from a Vietnamese speaker.

**Review by devtooligan — APPROVED** [review]
I speak Vietnamese I can approve these changes.

The first change translates "More info" into Viet.
The second change uses the English word "Ethereum-Stack" instead of a literal translation of the word "stack"
The third capitalizes JavaScript (not sure why Javascript not capitalized in the line before that though....)
And the last change replaces a commonly used but very informal abbreviation for the word "and" with the actual word for "and"

I dunno why the build is failing though

**Review by minimalsm — APPROVED** [review]

**Comment by minimalsm** [comment]
Thanks for the review @devtooligan <3 Looks like the build is being flakey, nothing to do with this PR.

**Comment by minimalsm** [comment]
@xcaro thanks again for the PR ❤️ 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @xcaro for docs, translations

**Comment by ohayo1234** [comment]
how to claim?

**Pull request merged**
