### PR TITLE
Fix typos in echidna tutorial

### PR DESCRIPTION
**Pull request by bestpilotingalaxy**

### CODE REVIEW

**Review by corwintines — APPROVED** [review]
LGTM, thanks @bestpilotingalaxy

**Review by minimalsm — APPROVED** [review]
Thanks for spotting and fixing this @bestpilotingalaxy ✌️.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

**Comment by minimalsm** [comment]
@all-contributors please add @bestpilotingalaxy for docs

**Comment by bestpilotingalaxy** [comment]
Hehe, become proud  ethereum.org contributor by 2 grammar marks :)

**Pull request merged**
