### PR TITLE
adds back to top button [Fixes #12194]

### LINKED ISSUE #12194: Add a "back to top" button on pages
### Is your feature request related to a problem? Please describe.

Some pages on ethereum.org are very long, and could benefit from a "back to top" button to help reset the user

### Describe the solution you'd like

At the bottom of the page (or a button that floats at some point), we add a back to top button that takes the user to the top of the page. 

- [ ] Needs design first

### Describe alternatives you've considered

Not having this button at all, may not be necessary as all nav is still accessible from wherever you are in the content generally.

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by alex1092**
## Description

Adds a back to top button to the `<Footer />` component,

Also refactors some of the layout based on design changes

## Related Issue

[Fixes #12194]

## Screenshots 

Ethereum-Developer-Resources-ethereum-org

### CODE REVIEW

**Comment by minimalsm** [comment]
hey @alex1092, thanks for the PR! 

is this a duplicate of #12906? which one should be reviewed?

**Comment by alex1092** [comment]
Review this one, ill close the other pr

**Review by nloureiro — APPROVED** [review]

**Review by corwintines — APPROVED** [review]
Awesome, thank you @alex1092!

LGTM, I just added .idea to the .gitignore file to get rid of the .idea workspace files. We do this for .vscode files as well.

**Comment by corwintines** [comment]
@all-contributors can you add @alex1092 for code

**Pull request merged**
