### PR TITLE
Move use cases into use Ethereum navigation dropdown

### PR DESCRIPTION
**Pull request by minimalsm**
## Description
Moves NFTs, DeFi, and DAOs from the 'Learn' dropdown of the navigation into the 'Use Ethereum' dropdown.

## Related Issue
Short term patch for #3984

### CODE REVIEW

**Comment by samajammin** [comment]
Looks like build failed 🧐 - did you cancel it?
Screen Shot 2022-03-31 at 1 28 40 PM

**Comment by samajammin** [comment]
My (weakly held) preference on order:
- wallets
- get eth
- dapps
- nft
- defi
- daos
- stablecoins
- stake
- run a node

**Review by wackerow — APPROVED** [review]
Suggesting we also bump "Ethereum upgrades" which is a React component page, above all the other markdown pages (which is everything else from Security down, just below "What is ether?"

Scope creep though, I know... feel free to not include in this PR, just wanted to mention.

**Comment by wackerow** [comment]
And yeah, I agree that NFT above would be best given search volume.

**Comment by minimalsm** [comment]
> Looks like build failed 🧐 - did you cancel it? Screen Shot 2022-03-31 at 1 28 40 PM

Nope, it's working fine locally.

---

> My (weakly held) preference on order:
> 
> * wallets
> * get eth
> * dapps
> * nft
> * defi
> * daos
> * stablecoins
> * stake
> * run a node

Updated to this.

**Comment by minimalsm** [comment]
Tested on average browser size (1366 x 784) it's looking better 🙂 

Screenshot 2022-03-31 at 21 56 37

**Review by corwintines — APPROVED** [review]

**Review by samajammin — APPROVED** [review]

**Pull request merged**
