### PR TITLE
Update index.md to include Solidity & Vyper cheat sheet

### PR DESCRIPTION
**Pull request by Pet3ris**
## Description

I've added the links for the Solidity & Vyper cheat sheet at [http://reference.auditless.com/cheatsheet](http://reference.auditless.com/cheatsheet). This cheat sheet is open source and already has contributions from Solidity/Vyper devs/core team.

I'm not happy with the placement since there is no joint section for Solidity/Vyper so proposing a separate link in both (but it's one side-by-side cheat sheet in reality).

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by faraggi** [comment]
I think this is a great addition to the docs. thanks @Pet3ris

**Comment by Pet3ris** [comment]
@faraggi - yep that's right, thank you!

**Comment by samajammin** [comment]
@all-contributes please add @Pet3ris for content

**Comment by samajammin** [comment]
@all-contributors please add @Pet3ris for content

**Pull request merged**
