### PR TITLE
Improve the Ethereum Stack Page

### PR DESCRIPTION
**Pull request by SebastianSupreme**
I've added some information and corrected a few grammar mistakes.

### CODE REVIEW

**Review by jmcook1186 — CHANGES_REQUESTED** [review]
Hi - sorry but I don't think we should add any of this new information. There is no need to talk about `view` and `pure` functions in solidity in this introduction to the stack, it will only make it difficult for non-technical readers to understand. The section is also not Solidity-specific, it applies to any language that compiles to EVM bytecode. Same goes for discussing the different clients - it is orthogonal to the point of the section and only adds friction for a novice reader.

IMO only the typo fixes should be merged. 

Thanks

**Comment by SebastianSupreme** [comment]
That's fine. Then, let's just do that.

**Review by jmcook1186 — APPROVED** [review]
cool, thanks

**Comment by SebastianSupreme** [comment]
@jmcook1186 @minimalsm @corwintines 
Can this be merged too in today's master branch merge?

**Review by corwintines — APPROVED** [review]

**Pull request merged**
