### PR TITLE
Update web3 learn page (Chinese simplified)

### PR DESCRIPTION
**Pull request by opensourcex123**

### CODE REVIEW

**Comment by minimalsm** [comment]
Thanks @opensourcex123, have asked that someone who can write Chinese reviews this suggestion 😀

**Comment by minimalsm** [comment]
@all-contributors please add @opensourcex123 for docs

**Comment by minimalsm** [comment]
@all-contributors please add @opensourcex123 for translation

**Review by Riely007 — COMMENTED** [review]
It's correct. Should be “采用去中心化“.

**Pull request merged**
